# -*- coding: utf-8 -*-
"""FAMILLE 04 · ADMIN — ADM-53 → ADM-63"""
from ..model import S, Z
from .adm_a import CHROME_ADM

SCREENS = [

S("ADM-53", "Sécurité — rate limits & abus", "ADM", "System Ops & Sec", "/admin/securite/rate-limits", "Admin", "P1", "Protéger sans étouffer",
  intent="Surveiller les limitations de débit : qui est bloqué, pour quel motif, et les faux positifs. Un rate limit mal "
         "réglé bloque des utilisateurs légitimes — cet écran sert à le vérifier.",
  zones=[
    Z("table", "Règles & effet", 6, "Colonnes : règle (endpoint, portée, seuil, fenêtre), appliquée à (anonyme, authentifié, partenaire), volume déclenché 24 h, blocages, contestations utilisateurs, taux de faux positifs estimé."),
    Z("kpi", "Bandeau", 3, "Blocages 24 h · IP tronquées bloquées · utilisateurs authentifiés touchés (ambre : risque d'étouffement légitime) · contestations ouvertes."),
    Z("list", "Contestations d'utilisateurs", 4, "File : utilisateur bloqué à tort, contexte (usage légitime, script tiers, réseau partagé), décision proposée (débloquer, ajuster la règle)."),
    Z("cta", "Actions", 1, "« Ajuster une règle » or (avec simulation) · « Débloquer un utilisateur » fantôme (journalisé)."),
  ],
  comps=[("Table de règles", "seuils lisibles, taux de faux positifs"),
         ("Simulateur de règle", "impact estimé sur 7 jours de trafic réel"),
         ("File de contestations", "priorité aux utilisateurs authentifiés"),
         ("Exemptions", "partenaires de confiance, liste courte, révisée régulièrement")],
  states=[("Nominal", "blocages faibles, faux positifs limités."),
          ("Étouffement", "ambre : blocages d'utilisateurs authentifiés en hausse → révision proposée."),
          ("Attaque", "clay : trafic hostile massif, règles renforcées automatiquement, journalisé."),
          ("Ajusté", "émeraude : règle modifiée, effet mesuré et affiché après 24 h.")],
  motion=[("Simulation", "courbe d'impact qui se trace 420 ms"),
          ("Renforcement", "bandeau clay persistant jusqu'à la fin de l'attaque")],
  rules=["Un utilisateur authentifié bloqué à tort doit pouvoir contester : la file de contestations est affichée ici, pas ailleurs.",
         "Toute règle modifiée est simulée avant application : aucun réglage à l'aveugle.",
         "Les exemptions de partenaires sont limitées, listées et revues tous les 90 jours."],
  tokens=["--amber-500", "--clay-500", "--violet-500", "--mono", "--table"],
  api=["GET /admin/security/rate-limits", "POST /admin/security/rate-limits/:rule/simulate", "POST /admin/security/rate-limits/:rule/apply", "POST /admin/security/unblock {userId, motive}"],
  tech="Règles de rate limiting stockées en configuration versionnée, appliquées au bord (Worker) et à l'API. Le simulateur "
       "rejoue le trafic des 7 derniers jours sur la nouvelle règle.",
  canon="ADM — sécurité (rate limits)", chrome=CHROME_ADM),

S("ADM-54", "Sécurité — webhooks", "ADM", "System Ops & Sec", "/admin/securite/webhooks", "Admin", "P1", "Écouter les partenaires",
  intent="Superviser les webhooks entrants (PSP, opérateurs, fournisseurs) et sortants (notifications partenaires) : "
         "signatures, retards, échecs, rejeux. Une panne de webhook PSP, c'est de l'argent qui ne se confirme pas.",
  zones=[
    Z("table", "Webhooks", 6, "Colonnes : source/destination (nom du partenaire), type d'événement, volume 24 h, latence médiane, échecs (%), signature (valide/invalide), dernier succès, statut."),
    Z("timeline", "Latence & échecs", 3, "Courbes par partenaire, seuils marqués."),
    Z("list", "File de rejeu", 4, "Événements échoués en attente de rejeu : cause (signature, timeout, 5xx partenaire), tentatives, prochain essai, impact métier (paiement non confirmé → priorité)."),
    Z("cta", "Actions", 1, "« Rejouer » or · « Voir un événement » fantôme · « Contacter le partenaire » texte."),
  ],
  comps=[("Table partenaires", "signature valide affichée en état, jamais la clé"),
         ("File de rejeu", "impact métier priorisé (paiement > information)"),
         ("Analyse d'événement", "charge utile expurgée, en-têtes de signature masqués")],
  states=[("Nominal", "signatures valides, latences basses."),
          ("Dégradé", "ambre : échecs en hausse vers un partenaire."),
          ("Panne partenaire", "clay : file de rejeu qui grossit, bascule vers canal alternatif si disponible, information interne."),
          ("Incident sécurité", "clay plein : signatures invalides massives → blocage de la source, incident ouvert (ADM-52).")],
  motion=[("Rafraîchissement", "tick 30 s"),
          ("Rejeu", "événement qui quitte la file 240 ms")],
  rules=["Les clés de signature ne sont jamais affichées ni transmises, même en back-office : uniquement l'état et la date de dernière rotation.",
         "Les événements de paiement en échec sont prioritaires : ils peuvent concerner le salaire d'un travailleur.",
         "Un webhook rejoué est idempotent par construction (clé d'événement) : le rejeu ne double jamais une opération."],
  tokens=["--mono", "--clay-500", "--amber-500", "--emerald-500", "--table"],
  api=["GET /admin/security/webhooks", "GET /admin/security/webhooks/:partner/events", "POST /admin/security/webhooks/events/:id/retry"],
  tech="Réception au bord (Worker) avec vérification de signature, mise en file, traitement idempotent. Le rejeu passe par "
       "l'API d'admin avec journal.",
  canon="ADM — sécurité (webhooks)", chrome=CHROME_ADM),

S("ADM-55", "Sécurité — incidents & procédures", "ADM", "System Ops & Sec", "/admin/securite/incidents", "Admin", "P0", "Réponse à incident",
  intent="Piloter un incident de sécurité : classification, confinement, éradication, notification, post-mortem. "
         "Procédure écrite, étapes obligatoires, traçabilité complète.",
  zones=[
    Z("hero", "Incident", 3, "Référence SEC-Mono, classification (fuite de données, compromission, abus, disponibilité), sévérité, périmètre estimé, statut, responsable."),
    Z("timeline", "Procédure", 6, "Étapes obligatoires : détection → qualification → confinement → éradication → rétablissement → notification → post-mortem. Chaque étape datée, signée, avec preuve."),
    Z("list", "Obligations de notification", 4, "Évaluation : utilisateurs concernés, autorités (selon juridiction), partenaires, presse (si nécessaire). Chaque décision est tracée avec son motif."),
    Z("cta", "Actions", 1, "« Avancer l'étape » or · « Consigner une preuve » fantôme · « Clore avec post-mortem » texte."),
  ],
  comps=[("C-06 TimelineTrack", "étapes de procédure, obligatoires"),
         ("Registre de preuves", "chaque action conservée (logs, captures, hash)"),
         ("Évaluateur de notification", "arbre de décision documenté"),
         ("Post-mortem", "structure : cause, impact, actions, délais")],
  states=[("Qualifié", "sévérité et périmètre établis."),
          ("Confiné", "propagation stoppée, preuves conservées."),
          ("Rétabli", "services restaurés, surveillance renforcée."),
          ("Clos", "post-mortem publié, actions suivies dans ADM-47."),
          ("Fausse alerte", "ardoise : clôturé avec motif, calibrage mis à jour.")],
  motion=[("Étape", "progression qui se trace 420 ms, sceau sobre"),
          ("Notification", "envois visibles, horodatés")],
  rules=["Aucune étape ne peut être sautée : la procédure est imposée, y compris sous pression.",
         "La conservation des preuves est prioritaire sur la remise en service (aucune destruction de traces).",
         "La notification aux personnes concernées est évaluée systématiquement ; toute décision de ne pas notifier est motivée et tracée.",
         "Les secrets compromis sont révoqués et faire tourner : l'UI ne les affiche jamais, même dans ce contexte (§3.6)."],
  tokens=["--clay-600", "--clay-500", "--violet-500", "--mono", "--glass-2"],
  api=["GET /admin/security/incidents/:id", "POST /admin/security/incidents/:id/step {step, evidence}", "POST /admin/security/incidents/:id/close {postmortem}"],
  tech="Gestion d'incident sécurité dédiée avec machine d'étapes, coffre de preuves (R2 immuable), et intégration au "
       "système d'incident global (ADM-49).",
  canon="ADM — sécurité (incidents)", chrome=CHROME_ADM),

S("ADM-56", "Sécurité — journal d'audit", "ADM", "System Ops & Sec", "/admin/securite/audit", "Admin", "P0", "La vérité enregistrée",
  intent="Consulter le journal d'audit complet : toutes les actions sensibles, par tout acteur (utilisateur, agent, système). "
         "Chaîné par empreintes, immuable, exportable. C'est la mémoire qui permet la confiance et la justice interne.",
  zones=[
    Z("table", "Journal", 6, "Colonnes : horodatage (ms), acteur (type + id interne), action, ressource (type + empreinte courte), résultat, empreinte d'événement, lien de chaîne."),
    Z("kpi", "Intégrité", 3, "Entrées 24 h · chaîne vérifiée ✓ · dernier audit d'intégrité · recherche en cours (requête affichée, coût estimé)."),
    Z("form", "Recherche avancée", 3, "Filtres : acteur, action, ressource, période, résultat. Requêtes lourdes exécutées en tâche de fond avec notification."),
    Z("cta", "Actions", 2, "« Exporter (JSON signé) » or outline · « Vérifier l'intégrité » fantôme · « Ouvrir une ressource » texte."),
  ],
  comps=[("Table de journal", "chaînage visible (hash précédent)"),
         ("Recherche asynchrone", "requêtes lourdes détachées, résultat notifié"),
         ("Export signé", "manifeste d'empreintes, usage juridique")],
  states=[("Intègre", "émeraude : vérification passée."),
          ("Rupture", "clay : alerte majeure, incident sécurité automatique (ADM-55)."),
          ("Recherche longue", "violet : exécution en tâche de fond, lien de suivi."),
          ("Export en cours", "génération asynchrone, lien signé 24 h.")],
  motion=[("Vérification", "progression réelle, sceau à la fin"),
          ("Recherche", "résultats en flux si disponibles, sinon notification")],
  rules=["Le journal d'audit est immuable et chaîné : aucune écriture manuelle, aucune suppression, même par un administrateur.",
         "La consultation du journal est elle-même journalisée (qui a cherché quoi) : le surveillant est surveillé.",
         "Les exports sont signés et comportent un manifeste d'empreintes utilisable en procédure."],
  tokens=["--mono", "--emerald-500", "--clay-500", "--table"],
  api=["GET /admin/security/audit?cursor=&filters=", "POST /admin/security/audit/search {query}", "POST /admin/security/audit/verify", "GET /admin/security/audit/export"],
  tech="Event store chaîné (hash prev) ; recherche via index inversé ; vérification de chaîne en streaming. Rétention "
       "légale : 10 ans, stockage froid R2 après 12 mois.",
  canon="ADM — sécurité (audit)", chrome=CHROME_ADM),

S("ADM-57", "Infra — topologie & bord Cloudflare", "ADM", "System Ops & Sec", "/admin/infra", "Admin", "P0", "Carte du système",
  intent="Comprendre la topologie réelle (bord, API, données, médias) et son état de santé — sans jamais exposer un secret, "
         "un hôte ou une clé. Une carte pour décider, pas pour la documentation technique.",
  zones=[
    Z("node", "Topologie", 6, "Schéma : PoP Cloudflare → Worker edge (routage, cache, WAF) → API (contrats, paiements) → PostgreSQL via Hyperdrive · R2 (documents, médias) · TURN/STUN (WebRTC). Chaque nœud porte un état et un lien vers sa fiche."),
    Z("kpi", "État des nœuds", 3, "Statut par nœud (nominal, dégradé, incident) · latence inter-nœuds · débit médian."),
    Z("list", "Bord : cache & WAF", 4, "Taux de cache hit · règles WAF actives (nombre) · requêtes bloquées · pics géographiques (pays, jamais d'IP)."),
    Z("cta", "Actions", 1, "« Ouvrir un nœud » or · « Voir le statut public » fantôme."),
  ],
  comps=[("Schéma de topologie", "nœuds cliquables, états colorés"),
         ("États par nœud", "jamais de valeur sensible (hôtes, ports, clés)"),
         ("Bord : métriques agrégées", "cache, WAF, geographic distribution")],
  states=[("Nominal", "tous les nœuds verts."),
          ("Dégradé", "ambre : un nœud lent, causes possibles listées."),
          ("Incident bord", "clay : bascule de routage, statut public activé."),
          ("Mode dégradé assumé", "violet : fonctionnalités non critiques désactivées explicitement (ex. particules, précalculs).")],
  motion=[("Rafraîchissement", "tick 30 s, nœuds qui pulsent brièvement"),
          ("Bascule", "flux de routage qui se redessine 420 ms")],
  rules=["Aucun secret, hôte, port, DSN ou nom de ressource interne n'est affiché : uniquement des états et des métriques agrégées (§3.6).",
         "Chaque nœud est décrit par son rôle fonctionnel, pas par sa configuration technique.",
         "Les bascules de routage sont automatiques et journalisées ; l'action manuelle est bornée et tracée."],
  tokens=["--cyan-500", "--emerald-500", "--clay-500", "--mono", "--glass-1"],
  api=["GET /admin/infra/topology", "GET /admin/infra/nodes/:id/health", "GET /admin/infra/edge/metrics"],
  tech="Les agents internes remontent l'état des nœuds via des endpoints de santé ; la carte est une projection de ces états. "
       "Aucune clé d'accès n'est jamais transmise au navigateur : tout passe par l'API d'admin.",
  canon="ADM — infra (topologie)", chrome=CHROME_ADM),

S("ADM-58", "Infra — Worker edge", "ADM", "System Ops & Sec", "/admin/infra/worker", "Admin", "P1", "La première ligne",
  intent="Superviser le Worker edge : déploiements, invocations, erreurs, règles de routage et de cache. C'est ce qui voit "
         "toutes les requêtes avant l'API — et ce qui doit rester invisible et rapide.",
  zones=[
    Z("kpi", "Bandeau edge", 4, "Invocations 24 h · latence p50/p95 · taux d'erreur (5xx, clay) · taux de cache hit. Aucune version de code exposée publiquement : un identifiant de déploiement interne tronqué si nécessaire."),
    Z("table", "Déploiements", 5, "Colonnes : déploiement (id interne tronqué), date, environnement (prod, préprod), statut, part de trafic, incidents liés, retour arrière disponible."),
    Z("list", "Règles actives", 3, "Routage (par chemin, par méthode) · cache (règles par type de contenu, TTL) · WAF (jeux de règles activés) · redirections. Descriptions fonctionnelles uniquement."),
    Z("cta", "Actions", 1, "« Ouvrir un déploiement » or · « Retour arrière » clay outline (à chaud, journalisé, double validation)."),
  ],
  comps=[("Tuiles edge", "latences et erreurs"),
         ("Table de déploiements", "statut, part de trafic"),
         ("Actions de retour arrière", "double validation, journalisation, effet immédiat affiché")],
  states=[("Nominal", "latence stable, erreurs faibles."),
          ("Déploiement en cours", "violet : canari 5 %, métriques comparées, retour arrière armé."),
          ("Erreurs en hausse", "clay : corrélation avec un déploiement → retour arrière proposé automatiquement."),
          ("Retour arrière", "émeraude après stabilisation, incident lié si service dégradé.")],
  motion=[("Canari", "deux courbes comparées (avant/après) qui se tracent"),
          ("Retour arrière", "bascule claire, statut qui passe émeraude à stabilisation")],
  rules=["Aucune donnée de configuration sensible (clés, buckets, DSN) affichée : seules les règles fonctionnelles et les états.",
         "Tout déploiement en canari expose un retour arrière armé et testé : pas de déploiement sans filet.",
         "Les actions d'infrastructure sont double-validées et journalisées dans le journal d'audit (ADM-56)."],
  tokens=["--cyan-500", "--violet-500", "--clay-500", "--mono"],
  api=["GET /admin/infra/worker", "GET /admin/infra/worker/deployments", "POST /admin/infra/worker/rollback {deploymentId}", "POST /admin/infra/worker/deployments/:id/countersign"],
  tech="Métriques collectées via l'observabilité edge (analytics Cloudflare + traces) ; actions de déploiement via l'API de "
       "la plateforme d'hébergement, médiées par notre API d'admin (aucun jeton en clair côté navigateur).",
  canon="ADM — infra (worker edge)", chrome=CHROME_ADM),

S("ADM-59", "Infra — PostgreSQL & Hyperdrive", "ADM", "System Ops & Sec", "/admin/infra/postgres", "Admin", "P0", "Le cœur des données",
  intent="Surveiller la base de données et le pooling (Hyperdrive) : latences, connexions, requêtes lentes, réplication, "
         "migrations. L'écran montre l'état, jamais les chaînes de connexion.",
  zones=[
    Z("kpi", "Bandeau DB", 4, "Latence requête p95 · connexions actives / pool · requêtes lentes (n, seuil) · état réplication (retard en ms) · dernière migration."),
    Z("timeline", "Charge & latence 24 h", 4, "Courbes : requêtes/s, latence p50/p95, connexions. Seuils de saturation marqués."),
    Z("table", "Requêtes lentes", 5, "Table : requête (forme normalisée, valeurs masquées), appels, latence médiane, index utilisé ou non, origine (service), impact estimé."),
    Z("cta", "Actions", 1, "« Ouvrir une requête » or · « Voir les migrations » fantôme · « Proposer un index » texte (revue obligatoire avant application)."),
  ],
  comps=[("Courbes de charge", "trois séries, seuils"),
         ("Table de requêtes", "forme normalisée, jamais de valeurs de données"),
         ("État de réplication", "retard en ms, alerte si > seuil"),
         ("Migrations", "historique versionné, irréversibles identifiées, fenêtres respectées")],
  states=[("Nominal", "latences et connexions stables."),
          ("Saturation", "ambre : pool proche de la limite → scaling proposé."),
          ("Réplication en retard", "clay : bascule lecture sur primaire si critique, message explicite."),
          ("Migration en cours", "violet : fenêtre annoncée à l'avance, impact estimé affiché (et communiqué via PUB-10 si downtime).")],
  motion=[("Rafraîchissement", "tick 20 s, courbes qui glissent"),
          ("Alerte", "tuile qui pulse une fois, puis sobre")],
  rules=["Aucune chaîne de connexion, aucun hôte, aucun identifiant de base n'est jamais affiché — Hyperdrive est un état, pas une cible (§3.6).",
         "Les requêtes lentes sont affichées sous forme normalisée : aucune valeur de donnée utilisateur.",
         "Toute migration est annoncée, versionnée et répétée en préproduction ; les migrations destructives exigent une double validation.",
         "Un index ne s'applique pas sans revue : les agents proposent, la revue valide."],
  tokens=["--cyan-500", "--amber-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/infra/postgres", "GET /admin/infra/postgres/slow-queries", "GET /admin/infra/postgres/migrations", "POST /admin/infra/postgres/index-proposals"],
  tech="Métriques à partir de l'observabilité de la base et du pooling ; requêtes lentes depuis pg_stat_statements (normalisées). "
       "Toute action structurelle passe par la migration versionnée, jamais par une console SQL depuis le navigateur.",
  canon="ADM — infra (postgres)", chrome=CHROME_ADM),

S("ADM-60", "Infra — R2 & stockage média", "ADM", "System Ops & Sec", "/admin/infra/r2", "Admin", "P1", "Les octets du dossier",
  intent="Superviser le stockage objet : volume, classes, coûts, erreurs, latence de distribution CDN. Le stockage porte "
         "les preuves — sa santé est une affaire de confiance, pas seulement d'octets.",
  zones=[
    Z("kpi", "Bandeau stockage", 4, "Volume total (Go) · objets (n) · coût estimé du mois (or, tnum) · latence de distribution p95 · erreurs d'accès (clay)."),
    Z("timeline", "Volume par classe", 4, "Répartition chaud/froid/archive (barres empilées) + courbe de croissance 30 j. Politique de transition automatique affichée."),
    Z("table", "Préfixes logiques", 5, "Table : domaine (documents, preuves, médias de session, exports), objets, volume, dernière écriture, intégrité des checksums, préfixe logique (jamais de nom de bucket exposé)."),
    Z("cta", "Actions", 1, "« Vérifier l'intégrité d'un préfixe » or (échantillonnage) · « Voir la politique de rétention » fantôme."),
  ],
  comps=[("Barres empilées", "chaud/froid/archive, légende claire"),
         ("Table de préfixes", "domaines fonctionnels, pas d'URL exposée"),
         ("Vérificateur d'intégrité", "échantillon, résultat binaire, rapport signé")],
  states=[("Nominal", "latence basse, erreurs nulles."),
          ("Coût élevé", "ambre : croissance anormale — détection de fuite de stockage (fichiers orphelins) et nettoyage proposé."),
          ("Erreurs d'accès", "clay : URLs signées expirées ou permissions — cause et correctif affichés."),
          ("Intégrité compromise", "clay plein : checksums en échec → incident majeur, restauration depuis réplique.")],
  motion=[("Rafraîchissement", "tick 60 s"),
          ("Vérification", "progression d'échantillonnage, sceau final")],
  rules=["Aucun nom de bucket, de préfixe physique ou d'URL présignée n'est affiché dans cette console : uniquement les domaines fonctionnels (§3.6).",
         "Les transitions de classe de stockage sont automatiques selon l'âge et l'usage : la rétention légale prime sur l'économie.",
         "Les fichiers orphelins (sans référence en base) sont détectés et nettoyés avec journalisation, jamais supprimés silencieusement."],
  tokens=["--cyan-500", "--emerald-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/infra/r2", "GET /admin/infra/r2/prefixes", "POST /admin/infra/r2/verify {prefix}", "GET /admin/infra/r2/retention"],
  tech="Métriques depuis l'API de stockage ; vérification d'intégrité par échantillonnage (checksums) ; aucune clé d'accès "
       "au stockage n'est exposée au navigateur.",
  canon="ADM — infra (R2)", chrome=CHROME_ADM),

S("ADM-61", "Infra — WebRTC & TURN", "ADM", "System Ops & Sec", "/admin/infra/webrtc", "Admin", "P1", "La voix du travail",
  intent="Surveiller l'infrastructure d'appel : sessions actives, qualité (latence, gigue, perte), relais TURN utilisés, "
         "coûts. Les appels de sélection et de médiation doivent fonctionner — sinon, la mission s'arrête.",
  zones=[
    Z("kpi", "Bandeau média", 4, "Sessions actives · taux d'établissement (%) · latence médiane · perte de paquets médiane · recours au TURN (%) · coût estimé du jour (tnum)."),
    Z("timeline", "Qualité 24 h", 4, "Courbes : MOS estimé, gigue, perte. Bandes de qualité (bonne, dégradée, mauvaise) en fond."),
    Z("table", "Sessions en cours", 5, "Table : session (id Mono), type (entrevue, médiation), participants (rôles, jamais de noms en clair), durée, qualité actuelle, relais utilisé (oui/non), pays (agrégé)."),
    Z("cta", "Actions", 1, "« Ouvrir une session (métriques) » or · « Voir un incident média » fantôme."),
  ],
  comps=[("Bandes de qualité", "fond coloré subtil, jamais dominant"),
         ("Table de sessions", "rôles et qualité, pas d'identités"),
         ("Indicateur TURN", "pourcentage de relais — signal de coût et de complexité réseau")],
  states=[("Nominal", "qualité bonne, TURN marginal."),
          ("Dégradé régional", "ambre : perte élevée sur une zone → suggestion de relais supplémentaire."),
          ("Session critique en difficulté", "clay : intervention possible (indication au participant via RTC-07)."),
          ("Panne TURN", "clay plein : bascule vers autre relais, sessions en cours maintenues si possible, incident ouvert.")],
  motion=[("Rafraîchissement", "tick 15 s, courbes média qui glissent"),
          ("Session qui se dégrade", "ligne qui passe ambre progressivement")],
  rules=["Aucun nom de participant, aucune adresse IP complète, aucune URL de serveur TURN n'est affichée : rôles et métriques uniquement (§3.6).",
         "L'enregistrement d'une session n'existe que si les deux parties ont consenti (RTC-05) : cet écran affiche l'état de consentement, jamais le contenu.",
         "Les coûts média sont surveillés comme les coûts de stockage : dérive = alerte."],
  tokens=["--cyan-500", "--amber-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/infra/webrtc", "GET /admin/infra/webrtc/sessions?cursor=", "GET /admin/infra/webrtc/quality", "GET /admin/infra/webrtc/costs"],
  tech="Métriques collectées depuis les SFU/Session servers (stats WebRTC) et les relais TURN ; agrégation côté serveur, "
       "aucune donnée de média n'est stockée sans consentement explicite.",
  canon="ADM — infra (webrtc/turn)", chrome=CHROME_ADM),

S("ADM-62", "Infra — observabilité", "ADM", "System Ops & Sec", "/admin/infra/observabilite", "Admin", "P1", "Voir l'invisible",
  intent="Superviser l'observabilité elle-même : couverture des traces, coût, qualité des alertes. Une plateforme qui "
         "s'observe mal ne peut pas tenir ses promesses.",
  zones=[
    Z("kpi", "Bandeau", 4, "Couverture des traces (% requêtes tracées) · alertes actives (n) · bruit d'alerte (alertes/jour, cible < 5) · coût observabilité du mois (tnum)."),
    Z("table", "Alertes", 5, "Table : alerte, condition, sévérité, déclenchements 7 j, taux d'action (a-t-elle mené à une action ?), dernier déclenchement, propriétaire."),
    Z("list", "Qualité des signaux", 4, "Contrôles : traces orphelines · spans manquants sur chemins critiques (paiement, OTP) · journaux sans corrélation · métriques sans seuil."),
    Z("cta", "Actions", 1, "« Ouvrir une alerte » or · « Simuler un déclenchement » fantôme (test annoncé, jamais en prod réelle)."),
  ],
  comps=[("Table d'alertes", "taux d'action — mesure la qualité, pas le volume"),
         ("Couverture", "chemins critiques listés avec leur état de traçage"),
         ("Coût", "tnum, comparaison mois précédent")],
  states=[("Sain", "couverture > 95 %, bruit faible."),
          ("Bruyant", "ambre : trop d'alertes sans action → révision proposée (alert fatigue)."),
          ("Aveugle", "clay : chemin critique non tracé (ex. OTP) → priorité haute."),
          ("Coût en dérive", "violet : rétention d'échantillonnage ajustable, jamais la couverture des chemins critiques.")],
  motion=[("Rafraîchissement", "tick 60 s"),
          ("Simulation", "déclenchement visible dans un bac à sable, aucune notification réelle")],
  rules=["Les chemins critiques (paiement, OTP, contrat, litige) doivent être tracés à 100 % : le sampling s'applique au reste.",
         "Les alertes sans action mesurable sont révisées ou supprimées : le bruit tue la vigilance.",
         "Aucune donnée personnelle dans les traces : identifiants internes et corrélations uniquement."],
  tokens=["--violet-500", "--cyan-500", "--mono", "--table"],
  api=["GET /admin/infra/observability", "GET /admin/infra/observability/alerts", "POST /admin/infra/observability/alerts/:id/simulate"],
  tech="Auto-observation : la plateforme ingère ses propres métriques/traces et produit des contrôles de couverture ; "
       "les simulations s'exécutent en environnement isolé.",
  canon="ADM — infra (observabilité)", chrome=CHROME_ADM),

S("ADM-63", "Infra — statut global & page publique", "ADM", "System Ops & Sec", "/admin/infra/statut", "Admin", "P0", "Dire la vérité en public",
  intent="Gérer la page de statut publique : composants, incidents, maintenances planifiées. C'est le même contenu que "
         "verront les travailleurs — l'écran d'admin doit garantir sa sincérité, sans possibilité d'embellir.",
  zones=[
    Z("list", "Composants & états", 4, "Liste des composants publics : API, applications, paiements, documents, appels, notifications. Chaque état (opérationnel, dégradé, panne, maintenance) est repris tel quel de la télémétrie, jamais saisi à la main."),
    Z("timeline", "Incidents & maintenances", 4, "Historique public : incidents (avec post-mortems liés), maintenances planifiées (fenêtres, impact, report policy). Publication préparée ici, visible là-bas."),
    Z("kpi", "Sincérité", 3, "Écarts détectés entre télémétrie et état public (clay, indicateur d'honnêteté) · délai médian de publication d'incident · taux de mises à jour dans les délais annoncés."),
    Z("cta", "Actions", 1, "« Publier une mise à jour » or (gabarits contrôlés) · « Prévisualiser la page » fantôme · « Planifier une maintenance » texte."),
  ],
  comps=[("Composants", "état dérivé de la télémétrie — non éditable manuellement"),
         ("Gabarits de publication", "contrôlés, sans jargon, sans ETA inventée"),
         ("Détecteur d'écart", "compare télémétrie et page publique : tout embellissement est signalé"),
         ("Historique public", "incidents et post-mortems liés")],
  states=[("Synchronisé", "émeraude : page publique = réalité télémétrique."),
          ("Écart", "clay : la page publique minimise ou retarde → correction proposée et tracée."),
          ("Maintenance planifiée", "violet : fenêtre annoncée ≥ 24 h avant, échéances reportées automatiquement (PUB-10)."),
          ("Incident majeur", "clay plein : bandeau public actif, mises à jour horodatées obligatoires.")],
  motion=[("Publication", "aperçu public exact qui s'affiche 240 ms avant envoi"),
          ("Écart détecté", "bascule clay immédiate, aucune possibilité de la masquer")],
  rules=["L'état des composants n'est jamais saisi manuellement : il est dérivé de la télémétrie réelle. L'embellissement est structurellement impossible.",
         "Toute maintenance planifiée est annoncée au moins 24 h avant et entraîne le report automatique des échéances contractuelles concernées.",
         "Les mises à jour d'incident respectent la cadence annoncée ; un manquement est lui-même affiché (taux de respect)."],
  tokens=["--emerald-500", "--clay-500", "--violet-500", "--mono", "--glass-1"],
  api=["GET /admin/status/components", "POST /admin/status/updates {template, body}", "POST /admin/status/maintenance {window, impact}", "GET /admin/status/public-preview"],
  tech="La page publique est servie statiquement par le Worker edge (disponible même si l'API est en panne — PUB-10 réutilise "
       "ce socle). Les états proviennent de la télémétrie via KV (TTL 30 s).",
  canon="ADM — infra (statut)", chrome=CHROME_ADM),
]
