# -*- coding: utf-8 -*-
"""FAMILLE 04 · ADMIN — ADM-27 → ADM-39"""
from ..model import S, Z
from .adm_a import CHROME_ADM

SCREENS = [

S("ADM-27", "Litige — fiche de dossier", "ADM", "Litiges, remplacement & réputation", "/admin/litiges/:id", "Admin", "P0", "Dossier contradictoire complet",
  intent="Lire le dossier intégralement : faits, pièces des deux parties, analyses automatiques, historique des échanges. "
         "L'agent doit pouvoir écrire une décision qui résiste à la lecture d'un tiers.",
  zones=[
    Z("hero", "En-tête de dossier", 3, "Référence L-Mono, mission, parties (ids + fiabilité), montant en jeu, étape, SLA restant, agent en charge."),
    Z("chat", "Faits & échanges", 5, "Chronologie contradictoire complète : messages des parties, ajouts tardifs signalés, réponses dans les délais ou hors délais (marqué)."),
    Z("table", "Pièces du dossier", 4, "Table : pièce, partie, type, horodatage, verdict automatique (indicatif), poids relatif calculé, contradictions signalées avec liens."),
    Z("list", "Analyses automatiques", 3, "Résumé factuel généré (déterministe) : chronologie, écarts, éléments manquants. Jamais une recommandation de verdict — l'humain décide."),
    Z("cta", "Actions", 1, "« Ouvrir la décision » or (ADM-29) · « Demander une pièce » fantôme · « Proposer une médiation » texte."),
  ],
  comps=[("Chronologie contradictoire", "messages horodatés, parties identifiées"),
         ("Table de pièces", "verdicts indicatifs + contradictions liées"),
         ("Résumé factuel", "extraction automatique, explicitement non décisionnelle"),
         ("Notes d'agent", "privées, horodatées, jamais dans la motivation")],
  states=[("Instruction", "pièces visibles, délais en cours."),
          ("Complète", "les deux parties ont répondu : décision possible."),
          ("Incomplète (silence)", "délais échus : signalé, la décision peut être rendue sur pièces."),
          ("Recours", "dossier marqué, l'agent auteur ne peut pas traiter le recours.")],
  motion=[("Entrée", "dossier 420 ms, pièces qui s'alignent"),
          ("Contradiction", "trait pointillé clay entre les deux pièces concernées")],
  rules=["Aucune décision ne peut être rendue sans une phase contradictoire complète (au moins une tentative de contact de chaque partie, horodatée).",
         "Le résumé automatique est explicitement étiqueté « extraction, non décisionnel » : jamais présenté comme un avis.",
         "Les notes d'agent ne fondent jamais la décision : seules les pièces et les règles citées comptent.",
         "Récusation possible et tracée en cas de conflit d'intérêts."],
  tokens=["--clay-500", "--amber-500", "--mono", "--glass-1", "--text-mid"],
  api=["GET /admin/disputes/:id/full", "POST /admin/disputes/:id/request-evidence", "POST /admin/disputes/:id/recuse"],
  tech="Assemblage du dossier depuis le service litiges (event store) + R2 pour les pièces. Le résumé automatique est un "
       "algorithme déterministe (extraction + agrégation), pas un modèle génératif.",
  canon="ADM — litige (fiche)", chrome=CHROME_ADM),

S("ADM-28", "Litige — pièces & contradictions", "ADM", "Litiges, remplacement & réputation", "/admin/litiges/:id/pieces", "Admin", "P1", "Vérité matérielle",
  intent="Examiner les pièces matérielles : visionneuse, métadonnées, points de contradiction. C'est ici que se joue la "
         "réalité des faits — avant toute interprétation juridique.",
  zones=[
    Z("list", "Galerie & lecteur", 5, "Visionneuse plein cadre (photo, PDF, vidéo), avec métadonnées affichées : horodatage appareil vs serveur, géolocalisation, appareil émetteur, hash R2."),
    Z("table", "Table comparative", 5, "Table de toutes les pièces : type, partie, technicité (contrôles passés/échoués), contradiction avec quelle autre pièce, pertinence (calculée, expliquée)."),
    Z("kpi", "Synthèse matérielle", 3, "Pièces recevables (n) · non recevables (n, avec motif) · contradictions ouvertes (n) · éléments manquants suggérés."),
    Z("cta", "Actions", 1, "« Ouvrir la décision » or · « Demander une pièce précise » fantôme."),
  ],
  comps=[("Visionneuse", "zoom, comparaison côte à côte de deux pièces"),
         ("Métadonnées techniques", "EXIF, horodatage serveur, appareil, hash"),
         ("Matrice de contradictions", "paires liées, nature de la contradiction"),
         ("Recevabilité", "motifs standardisés (hors délai, illisible, incomplet)")],
  states=[("Concordant", "les pièces se confirment."),
          ("Contradictoire", "clay : paires signalées, comparaison automatique proposée."),
          ("Insuffisant", "ambre : aucun élément décisif, décision « partage » probable."),
          ("Pièce tardive", "ardoise : acceptée mais signalée tardive (jamais rejetée d'office).")],
  motion=[("Comparaison", "deux pièces qui se rapprochent côte à côte 420 ms"),
          ("Contradiction", "surlignage conjoint des zones divergentes (rectangle clay)")],
  rules=["Aucune pièce n'est retirée du dossier : les ajouts sont permanents, y compris tardifs (signalés comme tels).",
         "La recevabilité se juge sur des motifs standardisés affichés, jamais sur l'appréciation libre de l'agent.",
         "Les métadonnées techniques ne suffisent pas à établir un fait : elles éclairent, l'humain interprète."],
  tokens=["--mono", "--clay-500", "--amber-500", "--glass-1"],
  api=["GET /admin/disputes/:id/evidence", "POST /admin/disputes/:id/evidence/:eid/admissibility", "GET /admin/disputes/:id/contradictions"],
  tech="Analyse technique côté serveur (EXIF, hash, cohérence temporelle) ; la visionneuse consomme des variantes R2 "
       "(miniatures, flux HLS court pour vidéo).",
  canon="ADM — litige (pièces)", chrome=CHROME_ADM),

S("ADM-29", "Litige — décision", "ADM", "Litiges, remplacement & réputation", "/admin/litiges/:id/decision", "Admin", "P0", "Rédiger le verdict",
  intent="Écrire une décision motivée qui sera lue par deux parties en conflit : faits retenus, pièces décisives, règles "
         "appliquées, conséquences financières. Chaque phrase doit pouvoir être citée.",
  zones=[
    Z("verdict", "Issue", 4, "Quatre issues : conforme à la demande du client · conforme à la défense du prestataire · partage (répartition chiffrée) · rejet (aucun manquement établi). Chaque issue affiche ses effets automatiques."),
    Z("doc", "Motivation", 6, "Structure imposée : faits retenus (liés aux pièces CL-n) · pièces décisives · règles appliquées (clauses + CGU) · calcul financier · décision. Rédaction assistée par gabarits, jamais vide."),
    Z("price", "Conséquences chiffrées", 4, "Écritures au ledger : montants qui restent dus, remboursements, ajustements, frais. Triplet FIN recalculé si le montant final change ; deltas signés tnum."),
    Z("cta", "Rendre la décision", 2, "« Confirmer et publier » or (double validation si montant > seuil) · « Enregistrer un brouillon » fantôme."),
  ],
  comps=[("Gabarits de motivation", "structures types par nature de litige"),
         ("Liaison pièces", "chaque assertion liée à CL-n cliquable"),
         ("Simulateur d'écritures", "aperçu des lignes au ledger avant application"),
         ("Double validation", "superviseur requis au-delà du seuil")],
  states=[("Brouillon", "rédaction en cours, non publique."),
          ("Contre-signature", "attente superviseur (24 h)."),
          ("Publiée", "émeraude : décision visible des parties, exécution planifiée sous 72 h."),
          ("Infirmée en recours", "si un superviseur renverse : nouvelle décision liée, écriture inverse, traçabilité complète.")],
  motion=[("Application", "écritures qui se posent ligne à ligne 120 ms"),
          ("Publication", "sceau sobre (émeraude/ambre/clay selon issue), notification aux deux parties")],
  rules=["Toute décision est motivée par écrit et lie ses assertions à des pièces : aucune décision « d'autorité ».",
         "Les écritures au ledger sont des compensations : rien n'est supprimé (INV-5).",
         "Double validation obligatoire au-delà du seuil de montant : aucun agent ne décide seul d'un montant important.",
         "Les deux parties voient la même décision, au même moment : aucun accès privilégié.",
         "L'issue « partage » doit comporter un calcul explicite : jamais un « 50/50 » implicite non chiffré."],
  tokens=["--gold-500", "--clay-500", "--emerald-500", "--mono", "--glass-2"],
  api=["POST /admin/disputes/:id/decision {issue, facts, evidenceRefs, ruleRefs, calculation}", "GET /admin/disputes/:id/decision/preview-effects"],
  tech="Rédaction dans un modèle structuré (champs contraints) ; publication génère : décision PDF/A, écritures ledger, "
       "notifications, mise à jour des contrats liés. Opération transactionnelle avec compensation en cas d'infirmation.",
  canon="ADM — litige (décision)", chrome=CHROME_ADM),

S("ADM-30", "Litige — journal des décisions", "ADM", "Litiges, remplacement & réputation", "/admin/litiges/decisions", "Admin", "P1", "Jurisprudence interne",
  intent="Exploiter l'historique des décisions : cohérence, taux d'infirmation en recours, typologies. Sert à améliorer les "
         "règles et à garantir une justice prévisible.",
  zones=[
    Z("table", "Décisions", 6, "Colonnes : date, référence L-Mono, type, issue, montant ajusté, agent (interne), recours (oui/non), issue du recours, durée de traitement."),
    Z("kpi", "Qualité", 3, "Taux d'infirmation en recours (indicateur clé) · délai médian · distribution des issues (barres sobres) · écart de traitement entre agents (détection de divergence, jamais sanction automatique)."),
    Z("list", "Comparateur de dossiers", 3, "Sélection de 2-3 dossiers similaires : mêmes faits, issues différentes ? → signal de calibrage, revue de cohérence proposée."),
    Z("cta", "Actions", 1, "« Ouvrir une revue de cohérence » or outline · « Exporter » fantôme (journalisé)."),
  ],
  comps=[("Table dense", "issues typées, recours liés"),
         ("Indicateur qualité", "taux d'infirmation mis en avant (auto-critique assumée)"),
         ("Comparateur", "dossiers similaires alignés côte à côte")],
  states=[("Stable", "distribution constante."),
          ("Divergence détectée", "violet : revue de cohérence proposée, sans accusation."),
          ("Infirmation élevée", "clay atténué : signal d'un besoin de formation ou de règle plus claire."),
          ("Vide", "aucune décision sur la période.")],
  motion=[("Filtres", "recomposition 240 ms"),
          ("Comparaison", "colonnes qui s'alignent 240 ms, écarts surlignés")],
  rules=["Les indicateurs d'agent servent exclusivement au calibrage collectif et à la formation : jamais de sanction automatique.",
         "Les décisions sont publiques en interne (base de jurisprudence interne) mais anonymisées vers l'extérieur.",
         "Les taux d'infirmation sont publiés dans les revues internes : la modération s'audite elle-même."],
  tokens=["--mono", "--violet-500", "--clay-500", "--table"],
  api=["GET /admin/disputes/decisions?cursor=", "GET /admin/disputes/decisions/analytics", "GET /admin/disputes/decisions/compare?ids="],
  tech="Agrégats sur le journal des décisions ; le comparateur utilise la classification par type de litige (algorithme simple, "
       "mots-clés + structure) pour rapprocher les dossiers.",
  canon="ADM — litige (décision)", variant_of="ADM-29", chrome=CHROME_ADM),

S("ADM-31", "Remplacements — file & suivi", "ADM", "Litiges, remplacement & réputation", "/admin/remplacements", "Admin", "P1", "Transition sous surveillance",
  intent="Suivre tous les remplacements en cours : causes, états, litiges associés, remplaçants trouvés ou non. Les "
         "remplacements sont des points de fragilité — ils méritent une file dédiée.",
  zones=[
    Z("kpi", "Bandeau", 3, "Remplacements en cours (n) · sans remplaçant depuis > 7 j (ambre) · contestés (clay) · réussis 30 j (émeraude)."),
    Z("table", "Remplacements", 6, "Colonnes : mission, motif, prestataire sortant, état (notification, contestation, recherche, bascule, clôturé), ancienneté, remplaçant (id si trouvé), litige lié."),
    Z("list", "Filtres", 2, "Par motif, état, ancienneté, litige associé."),
    Z("cta", "Actions", 1, "« Ouvrir un dossier » or · « Réassigner un agent » fantôme."),
  ],
  comps=[("Table de file", "état du remplacement, ancienneté"),
         ("Badge de motif", "accord mutuel, défaillance, faute alléguée, force majeure"),
         ("Alerte d'enlisement", "remplacement > 7 j sans candidat : proposition d'intervention (accompagnement client)")],
  states=[("Fluide", "remplacements qui se déroulent normalement."),
          ("Enlisé", "ambre : interventions proposées (aide à la recherche, ajustement de prix)."),
          ("Contesté", "clay : procédure contradictoire en cours."),
          ("Échoué", "mission résiliée sans remplaçant : paiement du validé + clôture propre.")],
  motion=[("Rafraîchissement", "tick 30 s"),
          ("Escalade", "ligne qui passe ambre puis clay selon ancienneté")],
  rules=["Un remplacement ne suspend jamais le paiement du travail validé par le sortant.",
         "L'enlisement déclenche un accompagnement (pas une résiliation d'office du client).",
         "Tous les remplacements sont tracés avec leur cause réelle, y compris les accords mutuels."],
  tokens=["--clay-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/replacements?cursor=", "POST /admin/replacements/:id/reassign", "GET /admin/replacements/stats"],
  tech="Read model sur le service de remplacement + service de matching (état de la recherche de remplaçant).",
  canon="ADM — remplacements (file)", chrome=CHROME_ADM),

S("ADM-32", "Remplacement — suivi détaillé", "ADM", "Litiges, remplacement & réputation", "/admin/remplacements/:id", "Admin", "P1", "Dossier de bascule",
  intent="Suivre un remplacement de bout en bout : faits, contestations, passation, paiements des deux prestataires, "
         "continuité de la mission. L'écran sert aussi de dossier de preuve.",
  zones=[
    Z("hero", "En-tête", 3, "Mission, motif, état, dates clés, sortant, entrant, montants dus à chacun (tnum)."),
    Z("timeline", "Déroulé", 5, "Frise complète : notification, décision du sortant (acceptation/contestation), passation, sélection, contrat successeur, clôtures. Chaque étape avec horodatage et pièces."),
    Z("table", "Paiements croisés", 4, "Table : sortant (travail validé dû), entrant (nouveau contrat), frais SaaS des deux, état de chaque versement."),
    Z("cta", "Actions", 1, "« Intervenir » or (relance, médiation, correction) · « Ouvrir le litige lié » fantôme."),
  ],
  comps=[("C-06 TimelineTrack", "déroulé de bascule"),
         ("Table financière double", "deux colonnes symétriques (sortant / entrant)"),
         ("Contestation liée", "lien direct vers le dossier de contestation")],
  states=[("Nominal", "étapes dans les délais."),
          ("Contestation active", "clay sur l'étape concernée."),
          ("Paiement du sortant en retard", "clay : priorité de traitement, relance automatique."),
          ("Clôturé", "émeraude : les deux dossiers soldés, chaîne de succession complète.")],
  motion=[("Étapes", "points qui s'allument 420 ms"),
          ("Intervention", "fly-to vers l'action, journal ajouté")],
  rules=["Les deux prestataires sont payés selon leurs propres contrats : aucune fusion des décomptes.",
         "Le paiement du sortant est prioritaire en cas d'arbitrage de calendrier (« argent déjà gagné »).",
         "La chaîne de succession est conservée sans limite de durée (audit)."],
  tokens=["--gold-500", "--clay-500", "--emerald-500", "--mono"],
  api=["GET /admin/replacements/:id/full", "POST /admin/replacements/:id/intervene"],
  tech="Assemblage multi-services (remplacement, contrats, paiements) avec indicateur d'état par bloc.",
  canon="ADM — remplacements (file)", variant_of="ADM-31", chrome=CHROME_ADM),

S("ADM-33", "Remplacement — arbitrage", "ADM", "Litiges, remplacement & réputation", "/admin/remplacements/:id/arbitrage", "Admin", "P0", "Trancher la bascule",
  intent="Quand un remplacement est contesté, arbitrer : la cause est-elle fondée ? le paiement du sortant est-il correct ? "
         "le remplaçant doit-il reprendre ou le périmètre être ajusté ? Décision motivée, exécutée automatiquement.",
  zones=[
    Z("verdict", "Objet de l'arbitrage", 4, "Trois questions à trancher : fondement de la cause · exactitude du décompte du sortant · validité du périmètre repris par l'entrant. Chacune avec les pièces liées."),
    Z("doc", "Motivation", 5, "Rédaction structurée (faits, pièces, clauses, décision), avec gabarits par motif de remplacement."),
    Z("price", "Effets chiffrés", 4, "Écritures : ajustement du décompte du sortant, correction du périmètre/finance de l'entrant, frais. Aperçu avant application."),
    Z("cta", "Arbitrer", 2, "« Rendre l'arbitrage » or (double validation requise) · « Enregistrer » fantôme."),
  ],
  comps=[("Panneau à trois questions", "chaque question avec réponse motivée"),
         ("Simulateur d'écritures", "aperçu ledger"),
         ("Double validation", "superviseur"),
         ("Notification double", "les deux prestataires + le client, chacun avec sa partie")],
  states=[("À trancher", "dossier complet, CTA or."),
          ("Contre-signature", "attente superviseur."),
          ("Rendu", "effets appliqués, notifications envoyées, recours 7 jours."),
          ("Infirmé", "arbitrage renversé, écritures inverses, dossier d'audit renforcé.")],
  motion=[("Application", "écritures 120 ms, sceau sobre"),
          ("Notification", "deux envois visibles")],
  rules=["L'arbitrage lie un fait à une clause ; sans clause applicable, la règle par défaut est citée.",
         "Le paiement du travail validé n'est jamais réduit par l'arbitrage d'une cause de remplacement.",
         "Double validation au-delà du seuil ; recours unique de 7 jours traité par un autre superviseur."],
  tokens=["--clay-600", "--gold-500", "--mono", "--glass-3"],
  api=["POST /admin/replacements/:id/arbitrate {causeFound, payoutCorrect, perimeterValid, motive, entries}", "GET /admin/replacements/:id/arbitrate/preview"],
  tech="Arbitrage transactionnel : écritures ledger, mise à jour des contrats successeurs, notifications, audit renforcé.",
  canon="ADM — remplacement (arbitrage)", chrome=CHROME_ADM),

S("ADM-34", "Réputation — ledger global & corrections", "ADM", "Litiges, remplacement & réputation", "/admin/reputation", "Admin", "P0", "Grand livre de l'honneur",
  intent="Superviser les écritures de réputation à l'échelle de la plateforme : volumes, corrections, contestations. "
         "Toute correction est une écriture nouvelle, signée, jamais une suppression (INV-5).",
  zones=[
    Z("kpi", "Bandeau", 3, "Écritures 24 h (positives/négatives) · corrections appliquées · contestations en attente (ambre) · délai médian de traitement."),
    Z("table", "Écritures récentes", 5, "Table : date, sujet (id Mono), type, delta, motif, dossier source, agent si correction."),
    Z("form", "Écriture de correction", 4, "Formulaire de correction : sujet, delta compensatoire, motif (≥ 40 c.), référence de dossier obligatoire, aperçu du nouvel état."),
    Z("cta", "Actions", 1, "« Appliquer la correction » or (double validation si impact > seuil) · « Ouvrir le sujet » fantôme."),
  ],
  comps=[("Table d'écritures", "delta signé, motif, source"),
         ("Formulaire de correction", "jamais de valeur absolue : toujours un delta compensatoire"),
         ("Aperçu avant/après", "score et solde, tnum"),
         ("Journal renforcé", "chaque correction est signée et chaînée")],
  states=[("Nominal", "corrections rares."),
          ("Corrections élevées", "ambre : signal de qualité (des bugs ? des décisions erronées ?) → revue proposée."),
          ("Contestation en attente", "violet : priorisation."),
          ("Rupture de chaîne", "clay : audit sécurité immédiat (ADM-56), alerte majeure.")],
  motion=[("Correction", "nouvelle ligne qui s'insère et pointe vers l'originale 240 ms"),
          ("Aperçu", "score qui se recalcule tnum 240 ms")],
  rules=["INV-5 : aucune écriture n'est modifiée ou supprimée, même pour corriger une erreur — la correction est une écriture nouvelle, visible.",
         "Toute correction référence un dossier (contestation, litige, incident) : jamais une correction « à la main » non motivée.",
         "Double validation au-delà du seuil d'impact.",
         "Le sujet concerné est toujours notifié de la correction, avec le motif (transparence)."],
  tokens=["--mono", "--emerald-500", "--clay-500", "--amber-500", "--table"],
  api=["GET /admin/reputation/entries?cursor=", "POST /admin/reputation/entries/corrections {subjectId, delta, motive, caseRef}", "GET /admin/reputation/summary"],
  tech="Service de réputation append-only avec chaînage de hash ; corrections appliquées par écriture compensatoire signée "
       "par l'agent (id interne) et notifiées au sujet.",
  canon="ADM — réputation (ledger & corrections)", chrome=CHROME_ADM),

S("ADM-35", "Réputation — file de contestations", "ADM", "Litiges, remplacement & réputation", "/admin/reputation/contestations", "Admin", "P1", "Écouter les recours",
  intent="Traiter les contestations d'écritures de réputation : vérifier, décider, corriger si nécessaire. Un recours mal "
         "traité détruit la confiance dans tout le système de réputation.",
  zones=[
    Z("table", "File", 5, "Colonnes : date, sujet (id), écriture contestée, motif de contestation, pièces fournies, ancienneté, SLA (5 jours ouvrés), agent."),
    Z("doc", "Dossier comparatif", 5, "Côte à côte : écriture contestée (motif, source, dossier) vs arguments du sujet + pièces. Analyse des faits uniquement."),
    Z("kpi", "Qualité du système", 3, "Taux d'acceptation des contestations 30 j · motifs récurrents · écritures sources les plus contestées (signal de règles à revoir)."),
    Z("cta", "Décider", 1, "« Accepter (corriger) » or · « Rejeter (motivé) » fantôme."),
  ],
  comps=[("Dossier comparatif", "deux colonnes symétriques"),
         ("Analyse de motifs", "catégorisation des contestations"),
         ("Signal d'amélioration", "écritures les plus contestées → revue de règles")],
  states=[("Dans les délais", "SLA affiché."),
          ("Acceptée", "écriture compensatoire + notification + statistique mise à jour."),
          ("Rejetée", "motivation écrite obligatoire, recours unique possible."),
          ("SLA dépassé", "clay : le système a échoué, traitement prioritaire + excuse automatique au sujet.")],
  motion=[("Décision", "bascule sobre (l'issue n'est jamais festive)"),
          ("Correction", "ligne de ledger qui apparaît avec trait de liaison")],
  rules=["Le taux d'acceptation des contestations est un indicateur de qualité du système, affiché sans maquillage.",
         "Un rejet exige une motivation écrite : aucun refus laconique.",
         "Les écritures provenant de procédures automatisées défaillantes sont identifiées et corrigées par lots (pas une à une)."],
  tokens=["--amber-500", "--emerald-500", "--mono", "--table"],
  api=["GET /admin/reputation/contests?cursor=", "POST /admin/reputation/contests/:id/decide {outcome, motive, delta?}"],
  tech="File alimentée par les contestations utilisateurs ; SLA surveillé par jobs. Les décisions créent des écritures "
       "compensatoires liées à la contestation d'origine.",
  canon="ADM — réputation (contestations)", chrome=CHROME_ADM),

S("ADM-36", "Réputation — audit d'intégrité", "ADM", "Litiges, remplacement & réputation", "/admin/reputation/audit", "Admin", "P1", "Vérifier la chaîne",
  intent="Vérifier automatiquement l'intégrité du ledger de réputation (chaîne de hash) et du ledger financier : aucune "
         "réécriture invisible ne doit être possible. La surveillance de la surveillance.",
  zones=[
    Z("kpi", "État de vérification", 4, "Dernière vérification (Mono) · entrées vérifiées · chaîne intègre ✓ / rupture ✕ · prochaine vérification planifiée."),
    Z("table", "Vérifications", 5, "Table : horodatage, périmètre (réputation, financier, contrats, journal d'audit), entrées, résultat, durée, anomalies."),
    Z("list", "Contrôles exécutés", 3, "Chaîne de hash · cohérence des soldes · correspondance écritures/événements sources · détection d'écritures orphelines · cohérence des horodatages."),
    Z("cta", "Actions", 1, "« Lancer une vérification complète » or · « Exporter le rapport » fantôme (signé)."),
  ],
  comps=[("Vérificateur de chaîne", "progression réelle, résultat binaire"),
         ("Tableau des contrôles", "chaque contrôle avec méthode et résultat"),
         ("Rapport signé", "export avec empreinte, usage d'audit")],
  states=[("Intègre", "émeraude : tous les contrôles passent."),
          ("Anomalie", "clay : détail technique immédiat, alerte sécurité, procédure d'incident."),
          ("Vérification en cours", "progression réelle, jamais simulée."),
          ("Non planifiée", "si la dernière vérification date de > 7 jours : rappel ambre.")],
  motion=[("Vérification", "ligne à ligne, compteur d'entrées, sceau émeraude/clay à la fin"),
          ("Anomalie", "isolation de l'entrée concernée avec contexte")],
  rules=["La vérification est automatique (quotidienne) et manuelle à la demande : jamais uniquement sur action humaine.",
         "Une rupture de chaîne est un incident de sécurité majeur : escalation immédiate (ADM-55) et information de la direction.",
         "Les rapports de vérification sont conservés et signés : ils constituent la preuve de l'intégrité dans le temps."],
  tokens=["--emerald-500", "--clay-500", "--mono", "--table"],
  api=["POST /admin/audit/integrity/run {scope}", "GET /admin/audit/integrity/runs", "GET /admin/audit/integrity/report.pdf"],
  tech="Vérificateur dédié parcourant les chaînes de hash côté serveur (streaming, pagination) avec résultat signé et archivé "
       "en R2 froid.",
  canon="ADM — réputation (audit)", chrome=CHROME_ADM),

S("ADM-37", "Documents — registre R2", "ADM", "System Ops & Sec", "/admin/documents", "Admin", "P1", "Catalogue des pièces",
  intent="Superviser les pièces de la plateforme : volumes, types, statuts de vérification, quarantaine. Sans jamais afficher "
         "le contenu des pièces d'identité.",
  zones=[
    Z("kpi", "Bandeau", 4, "Pièces stockées (n) · en vérification (n) · en quarantaine (n, clay) · volume total (Go) · rétention respectée."),
    Z("table", "Registre", 6, "Colonnes : id (Mono), type, propriétaire (id interne), statut, version, date de dépôt, date de vérification, taille, empreinte courte."),
    Z("list", "Filtres", 2, "Par type, statut, période, taille, pays."),
    Z("cta", "Actions", 1, "« Ouvrir une fiche » or · « Voir la quarantaine » fantôme (ADM-39)."),
  ],
  comps=[("Table dense", "statuts typés, empreintes Mono"),
         ("Vue volume", "mini-graphe de stockage 30 j"),
         ("Bandeau de minimisation", "« le contenu des pièces d'identité n'est jamais affiché ici »")],
  states=[("Nominal", "flux normal."),
          ("Quarantaine", "clay : pièces suspectes isolées, liens vers ADM-39."),
          ("Pic de volume", "ambre : stockage approchant d'un seuil, politique de rétention affichée."),
          ("Panne R2", "clay plein : dépôts en attente, aucune perte (files), statut explicite.")],
  motion=[("Rafraîchissement", "tick 60 s"),
          ("Quarantaine", "ligne qui se déplace vers la file quarantaine avec fade")],
  rules=["Le contenu des pièces d'identité n'est jamais consultable depuis le registre général (deux étapes et permission dédiée seulement).",
         "Les empreintes affichées permettent de vérifier l'intégrité sans exposer le contenu.",
         "La rétention est appliquée automatiquement, avec journalisation des suppressions (durée légale, preuve conservée)."],
  tokens=["--surface-1", "--mono", "--clay-500", "--emerald-500", "--table"],
  api=["GET /admin/documents?cursor=&filters=", "GET /admin/documents/storage", "GET /admin/documents/quarantine"],
  tech="Métadonnées en PostgreSQL, objets en R2. Aucune clé d'accès R2 côté client : toutes les consultations passent par "
       "des URLs présignées courtes émises par l'API.",
  canon="ADM — documents (registre)", chrome=CHROME_ADM),

S("ADM-38", "Documents — vérification", "ADM", "System Ops & Sec", "/admin/documents/:id/verification", "Admin", "P0", "Contrôler les pièces",
  intent="Vérifier une pièce (habilitation, assurance, identité) avec une grille standardisée, sans arbitraire, et avec un "
         "motif de rejet actionnable pour le travailleur.",
  zones=[
    Z("doc", "Pièce examinée", 5, "Visionneuse sécurisée (filigrane nominatif, journalisée) : zoom, rotation, comparaison avec la version précédente si existante."),
    Z("list", "Grille de contrôle", 4, "Critères standardisés par type de pièce : lisibilité · validité des dates · cohérence d'identité · conformité légale (légalisation, traduction) · absence de falsification apparente."),
    Z("kpi", "Décision & délai", 3, "« Décision attendue sous 48 h » · impact de la décision (accès aux missions réglementées) · historique du titulaire (rejets antérieurs avec motifs)."),
    Z("cta", "Décider", 2, "« Valider » émeraude · « Rejeter » clay outline (motif obligatoire, actionnable) · « Demander un complément » fantôme."),
  ],
  comps=[("Visionneuse filigranée", "filigrane nominatif de l'agent + horodatage, anti-fuite"),
         ("Grille de contrôle", "cases par critère, traçables"),
         ("Motif de rejet actionnable", "gabarits : « photo floue », « recto manquant », « date expirée »…"),
         ("Journal de consultation", "toute ouverture est journalisée au nom de l'agent")],
  states=[("À vérifier", "file priorisée par impact (missions en attente)."),
          ("Validée", "émeraude, notification au titulaire, mention « vérifié le … »."),
          ("Rejetée", "clay, motif + exemple pour corriger, notification immédiate."),
          ("Complément demandé", "ambre : information manquante précise, délai 48 h.")],
  motion=[("Décision", "sceau (émeraude/clay) sobre 480 ms"),
          ("Filigrane", "opacité 6 %, jamais gênant pour la lecture")],
  rules=["Le visionnage d'une pièce est journalisé avec l'identité de l'agent et le filigraine : dissuasion de fuite.",
         "Les critères de rejet sont standardisés : aucun rejet hors grille, aucune décision discrétionnaire.",
         "Les pièces d'identité ne sont consultables que par les agents habilités, avec double authentification renforcée.",
         "Le rejet doit être actionnable : à défaut, il est considéré comme un défaut de service."],
  tokens=["--emerald-500", "--clay-500", "--amber-500", "--mono", "--glass-2"],
  api=["GET /admin/documents/:id/review", "POST /admin/documents/:id/review/decide {criteria, outcome, rejectReason?}"],
  tech="Visionneuse avec filigrane dynamique côté serveur (pas côté client), URLs présignées de 60 s, journalisation "
       "systématique, grille de contrôle versionnée.",
  canon="ADM — documents (vérification)", chrome=CHROME_ADM),

S("ADM-39", "Documents — quarantaine", "ADM", "System Ops & Sec", "/admin/documents/quarantaine", "Admin", "P0", "Isoler le dangereux",
  intent="Traiter les pièces signalées comme suspectes (falsification apparente, malware, doublon d'identité, contenus "
         "inappropriés). Isolation immédiate, examen, décision et notification.",
  zones=[
    Z("list", "File de quarantaine", 6, "Carte par pièce : raison d'isolement (type de détection), propriétaire (id), contexte (mission/contrat), gravité, date, statut."),
    Z("doc", "Examen sécurisé", 4, "Analyse technique : métadonnées, cohérence, détection de manipulation, doublons (comparaison de hash et de contenu), éventuelle similarité avec d'autres documents."),
    Z("kpi", "Gravité & effets", 3, "« Cette pièce est isolée : elle n'est plus utilisée dans les candidatures. » · impacts (missions bloquées, compte en revue) · délai de traitement."),
    Z("cta", "Décider", 1, "« Lever l'isolement » émeraude · « Confirmer la fraude » clay (mène à ADM-04) · « Demander une pièce alternative » fantôme."),
  ],
  comps=[("Carte d'isolement", "raison, gravité, contexte"),
         ("Comparateur de doublons", "similarité de documents entre comptes"),
         ("Décision structurée", "issue + motifs + effets"),
         ("Sandbox d'examen", "aucune exécution de contenu, analyse statique uniquement")],
  states=[("Isolée", "clay, effets immédiats appliqués."),
          ("En examen", "progression de l'analyse technique visible."),
          ("Levée", "émeraude : pièce restaurée, notification d'excuses si isolement erroné."),
          ("Fraude confirmée", "clay plein : compte en revue, pièce conservée comme preuve (rétention renforcée).")],
  motion=[("Isolement", "la pièce se déplace vers la quarantaine avec fade + sceau clay"),
          ("Levée", "retour de la pièce dans le dossier 420 ms")],
  rules=["L'isolement est immédiat et conservateur : en cas de doute, la pièce est isolée puis examinée (jamais utilisée pendant le doute).",
         "Aucun fichier n'est jamais exécuté ou ouvert hors sandbox ; l'analyse est statique.",
         "Un isolement erroné donne lieu à des excuses explicites et à un examen du détecteur (traçabilité des faux positifs).",
         "Les pièces liées à une fraude confirmée sont conservées comme preuves selon la politique de rétention légale."],
  tokens=["--clay-600", "--clay-500", "--emerald-500", "--mono"],
  api=["GET /admin/documents/quarantine?cursor=", "POST /admin/documents/:id/quarantine/lift", "POST /admin/documents/:id/quarantine/confirm-fraud {motive}"],
  tech="Pipeline de détection (analyse statique, anti-malware, doublons) + file d'examen humaine. Les pièces en quarantaine "
       "sont déplacées vers un préfixe R2 isolé avec accès restreint.",
  canon="ADM — documents (quarantaine)", chrome=CHROME_ADM),
]
