# -*- coding: utf-8 -*-
"""FAMILLE 04 · ADMIN / SUPERVISION — ADM-01 → ADM-13"""
from ..model import S, Z

CHROME_ADM = {"appbar": "SUPERVISION", "dock": ["Flux", "Files", "Litiges", "Sécu", "Infra"], "glyph": "◆"}

SCREENS = [

S("ADM-01", "Dashboard général", "ADM", "Supervision globale", "/admin", "Admin", "P0", "Salle de contrôle",
  intent="Voir l'état de la plateforme en un écran : flux à traiter, incidents ouverts, sécurité, finances du jour. "
         "L'admin doit savoir quoi faire dans les 10 secondes qui suivent l'ouverture.",
  zones=[
    Z("kpi", "Bandeau d'état", 3, "Quatre indicateurs : files en attente (n) · SLA à risque (n, ambre) · incidents sécurité (n, clay) · volume financier du jour (or, tnum)."),
    Z("list", "Files prioritaires", 5, "Quatre files actionnables avec compteur et délai le plus ancien : Qualification revue (ADM-06) · Litiges (ADM-26) · Remplacements (ADM-31) · Documents en vérification (ADM-38)."),
    Z("table", "Activité récente", 4, "Journal compact : dernière heure d'actions système et humaines, colonne acteur (agent, système, cron), lien vers l'objet concerné."),
    Z("timeline", "Santé plateforme", 3, "Mini-graphes 24 h : latence API p95, taux d'erreur, profondeur des queues. Seuils affichés en lignes pointillées."),
    Z("cta", "Actions", 1, "« Ouvrir la file la plus urgente » or · « Basculer en mode incident » clay outline."),
  ],
  comps=[("Tuile KPI", "chiffre tnum, seuil coloré, sparkline 24 h"),
         ("Carte de file", "compteur + ancienneté du plus vieil élément + SLA"),
         ("Journal compact", "acteur typé, horodatage Mono, lien profond"),
         ("Mode incident", "bandeau global visible de tous les admins, actif jusqu'à clôture")],
  states=[("Nominal", "or sobre, aucun seuil franchi."),
          ("Charge", "files > seuil : ambre, priorisation automatique proposée."),
          ("Incident", "clay : bandeau persistant, propriétaire d'incident désigné, timeline dédiée."),
          ("Astreinte", "hors heures : bandeau indique le mode astreinte et le canal d'escalade.")],
  motion=[("Rafraîchissement", "tick 30 s, chiffres qui glissent verticalement 120 ms (jamais de flash global)"),
          ("Alerte", "pulsation ambre 2 400 ms sur la tuile concernée uniquement"),
          ("Mode incident", "bandeau clay qui descend 240 ms, son doux optionnel")],
  rules=["Aucune donnée personnelle affichée sur le dashboard : uniquement des compteurs et des identifiants de dossier.",
         "Les compteurs sont des lectures directes (jamais estimés) ; en cas de source indisponible, la tuile affiche « — » et non un chiffre périmé.",
         "Le mode incident fige la priorisation et journalise toute action dans un fil dédié."],
  tokens=["--surface-0", "--gold-500", "--clay-500", "--amber-500", "--mono", "--emerald-500"],
  api=["GET /admin/overview", "GET /admin/queues/summary", "GET /admin/activity?since=", "GET /admin/health/series?window=24h"],
  tech="Back-office Next.js ; données agrégées par service dédié avec cache 10 s. Flux SSE pour les compteurs, "
       "repli en polling 30 s si SSE indisponible (statut affiché).",
  canon="ADM — dashboard général", chrome=CHROME_ADM),

S("ADM-02", "Utilisateurs — liste & recherche", "ADM", "Supervision globale", "/admin/utilisateurs", "Admin", "P0", "Annuaire opérationnel",
  intent="Retrouver un compte en moins de dix secondes : par identifiant, e-mail masqué, téléphone partiel, référence de "
         "mission ou de contrat. L'écran est un outil de travail, pas un annuaire de surveillance.",
  zones=[
    Z("form", "Recherche & filtres", 3, "Recherche unique multi-critères (id, e-mail, téléphone, mission, contrat) · filtres : rôle (client/prestataire), état (actif, en revue, bloqué, supprimé), pays, date d'inscription, signalements."),
    Z("table", "Table de résultats", 6, "Colonnes : identifiant (Mono), rôle, état, inscription, dernière activité, missions, litiges, signalements. Tri multi-colonnes, densité 40 px."),
    Z("kpi", "Synthèse de sélection", 3, "Sur la sélection : compteurs d'activité, drapeaux (récidive de litige, blocages antérieurs). Aucune donnée personnelle brute."),
    Z("cta", "Actions", 1, "« Ouvrir la fiche » or · « Exporter la sélection » fantôme (CSV journalisé, usage nominatif)."),
  ],
  comps=[("Table dense", "TanStack Table virtualisée, colonnes figées"),
         ("Recherche unique", "debounce 150 ms, indexée serveur"),
         ("Badge d'état", "actif émeraude · en revue ambre · bloqué clay · supprimé ardoise"),
         ("Journal d'export", "tout export nominatif est tracé avec motif obligatoire")],
  states=[("Vide", "invite à saisir un critère ; aucun listing par défaut (principe de minimisation)."),
          ("Résultats", "tri par pertinence puis activité."),
          ("Sélection multiple", "actions groupées limitées (export, revue) — le blocage groupé n'existe pas."),
          ("Accès refusé", "si l'agent n'a pas la permission : écran SYS-04 avec raison et voie de demande d'accès.")],
  motion=[("Frappe", "résultats qui se rafraîchissent sans saut de layout"),
          ("Ouverture de fiche", "ligne qui se déplie en panneau latéral 240 ms"),
          ("Export", "bandeau de traçabilité 3 s")],
  rules=["Aucun listing complet par défaut : la recherche est obligatoire (minimisation des données et traçabilité des accès).",
         "Chaque consultation de fiche est journalisée (qui, quand, quoi) — l'admin le sait et l'écran le rappelle discrètement.",
         "Les e-mails et téléphones sont partiellement masqués sauf nécessité opérationnelle justifiée (déblocage nominatif tracé)."],
  tokens=["--surface-1", "--mono", "--clay-500", "--emerald-500", "--amber-500", "--table"],
  api=["GET /admin/users?q=&role=&state=&cursor=", "POST /admin/exports {type, filters, motive}"],
  tech="Recherche via index dédié (trigram + identifiants) ; pagination curseur. Les exports sont générés en tâche de fond "
       "avec motif obligatoire et journal d'audit signé.",
  canon="ADM — utilisateurs (liste)", chrome=CHROME_ADM),

S("ADM-03", "Fiche utilisateur", "ADM", "Supervision globale", "/admin/utilisateurs/:id", "Admin", "P0", "Dossier opérationnel",
  intent="Voir la situation complète d'un compte : historique de contrats, litiges, réputation, signalements, blocages. "
         "La fiche sert à décider — pas à juger les personnes.",
  zones=[
    Z("hero", "En-tête de compte", 3, "Identifiant (Mono), rôle, état, inscription, dernière activité, drapeaux d'alerte (signalements ouverts, récidive)."),
    Z("kpi", "Indicateurs d'activité", 3, "Missions/contrats (n) · taux de complétion · litiges (n, avec issues) · réputation ou taux de paiement selon le rôle."),
    Z("list", "Historique chronologique", 5, "Journal : inscriptions, contrats, litiges, blocages, corrections, contestations, avec liens vers chaque dossier."),
    Z("table", "Signalements reçus", 3, "Table : date, type, statut, décision. Permet de repérer les schémas, pas d'inférer des intentions."),
    Z("cta", "Actions", 1, "« Envoyer en revue » or · « Bloquer » clay outline (mène à ADM-04) · « Journaliser une note interne » fantôme."),
  ],
  comps=[("En-tête de compte", "identifiant + état + drapeaux"),
         ("Chronologie", "événements typés, liens profonds"),
         ("Notes internes", "visibles admin uniquement, horodatées, jamais utilisées comme décision automatique"),
         ("Bandeau de traçabilité", "« cette consultation est journalisée » — discret mais présent")],
  states=[("Compte sain", "aucun drapeau."),
          ("Compte sous surveillance", "ambre : signalements ≥ 2 ou litiges répétés, sans blocage."),
          ("Compte bloqué", "clay : historique de blocage, motifs, contestations, voie de réexamen."),
          ("Compte supprimé", "ardoise : données anonymisées mais trace légale conservée (contrats, paiements).")],
  motion=[("Ouverture", "panneau 240 ms, chronologie qui se charge en flux"),
          ("Blocage", "transition vers ADM-04, sceau clay à l'issue"),
          ("Note interne", "insertion 120 ms, badge « interne » or discret")],
  rules=["Aucune inférence sensible : la fiche présente des faits (contrats, litiges), jamais des jugements automatiques sur les personnes.",
         "Les notes internes ne sont jamais communicables et ne fondent pas une décision : toute décision cite des faits et une règle.",
         "La consultation est journalisée ; l'accès aux fiches est limité par permission (principe du moindre privilège)."],
  tokens=["--surface-1", "--mono", "--clay-500", "--amber-500", "--text-lo"],
  api=["GET /admin/users/:id", "GET /admin/users/:id/timeline", "POST /admin/users/:id/notes", "POST /admin/users/:id/review"],
  tech="Fiche assemblée depuis plusieurs services (identité, contrats, litiges, réputation) avec appels parallèles et "
       "dégradation partielle (chaque bloc affiche son état de chargement).",
  canon="ADM — utilisateur (fiche)", chrome=CHROME_ADM),

S("ADM-04", "Blocage / déblocage d'un utilisateur", "ADM", "Supervision globale", "/admin/utilisateurs/:id/blocage", "Admin", "P0", "Geste lourd, tracé",
  intent="Prononcer ou lever un blocage avec toutes les garanties : motif obligatoire, portée choisie, durée, notification, "
         "voie de contestation. Aucun blocage en un clic sans trace.",
  zones=[
    Z("form", "Paramètres du blocage", 5, "Portée : suspension simple (lecture seule) · blocage complet · blocage ciblé (retrait de candidature/création) · gel financier conservatoire. Durée : 7/30/90 jours, indéfini (motif aggravant requis). Motif : catégorisé + texte ≥ 40 caractères."),
    Z("list", "Conséquences automatiques", 4, "Liste générée : contrats en cours (maintien, suspension, transfert) · paiements dus (gel ou maintien) · pièces et documents (accès conservé) · réputation (aucune écriture automatique)."),
    Z("kpi", "Garde-fous", 3, "« Toute personne bloquée doit pouvoir contester. » · « Les paiements déjà dus ne sont jamais annulés par un blocage. » · Double validation si blocage indéfini."),
    Z("cta", "Prononcer", 2, "« Confirmer le blocage » clay (double étape : motif puis saisie du mot « CONFIRMER ») · « Annuler » or."),
  ],
  comps=[("Formulaire de portée", "radios explicites, conséquences affichées en direct"),
         ("Simulateur d'effets", "aperçu des effets avant validation (contrats, paiements, accès)"),
         ("Double validation", "contre-signature d'un second agent si blocage indéfini"),
         ("Notification", "gabarit neutre, jamais de motif détaillé côté utilisateur")],
  states=[("Préparation", "motif + portée + durée."),
          ("Contre-signature requise", "attente d'un second agent (traçable, 24 h max)."),
          ("Prononcé", "sceau clay, notification envoyée, dossier créé."),
          ("Contestation", "l'utilisateur peut contester (PUB-09) : la fiche ADM affiche l'état du recours."),
          ("Levée", "sceau émeraude, restauration des accès, journalisation de la levée.")],
  motion=[("Sceau de blocage", "contre-forge clay 640 ms, haptique rigid"),
          ("Levée", "sceau émeraude 480 ms"),
          ("Simulateur", "lignes de conséquences qui se calculent 120 ms")],
  rules=["Motif obligatoire (≥ 40 caractères) et catégorisé : aucun blocage sur simple impression.",
         "Les paiements dus au travailleur ne sont JAMAIS annulés par un blocage : au pire gelés, puis versés après décision.",
         "Les blocages indéfinis exigent une double validation humaine et une revue automatique à 90 jours.",
         "Aucune sanction silencieuse : la personne bloquée est toujours notifiée avec un délai de contestation."],
  tokens=["--clay-500", "--clay-600", "--amber-500", "--mono", "--glass-3"],
  api=["POST /admin/users/:id/block {scope, duration, motive}", "POST /admin/users/:id/unblock", "POST /admin/users/:id/block/countersign"],
  tech="Service de sanctions avec machine d'états (draft → pending_countersign → active → contested → lifted) ; effets "
       "appliqués par orchestration transactionnelle (contrats, paiements, accès) avec compensation en cas d'annulation.",
  canon="ADM — blocage (geste)", chrome=CHROME_ADM),

S("ADM-05", "Journal des blocages", "ADM", "Supervision globale", "/admin/blocages", "Admin", "P1", "Mémoire des sanctions",
  intent="Auditer toutes les sanctions : qui a bloqué qui, pourquoi, quand, avec quelle issue. Cet écran protège les "
         "utilisateurs contre l'arbitraire et les agents contre les soupçons.",
  zones=[
    Z("table", "Registre", 6, "Colonnes : date, utilisateur (id Mono), type de blocage, portée, durée, motif, agent (identifiant interne), statut (actif, levé, annulé en appel), lien fiche."),
    Z("kpi", "Statistiques", 3, "Blocages 30 jours · taux de levée en appel · motif dominant · délai moyen de traitement des recours."),
    Z("list", "Filtres", 2, "Par motif, agent, durée, statut, période."),
    Z("cta", "Actions", 1, "« Exporter » (CSV journalisé) · « Voir un dossier » or outline."),
  ],
  comps=[("Table dense", "tri, filtres, liens profonds"),
         ("Badge de statut", "actif clay · levé émeraude · annulé en appel ardoise"),
         ("Statistiques explicables", "avec définitions et fenêtres")],
  states=[("Vide", "« Aucun blocage sur la période. »"),
          ("Actif", "lignes clay atténuées."),
          ("Appel en cours", "ambre, badge « recours »."),
          ("Annulé en appel", "ardoise : la sanction est conservée dans l'historique mais marquée annulée (leçon organisationnelle).")],
  motion=[("Filtres", "recomposition FLIP 240 ms"),
          ("Export", "traçabilité affichée")],
  rules=["Le registre est immuable : une levée est une écriture nouvelle, jamais une suppression de ligne.",
         "Les statistiques de levée en appel sont visibles : elles mesurent la qualité des décisions, pas seulement l'activité.",
         "L'identité externe des agents n'est jamais exposée dans les exports généraux."],
  tokens=["--mono", "--clay-500", "--emerald-500", "--table"],
  api=["GET /admin/blocks?cursor=&filters=", "GET /admin/blocks/stats", "POST /admin/blocks/export"],
  tech="Lecture depuis le journal de sanctions (append-only). Les exports passent par la même file de traçabilité que ADM-02.",
  canon="ADM — blocage (geste)", variant_of="ADM-04", chrome=CHROME_ADM),

S("ADM-06", "Qualification — file de revue", "ADM", "Qualification & Matching", "/admin/qualification", "Admin", "P0", "File des verdicts en attente",
  intent="Traiter les missions laissées en « Revue » par le moteur : les examiner, décider vite, décider juste. La file "
         "est ordonnée par ancienneté et par risque, jamais par intérêt commercial.",
  zones=[
    Z("kpi", "État de la file", 3, "En attente (n) · SLA à risque (n, ambre) · traitées aujourd'hui · délai médian de traitement."),
    Z("table", "Missions en revue", 6, "Colonnes : référence mission (Mono), client, catégorie, montant total client, motif de revue (règle déclenchée), ancienneté, priorité, lien revue."),
    Z("list", "Filtres", 2, "Par règle déclenchée, catégorie, montant, pays, ancienneté."),
    Z("cta", "Actions", 2, "« Ouvrir la revue » or · « Prendre en charge » fantôme (verrouille l'élément 30 min, évite le doublon)."),
  ],
  comps=[("Table de file", "tri par ancienneté/priorité, badges de règle"),
         ("Badge de règle", "règle déclenchée + article"),
         ("Verrou de prise en charge", "visibilité du verrou pour les autres agents"),
         ("Compteur SLA", "Mono, ambre à 80 % du délai")],
  states=[("File saine", "aucun SLA à risque."),
          ("Surcharge", "ambre : bandeau suggérant renfort ou priorisation par risque."),
          ("Élément verrouillé", "ardoise : agent en charge et temps restant affichés."),
          ("Vide", "« Aucune mission en revue. » (état satisfaisant, pas un échec).")],
  motion=[("Prise en charge", "ligne qui se colore ardoise + badge agent 240 ms"),
          ("Traitement", "ligne qui sort en fondu 240 ms, compteur qui décrémente"),
          ("SLA", "compteur qui bascule ambre puis clay")],
  rules=["Le tri par défaut est l'ancienneté (FIFO) pondérée par le risque : aucun tri par montant ou par client.",
         "Un élément est verrouillé à la prise en charge : deux agents ne traitent jamais la même revue.",
         "Le délai annoncé au client (24 h ouvrées) est un SLA opposable, mesuré et affiché."],
  tokens=["--surface-1", "--amber-500", "--violet-500", "--mono", "--table"],
  api=["GET /admin/qualification/queue?cursor=", "POST /admin/qualification/:id/claim", "GET /admin/qualification/sla"],
  tech="File alimentée par le service de qualification ; verrous distribués (Postgres advisory locks ou Redis) avec TTL 30 min. "
       "Les compteurs SLA sont calculés en SQL sur les échéances.",
  canon="ADM — qualification (file)", chrome=CHROME_ADM),

S("ADM-07", "Qualification — revue humaine", "ADM", "Qualification & Matching", "/admin/qualification/:id", "Admin", "P0", "Examen au cas par cas",
  intent="Examiner une mission signalée par le moteur : lire le dossier complet, voir pourquoi la règle s'est déclenchée, "
         "interroger le client si nécessaire, puis décider. La décision doit être défendable par écrit.",
  zones=[
    Z("hero", "Dossier mission", 4, "Mission intégrale : titre, description, catégorie, lieu, livrables, prix prestataire, total client, client (fiabilité), historique."),
    Z("verdict", "Déclenchement de la revue", 3, "Règles déclenchées avec leur article, score de confiance du moteur, éléments manquants. Deux colonnes : « ce qui inquiète » / « ce qui rassure »."),
    Z("list", "Pièces & contexte", 4, "Pièces jointes, historique client, missions similaires validées (référence utile), signaux externes éventuels (récurrence, cohérence)."),
    Z("chat", "Demande d'information au client", 3, "Fil horodaté : question structurée (pièce manquante, précision juridique), réponse attendue sous 48 h."),
    Z("cta", "Décider", 1, "« Rendre une décision » or (mène à ADM-08) · « Demander un complément » fantôme."),
  ],
  comps=[("Panneau de règles", "règle + article + score"),
         ("Comparateur de précédents", "missions similaires validées, sans révéler les données personnelles"),
         ("Fil de demande", "questions typées, pas de chat libre"),
         ("Checklist d'examen", "trace l'examen réel (chaque bloc lu)")],
  states=[("En examen", "verrou actif, checklist visible."),
          ("Complément demandé", "attente client 48 h, file reprend ensuite."),
          ("Décision prête", "CTA or."),
          ("Abandon/skip", "possible avec motif (récusation si conflit d'intérêts déclaré).")],
  motion=[("Entrée", "dossier puis règles 240 ms chacune"),
          ("Décision", "transition vers ADM-08 avec partage élément")],
  rules=["Conflit d'intérêts : un agent qui connaît le client ou la mission doit se récuser (bouton dédié, tracé).",
         "Aucune décision fondée sur des éléments non écrits dans le dossier : tout ce qui fonde la décision y est annexé.",
         "Le délai de 48 h pour un complément est opposable ; l'absence de réponse n'entraîne jamais une validation par défaut."],
  tokens=["--violet-500", "--gold-500", "--mono", "--glass-1", "--text-mid"],
  api=["GET /admin/qualification/:id", "POST /admin/qualification/:id/request-info", "POST /admin/qualification/:id/recuse"],
  tech="Le dossier de revue est reconstruit depuis le service de qualification (règles + artefacts) et le service mission. "
       "La checklist d'examen est persistée pour l'audit.",
  canon="ADM — qualification (revue)", chrome=CHROME_ADM),

S("ADM-08", "Qualification — décision", "ADM", "Qualification & Matching", "/admin/qualification/:id/decision", "Admin", "P0", "Verdict humain",
  intent="Rendre un verdict motivé : Éligible, Revue prolongée (complément), ou Bloquée. La décision cite ses motifs et "
         "génère automatiquement la communication au client — sans jargon, sans humiliation.",
  zones=[
    Z("verdict", "Choix de verdict", 4, "Trois cartes : Éligible (publication immédiate) · Bloquée (interdiction, motifs) · Complément requis (revue prolongée). Chaque carte indique ses effets."),
    Z("doc", "Motivation structurée", 5, "Champs : règle appliquée · faits constatés · pièces examinées · décision · voie de recours. Génération automatique du texte client à partir de ces champs (modifiable, jamais vide)."),
    Z("kpi", "Effets automatiques", 3, "Publication/dépublication · notification client · délai de recours (7 jours) · journalisation avec identité de l'agent."),
    Z("cta", "Rendre la décision", 2, "« Confirmer la décision » or · « Enregistrer un brouillon » fantôme."),
  ],
  comps=[("Cartes de verdict", "effets listés avant choix"),
         ("Générateur de motivation", "texte client dérivé, éditable"),
         ("Récapitulatif d'effets", "liste exhaustive, y compris notification et recours"),
         ("Signature d'agent", "identifiant interne, horodatage, en Mono")],
  states=[("Brouillon", "décision préparée, non appliquée."),
          ("Publiée", "mission éligible : sceau émeraude, notification immédiate."),
          ("Bloquée", "sceau clay, notification avec motifs et recours."),
          ("Annulée en recours", "si un superviseur infirme : écriture de correction, traçabilité complète.")],
  motion=[("Choix", "carte qui se soulève, effets qui s'affichent 240 ms"),
          ("Application", "sceau (émeraude/clay) 640 ms + notification qui part")],
  rules=["Un blocage exige un motif rattaché à une règle et un texte client compréhensible : aucun refus laconique.",
         "Toute décision est signée (agent + horodatage) et consultable par le client dans son dossier.",
         "Le recours de 7 jours est automatiquement rappelé ; le superviseur qui l'examine est différent de l'auteur de la décision."],
  tokens=["--emerald-500", "--clay-500", "--amber-500", "--mono", "--glass-2"],
  api=["POST /admin/qualification/:id/decision {verdict, ruleRefs, facts, clientText}", "GET /admin/qualification/:id/effects-preview"],
  tech="Application de décision transactionnelle : état mission, notification, journal. Les textes clients sont générés "
       "depuis des gabarits contrôlés, jamais rédigés à la volée par un modèle génératif en production.",
  canon="ADM — qualification (décision)", chrome=CHROME_ADM),

S("ADM-09", "Qualification — historique", "ADM", "Qualification & Matching", "/admin/qualification/historique", "Admin", "P2", "Traçabilité des verdicts",
  intent="Reconstituer l'historique des verdicts pour comprendre les évolutions, détecter les dérives (taux de blocage "
         "anormal par catégorie ou par agent) et améliorer les règles.",
  zones=[
    Z("table", "Verdicts", 6, "Colonnes : date, mission (Mono), verdict, règle, agent (interne), durée de traitement, recours éventuel, issue."),
    Z("kpi", "Distribution", 3, "Répartition des verdicts 30 jours · taux de recours · taux d'annulation en recours · délai médian."),
    Z("list", "Filtres", 2, "Par verdict, règle, agent, catégorie, période."),
    Z("cta", "Actions", 1, "« Exporter » (CSV journalisé) · « Comparer deux périodes » fantôme."),
  ],
  comps=[("Table dense", "tri, filtres, liens"),
         ("Distribution visuelle", "barres sobres par verdict"),
         ("Détecteur de dérive", "alerte si taux de blocage d'un agent s'écarte de la médiane de l'équipe (signal d'amélioration, jamais sanction automatique)")],
  states=[("Nominal", "distribution stable."),
          ("Dérive détectée", "ambre : revue de calibrage proposée (non punitive)."),
          ("Recours élevé", "violet : revue des critères de règles."),
          ("Vide", "aucun verdict sur la période.")],
  motion=[("Filtres", "recomposition 240 ms"),
          ("Comparaison", "deux séries en surimpression avec delta tnum")],
  rules=["Le détecteur de dérive sert au calibrage, jamais à la sanction automatique des agents.",
         "L'historique est immuable ; les corrections en recours apparaissent comme des lignes nouvelles liées.",
         "Aucune donnée personnelle du client n'est exposée dans les exports agrégés."],
  tokens=["--mono", "--violet-500", "--amber-500", "--table"],
  api=["GET /admin/qualification/history?cursor=&filters=", "GET /admin/qualification/analytics", "POST /admin/qualification/export"],
  tech="Agrégats sur vues matérialisées rafraîchies toutes les 15 minutes ; les exports passent par la file de traçabilité.",
  canon="ADM — qualification (décision)", variant_of="ADM-08", chrome=CHROME_ADM),

S("ADM-10", "Matching — runs", "ADM", "Qualification & Matching", "/admin/matching", "Admin", "P1", "Salle des moteurs",
  intent="Surveiller les runs de matching : durée, volume, taux d'échec, version de règles. Le matching est un service : "
         "il doit avoir une salle de contrôle comme les autres.",
  zones=[
    Z("kpi", "Santé du service", 3, "Runs 24 h · durée médiane · taux d'échec · files en attente."),
    Z("table", "Runs récents", 6, "Colonnes : run id (Mono), déclencheur (mission publiée, relance manuelle, cron), mission, candidats évalués, durée, statut, version de ruleset."),
    Z("list", "Filtres", 2, "Par statut, déclencheur, période, version de règles."),
    Z("cta", "Actions", 2, "« Ouvrir un run » or · « Relancer » fantôme (limité, journalisé)."),
  ],
  comps=[("Table de runs", "statut typé, durée Mono"),
         ("Badge de ruleset", "version affichée sur chaque run (traçabilité des scores)"),
         ("Indicateur de file", "profondeur et attente médiane")],
  states=[("Nominal", "runs verts, durée stable."),
          ("Lent", "ambre : durée > seuil + cause probable (charge DB, volume)."),
          ("Échec", "clay : cause, tentatives, lien vers la file d'échecs (ADM-44)."),
          ("Vide", "aucun run sur la période.")],
  motion=[("Rafraîchissement", "tick 15 s"),
          ("Run actif", "ligne qui pulse doucement jusqu'à complétion")],
  rules=["Tout score affiché à un client est rattaché à un run et une version de règles : sans traçabilité, pas de score.",
         "Une relance de run n'écrase pas les résultats précédents : elle produit un nouveau run, l'ancien reste consultable.",
         "Le service de matching ne modifie jamais un contrat ni une candidature : il produit des classements, rien d'autre."],
  tokens=["--violet-500", "--mono", "--emerald-500", "--table"],
  api=["GET /admin/matching/runs?cursor=", "POST /admin/matching/runs/:id/retry", "GET /admin/matching/health"],
  tech="Les runs sont des jobs idempotents tracés en base (run_id, version, entrées, sortie hashée). L'UI lit un read model "
       "temps réel alimenté par le worker.",
  canon="ADM — matching (runs)", chrome=CHROME_ADM),

S("ADM-11", "Matching — détail & audit de biais", "ADM", "Qualification & Matching", "/admin/matching/runs/:id", "Admin", "P0", "Rayons X du moteur",
  intent="Auditer un run : quels candidats, quels scores, quels facteurs, et surtout — les corrélations interdites sont-elles "
         "absentes ? C'est l'écran qui protège LE LABEUR d'un moteur de discrimination.",
  zones=[
    Z("ring", "Résumé du run", 3, "Volume évalué, distribution des scores (histogramme), facteurs les plus discriminants (avec poids), durée, version de règles."),
    Z("table", "Candidats & contributions", 6, "Table : candidat (id anonymisé), score, contributions par facteur (colonnes), drapeaux éventuels (donnée manquante, pièce expirée)."),
    Z("list", "Audit de biais", 4, "Tests automatiques : corrélation score/géographie (surveillée), score/ancienneté d'inscription, score/ratio de prix. Résultats : dans les seuils / à surveiller / hors seuil (clay, avec correctif proposé)."),
    Z("cta", "Actions", 1, "« Exporter l'audit » or outline · « Ouvrir une revue de règles » fantôme."),
  ],
  comps=[("Histogramme de distribution", "barres fines, seuils de score marqués"),
         ("Matrice de contributions", "colonnes par facteur, tnum"),
         ("Tests de biais", "liste de tests avec seuil et résultat"),
         ("Anonymisation", "identifiants courts, ré-identification impossible depuis cet écran")],
  states=[("Conforme", "tous les tests dans les seuils."),
          ("À surveiller", "ambre : corrélation modérée, suivi automatique sur 30 jours."),
          ("Hors seuil", "clay : règle désactivée automatiquement en attente de revue (kill switch par facteur)."),
          ("Run purgé", "si au-delà de la rétention : résumé conservé, détails supprimés (minimisation).")],
  motion=[("Ouverture", "résumé puis matrice 240 ms"),
          ("Détail candidat", "panneau latéral 240 ms avec contributions détaillées"),
          ("Alerte biais", "bascule clay immédiate, ton neutre — c'est un signal technique")],
  rules=["Un facteur qui échoue aux tests de biais est désactivé pour les runs suivants jusqu'à revue (kill switch).",
         "Les identifiants affichés ici sont internes et non ré-identifiables sans permission supplémentaire (journalisée).",
         "Toute donnée discriminatoire en entrée est proscrite : le moteur rejette les champs protégés, il ne les neutralise pas.",
         "Les règles et leurs seuils sont publics (page méthodologie) : la confiance se construit par la transparence."],
  tokens=["--violet-500", "--clay-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/matching/runs/:id", "GET /admin/matching/runs/:id/bias-tests", "POST /admin/matching/factors/:id/disable"],
  tech="Audit calculé côté serveur (tests statistiques simples, seuils documentés) sur les données du run ; kill switch appliqué "
       "au moteur via feature flags versionnés.",
  canon="ADM — matching (audit)", chrome=CHROME_ADM),

S("ADM-12", "Matching — règles & versions", "ADM", "Qualification & Matching", "/admin/matching/rulesets", "Admin", "P1", "Constitution du score",
  intent="Gérer les versions de règles de matching : poids des facteurs, seuils, effets mesurés. Toute modification est "
         "simulée avant activation (shadow scoring) pour éviter de casser l'équité en production.",
  zones=[
    Z("table", "Rulesets", 5, "Table : version, statut (active, en test, archivée), facteurs clés avec poids, date d'activation, effet mesuré (delta de distribution, taux de présélection)."),
    Z("form", "Édition de facteur", 4, "Poids (curseur 0-3), conditions d'application, garde-fous (maximum de poids cumulé, tests de biais obligatoires avant activation)."),
    Z("kpi", "Simulation", 3, "« Shadow scoring sur 500 missions réelles : +8 % de candidats éligibles, distribution inchangée. » Résultats obligatoires avant activation."),
    Z("cta", "Activer", 2, "« Activer la version v8 » or (après simulation et double validation) · « Archiver » fantôme."),
  ],
  comps=[("Éditeur de règles", "formulaire structuré, jamais de code libre"),
         ("Simulation comparée", "deux distributions superposées, deltas tnum"),
         ("Garde-fous", "tests de biais bloquants"),
         ("Historique d'activation", "qui, quand, pourquoi, avec simulation liée")],
  states=[("Active", "émeraude, version courante."),
          ("En test", "violet : shadow scoring, aucun impact utilisateur."),
          ("Bloquée", "clay : tests de biais échoués, activation impossible."),
          ("Archivée", "ardoise, consultable.")],
  motion=[("Simulation", "deux courbes qui se tracent 640 ms"),
          ("Activation", "sceau or + bandeau de version mis à jour partout (le badge ruleset du client change)")],
  rules=["Aucune activation sans shadow scoring et tests de biais : le bouton reste désarmé sinon (et dit pourquoi).",
         "Les changements sont rétroactifs uniquement sur les nouveaux runs : les scores passés restent expliqués par leur version.",
         "Double validation obligatoire (deux agents, dont un superviseur) pour toute modification de poids > 20 %."],
  tokens=["--violet-500", "--gold-500", "--clay-500", "--mono"],
  api=["GET /admin/matching/rulesets", "POST /admin/matching/rulesets/:v/simulate", "POST /admin/matching/rulesets/:v/activate"],
  tech="Les rulesets sont des artefacts versionnés (JSON signé) chargés par le moteur de matching. La simulation rejoue des "
       "missions historiques en shadow, sans toucher à la production.",
  canon="ADM — matching (règles)", chrome=CHROME_ADM),

S("ADM-13", "Contrats — registre", "ADM", "Contrats, exécution & financier", "/admin/contrats", "Admin", "P0", "Grand livre des engagements",
  intent="Voir tous les contrats actifs et leur santé : signature, exécution, paiements, incidents. Le registre sert au suivi "
         "opérationnel et à la production de preuves.",
  zones=[
    Z("chips", "Segments", 2, "Tous · En signature · Actifs · En incident · Terminés · Résiliés · Remplacés."),
    Z("table", "Registre de contrats", 6, "Colonnes : référence (Mono), parties (ids internes), montant total client, prix prestataire, état, échéance prochaine, incidents, drapeaux."),
    Z("kpi", "Synthèse", 3, "Contrats actifs · valeur totale en cours · contrats sans activité 7 j (risque d'abandon) · signatures en attente > 48 h."),
    Z("cta", "Actions", 1, "« Ouvrir un contrat » or · « Exporter le registre » fantôme (journalisé)."),
  ],
  comps=[("Table dense", "tri multi-colonnes, colonnes figées"),
         ("Badge d'état", "7 états, jamais couleur seule"),
         ("Détecteur d'inactivité", "contrats dormants signalés — opportunité d'accompagnement, jamais de résiliation automatique")],
  states=[("Nominal", "peu d'incidents."),
          ("Charge incident", "ambre : incidents > seuil de la semaine."),
          ("Signatures bloquées", "violet : contrats en attente de signature > 48 h, relances possibles."),
          ("Vide", "aucun contrat sur les filtres.")],
  motion=[("Filtres", "recomposition FLIP"),
          ("Alerte", "ligne qui se teinte sobrement, sans clignotement")],
  rules=["Le registre est en lecture majoritairement : les modifications de contrat passent par les flux métier (avenants), jamais par l'admin directement.",
         "Les montants sont affichés en triplet FIN complet, jamais tronqués (même en back-office).",
         "Les exports contiennent des données contractuelles : usage journalisé avec motif."],
  tokens=["--surface-1", "--gold-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/contracts?segment=&cursor=", "GET /admin/contracts/summary", "POST /admin/contracts/export"],
  tech="Read model contrats + agrégats financiers. Les liens profonds ouvrent ADM-14 avec le contexte du registre conservé "
       "(retour arrière préservé).",
  canon="ADM — contrats (registre)", chrome=CHROME_ADM),
]
