# -*- coding: utf-8 -*-
"""FAMILLE 04 · ADMIN — ADM-40 → ADM-52"""
from ..model import S, Z
from .adm_a import CHROME_ADM

SCREENS = [

S("ADM-40", "Documents — audit & rétention", "ADM", "System Ops & Sec", "/admin/documents/audit", "Admin", "P1", "Mémoire et oubli",
  intent="Auditer les accès aux documents et appliquer les politiques de rétention : qui a vu quoi, quand, et quelles "
         "pièces seront supprimées quand. Un écran de conformité, pas de curiosité.",
  zones=[
    Z("table", "Journal d'accès", 6, "Colonnes : horodatage, agent (id interne) ou service, document (id Mono), type d'accès (consultation, téléchargement, présignature), motif, IP tronquée."),
    Z("kpi", "Rétention", 3, "Documents purgés ce mois · prochaine purge planifiée · documents en conservation légale prolongée (litiges, obligations)."),
    Z("list", "Politiques appliquées", 4, "Table des politiques par type de document : durée de conservation, base légale, responsables, exceptions. Chaque politique est versionnée et publique en interne."),
    Z("cta", "Actions", 1, "« Exporter le journal » (journalisé) · « Voir une politique » or outline."),
  ],
  comps=[("Table de journal", "accès typés, IP tronquée (jamais complète)"),
         ("Compteur de rétention", "échéances Mono"),
         ("Politiques versionnées", "base légale affichée pour chaque durée")],
  states=[("Conforme", "aucun accès anormal."),
          ("Accès inhabituel", "ambre : volume ou horaire atypique → vérification demandée."),
          ("Accès non autorisé tenté", "clay : refus journalisé (SYS-04), alerte sécurité."),
          ("Purge en cours", "progression réelle, journalisation de chaque suppression.")],
  motion=[("Filtres", "recomposition 240 ms"),
          ("Alerte", "ligne isolée avec explication")],
  rules=["Les accès aux pièces d'identité sont journalisés individuellement, avec motif : aucun accès « pour voir ».",
         "Les IP sont tronquées dans l'affichage (analytique suffisante, minimisation).",
         "Les purges sont appliquées automatiquement selon la politique, sauf conservation légale motivée (litige en cours)."],
  tokens=["--mono", "--amber-500", "--clay-500", "--table"],
  api=["GET /admin/documents/access-log?cursor=", "GET /admin/documents/retention/policies", "POST /admin/documents/retention/purge"],
  tech="Journal d'accès append-only ; purges en jobs planifiés avec vérification post-purge (empreinte conservée, contenu "
       "supprimé) et journalisation complète.",
  canon="ADM — documents (audit)", chrome=CHROME_ADM),

S("ADM-41", "Notifications — orchestration", "ADM", "System Ops & Sec", "/admin/notifications", "Admin", "P1", "Chef d'orchestre des messages",
  intent="Voir le flux de notifications à l'échelle plateforme : volumes par gabarit, canaux, taux de délivrabilité, files "
         "en attente. Le produit parle aux gens — cet écran vérifie qu'il n'est pas muet.",
  zones=[
    Z("kpi", "Bandeau", 4, "Envoyées 24 h · taux d'ouverture (par canal, indicatif) · échecs (clay) · file en attente (n, ambre)."),
    Z("table", "Par gabarit", 6, "Colonnes : gabarit (OTP, proposition reçue, échéance proche, litige…), canal (push, e-mail, SMS), volume 24 h, échec %, délai médian, état de santé."),
    Z("timeline", "Volume horaire", 3, "Histogramme 24 h toutes catégories, avec marqueurs d'incidents fournisseurs."),
    Z("cta", "Actions", 1, "« Ouvrir un gabarit » or · « Tester un envoi » fantôme (vers un compte de test, journalisé)."),
  ],
  comps=[("Table par gabarit", "santé par gabarit, seuils"),
         ("Histogramme", "barres fines, seuils"),
         ("Test d'envoi", "destinataire de test uniquement, jamais un utilisateur réel")],
  states=[("Nominal", "volumes et taux normaux."),
          ("Échec fournisseur", "clay : bascule vers canal de secours, état explicite, aucune perte de message (files)."),
          ("Pic", "ambre : volume > seuil (campagne d'échéances) — anticipation, files dimensionnées."),
          ("Quiet hours actives", "violet : files retenues pendant les heures calmes (affiché comme un comportement volontaire).")],
  motion=[("Rafraîchissement", "tick 30 s"),
          ("Incident", "tuile concernée qui pulse clay, une fois")],
  rules=["Aucune notification marketing ne figure dans ces volumes : la plateforme n'utilise ces canaux que pour les événements de contrat.",
         "Les heures calmes sont respectées par construction : les files retenues le sont volontairement (visible ici).",
         "Un OTP est toujours envoyé par le canal le plus fiable disponible, avec bascule automatique en cas d'échec."],
  tokens=["--violet-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/notifications/overview", "GET /admin/notifications/templates/health", "POST /admin/notifications/test-send"],
  tech="Service de notification multi-canal avec files par priorité (OTP > transactionnel > rappels). Les métriques sont "
       "agrégées depuis les journaux d'envoi (sans contenu des messages).",
  canon="ADM — notifications (orchestration)", chrome=CHROME_ADM),

S("ADM-42", "Notifications — gabarits & versions", "ADM", "System Ops & Sec", "/admin/notifications/gabarits", "Admin", "P2", "Écrire ce que le produit dit",
  intent="Gérer les gabarits de notification : texte, variables, canaux, langues. Tout changement est versionné et testé — "
         "un gabarit erroné peut dire des choses fausses sur de l'argent.",
  zones=[
    Z("list", "Gabarits", 4, "Liste par catégorie, avec statut (actif, en test, obsolète), langues disponibles, dernière modification."),
    Z("form", "Éditeur de gabarit", 5, "Texte avec variables contrôlées ({{montant}}, {{mission_ref}}, {{date}}), contraintes : les variables financières doivent utiliser les libellés FIN officiels (prix prestataire, total client, jamais « frais » seul)."),
    Z("kpi", "Contrôles", 3, "Vérifications automatiques : variables valides ✓ · libellés financiers conformes ✓ · longueur SMS < 160 c. ⚠ · langue complète ✔."),
    Z("cta", "Actions", 2, "« Enregistrer une version » or · « Prévisualiser » fantôme (aperçu réel avec données fictives)."),
  ],
  comps=[("Éditeur avec variables", "insertion contrôlée, aucune saisie libre de balise"),
         ("Contrôle FIN", "bloque les libellés non conformes (garde-fou automatique)"),
         ("Prévisualisation multi-canal", "push, e-mail, SMS rendus côte à côte")],
  states=[("Valide", "contrôles passés."),
          ("Non conforme", "clay : libellé financier interdit détecté (ex. « frais déduits ») → blocage à l'enregistrement."),
          ("En test", "violet : diffusion à un pourcentage d'utilisateurs volontaires internes."),
          ("Obsolète", "ardoise : remplacé par une version plus récente.")],
  motion=[("Prévisualisation", "trois rendus qui apparaissent 240 ms"),
          ("Enregistrement", "bandeau de version 3 s")],
  rules=["Les gabarits financiers ne peuvent pas employer de formulation ambiguë : le contrôle est automatique et bloquant.",
         "Aucune version de gabarit n'est supprimée : historique complet pour comprendre ce qui a été dit à un utilisateur.",
         "Les langues doivent toutes être complètes : un gabarit partiellement traduit est refusé."],
  tokens=["--surface-1", "--gold-500", "--clay-500", "--mono"],
  api=["GET /admin/notifications/templates", "PUT /admin/notifications/templates/:id", "POST /admin/notifications/templates/:id/validate"],
  tech="Gabarits versionnés en base (jamais de code exécutable), rendus par un moteur de template restreint (variables "
       "whitelistées). Le contrôle FIN est un linter dédié.",
  canon="ADM — notifications (gabarits)", chrome=CHROME_ADM),

S("ADM-43", "Notifications — délivrabilité", "ADM", "System Ops & Sec", "/admin/notifications/delivrabilite", "Admin", "P1", "Vérifier que le message arrive",
  intent="Surveiller la délivrabilité réelle par canal et par opérateur (SMS locaux, e-mail, push) : c'est vital pour les "
         "OTP. Un OTP qui n'arrive pas bloque un salaire.",
  zones=[
    Z("table", "Par fournisseur / opérateur", 6, "Colonnes : canal, opérateur, volume, taux de livraison, latence médiane, échecs (types), statut, bascule automatique active (oui/non)."),
    Z("kpi", "Santé OTP", 4, "OTP livrés < 30 s · OTP en échec (clay) · bascules de canal 24 h · incidents ouverts."),
    Z("timeline", "Latence par heure", 3, "Courbe de latence P50/P95 par canal, seuils marqués."),
    Z("cta", "Actions", 1, "« Forcer une bascule de canal » clay outline (tracé, temporaire) · « Voir un incident » or."),
  ],
  comps=[("Table opérateurs", "taux et latence, seuils"),
         ("Courbe de latence", "deux séries, seuils en pointillés"),
         ("Bascule de canal", "action rare, avec durée limitée et journal")],
  states=[("Nominal", "taux > seuil partout."),
          ("Dégradé", "ambre : un opérateur sous le seuil, bascule automatique activée pour ses numéros."),
          ("Incident", "clay : OTP non délivrés → canal de secours + monitoring renforcé + information des utilisateurs concernés."),
          ("Résolu", "émeraude : retour à la normale, post-mortem lié (ADM-55).")],
  motion=[("Rafraîchissement", "tick 60 s"),
          ("Bascule", "ligne qui s'illumine violet puis revient à la normale")],
  rules=["La livraison d'un OTP est un chemin critique : tout échec déclenche une bascule automatique de canal, sans intervention humaine.",
         "Les numéros en échec sont réessayés avec backoff puis, en dernier recours, une procédure alternative vérifiée (support) est proposée.",
         "Aucun numéro complet n'est affiché : seuls les indicatifs et les préfixes opérateurs."],
  tokens=["--clay-500", "--amber-500", "--emerald-500", "--mono", "--table"],
  api=["GET /admin/notifications/deliverability", "GET /admin/notifications/otp-health", "POST /admin/notifications/failover {channel, scope}"],
  tech="Collecte des accusés de livraison des fournisseurs (webhooks) ; calcul de taux et latences par fenêtre glissante ; "
       "bascule pilotée par feature flags.",
  canon="ADM — notifications (délivrabilité)", chrome=CHROME_ADM),

S("ADM-44", "Ops — queues & jobs", "ADM", "System Ops & Sec", "/admin/ops/queues", "Admin", "P0", "Salle des machines",
  intent="Voir toutes les files de traitement : profondeur, débit, latence, échecs. C'est le pouls technique du produit — "
         "l'admin doit voir une file qui sature avant que les utilisateurs ne s'en aperçoivent.",
  zones=[
    Z("kpi", "Bandeau", 4, "Jobs en attente · débit (jobs/min) · échecs 1 h (clay) · âge du plus ancien job (Mono)."),
    Z("table", "Files", 6, "Colonnes : file, type (email, payout.sync, doc.scan, match.run, otp.send…), profondeur, débit, latence p95, taux d'échec, workers actifs, statut."),
    Z("timeline", "Profondeur 24 h", 3, "Courbe par file principale, seuils marqués, incidents annotés."),
    Z("cta", "Actions", 1, "« Ouvrir une file » or · « Augmenter les workers » fantôme (borné, journalisé) · « Voir la dead-letter » (ADM-48)."),
  ],
  comps=[("Table de files", "seuils par file, statut typé"),
         ("Courbe de profondeur", "une série par file majeure"),
         ("Contrôle de workers", "augmentation bornée, effet affiché après 60 s")],
  states=[("Nominal", "profondeurs faibles, débit stable."),
          ("Saturation", "ambre : une file croît — suggestion de scaling, cause probable."),
          ("Blocage", "clay : débit 0 alors que la file croît → incident, page d'astreinte."),
          ("Backlog historique", "violet : vieux jobs > 24 h, traitement de rattrapage planifié.")],
  motion=[("Rafraîchissement", "tick 15 s, courbes qui glissent"),
          ("Alerte", "file concernée qui pulse ambre/clay, une fois")],
  rules=["Les files critiques (OTP, paiements) ont priorité absolue : toute saturation déclenche une alerte d'astreinte automatique.",
         "Aucune action destructrice depuis cette console : les jobs ne peuvent pas être supprimés en masse (uniquement rejoués avec traçabilité).",
         "Les workers sont dimensionnés automatiquement ; l'action manuelle est une exception bornée et journalisée."],
  tokens=["--violet-500", "--clay-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/ops/queues", "GET /admin/ops/queues/:name/series", "POST /admin/ops/queues/:name/scale {workers, durationMin}"],
  tech="Métriques exposées par les workers (Prometheus/OpenTelemetry) agrégées en base de séries ; console lit en "
       "temps quasi réel (cache 10 s). Aucun accès direct à la file depuis le client : tout passe par l'API d'admin.",
  canon="ADM — ops (queues)", chrome=CHROME_ADM),

S("ADM-45", "Ops — détail d'une file & jobs", "ADM", "System Ops & Sec", "/admin/ops/queues/:name", "Admin", "P1", "Anatomie d'une file",
  intent="Examiner une file en détail : jobs en attente, en cours, échoués, avec leurs tentatives et leurs erreurs. "
         "Sert au diagnostic fin et au rejeu contrôlé.",
  zones=[
    Z("kpi", "État", 3, "Profondeur · en cours · échoués (P1) · temps médian de traitement."),
    Z("table", "Jobs", 6, "Colonnes : id (Mono), type, créé il y a, tentatives (n/max), prochain essai (Mono), état, dernière erreur (tronquée), actions (détails, rejouer)."),
    Z("doc", "Détail d'un job", 4, "Payload résumé (sans données personnelles sensibles), historique des tentatives avec erreurs classées, trace de corrélation (link), dépendances."),
    Z("cta", "Actions", 2, "« Rejouer » or (1 job) · « Rejouer les échecs filtrés » fantôme (limité à 100, journalisé) · « Voir la DLQ » texte."),
  ],
  comps=[("Table de jobs", "état typé, tentatives / max"),
         ("Panneau de détail", "payload résumé, erreurs classées"),
         ("Rejeu contrôlé", "concurrence limitée, journal obligatoire")],
  states=[("Fluide", "peu d'échecs."),
          ("Échecs concentrés", "ambre : un type de job échoue — cause probable affichée."),
          ("Rejeu en cours", "violet : progression, ne pas relancer en parallèle (le bouton se désarme)."),
          ("Payload illisible", "ardoise : job d'un format obsolète (version de schéma) → migration requise, proposée.")],
  motion=[("Détail", "panneau latéral 240 ms"),
          ("Rejeu", "lignes concernées qui repassent en attente 240 ms, compteur mis à jour")],
  rules=["Les payloads affichés sont expurgés des données personnelles : l'admin voit la structure, pas les secrets des gens.",
         "Le rejeu est borné et journalisé (qui, combien, pourquoi) : pas d'action de masse non tracée.",
         "Un job ne peut pas être marqué « réussi » manuellement : il est rejoué ou abandonné (avec motif), jamais maquillé."],
  tokens=["--mono", "--violet-500", "--clay-500", "--table"],
  api=["GET /admin/ops/queues/:name/jobs?cursor=", "GET /admin/ops/jobs/:id", "POST /admin/ops/jobs/:id/retry", "POST /admin/ops/jobs/retry-batch {filter, limit}"],
  tech="Console ops : lecture des métriques de file + API de rejeu bornée. Les payloads sont expurgés par le service "
       "d'admin (allow-list de champs), jamais par le client.",
  a11y=["Table dense mais navigable au clavier : focus visible, raccourcis (j/k, Entrée pour détails)."],
  canon="ADM — ops (jobs)", chrome=CHROME_ADM),

S("ADM-46", "Ops — cron & planifications", "ADM", "System Ops & Sec", "/admin/ops/cron", "Admin", "P1", "Horlogerie de la plateforme",
  intent="Voir toutes les tâches planifiées : prochaine exécution, dernière exécution, durée, échecs. Un cron silencieux qui "
         "échoue est un désastre : ici, il est impossible de l'ignorer.",
  zones=[
    Z("table", "Tâches planifiées", 6, "Colonnes : nom, description, cadence (cron lisible), dernière exécution (statut, durée), prochaine exécution (Mono), échecs consécutifs, propriétaire."),
    Z("kpi", "Santé du planificateur", 3, "Tâches actives · en retard (ambre) · en échec (clay) · tâches désactivées (ardoise, motif affiché)."),
    Z("list", "Alertes de dérive", 4, "Tâches qui dérivent (durée croissante) · tâches qui échouent toujours au même moment · tâches sans effet mesurable depuis 30 j (candidates à la suppression, jamais supprimées automatiquement)."),
    Z("cta", "Actions", 1, "« Exécuter maintenant » or (journalisé) · « Voir l'historique » fantôme."),
  ],
  comps=[("Table de tâches", "cadence lisible, échecs consécutifs visibles"),
         ("Historique d'exécution", "durée et statut par run"),
         ("Détecteur de dérive", "alertes sur durée croissante — signale les problèmes avant la panne")],
  states=[("Nominal", "toutes les tâches à l'heure."),
          ("Retard", "ambre : une tâche n'a pas tourné dans sa fenêtre."),
          ("Échec répété", "clay : 3 échecs consécutifs → alerte d'astreinte."),
          ("Désactivée", "ardoise : motif obligatoire (maintenance, obsolescence).")],
  motion=[("Exécution manuelle", "ligne qui pulse jusqu'à complétion 240 ms"),
          ("Rafraîchissement", "tick 30 s")],
  rules=["Aucune tâche planifiée ne peut être supprimée sans documenter son remplacement : l'horlogerie est critique.",
         "Les tâches financières (payout.sync, relances) ont une priorité de surveillance supérieure aux tâches de confort.",
         "Une tâche désactivée doit avoir un motif et une date de réexamen."],
  tokens=["--mono", "--amber-500", "--clay-500", "--table"],
  api=["GET /admin/ops/cron", "POST /admin/ops/cron/:name/run", "GET /admin/ops/cron/:name/history"],
  tech="Planificateur centralisé avec registre déclaratif (les tâches sont définies en code, listées dynamiquement ici) ; "
       "métriques d'exécution conservées 90 jours.",
  canon="ADM — ops (cron)", chrome=CHROME_ADM),

S("ADM-47", "Ops — détection de dérive & SLO", "ADM", "System Ops & Sec", "/admin/ops/slo", "Admin", "P1", "Tenir la promesse",
  intent="Afficher les SLO de la plateforme et leur consommation : engagement de délai de qualification, de réponse support, "
         "de livraison OTP, de disponibilité. Les promesses doivent être mesurées, pas proclamées.",
  zones=[
    Z("kpi", "Budget d'erreur", 4, "Par SLO : objectif (99,5 %), consommation du budget (barre), état (sain, tendu, épuisé), jours restants dans la fenêtre."),
    Z("table", "SLO détaillés", 6, "Colonnes : SLO, cible, mesuré 7 j / 30 j, budget restant, incidents imputés, propriétaire, actions prévues si épuisement."),
    Z("list", "Actions au titre du budget", 3, "Quand le budget est épuisé : gel des déploiements non critiques, revue d'incident obligatoire, priorisation fiabilité. Affiché comme une règle, pas une suggestion."),
    Z("cta", "Actions", 1, "« Voir un incident imputé » or · « Exporter le rapport » fantôme (signé)."),
  ],
  comps=[("Barres de budget", "consommation, seuils 50/80/100 %"),
         ("Table SLO", "mesures sur deux fenêtres"),
         ("Règles automatiques", "gel de déploiement, revue obligatoire, listées explicitement")],
  states=[("Sain", "budget > 50 % restant."),
          ("Tendu", "ambre : 20-50 % restant, vigilance."),
          ("Épuisé", "clay : gel des déploiements non critiques activé, revue obligatoire."),
          ("En rétablissement", "violet : plan de correction suivi, date de sortie affichée.")],
  motion=[("Rafraîchissement", "tick 60 s, barres animées seulement si changement"),
          ("Épuisement", "bascule clay, bandeau persistant")],
  rules=["Les SLO sont publics en interne et mesurés automatiquement : pas de déclaration manuelle d'incident pour maquiller la mesure.",
         "L'épuisement du budget d'erreur déclenche des conséquences automatiques (gel des déploiements), pas seulement un avertissement.",
         "Les SLO commerciaux (délai de modération, réponse support) figurent ici au même titre que les SLO techniques."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/ops/slo", "GET /admin/ops/slo/:id/history", "GET /admin/ops/slo/report.pdf"],
  tech="Calcul sur séries temporelles (fenêtres glissantes), avec imputation d'incidents ; les règles de budget sont des "
       "politiques versionnées appliquées par la plateforme de déploiement.",
  canon="ADM — ops (SLO)", chrome=CHROME_ADM),

S("ADM-48", "Ops — dead-letter (DLQ)", "ADM", "System Ops & Sec", "/admin/ops/dead-letter", "Admin", "P0", "Là où les messages meurent",
  intent="Traiter les messages définitivement échoués : comprendre pourquoi, corriger, rejouer ou abandonner proprement. "
         "Une DLQ non traitée est une dette silencieuse qui finit en incident utilisateur.",
  zones=[
    Z("kpi", "Bandeau", 4, "Messages en DLQ · âge du plus ancien (Mono) · motifs dominants · messages abandonnés (avec procédure de compensation)."),
    Z("table", "Messages", 6, "Colonnes : id (Mono), file d'origine, type, créé il y a, tentatives, dernier échec (classé), impact utilisateur estimé, action proposée."),
    Z("doc", "Analyse d'un message", 4, "Cause racine probable (corrélations), payload expurgé, dépendances, correctif proposé (code, donnée, configuration), simulation de rejeu."),
    Z("cta", "Actions", 2, "« Rejouer » or · « Abandonner avec compensation » clay outline (écriture compensatoire ou notification utilisateur) · « Créer un incident » fantôme."),
  ],
  comps=[("Table DLQ", "impact utilisateur estimé — priorise le travail"),
         ("Analyse de cause", "corrélations et cause probable"),
         ("Abandon compensé", "jamais d'abandon silencieux : soit rejeu, soit compensation tracée")],
  states=[("Vide", "« Aucun message en échec définitif. » — état idéal, pas un vide gênant."),
          ("Charge", "ambre : accumulation, priorisation par impact utilisateur."),
          ("Cause systémique", "clay : un même type échoue en masse → incident, correctif de code requis."),
          ("Résorbée", "émeraude : DLQ vidée, historique conservé 30 jours.")],
  motion=[("Analyse", "panneau latéral 240 ms, corrélations qui se lient"),
          ("Rejeu", "message qui quitte la DLQ 240 ms, compteur mis à jour")],
  rules=["Aucun message n'est abandonné silencieusement : soit il est rejoué, soit une compensation est produite (paiement, notification, correction).",
         "L'impact utilisateur estimé est affiché : la priorisation se fait sur le préjudice humain, pas sur la simplicité technique.",
         "Les données personnelles des payloads sont expurgées à l'affichage."],
  tokens=["--clay-600", "--clay-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/ops/dlq?cursor=", "GET /admin/ops/dlq/:id/analysis", "POST /admin/ops/dlq/:id/retry", "POST /admin/ops/dlq/:id/abandon {compensation}"],
  tech="Broker avec file de lettres mortes native ; analyse par corrélation d'erreurs ; les compensations sont exécutées par "
       "les services métier concernés (jamais par la console).",
  canon="ADM — ops (dead-letter)", chrome=CHROME_ADM),

S("ADM-49", "Ops — narration d'incident", "ADM", "System Ops & Sec", "/admin/ops/incidents/:id", "Admin", "P0", "Raconter la panne",
  intent="Piloter un incident : chronologie, actions, communications aux utilisateurs, statut. Un bon incident est un incident "
         "raconté honnêtement — c'est l'écran de la transparence envers les travailleurs et les clients.",
  zones=[
    Z("hero", "En-tête d'incident", 3, "Référence INC-Mono, sévérité (1-3), portée (services touchés), statut (détecté, diagnostiqué, atténué, résolu, post-mortem), propriétaire, durée écoulée."),
    Z("timeline", "Chronologie", 6, "Ajout d'entrées horodatées : détection, hypothèses, actions, décisions, communications envoyées. Chaque entrée signée par son auteur (agent ou système)."),
    Z("list", "Communications", 4, "Journal des messages diffusés : bandeau in-app, e-mail, statut public. Gabarits honnêtes, sans jargon, avec impact estimé et prochaine mise à jour."),
    Z("cta", "Actions", 1, "« Ajouter une entrée » or · « Publier une mise à jour » fantôme · « Clore et ouvrir un post-mortem » texte."),
  ],
  comps=[("Chronologie d'incident", "entrées signées, horodatage Mono"),
         ("Gabarits de communication", "honnêtes, sans ETA inventée"),
         ("Post-mortem lié", "document structuré, publié en interne")],
  states=[("Détecté", "clay : bandeau public actif."),
          ("Atténué", "ambre : impact réduit, communication mise à jour."),
          ("Résolu", "émeraude : bandeau retiré, post-mortem en cours."),
          ("Post-mortem", "violet : analyse publiée, actions suivies dans ADM-47.")],
  motion=[("Entrée", "insertion 240 ms, surlignage 3 s"),
          ("Communication", "envoi visible vers les canaux concernés")],
  rules=["Les communications publiques n'annoncent jamais d'ETA inventée : elles disent ce qui est su, quand la prochaine mise à jour aura lieu.",
         "Les incidents touchant les paiements ou les OTP reçoivent une communication automatique aux personnes concernées.",
         "Le post-mortem est obligatoire pour tout incident de sévérité 1 ou 2, publié en interne dans les 5 jours."],
  tokens=["--clay-500", "--amber-500", "--emerald-500", "--mono", "--glass-1"],
  api=["GET /admin/ops/incidents/:id", "POST /admin/ops/incidents/:id/entries", "POST /admin/ops/incidents/:id/broadcast {template, channels}"],
  tech="Gestion d'incident maison reliée au système de statut public ; les diffusions passent par le service de notification "
       "avec priorité maximale et contournement des heures calmes (incident = urgence légitime).",
  canon="ADM — ops (incident)", chrome=CHROME_ADM),

S("ADM-50", "Sécurité — dashboard", "ADM", "System Ops & Sec", "/admin/securite", "Admin", "P0", "Muraille visible",
  intent="Vue d'ensemble de la posture de sécurité : détections, verrous, anomalies d'accès, incidents. L'écran doit "
         "permettre de distinguer le bruit du signal en dix secondes.",
  zones=[
    Z("kpi", "Bandeau", 4, "Détections 24 h (par famille : IDOR, replay, rate-limit, webhooks) · comptes verrouillés · incidents ouverts · dernier audit d'intégrité."),
    Z("table", "Détections récentes", 6, "Colonnes : horodatage, famille, sévérité, acteur (id ou IP tronquée), ressource visée (type, jamais l'ID complet si sensible), action automatique prise, statut."),
    Z("list", "Posture par domaine", 4, "Quatre tuiles : authentification (échecs, verrous, tentatives) · autorisation (refus, IDOR) · intégrité (signatures, replays) · disponibilité (rate limits, IP bloquées)."),
    Z("cta", "Actions", 1, "« Ouvrir une famille » or · « Voir l'audit d'intégrité » fantôme (ADM-36)."),
  ],
  comps=[("Table de détections", "sévérité typée, action automatique affichée"),
         ("Tuiles de posture", "seuils et tendances"),
         ("Marqueur de faux positif", "chaque détection peut être qualifiée, alimente le calibrage")],
  states=[("Calme", "peu de détections, aucun incident."),
          ("Actif", "ambre : détections en hausse, surveillance renforcée."),
          ("Attaque", "clay : motif coordonné détecté, procédures automatiques déclenchées (blocages, captcha, throttling)."),
          ("Post-incident", "violet : revue en cours, durcissements planifiés.")],
  motion=[("Rafraîchissement", "tick 15 s"),
          ("Détection critique", "ligne isolée avec halo clay une fois, puis sobre")],
  rules=["Aucun identifiant sensible complet n'est affiché : les ressources visées sont décrites par type et empreinte courte.",
         "Les actions automatiques (blocage, throttling) sont toujours visibles et réversibles avec traçabilité.",
         "Toute détection de sévérité haute crée un incident (ADM-49) automatiquement."],
  tokens=["--clay-500", "--violet-500", "--mono", "--table", "--emerald-500"],
  api=["GET /admin/security/overview", "GET /admin/security/detections?cursor=", "POST /admin/security/detections/:id/qualify {verdict}"],
  tech="Agrégation depuis les services de sécurité (WAF Cloudflare, traces applicatives, journaux d'auth). Les IP sont "
       "tronquées ; les identifiants de ressource sont hashés courts.",
  canon="ADM — sécurité (dashboard)", chrome=CHROME_ADM),

S("ADM-51", "Sécurité — IDOR & contrôles d'accès", "ADM", "System Ops & Sec", "/admin/securite/idor", "Admin", "P0", "Tentatives de franchissement",
  intent="Traiter les tentatives d'accès à des ressources non autorisées (IDOR) : identifier le motif (bug applicatif ou "
         "attaque), corriger, et vérifier qu'aucune donnée n'a fuité.",
  zones=[
    Z("table", "Tentatives", 6, "Colonnes : horodatage, acteur (id tronqué), ressource visée (type + empreinte), relation d'autorisation attendue, résultat (refusé ✓), récurrence, statut."),
    Z("doc", "Analyse", 4, "Détail : endpoint, paramètre manipulé, politique d'autorisation appliquée, réponse (refus), contexte (session, appareil), similarité avec d'autres tentatives."),
    Z("kpi", "Qualification", 3, "Tentatives uniques vs récurrentes · acteurs distincts · corrélation avec des comptes légitimes (bug présumé) · corrélation avec plages suspectes (attaque)."),
    Z("cta", "Actions", 1, "« Qualifier » or (bug / attaque / test légitime) · « Ouvrir un correctif » fantôme · « Renforcer la règle » texte."),
  ],
  comps=[("Table des tentatives", "résultat toujours visible (refusé, jamais de fuite silencieuse)"),
         ("Corrélateur", "regroupe par acteur et par endpoint"),
         ("Qualification", "bug, attaque ou test — chaque voie a ses suites")],
  states=[("Refus systématique", "émeraude : la défense a tenu, aucune donnée exposée."),
          ("Motif unique", "bug applicatif probable → correctif prioritaire."),
          ("Motif coordonné", "clay : attaque — durcissement automatique + blocage."),
          ("Fuite suspectée", "clay plein : procédure d'incident majeure, notification réglementaire évaluée.")],
  motion=[("Corrélation", "lignes qui se regroupent 240 ms"),
          ("Qualification", "bascule sobre + suites listées")],
  rules=["Toute tentative refusée est journalisée avec la politique appliquée : la défense doit être auditable.",
         "Une fuite suspectée déclenche immédiatement la procédure d'incident majeure et l'évaluation d'une notification réglementaire.",
         "Aucun test de sécurité non autorisé : les tests internes sont déclarés et identifiés (marqueur), pour ne pas polluer la file.",
         "Aucune donnée personnelle exposée dans l'analyse (identifiants tronqués)."],
  tokens=["--clay-600", "--clay-500", "--emerald-500", "--mono"],
  api=["GET /admin/security/idor?cursor=", "POST /admin/security/idor/:id/qualify {verdict, notes}", "POST /admin/security/idor/:id/reinforce"],
  tech="Détection issue des contrôles d'autorisation centralisés (policy engine) : chaque refus remonte un événement structuré "
       "avec endpoint, acteur et politique. Corrélation en base d'événements.",
  canon="ADM — sécurité (IDOR)", chrome=CHROME_ADM),

S("ADM-52", "Sécurité — replay & signatures", "ADM", "System Ops & Sec", "/admin/securite/replay", "Admin", "P0", "Le temps ne se répète pas",
  intent="Détecter les rejeux de requêtes et les signatures invalides : webhooks rejoués, tokens réutilisés, horodatages "
         "manipulés. Protège l'intégrité des opérations financières et des preuves.",
  zones=[
    Z("table", "Détections", 6, "Colonnes : horodatage, type (replay de webhook, signature invalide, token réutilisé, horodatage décalé), source (fournisseur, client, interne), ressource, résultat (bloqué), récurrence."),
    Z("doc", "Analyse de cas", 4, "Détail : en-têtes de signature (masqués en partie), fenêtre temporelle, comparaison avec l'original, verdict de blocage, impact potentiel si non bloqué."),
    Z("kpi", "Intégrité", 3, "Rejeux bloqués 24 h · signatures invalides · sources en anomalie · dernière rotation de secret (affichée en état, jamais les valeurs)."),
    Z("cta", "Actions", 1, "« Qualifier » or · « Faire tourner un secret » clay outline (procédure guidée, sans afficher la valeur) · « Contacter le fournisseur » fantôme."),
  ],
  comps=[("Table de détections", "source typée, résultat"),
         ("Analyse comparative", "original vs rejeu, différences surlignées"),
         ("Rotation de secret", "procédure guidée : nouvelle version créée, ancienne conservée pour grâce, jamais affichée")],
  states=[("Sain", "aucune détection."),
          ("Rejeux isolés", "ambre : source identifiée, exclusion de fenêtre (horloge) vérifiée avant accusation."),
          ("Motif coordonné", "clay : blocage de la source, incident ouvert."),
          ("Faux positif", "ardoise : fenêtre de tolérance ajustée, calibrage documenté.")],
  motion=[("Analyse", "comparaison qui se déplie 240 ms, différences surlignées"),
          ("Rotation", "étapes guidées, sceau émeraude à la fin (jamais de valeur affichée)")],
  rules=["Aucun secret n'est jamais affiché, même partiellement, même à un administrateur : seuls les états (actif, en rotation, révoqué) sont visibles (§3.6).",
         "Avant de qualifier un rejeu, la fenêtre d'horloge des partenaires est vérifiée : un décalage réseau n'est pas une attaque.",
         "Les rotations de secrets sont guidées, journalisées et double-validées pour les secrets critiques."],
  tokens=["--clay-500", "--violet-500", "--mono", "--table"],
  api=["GET /admin/security/replay?cursor=", "POST /admin/security/replay/:id/qualify", "POST /admin/security/secrets/:id/rotate"],
  tech="Vérification de signature et anti-rejeu côté bord (Worker) et côté API : horodatage + nonce + fenêtre glissante. "
       "Les secrets sont gérés par un coffre (aucune valeur en base, aucune valeur en logs, aucune valeur en UI).",
  canon="ADM — sécurité (replay)", chrome=CHROME_ADM),
]
