# -*- coding: utf-8 -*-
"""FAMILLE 04 · ADMIN — ADM-14 → ADM-26"""
from ..model import S, Z
from .adm_a import CHROME_ADM

SCREENS = [

S("ADM-14", "Contrat — fiche admin", "ADM", "Contrats, exécution & financier", "/admin/contrats/:id", "Admin", "P0", "Dossier contractuel complet",
  intent="Examiner un contrat en tant qu'opérateur : versions, signatures, exécution, paiements, incidents. Sert au support "
         "de niveau 2 et aux procédures de litige.",
  zones=[
    Z("hero", "En-tête", 3, "Référence (Mono), état, parties (ids), dates, montants FIN complets, drapeaux d'incident."),
    Z("timeline", "Vie du contrat", 4, "Frise complète : proposition, signatures (horodatages + empreintes), jalons d'exécution, échéances, avenants, incidents. Chaque point ouvre l'événement source."),
    Z("table", "Versions & signatures", 4, "Table : version, date, auteur, état de signature (deux parties), empreinte, diff disponible."),
    Z("doc", "Pièces", 3, "C-11 : pièces du contrat, preuves d'exécution, reçus, décisions de litige liées."),
    Z("cta", "Actions", 1, "« Ouvrir le contrat (vue lecture) » or · « Ajouter une note interne » fantôme · « Escalader » texte."),
  ],
  comps=[("C-06 TimelineTrack", "vie contractuelle complète"),
         ("Table de versions", "empreintes Mono, diffs liés"),
         ("Notes internes", "jamais visibles des parties"),
         ("Bandeau de permission", "affiche le niveau d'accès de l'agent (lecture, action, financier)")],
  states=[("Actif sain", "aucun drapeau."),
          ("En incident", "clay atténué, lien vers ADM-15."),
          ("Contesté", "violet : litige lié, paiements gelés visibles."),
          ("Audit demandé", "ardoise : dossier marqué pour revue de conformité.")],
  motion=[("Entrée", "en-tête puis frise 240 ms"),
          ("Ouverture de version", "panneau latéral 240 ms avec diff")],
  rules=["L'admin ne modifie jamais un contrat directement : toute action passe par un flux métier tracé (avenant, décision de litige).",
         "Les empreintes sont affichées complètes en back-office (usage d'audit), jamais tronquées.",
         "Les notes internes ne sont jamais des décisions : elles n'ont aucun effet automatique."],
  tokens=["--surface-1", "--gold-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/contracts/:id", "POST /admin/contracts/:id/notes", "GET /admin/contracts/:id/versions"],
  tech="Assemblage multi-services (contrat, exécution, paiements, litiges) en parallèle avec dégradation partielle et "
       "indicateur d'état par bloc.",
  canon="ADM — contrat (fiche)", chrome=CHROME_ADM),

S("ADM-15", "Contrat — incidents", "ADM", "Contrats, exécution & financier", "/admin/contrats/:id/incidents", "Admin", "P1", "Registre d'incidents",
  intent="Suivre les incidents d'un contrat (retards, preuves refusées, obstacles signalés, absence de réponse) pour "
         "intervenir avant le litige. La prévention est l'activité principale de la modération.",
  zones=[
    Z("table", "Incidents", 6, "Colonnes : date, type, partie à l'origine, gravité (1-3), état (ouvert, en cours, résolu, escaladé), action engagée, échéance."),
    Z("kpi", "Risque de litige", 3, "Score de risque calculé à partir des incidents (explicable : type, fréquence, ancienneté) + recommandation d'action (relance, médiation préventive, revue)."),
    Z("list", "Actions préventives", 4, "Propositions concrètes : relance automatique du client, check-in du prestataire, proposition de médiation anticipée, ajustement d'échéance."),
    Z("cta", "Actions", 1, "« Engager une action préventive » or · « Créer un incident » fantôme (saisie manuelle motivée)."),
  ],
  comps=[("Table d'incidents", "gravité typée, échéances Mono"),
         ("Score de risque", "décomposition visible, jamais une note magique"),
         ("Actions préventives", "catalogue d'interventions tracées")],
  states=[("Stable", "peu d'incidents, aucune action."),
          ("À surveiller", "ambre : deux incidents ouverts."),
          ("Risque élevé", "clay : incident grave ou accumulation ; médiation proposée."),
          ("Résolu", "émeraude : incidents clos avec issue documentée.")],
  motion=[("Tri", "recomposition FLIP"),
          ("Action préventive", "fly-to vers le dossier concerné, statut mis à jour 240 ms")],
  rules=["Toute intervention préventive est tracée avec son effet mesuré (a-t-elle évité le litige ?).",
         "Le score de risque n'écrit jamais dans la réputation : il guide l'action humaine, il ne sanctionne pas.",
         "Aucune action préventive ne peut modifier un contrat sans accord des parties."],
  tokens=["--clay-500", "--amber-500", "--violet-500", "--mono"],
  api=["GET /admin/contracts/:id/incidents", "POST /admin/contracts/:id/incidents", "POST /admin/contracts/:id/preventions {type}"],
  tech="Détection d'incidents par règles (jobs) + saisie manuelle. Le score de risque est recalculé à chaque ouverture, "
       "avec ses facteurs exposés.",
  canon="ADM — contrat (incidents)", chrome=CHROME_ADM),

S("ADM-16", "Contrat — révision forcée (décision de modération)", "ADM", "Contrats, exécution & financier", "/admin/contrats/:id/revision-forcee", "Admin", "P0", "Écrire la loi du dossier",
  intent="Quand la modération doit modifier un contrat contre la volonté d'une partie (issue de litige), l'écran impose la "
         "procédure : base légale, motivation, effets, notification, recours. Un acte exceptionnel, encadré.",
  zones=[
    Z("form", "Paramètres de la révision", 5, "Type : ajustement de montant · modification de périmètre · prolongation · résiliation forcée · inscription de réputation. Base : décision de litige (référence obligatoire). Motif détaillé (≥ 60 caractères)."),
    Z("doc", "Nouvelle version R2", 4, "Aperçu de la version produite : clauses modifiées, nouvelles valeurs (montants tnum), mention explicite « révision par décision de modération, réf. L-2026-0007 »."),
    Z("kpi", "Garde-fous", 3, "« Double validation superviseur obligatoire. » · « Notification immédiate aux deux parties, avec voie de recours. » · « Journalisation complète, agent identifié. »"),
    Z("cta", "Appliquer", 2, "« Confirmer la révision » clay (double signature) · « Annuler » or."),
  ],
  comps=[("Formulaire encadré", "champs obligatoires, base légale référencée"),
         ("Aperçu de version", "diff complet avant application"),
         ("Double signature", "deux agents, identités journalisées"),
         ("Bloc de notification", "texte envoyé aux parties, relu avant envoi")],
  states=[("Préparation", "brouillon non appliqué."),
          ("Contre-signature", "attente du superviseur, 24 h max."),
          ("Appliquée", "version R2 active, notifications envoyées, recours 7 jours rappelé."),
          ("Annulée", "si erronée : correction publiée, dossier d'audit renforcé.")],
  motion=[("Application", "sceau clay 640 ms, haptique rigid — acte exceptionnel"),
          ("Notification", "deux envois visibles qui partent vers les parties")],
  rules=["Une révision forcée exige une décision de litige préalable : la référence est obligatoire, le système le vérifie.",
         "Double validation obligatoire, y compris hors heures ouvrées (astreinte superviseur).",
         "Les parties conservent un recours de 7 jours : la révision est appliquée mais peut être infirmée par un superviseur différent.",
         "Aucune révision forcée ne peut priver un travailleur de sa rémunération pour un travail validé."],
  tokens=["--clay-600", "--clay-500", "--mono", "--glass-3", "--gold-500"],
  api=["POST /admin/contracts/:id/forced-revision {type, legalBasis, motive, patch}", "POST /admin/contracts/:id/forced-revision/countersign"],
  tech="Opération sensible : génération d'une version R2 signée par la plateforme, application transactionnelle, notification, "
       "verrou d'audit renforcé (double écriture journal + objet immuable R2).",
  canon="ADM — contrat (révision forcée)", chrome=CHROME_ADM),

S("ADM-17", "Contrat — journal d'audit", "ADM", "Contrats, exécution & financier", "/admin/contrats/:id/journal", "Admin", "P1", "Mémoire probatoire",
  intent="Reconstituer l'histoire complète d'un contrat, à la seconde près, pour répondre à une réquisition, un litige ou "
         "un audit interne. Chaque ligne est signée et vérifiable.",
  zones=[
    Z("table", "Journal", 6, "Colonnes : horodatage (Mono, millisecondes), acteur (utilisateur/admin/système, id interne), action, objet touché, valeurs avant/après (delta compact), empreinte d'événement."),
    Z("kpi", "Intégrité", 3, "Chaîne d'empreintes vérifiée ✓ · nombre d'événements · plage temporelle · signale toute rupture de chaîne (clay, jamais masquée)."),
    Z("list", "Filtres", 2, "Par acteur, type d'action, période, source (client, prestataire, admin, système)."),
    Z("cta", "Actions", 1, "« Vérifier l'intégrité » or (recalcule les empreintes) · « Exporter le journal (JSON signé) » fantôme."),
  ],
  comps=[("Table de journal", "horodatage milliseconde, deltas compacts"),
         ("Vérificateur d'intégrité", "recalcul de chaîne, résultat binaire et daté"),
         ("Export signé", "JSON + manifeste d'empreintes, usage juridique")],
  states=[("Intègre", "émeraude : vérification réussie."),
          ("Rupture détectée", "clay : alerte immédiate, audit sécurité automatique (ADM-56), le journal reste consultable mais marqué."),
          ("Volumineux", "pagination par jour, estimation de taille affichée."),
          ("Vide", "aucun événement (contrat tout juste créé).")],
  motion=[("Vérification", "progression réelle ligne à ligne, sceau émeraude à la fin"),
          ("Rupture", "ligne concernée isolée visuellement avec explication technique")],
  rules=["Le journal est chaîné par empreintes : toute altération est détectable et signalée.",
         "L'export contient les données techniques nécessaires à un usage probatoire, pas de données personnelles superflues.",
         "Aucun agent ne peut écrire manuellement dans le journal : il est produit par les services."],
  tokens=["--mono", "--emerald-500", "--clay-500", "--table"],
  api=["GET /admin/contracts/:id/journal?cursor=", "POST /admin/contracts/:id/journal/verify", "GET /admin/contracts/:id/journal/export"],
  tech="Event store append-only chaîné (hash prev) ; la vérification recalcule la chaîne côté serveur (jamais côté client). "
       "Les exports sont signés et horodatés.",
  canon="ADM — contrat (journal)", chrome=CHROME_ADM),

S("ADM-18", "Paiements — vue globale", "ADM", "Paiements & Réconciliation", "/admin/paiements", "Admin", "P0", "Tour de contrôle financier",
  intent="Surveiller l'argent qui circule : volumes, encaissements, décaissements, échecs PSP, litiges financiers. "
         "L'écran dit où l'argent est bloqué et pourquoi.",
  zones=[
    Z("kpi", "Bandeau financier", 4, "Volume du jour (total client) · prix prestataire versé · frais SaaS constatés · en attente (n et montant, ambre) · en échec (clay). Chiffres tnum, triple lecture FIN respectée."),
    Z("timeline", "Flux 24 h", 3, "Histogramme par heure : encaissements/décaissements, avec marqueurs d'incidents PSP."),
    Z("table", "Derniers événements", 5, "Table : horodatage, type (encaissement, décaissement, déclaration externe, OTP confirmé, échec), référence (Mono), montant, état."),
    Z("cta", "Actions", 1, "« Ouvrir la réconciliation » or · « Voir les anomalies » fantôme (ADM-20)."),
  ],
  comps=[("Bandeau FIN", "trois valeurs côte à côte, jamais fusionnées"),
         ("Histogramme", "barres fines, seuils marqués"),
         ("Badge PSP", "état du prestataire de paiement par opérateur (jamais de clés affichées)")],
  states=[("Nominal", "flux réguliers, aucun échec."),
          ("Taux d'échec élevé", "clay : bandeau + lien vers anomalies ; cause probable proposée."),
          ("Volume inhabituel", "violet : détection d'anomalie de volume (fête, campagne, fraude potentielle)."),
          ("PSP indisponible", "clay plein : état réel, files d'attente, plan de reprise, aucune perte silencieuse.")],
  motion=[("Rafraîchissement", "tick 20 s, chiffres tnum qui glissent"),
          ("Alerte", "tuile concernée qui passe clay, une seule pulsation")],
  rules=["Les montants affichés respectent toujours la structure FIN : les trois valeurs ne sont jamais agrégées ensemble.",
         "Un échec de paiement n'est jamais requalifié silencieusement en succès : l'état réel est la seule vérité.",
         "Aucune donnée de carte ou de compte complet n'est visible : uniquement les 4 derniers chiffres et l'émetteur."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/payments/overview", "GET /admin/payments/events?since=", "GET /admin/psp/health"],
  tech="Agrégats financiers calculés sur le ledger avec vues matérialisées (5 min) + flux temps réel (SSE) pour les "
       "événements. Aucune donnée sensible de moyen de paiement transmise au client admin.",
  canon="ADM — paiements (vue globale)", chrome=CHROME_ADM),

S("ADM-19", "Réconciliation", "ADM", "Paiements & Réconciliation", "/admin/paiements/reconciliation", "Admin", "P0", "Faire parler les comptes",
  intent="Comparer ce que dit LE LABEUR et ce que disent les relevés PSP/mobile money : identifier les écarts, les imputer, "
         "les corriger. Sans réconciliation, pas de confiance dans le ledger.",
  zones=[
    Z("table", "Rapprochements", 6, "Colonnes : période, opérateur, montant attendu (interne), montant relevé (PSP), écart, écart expliqué/inexpliqué, statut, actions."),
    Z("kpi", "Bandeau d'écart", 3, "Écart total (tnum, clay si ≠ 0) · nombre d'écarts inexplicés · plus ancien écart (jours)."),
    Z("list", "File d'écarts", 4, "Chaque écart : cause probable détectée (double envoi, remboursement tardif, frais opérateur, déclaration externe non rapprochée), pièces liées, action proposée."),
    Z("cta", "Actions", 1, "« Imputer un écart » or (avec motif, écriture compensatoire) · « Demander un relevé » fantôme (canal opérateur)."),
  ],
  comps=[("Table de rapprochement", "écarts tnum signés, statut typé"),
         ("Détecteur de causes", "heuristiques documentées, jamais opaques"),
         ("Écriture compensatoire", "jamais une modification : nouvelle ligne compensant l'écart, tracée"),
         ("Journal opérateur", "échanges avec le PSP, horodatés")],
  states=[("Équilibré", "écart 0, émeraude."),
          ("Écart mineur", "ambre : < seuil, suivi automatique."),
          ("Écart significatif", "clay : imputation requise, priorité haute."),
          ("Imputé", "écriture compensatoire appliquée, écart clos avec motif.")],
  motion=[("Calcul", "progression ligne à ligne, barre réelle"),
          ("Imputation", "ligne qui passe émeraude, delta tnum qui se stabilise")],
  rules=["Aucune correction ne modifie une écriture existante : toujours une écriture compensatoire (INV-5 appliqué au ledger financier).",
         "Tout écart significatif est enquêté et documenté : le ledger financier doit être explicable au centime.",
         "Les écarts dus aux frais d'opérateur sont identifiés comme tels et ne sont jamais imputés au client ni au prestataire sans décision."],
  tokens=["--emerald-500", "--clay-500", "--amber-500", "--mono", "--table"],
  api=["GET /admin/reconciliation?period=&operator=", "POST /admin/reconciliation/gaps/:id/impute {motive, entry}", "GET /admin/reconciliation/summary"],
  tech="Service de réconciliation : import de relevés (fichiers PSP, API opérateur), appariement transactionnel, "
       "détection d'écarts, propositions d'imputation. Moteur déterministe et rejouable.",
  canon="ADM — réconciliation", chrome=CHROME_ADM),

S("ADM-20", "Paiements — anomalies", "ADM", "Paiements & Réconciliation", "/admin/paiements/anomalies", "Admin", "P0", "Chasse aux irrégularités",
  intent="Détecter les irrégularités financières : doublons, montants incohérents, déclarations suspectes, cycles de "
         "remboursement. Chaque anomalie est expliquée et actionnable.",
  zones=[
    Z("list", "File d'anomalies", 6, "Carte par anomalie : type, montant(s) concerné(s), parties (ids), détection (règle), gravité, ancienneté, action proposée."),
    Z("table", "Détection", 3, "Table des règles de détection : règle, seuil, volume détecté 30 j, taux de faux positifs mesuré (honnêteté sur la précision)."),
    Z("kpi", "Priorité", 3, "Anomalies critiques (clay, n) · en cours d'analyse · clôturées ce mois · montants concernés (tnum)."),
    Z("cta", "Actions", 1, "« Traiter » or · « Marquer faux positif » fantôme (avec motif — alimente le calibrage)."),
  ],
  comps=[("Carte d'anomalie", "gravité, montants, action"),
         ("Statistiques de détection", "taux de faux positifs affiché (transparence interne)"),
         ("Traitement guidé", "étapes : constat → pièces → décision → écriture")],
  states=[("Nominal", "peu d'anomalies."),
          ("Vague", "clay : bandeau volume > seuil, priorisation automatique par montant."),
          ("Faux positif", "ardoise : clôturé, alimentation du calibrage."),
          ("Confirmée", "clay plein : sanction possible (ADM-04), remboursement, correction ledger.")],
  motion=[("Nouvelle anomalie", "insertion 240 ms + badge clay"),
          ("Traitement", "glissement vers clôturées, compteur mis à jour")],
  rules=["Toute anomalie confirmée entraîne une correction du ledger ET un examen du compte (pas de sanction automatique par algorithme).",
         "Le taux de faux positifs est mesuré et affiché : la détection doit rester honnête et calibrée.",
         "Aucune donnée personnelle de moyen de paiement n'est exposée dans les fiches d'anomalie."],
  tokens=["--clay-500", "--clay-600", "--mono", "--amber-500", "--table"],
  api=["GET /admin/payments/anomalies?cursor=", "POST /admin/payments/anomalies/:id/treat", "POST /admin/payments/anomalies/:id/false-positive"],
  tech="Moteur de règles anti-fraude (déterministe, versionné) + file de traitement humaine. Chaque décision est journalisée "
       "et reliée à la règle déclenchante.",
  canon="ADM — paiements (anomalies)", chrome=CHROME_ADM),

S("ADM-21", "Déclarations de paiement externe", "ADM", "Paiements & Réconciliation", "/admin/paiements/declarations-externes", "Admin", "P1", "Arbitrer le hors-plateforme",
  intent="Traiter les déclarations de paiement hors plateforme non confirmées ou contestées : vérifier les pièces, décider, "
         "et protéger le travailleur quand le client ne joue pas le jeu.",
  zones=[
    Z("table", "File de déclarations", 6, "Colonnes : date, client, prestataire, mission (Mono), montant déclaré, statut (non confirmée, contestée, en vérification), échéance 72 h, drapeaux."),
    Z("doc", "Dossier de déclaration", 4, "Pièces du client (captures, références), contestation éventuelle du prestataire, contrôles automatiques (cohérence, doublons), historique du client."),
    Z("kpi", "Risque", 3, "Client à antécédents (n déclarations non confirmées) · montants concernés · délai écoulé."),
    Z("cta", "Décider", 1, "« Statuer » or (acceptation → échéance close, frais SaaS dus · rejet → paiement plateforme exigé · fraude → sanction + garantie prestataire)."),
  ],
  comps=[("Table de file", "échéances Mono, drapeaux"),
         ("Visionneuse de pièces", "zoom, horodatage, contrôle EXIF"),
         ("Décision structurée", "motifs catégorisés + texte obligatoire"),
         ("Lien garantie", "si fraude : application de la politique de garantie du travailleur")],
  states=[("Dans les délais", "attente de confirmation prestataire."),
          ("Contestée", "clay : traitement prioritaire."),
          ("Confirmée", "émeraude : clôture, frais SaaS à recouvrer auprès du client (rappel automatique)."),
          ("Fraude établie", "clay plein : sanction client, garantie activée pour le travailleur, dossier transmis.")],
  motion=[("Ouverture", "dossier en panneau 240 ms"),
          ("Décision", "sceau selon issue, notification partie(s)")],
  rules=["Le travailleur est protégé : en cas de fraude établie, la garantie LE LABEUR s'applique selon politique publique.",
         "Les déclarations non confirmées à 72 h passent automatiquement en vérification : le doute ne devient jamais un « payé » implicite.",
         "Les frais SaaS restent dus sur les paiements hors plateforme : le rappel est automatique et jamais agressif."],
  tokens=["--clay-500", "--amber-500", "--emerald-500", "--mono", "--glass-2"],
  api=["GET /admin/payments/external-declarations?cursor=", "POST /admin/payments/external-declarations/:id/decide"],
  tech="Même dossier que PRE-34/EMP-43, vue modération étendue (antécédents, contrôles). Décisions génèrent des écritures "
       "au ledger et déclenchent les politiques de garantie versionnées.",
  canon="ADM — déclarations externes", chrome=CHROME_ADM),

S("ADM-22", "Paiements — résolution d'incident financier", "ADM", "Paiements & Réconciliation", "/admin/paiements/incidents/:id", "Admin", "P0", "Réparer sans casser",
  intent="Résoudre un incident financier (double paiement, paiement perdu, mauvais destinataire, échec PSP) avec une "
         "procédure claire : constat, décision, écritures, communication. L'argent des gens n'attend pas.",
  zones=[
    Z("hero", "Incident", 3, "Type, montants, parties, horodatage de survenance, impact (qui a été lésé, de combien), urgence."),
    Z("timeline", "Procédure", 4, "Constat → vérification des faits (relevés, logs PSP) → décision → écritures compensatoires → notification des parties. Chaque étape horodatée."),
    Z("list", "Options de résolution", 4, "Remboursement · réémission du paiement · correction du ledger · prise en charge par LE LABEUR (geste) · recouvrement auprès du PSP. Chacune avec ses conséquences comptables."),
    Z("cta", "Appliquer", 2, "« Appliquer la résolution » or (double validation si montant > seuil) · « Escalader » fantôme."),
  ],
  comps=[("Panneau d'options", "conséquences comptables affichées avant choix"),
         ("Double validation", "seuil de montant, deux agents"),
         ("Preuve de résolution", "écritures liées + notification, dossier scellé")],
  states=[("Ouvert", "incident en cours."),
          ("Résolu", "émeraude : écritures appliquées, parties notifiées, dossier clos."),
          ("Escaladé", "violet : PSP ou direction, délai affiché."),
          ("Rouvert", "si l'écriture s'avère insuffisante : nouveau cycle lié au précédent.")],
  motion=[("Application", "lignes d'écritures qui se posent 240 ms, sceau émeraude"),
          ("Escalade", "bandeau violet, ton neutre")],
  rules=["Toute correction financière est une écriture compensatoire au ledger, jamais une modification d'historique.",
         "Au-delà du seuil, double validation humaine obligatoire, y compris en astreinte.",
         "La partie lésée est toujours notifiée avec le montant exact de la correction et sa date d'effet."],
  tokens=["--clay-500", "--emerald-500", "--violet-500", "--mono", "--glass-2"],
  api=["GET /admin/payments/incidents/:id", "POST /admin/payments/incidents/:id/resolve {option, entries}", "POST /admin/payments/incidents/:id/escalate"],
  tech="Orchestrateur financier : application atomique des écritures, idempotence stricte, journal d'audit renforcé et "
       "réconciliation post-opération automatique.",
  canon="ADM — incident financier", chrome=CHROME_ADM),

S("ADM-23", "Confirmations de salaire — file", "ADM", "Paiements & Réconciliation", "/admin/salaire/confirmations", "Admin", "P0", "Preuves de versement",
  intent="Suivre les confirmations OTP de réception de salaire : qui a confirmé, qui n'a pas répondu, quels versements "
         "restent non prouvés. C'est la mémoire de la vérité financière du produit (INV-4).",
  zones=[
    Z("kpi", "Bandeau", 3, "En attente d'OTP (n, ambre) · OTP expirés (n, clay) · confirmés 24 h (n, émeraude) · montant en attente (tnum)."),
    Z("table", "Versements", 6, "Colonnes : versement (id Mono), mission, prestataire (id), montant (prix prestataire), déclaré le, OTP demandé le, état (en attente, confirmé, expiré, contesté), relances."),
    Z("list", "Actions automatiques", 3, "Ce que fait le système : renvoi OTP à J+1, relance à J+2, alerte modération à J+3, revue prestataire à J+5. Journal des envois."),
    Z("cta", "Actions", 1, "« Ouvrir un dossier » or · « Relancer maintenant » fantôme (journalisé)."),
  ],
  comps=[("Table de versements", "état typé, relances comptées"),
         ("Journal d'automatismes", "chaque relance horodatée, jamais silencieuse"),
         ("Lien dossier prestataire", "vers PRE-32 côté travailleur")],
  states=[("Nominal", "flux normal de confirmations."),
          ("Accumulation", "ambre : > seuil en attente → vérifier la délivrabilité SMS (ADM-43)."),
          ("OTP expirés", "clay : le système sait qu'il y a un problème, il ne le cache pas."),
          ("Blocage complet", "si un opérateur SMS est en panne : canal de secours activé (e-mail + code temporaire), tracé.")],
  motion=[("Rafraîchissement", "tick 30 s"),
          ("Relance", "ligne qui pulse 240 ms, compteur de relances +1")],
  rules=["L'absence de confirmation n'est jamais assimilée à un paiement non effectué : c'est une preuve manquante, statut à part entière.",
         "Les relances sont bornées (max 5) puis escalade humaine : le travailleur n'est pas harcelé.",
         "Aucun code OTP n'est jamais visible, ni en back-office, ni dans les journaux."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--mono", "--table"],
  api=["GET /admin/salary/confirmations?cursor=", "POST /admin/salary/confirmations/:id/remind", "GET /admin/salary/confirmations/stats"],
  tech="Read model sur le ledger (versements) + journal des envois OTP (sans contenu de code). Relances gérées par la file "
       "de jobs avec cadence bornée et backoff.",
  canon="ADM — salaire (confirmations)", chrome=CHROME_ADM),

S("ADM-24", "Preuves OTP — vérification", "ADM", "Paiements & Réconciliation", "/admin/salaire/preuves/:id", "Admin", "P0", "Authentifier la preuve",
  intent="Vérifier l'authenticité d'une preuve de réception (empreinte, horodatage, canal d'envoi du code, appareil) pour "
         "trancher un doute. Sans exposer aucun secret.",
  zones=[
    Z("hero", "Preuve examinée", 4, "Empreinte de preuve 12 caractères, horodatage, versement concerné, prestataire (id), canal d'acheminement du code (SMS/email), statut de validité."),
    Z("table", "Traces", 5, "Table : événement, horodatage (Mono), acteur, résultat (envoi accepté/refusé, saisie réussie/échouée, tentatives). Aucun code, jamais."),
    Z("kpi", "Signaux de fraude", 3, "Contrôles : géolocalisation inhabituelle · appareil inconnu · tentative multiple · écart temporel anormal. Résultats indicatifs, jamais décisionnels seuls."),
    Z("cta", "Actions", 1, "« Valider la preuve » or · « Invalider » clay outline (déclenche la correction ledger) · « Demander une contre-preuve » fantôme."),
  ],
  comps=[("Bloc empreinte", "12 caractères, copiable, jamais tronqué en back-office"),
         ("Table de traces", "événements techniques sans secret"),
         ("Signaux", "liste avec seuils et explications"),
         ("Décision motivée", "texte obligatoire en cas d'invalidation")],
  states=[("Valide", "émeraude : preuve conforme, aucune action."),
          ("Douteuse", "ambre : signaux présents, examen manuel requis."),
          ("Invalidée", "clay : correction du ledger, notification aux parties, dossier de sanction éventuel."),
          ("Introuvable", "si la preuve a été purgée : la purge respecte la rétention légale, l'absence est expliquée.")],
  motion=[("Examen", "traces qui se chargent ligne à ligne"),
          ("Décision", "sceau (émeraude/clay), notification partie(s)")],
  rules=["Aucun secret n'est jamais affiché, même en back-office : ni code, ni hash de code, ni graine.",
         "L'invalidation d'une preuve exige un motif écrit et génère systématiquement une notification aux deux parties.",
         "Les signaux sont indicatifs : aucun rejet automatique sur la seule base de signaux statistiques."],
  tokens=["--mono", "--emerald-500", "--clay-500", "--amber-500", "--table"],
  api=["GET /admin/salary/proofs/:id", "POST /admin/salary/proofs/:id/validate", "POST /admin/salary/proofs/:id/invalidate {motive}"],
  tech="Dossier de preuve assemblé depuis le service OTP (traces, sans secrets) et le ledger. L'invalidation est "
       "transactionnelle (écriture compensatoire + notification + audit).",
  canon="ADM — salaire (preuves OTP)", chrome=CHROME_ADM),

S("ADM-25", "Salaire — litiges & corrections", "ADM", "Paiements & Réconciliation", "/admin/salaire/litiges", "Admin", "P1", "Corriger la vérité financière",
  intent="Traiter les désaccords sur les versements de salaire : montants, dates, preuves contestées. Chaque correction est "
         "une écriture motivée, jamais une modification d'historique.",
  zones=[
    Z("list", "File de litiges salariaux", 5, "Cartes : versement, montant contesté, partie qui conteste, motif (non reçu, montant erroné, preuve refusée), ancienneté, urgence."),
    Z("table", "Écritures proposées", 4, "Table d'écritures compensatoires proposées par le système, avec impact solde (tnum) et référence au journal."),
    Z("kpi", "Volume", 3, "Litiges ouverts · montant total en jeu · délai médian de résolution · taux de litiges jugés fondés (honnêteté)."),
    Z("cta", "Actions", 1, "« Résoudre » or · « Demander une pièce » fantôme."),
  ],
  comps=[("Carte de litige", "montants et motifs"),
         ("Table d'écritures", "avant/après solde, tnum"),
         ("Taux de fondement", "statistique de qualité des contestations — sert au calibrage")],
  states=[("Ouvert", "à traiter."),
          ("Preuve demandée", "attente d'une pièce (48 h)."),
          ("Résolu — fondé", "écriture appliquée, notification, éventuel signalement de partie."),
          ("Résolu — non fondé", "motivation écrite, pas de débat sans fin (recours unique).")],
  motion=[("Résolution", "écriture qui se pose 240 ms, solde qui se met à jour"),
          ("Notification", "bandeau d'envoi 3 s")],
  rules=["Corriger ne signifie jamais supprimer : le ledger reste append-only, la correction est une contre-écriture visible.",
         "Les litiges salariaux sont prioritaires sur les autres files : l'argent dû à un travailleur passe avant.",
         "Les décisions sont motivées et citent les pièces examinées."],
  tokens=["--clay-500", "--gold-500", "--mono", "--emerald-500", "--table"],
  api=["GET /admin/salary/disputes?cursor=", "POST /admin/salary/disputes/:id/resolve {decision, entries, motive}"],
  tech="Service financier + dossier de litige salarial, avec priorité de file paramétrée. Toutes les écritures sont "
       "idempotentes et réconciliées automatiquement le lendemain.",
  canon="ADM — salaire (litiges)", chrome=CHROME_ADM),

S("ADM-26", "Litiges — file de modération", "ADM", "Litiges, remplacement & réputation", "/admin/litiges", "Admin", "P0", "File des conflits",
  intent="Répartir et traiter les litiges par gravité, montant et ancienneté. La file est la porte d'entrée de toute "
         "l'activité de modération — elle doit être lisible en un regard.",
  zones=[
    Z("kpi", "Bandeau", 4, "Ouverts (n) · SLA à risque (n, ambre) · montant total en jeu (tnum) · médiations en attente (n) · décisions à rendre aujourd'hui."),
    Z("table", "Litiges", 6, "Colonnes : référence (L-Mono), mission, parties, type, montant en jeu, état (instruction, médiation, décision, recours), étape courante, ancienneté, agent en charge."),
    Z("list", "Filtres & files", 2, "Par type, montant, pays, ancienneté, agent. Files séparées : « petits litiges » (résolution assistée) et « litiges majeurs » (procédure complète)."),
    Z("cta", "Actions", 1, "« Ouvrir un dossier » or · « Prendre en charge » fantôme (verrou 30 min)."),
  ],
  comps=[("Table de file", "ancienneté + montant + type"),
         ("Verrou de prise en charge", "évite les doublons"),
         ("Marqueur de recours", "dossier déjà décidé et contesté (superviseur différent requis)"),
         ("Compteur SLA", "Mono ambre/clay")],
  states=[("File saine", "peu d'éléments, SLA respectés."),
          ("Surcharge", "clay : bandeau + suggestion de priorisation par gravité et montant."),
          ("Afflux", "si > 2× la médiane : renfort d'astreinte proposé, message aux parties sur les délais (honnêteté)."),
          ("Vide", "« Aucun litige ouvert. » — un bon signe.")],
  motion=[("Prise en charge", "ligne ardoise + badge agent 240 ms"),
          ("Traitement", "fondu de sortie 240 ms, compteur mis à jour"),
          ("Surcharge", "bandeau clay atténué, une seule fois")],
  rules=["La priorisation est : gravité > ancienneté > montant. Jamais par ancienneté du client ou valeur commerciale.",
         "Un dossier déjà décidé et contesté ne peut être repris que par un superviseur différent (l'auteur de la décision en est exclu techniquement).",
         "Les SLA sont publics et opposables : tout dépassement est notifié aux parties, automatiquement."],
  tokens=["--clay-500", "--amber-500", "--violet-500", "--mono", "--table"],
  api=["GET /admin/disputes?queue=&cursor=", "POST /admin/disputes/:id/claim", "GET /admin/disputes/sla"],
  tech="File alimentée par le service de litiges ; répartition par gravité calculée serveur. Verrous distribués TTL 30 min. "
       "Compteurs SLA calculés sur les échéances (job de surveillance).",
  canon="ADM — litiges (file)", chrome=CHROME_ADM),
]
