# -*- coding: utf-8 -*-
"""FAMILLE 02 · CLIENT / EMPLOYEUR — EMP-01 → EMP-15"""
from ..model import S, Z, CHROME_APP

SCREENS = [

S("EMP-01", "Dashboard client", "EMP", "Accueil & Profil", "/client", "Client", "P0", "Control room personnelle",
  intent="Répondre en 5 secondes à : « où en est mon travail ? ». Trois chiffres (missions actives, candidats en attente, "
         "prochains paiements), la file des missions actives, et une seule action : publier une mission.",
  zones=[
    Z("hero", "Salutation + état fiscal", 2, "« Bonjour, Awa. » + météo du compte : 3 missions actives, 12 candidats en attente. Avatar halo or discret à droite."),
    Z("kpi", "Trio vital", 3, "Missions actives · Candidats à examiner · Prochain versement (montant FIN, or). Chiffres --display-1 pour le montant seulement."),
    Z("list", "File des missions actives", 5, "Cartes mission triées par urgence d'action : sceau de statut (En revue, Publique, En cours, Livrée), prochaine échéance, compteur de candidats, mini-timeline d'exécution."),
    Z("timeline", "Prochaines échéances", 3, "Bande horodatée : « Demain 18:00 — validation de preuve · mission M-2026-0142 ». Rendu Mono pour les dates."),
    Z("cta", "Action unique", 1, "Bouton or « Publier une mission » ; action secondaire fantôme « Voir mon argent »."),
  ],
  comps=[("C-02 SquircleCard", "cartes mission E1→E2, sceau à droite"),
         ("C-04 StatusSeal", "5 états de mission, jamais couleur seule"),
         ("C-06 TimelineTrack", "mini-frise de la mission, point actif pulsé"),
         ("C-05 PriceBreakdown", "compact : « Total client 275 000 F » + chevron vers le détail FIN")],
  states=[("Nouveau client", "Zéro mission : état vide explicatif (C-19 variante douce) + guide en 3 actes."),
          ("Actif", "3 à 8 cartes, stagger d'apparition."),
          ("Urgence", "Échéance < 24 h : bord gauche ambre 2 px, haptique au chargement (une fois)."),
          ("Chargement", "Squelettes à la teinte exacte des cartes (pas de gris générique)."),
          ("Erreur réseau", "Bandeau ambre + données en cache horodatées ; jamais d'écran vide sans explication.")],
  motion=[("Entrée", "hero → KPI → liste → échéances, stagger 60 ms, spring soft"),
          ("Sceau actif", "pulse halo 2 400 ms uniquement sur la mission à action immédiate"),
          ("Pull-to-refresh", "sceau or qui se referme, spring snap, haptique light")],
  rules=["Le montant affiché est toujours le TOTAL CLIENT, jamais le prix prestataire seul (INV-1).",
         "Une seule mission peut porter le badge « Action requise » à la fois (sinon badge agrégé « 3 actions requises »).",
         "Le dashboard n'affiche jamais de métrique de vanité (vues, likes) : uniquement des états d'engagement contractuel."],
  tokens=["--surface-0", "--gold-500", "--display-1", "--price", "--glass-2", "--amber-500"],
  api=["GET /v1/client/dashboard", "GET /v1/missions?status=active&limit=8", "GET /v1/payments/upcoming"],
  tech="RSC + hydratation partielle des cartes ; cache SWR 60 s. Les cartes mission sont préchargées en prefetch au survol/focus.",
  canon="Dashboard client", chrome=CHROME_APP),

S("EMP-02", "Notifications client", "EMP", "Accueil & Profil", "/client/notifications", "Client", "P1", "Flux d'événements actionnables",
  intent="Chaque notification est un événement du contrat : elle dit quoi, où, et ce qu'on attend de vous. Aucune notification "
         "sans action utile, aucune promotion.",
  zones=[
    Z("chips", "Filtres de flux", 2, "Toutes · Action requise · Missions · Contrats · Paiements · Litiges. Chip active = --surface-4 + libellé or."),
    Z("list", "Liste chronologique", 6, "Cartes groupées par jour ; icône d'événement, titre court, mission liée (Mono), horodatage relatif, action en une ligne (« Valider la preuve », « Signer la version R2 »)."),
    Z("cta", "Tout marquer comme lu", 1, "Action fantôme ; les éléments « action requise » ne sont JAMAIS marqués lus automatiquement."),
  ],
  comps=[("Ligne d'événement", "glyphe contextuel + titre + route de destination"),
         ("Badge d'action", "émeraude si validation, or si montant, clay si litige"),
         ("Groupement par jour", "séparateurs --caps « AUJOURD'HUI »"),
         ("Swipe", "droite = archiver (undo 5 s), gauche = reporter (menu)")],
  states=[("Non lues", "Une ligne d'or 2 px à gauche + pastille pleine."),
          ("Vides", "« Rien de nouveau. Le travail est en ordre. » + illustration particulaire figée."),
          ("Non lues > 50", "Pagination par jour ; bouton « charger les jours précédents »."),
          ("Archivées", "Repositionnées avec fade 240 ms + snackbar d'annulation.")],
  motion=[("Apparition", "stagger 60 ms plafonné à 8, spring soft"),
          ("Swipe", "spring snap ; au-delà de 45 % de largeur, action confirmée"),
          ("Badge", "pop 240 ms à la réception temps réel (SSE)")],
  rules=["Une notification liée à un montant cite le triplet FIN complet ou renvoie explicitement à l'écran FIN.",
         "Aucune notification marketing dans ce flux : elle serait juridiquement indistinguable d'un événement de contrat.",
         "Les notifications de sécurité (nouvelle connexion, appareil inconnu) sont non supprimables pendant 30 jours."],
  tokens=["--surface-1", "--stroke-sub", "--gold-500", "--emerald-500", "--clay-500"],
  api=["GET /v1/notifications?filter=all", "POST /v1/notifications/read", "GET /v1/notifications/stream (SSE)"],
  tech="Flux SSE avec reconnexion exponentielle ; en cas de coupure, delta API par curseur `since`. Les notifications "
       "sont idempotentes côté serveur (dedup par event_id).",
  canon="Notifications (flux)", chrome=CHROME_APP),

S("EMP-03", "Profil client", "EMP", "Accueil & Profil", "/client/profil", "Client", "P1", "Identité vérifiable",
  intent="Un profil crédible pour attirer les meilleurs candidats : vérifications affichées, historique de contrat honnête, "
         "taux de paiement à l'heure. Ce que le prestataire verra de vous.",
  zones=[
    Z("hero", "Identité", 3, "Avatar halo or, nom, statut de vérification (e-mail ✓, téléphone ✓, identité entreprise ✓), ancienneté, note de fiabilité de paiement."),
    Z("kpi", "Preuves de fiabilité", 3, "Trio : contrats menés à terme · paiements à l'heure · litiges (avec taux). Chiffres tnum, émeraude si exemplaire."),
    Z("list", "Sections éditables", 4, "Identité & coordonnées · Entreprise/Structure · Facturation & mentions légales · Préférences d'équipe · Zones géographiques d'intervention."),
    Z("cta", "Actions", 2, "« Modifier » (or discret) · « Voir mon profil public » (fantôme) · « Exporter mes données » (texte, conformité)."),
  ],
  comps=[("Bloc vérification", "puce émeraude + libellé + date ; jamais de détail sensible"),
         ("Barre de complétude", "or, segments par section manquante"),
         ("Carte publique", "aperçu exact du profil vu par un prestataire (miroir)")],
  states=[("Complet", "Barre 100 %, halo or stable."),
          ("Incomplet", "Segments manquants en ambre + CTA « compléter » priorisé."),
          ("Vérification en cours", "puce ambre pulsée + délai indicatif (24-48 h)."),
          ("Modification sensible", "changer l'e-mail/téléphone exige une revalidation OTP (PUB-06 réutilisé).")],
  motion=[("Miroir", "bascule vers l'aperçu public : oscillation 3D Y de 6° spring heavy"),
          ("Complétude", "barre qui progresse par ressort soft à chaque champ validé")],
  rules=["Le taux de paiement à l'heure est calculé sur 12 mois glissants, publié avec sa méthode (lien).",
         "Un client avec un litige ouvert ne peut pas masquer cet état sur son profil public.",
         "Les coordonnées ne sont jamais exposées publiquement : seulement après accord d'une proposition."],
  tokens=["--gold-500", "--emerald-500", "--surface-2", "--text-mid", "--squircle-28"],
  api=["GET /v1/client/profile", "PATCH /v1/client/profile", "GET /v1/client/profile/public-preview"],
  tech="Édition en place (inline) avec sauvegarde optimiste par champ ; conflit d'édition résolu par la version serveur "
       "(409 → SYS-06). Images passent par R2 avec variantes AVIF.",
  canon="Profil client", chrome=CHROME_APP),

S("EMP-04", "Paramètres client", "EMP", "Accueil & Profil", "/client/parametres", "Client", "P1", "Salle des réglages",
  intent="Tout régler sans se perdre : notifications, sécurité, paiements, juridique, apparence, données. Les réglages "
         "dangereux sont isolés en bas, en clay, et jamais un seul tap.",
  zones=[
    Z("list", "Rubriques", 6, "Notifications (canaux, heures calmes) · Sécurité (2FA, appareils, sessions) · Paiements (moyens, devise, échéancier par défaut) · Juridique (mentions, CGU v3.2 + hash) · Apparence (thème, intensité des animations) · Accessibilité (réduction de mouvement, contraste, taille du texte)."),
    Z("form", "Zone sensible", 3, "Suspendre le compte · Supprimer le compte (double confirmation + délai de 14 jours) · Révoquer toutes les sessions."),
    Z("cta", "Vérification de version", 1, "Pied : version app, version CGU acceptée, empreinte de build, lien « Quoi de neuf »."),
  ],
  comps=[("Ligne de réglage", "libellé + description + contrôle (toggle, select, chevron)"),
         ("Toggle", "neumorphique, émeraude à l'activation, haptique light"),
         ("Zone danger", "bord clay, fond très légèrement clay, actions à confirmation"),
         ("Bloc légal", "version + hash Mono copiable")],
  states=[("Par défaut", "Réglages recommandés marqués d'un point or discret."),
          ("Modifié non enregistré", "Bandeau collant « Enregistrer » or, jamais de perte silencieuse."),
          ("Suspension", "Dialogue glass-4 : motif obligatoire, délai d'effet, conséquence sur missions en cours."),
          ("Suppression", "Chemin en 3 étapes : motif → export des données → confirmation typée (« SUPPRIMER »).")],
  motion=[("Accordéons", "hauteur animée spring soft, chevron rotation 180°"),
          ("Toggle", "glissement 120 ms + halo émeraude transitoire"),
          ("Renoncement", "annulation de suppression = sceau or « Conservé » 1 200 ms")],
  rules=["La suppression n'est jamais instantanée : 14 jours de réversibilité, missions en cours interdites de suppression.",
         "Les réglages d'accessibilité sont respectés partout, sans exception de composant.",
         "Chaque changement de sécurité (2FA, sessions) génère une notification non supprimable."],
  tokens=["--surface-2", "--emerald-500", "--clay-500", "--stroke-mid", "--text-lo"],
  api=["GET/PATCH /v1/client/settings", "POST /v1/account/suspend", "DELETE /v1/account (soft)", "GET /v1/sessions"],
  tech="Réglages stockés en JSONB côté serveur + miroir local (MMKV) pour l'instantanéité au démarrage. "
       "Les réglages d'apparence sont appliqués dès le premier pixel (blocage du flash).",
  canon="Paramètres (client)", chrome=CHROME_APP),

S("EMP-05", "Mes missions", "EMP", "Missions", "/client/missions", "Client", "P0", "Registre des missions",
  intent="Le registre complet, filtrable, trié par ce qui compte : ce qui exige une action humaine d'abord, le reste ensuite. "
         "Chaque ligne est un mini-dossier de preuve.",
  zones=[
    Z("chips", "Segments + filtres", 2, "Segments : En action requise · Actives · En revue · Clôturées · Litiges. Filtres avancés (EMP-20) disponibles en tiroir."),
    Z("list", "Liste des missions", 6, "Carte mission : titre, référence M-AAAA-NNNN (Mono), sceau de statut, total client (FIN compact), prochaine échéance, avancement de frise (n/n jalons), pastille candidats."),
    Z("table", "Compteurs de registre", 2, "Ligne de synthèse : 14 missions · 3 en action requise · 202 500 F dus cette semaine (tnum, or)."),
  ],
  comps=[("C-02 SquircleCard", "variante registre, hauteur 96 px"),
         ("C-04 StatusSeal", "statut en un coup d'œil"),
         ("C-06 TimelineTrack", "avancement condensé en 5 points"),
         ("Barre de recherche", "recherche par titre, référence, prestataire")],
  states=[("Aucune mission", "État vide pédagogique : illustration de contrat vierge + CTA publier."),
          ("Action requise > 0", "Bandeau or en tête, non masquable tant que l'action n'est pas traitée."),
          ("Litige actif", "Carte avec bord clay 2 px, mention « Suivi par la modération »."),
          ("Recherche", "Résultats indexés en < 120 ms, surlignage des correspondances.")],
  motion=[("Changement de segment", "morphing de surlignage 240 ms ease-labeur-inout ; contenu en fondu croisé"),
          ("Carte → détail", "partage élément (shared element) : carte qui s'agrandit en fiche EMP-14, spring heavy"),
          ("Litige", "aucune animation ludique : fade sobre 240 ms")],
  rules=["Le tri par défaut est : action requise → échéance imminente → date de création. Jamais trié par popularité.",
         "Toute mission montre sa référence : c'est l'identifiant de discussion avec le support et la modération.",
         "Les missions clôturées ne sont jamais supprimées : archivage à partir de 24 mois, toujours consultable."],
  tokens=["--surface-1", "--gold-500", "--clay-500", "--text-lo", "--squircle-22"],
  api=["GET /v1/missions?segment=&q=&cursor=", "GET /v1/missions/counters"],
  tech="Liste virtualisée (FlashList), curseur opaque côté serveur. Les compteurs sont calculés en SQL avec index partiels "
       "(status, next_deadline) pour rester < 30 ms.",
  canon="Missions — registre client", chrome=CHROME_APP),

S("EMP-06", "Création de mission — Étape 1 : Objet & catégorie", "EMP", "Missions", "/client/missions/nouvelle/1", "Client", "P0", "Wizard — cadrage",
  intent="Étape 1/4 : nommer le travail. Un objet clair, une catégorie normalisée (qui déclenche les règles juridiques), "
         "et un résumé de 3 lignes qui servira de contrat.",
  zones=[
    Z("chips", "Progression du wizard", 1, "Barre fine or + 4 pastilles : 1 actif, 2-4 ○. Libellé --caps « ÉTAPE 1 SUR 4 · CADRAGE »."),
    Z("form", "Objet du travail", 5, "Titre (60 c. max, compteur live) · Catégorie (autocomplete normalisée : BTP, transport, informatique, artisanat, services…) · Description brute guidée par des exemples réels."),
    Z("kpi", "Assistance", 3, "Encart « Comment écrire un objet opposable » : verbes d'action, livrable attendu, lieu — avec deux exemples avant/après."),
    Z("cta", "Navigation", 2, "« Continuer » or armé si titre + catégorie ; « Enregistrer le brouillon » fantôme (autosave toutes les 10 s)."),
  ],
  comps=[("Barre de progression", "4 segments, remplissage or animé"),
         ("Champ titre", "compteur 60 c., suggestion de reformulation si < 12 c."),
         ("Sélecteur catégorie", "liste normalisée + icône, jamais de texte libre"),
         ("Autosave", "indicateur discret « Brouillon enregistré · 14:02 » Mono")],
  states=[("Vide", "CTA désarmé, encart d'aide déployé."),
          ("Brouillon repris", "Bandeau ardoise « Brouillon repris le 06/10 à 18:40 » + « repartir de zéro »."),
          ("Catégorie sensible", "encart ambre immédiat : catégories réglementées → passeront en revue humaine (EMP-10)."),
          ("Erreur", "champ fautif rim clay + message précis, focus automatique.")],
  motion=[("Progression", "remplissage du segment 1, spring snap, 240 ms"),
          ("Assistance", "encart déplié 240 ms à la première frappe"),
          ("Autosave", "micro-pop du point émeraude, 120 ms")],
  rules=["La catégorie conditionne la qualification juridique : elle ne peut être libre, elle est normalisée et versionnée.",
         "Aucun champ obligatoire caché : l'étape 1 n'en compte que deux, et le dit.",
         "Le brouillon est chiffré localement et purgé au bout de 30 jours."],
  tokens=["--gold-500", "--amber-500", "--surface-2", "--mono", "--caps"],
  api=["POST /v1/missions/draft", "PATCH /v1/missions/draft/:id/step1", "GET /v1/catalog/categories"],
  tech="Wizard à état local + persistance brouillon. Validation zod partagée. Les catégories proviennent d'un catalogue "
       "versionné (changement → migration des missions en revue).",
  canon="Création de mission — wizard (4 étapes)", chrome={"appbar": "Nouvelle mission", "glyph": "◈"}),

S("EMP-07", "Création de mission — Étape 2 : Lieu & durée", "EMP", "Missions", "/client/missions/nouvelle/2", "Client", "P0", "Wizard — ancrage",
  intent="Étape 2/4 : ancrer le travail dans le réel. Lieu (ou distance pour le télétravail), dates, durée estimée, "
         "contraintes horaires. C'est ce qui rend le contrat exécutable.",
  zones=[
    Z("chips", "Progression", 1, "Segment 2/4 actif, précédent ✓ émeraude."),
    Z("form", "Lieu & fenêtre", 5, "Adresse avec autocomplete cartographique · type de lieu (sur site / à distance / hybride) · date de début · durée estimée (jours/halves) · contraintes horaires (plage, jours)."),
    Z("kpi", "Carte de contrôle", 3, "Mini-carte (si sur site) + récapitulatif « 3 jours · 08:00-17:00 · Cotonou, Littoral ». Mention : les déplacements hors zone ne sont pas couverts sauf clause."),
    Z("cta", "Navigation", 2, "« Retour » fantôme · « Continuer » or."),
  ],
  comps=[("Autocomplete lieu", "adresses normalisées + garde-fou sur zones non desservies"),
         ("Sélecteur date", "calendrier verre, bornes explicites (pas de date passée)"),
         ("Mini-carte", "statique, sans clé d'API exposée côté client (proxy serveur)"),
         ("Chips horaires", "plages prédéfinies + personnalisé")],
  states=[("Zone non desservie", "bandeau ambre : « Ce lieu sort de nos zones couvertes. » + demander l'ouverture (file ADM)."),
          ("Conflit de dates", "alerte si la même équipe est déjà engagée sur une autre mission (prévention sur-engagement)."),
          ("À distance", "la carte disparaît, la zone devient « fuseau horaire de référence »."),
          ("Champs incomplets", "CTA désarmé, mention exacte de ce qui manque.")],
  motion=[("Carte", "fondu + zoom 1.04 depuis la saisie d'adresse"),
          ("Passage à distance", "la carte se replie en hauteur 240 ms spring soft"),
          ("Chips", "sélection avec pop 240 ms")],
  rules=["Pas de date de début dans le passé ; les missions urgentes (< 48 h) affichent un avertissement sur la disponibilité des candidats.",
         "Les zones non desservies ne bloquent jamais silencieusement : l'utilisateur peut demander l'ouverture (tracée).",
         "La durée estimée est indicative mais entre dans le calcul de l'échéance contractuelle par défaut."],
  tokens=["--gold-500", "--amber-500", "--surface-2", "--emerald-500"],
  api=["PATCH /v1/missions/draft/:id/step2", "GET /v1/geo/autocomplete", "GET /v1/geo/coverage"],
  tech="Autocomplete géo via proxy serveur (clé jamais exposée). Les dates sont manipulées en UTC, affichées dans le fuseau "
       "du lieu de la mission.",
  canon="Création de mission — wizard (4 étapes)", variant_of="EMP-06", chrome={"appbar": "Nouvelle mission", "glyph": "◈"}),

S("EMP-08", "Création de mission — Étape 3 : Compétences & livrables", "EMP", "Missions", "/client/missions/nouvelle/3", "Client", "P0", "Wizard — exigences",
  intent="Étape 3/4 : décrire ce qui qualifie le travail et ce qui prouve sa réussite. Compétences requises, livrables "
         "attendus, preuves acceptées (photo, PDF, vidéo, jalon).",
  zones=[
    Z("chips", "Progression", 1, "Segment 3/4 actif."),
    Z("form", "Exigences", 5, "Compétences (chips normalisées, pondérées obligatoire/souhaité) · Livrables (liste avec type de preuve par livrable) · Matériel fourni ou non · Conditions d'accès (permis, badge, habilitation)."),
    Z("list", "Bibliothèque de preuves", 3, "Cartes de types de preuve avec aperçu : Photo horodatée géolocalisée · Fichier PDF signé · Vidéo ≤ 90 s · Jalon validé en double."),
    Z("cta", "Navigation", 2, "« Retour » · « Continuer » or (actif si ≥ 1 livrable)."),
  ],
  comps=[("Chips compétences", "normalisées, couleur neutre ; pondération or si obligatoire"),
         ("Éditeur de livrables", "lignes réordonnables par glisser, poids du livrable affiché"),
         ("Carte de preuve", "aperçu visuel du type + règle de validité (ex. photo datée < 2 h après exécution)")],
  states=[("Sans livrable", "CTA désarmé + encart : « Un contrat sans livrable est un litige futur. »"),
          ("Preuve incompatible", "si zone à distance + preuve badge sur site → incohérence signalée en ambre."),
          ("Exigence réglementée", "habilitations → passe en revue humaine automatique (EMP-10)."),
          ("Réordonnancement", "drag actif : lignes qui s'écartent 8 px, ombre E2")],
  motion=[("Chips", "ajout avec pop + haptique light"),
          ("Drag", "spring snap au relâchement, jamais de saut sec"),
          ("Cartes de preuve", "stagger 60 ms")],
  rules=["Toute mission exige au moins un livrable vérifiable ; le type de preuve conditionne la validation d'exécution (EMP-38).",
         "Les compétences obligatoires alimentent le scoring de matching : leur poids est visible et justifié (EMP-19).",
         "Une exigence illégale ou discriminatoire (âge, origine, sexe) est bloquée par le filtre de qualification (EMP-10)."],
  tokens=["--gold-500", "--emerald-500", "--surface-2", "--squircle-14", "--amber-500"],
  api=["PATCH /v1/missions/draft/:id/step3", "GET /v1/catalog/skills?q=", "GET /v1/catalog/evidence-types"],
  tech="Éditeur de livrables en état local (drag-and-drop Reanimated) avec commit au blur. Le catalogue de compétences "
       "est servi avec synonymes FR/EN pour le matching.",
  canon="Création de mission — wizard (4 étapes)", variant_of="EMP-06", chrome={"appbar": "Nouvelle mission", "glyph": "◈"}),

S("EMP-09", "Création de mission — Étape 4 : Budget & conditions", "EMP", "Missions", "/client/missions/nouvelle/4", "Client", "P0", "Wizard — valeur",
  intent="Étape 4/4 : fixer la valeur. Le client saisit le PRIX PRESTATAIRE ; les frais SaaS sont calculés et affichés en "
         "transparence immédiate. Le total client se construit sous ses yeux — jamais après coup.",
  zones=[
    Z("chips", "Progression", 1, "Segment 4/4 actif."),
    Z("form", "Budget", 4, "Saisie du prix prestataire (gros champ --price, or) · option « proposer une fourchette » · échéancier (paiement unique / jalons) · pénalités de retard client (facultatif, plafonnées)."),
    Z("price", "Construction du total (FIN)", 4, "Calcul en direct, trois lignes : Prix Prestataire 250 000 F + Frais SaaS LE LABEUR 25 000 F (10 %) = Total Client 275 000 F. Les frais affichent leur taux et un lien « pourquoi ? »"),
    Z("kpi", "Comparateur indicatif", 2, "Fourchette de marché observée pour la catégorie et la région (sourcée, datée, non prescriptive)."),
    Z("cta", "Navigation", 2, "« Retour » · « Vérifier l'éligibilité » or (mène à EMP-10)."),
  ],
  comps=[("C-05 PriceBreakdown", "calcul live, chiffres tnum, animation de compteur sur variation"),
         ("Champ monétaire", "masque de saisie, séparateurs d'espace, refus des valeurs absurdes"),
         ("Sélecteur d'échéancier", "unique / jalons liés aux livrables de l'étape 3"),
         ("Lien « pourquoi ces frais »", "ouvre FIN-02 en sheet")],
  states=[("Saisie en cours", "calcul live, le total pulse 120 ms à chaque changement de tranche"),
          ("Prix anormalement bas", "encart ambre factuel : « 62 % sous la fourchette observée. »"),
          ("Prix modifié après éligibilité", "re-qualification requise si le montant change de tranche réglementaire."),
          ("Non éditable", "si mission issue d'un catalogue à prix fixe : le champ devient lecture seule, explication affichée.")],
  motion=[("Compteur", "interpolation des chiffres 240 ms, tnum pour éviter le tremblement"),
          ("Ajout de jalon", "ligne du triplet qui s'insère en hauteur animée spring soft"),
          ("Validation", "sceau or bref sur le total, puis transition vers EMP-10")],
  rules=["INV-1 : le frais SaaS est affiché AVANT validation, en pourcentage ET en montant. Aucun frais caché, jamais.",
         "Le prix prestataire est la base de calcul unique ; le frais SaaS n'est jamais prélevé sur la rémunération du prestataire.",
         "Les pénalités de retard client sont plafonnées à 5 % du total et clairement réciproques si le prestataire est en retard."],
  tokens=["--gold-500", "--price", "--display-1", "--amber-500", "--grad-gold"],
  api=["PATCH /v1/missions/draft/:id/step4", "POST /v1/pricing/quote", "GET /v1/pricing/benchmark?category="],
  tech="Le calcul est fait côté serveur (POST /pricing/quote) et reproduit côté client à titre d'affichage : une seule "
       "source de vérité, le client ne calcule jamais un montant opposable.",
  canon="Création de mission — wizard (4 étapes)", variant_of="EMP-06", chrome={"appbar": "Nouvelle mission", "glyph": "◈"}),

S("EMP-10", "Qualification juridique", "EMP", "Missions", "/client/missions/:id/qualification", "Client", "P0", "Verdict à trois sceaux",
  intent="Le moment de vérité : LE LABEUR qualifie la mission. Éligible (publication immédiate), Revue (décision humaine "
         "sous 24 h ouvrées), Bloquée (interdite, avec motif et voie de recours). Le verdict est explicable, article par article.",
  zones=[
    Z("verdict", "Sceau de verdict", 4, "Sceau plein écran : Émeraude « Éligible » · Ambre « Revue humaine » · Clay « Bloquée ». Sous-titre : ce que cela signifie concrètement pour la publication."),
    Z("list", "Détail des contrôles", 5, "Liste des règles évaluées, chacune avec son statut (✓ conforme · ⚠ à préciser · ✕ non conforme) et son article de référence. Jamais de « erreur inconnue »."),
    Z("kpi", "Délai & alternatives", 3, "Revue : délai indicatif et file (ADM-06). Bloquée : reformulations possibles, catégorie alternative, recours humain avec délai."),
    Z("cta", "Sorties", 2, "Éligible → « Publier la mission » (or). Revue → « Recevoir la décision » (fantôme + notification). Bloquée → « Demander un réexamen » (clay outline)."),
  ],
  comps=[("C-04 StatusSeal", "variante verdict, 120 px, anneau conique complet"),
         ("Ligne de contrôle", "glyphe + règle + article + explication en langage clair"),
         ("Bandeau de recours", "délai de réponse affiché (contractuel côté support)"),
         ("Particules", "émeraude en éligible, ambre en revue, clay froid en bloquée")],
  states=[("Éligible", "Sceau émeraude, haptique heavy, particules vertes ascendantes, CTA publier or."),
          ("Revue", "Sceau ambre, frise d'attente avec position en file, possibilité de retirer la demande."),
          ("Bloquée", "Sceau clay, motifs hiérarchisés (le plus grave en premier), aucune particule animée."),
          ("Réexamen", "Historique des verdicts conservé, chaque décision avec auteur (algo ou humain) et horodatage.")],
  motion=[("Forge du verdict", "fermeture de l'anneau 640 ms spring heavy, sceau qui s'imprime (scale 1.08 → 1.0)"),
          ("Contrôles", "révélation séquentielle 60 ms par ligne"),
          ("Blocage", "contre-forge (anneau qui s'ouvre) — cohérent avec PUB-09")],
  rules=["INV-2 : aucune publication possible hors verdict Éligible.",
         "Le verdict liste TOUJOURS ses motifs au niveau article ; un refus sans motif est un bug bloquant.",
         "Le réexamen est un droit : une demande humaine, traitée dans un délai affiché et tracé (ADM-07/08)."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--grad-emerald", "--display-2"],
  api=["POST /v1/missions/:id/qualify", "GET /v1/missions/:id/qualification", "POST /v1/missions/:id/review-request"],
  tech="Le moteur de qualification est un service serveur déterministe et versionné (ruleset v7). L'UI ne réimplémente "
       "aucune règle : elle affiche le résultat et sa traçabilité (ruleset, version, exécution id en Mono).",
  a11y=["Le verdict est annoncé en role=status, avec le détail en texte (jamais par la couleur seule).",
        "Les particules sont aria-hidden et désactivées en reduced-motion."],
  canon="Qualification juridique (verdict)", chrome={"appbar": "Qualification", "glyph": "◈"}),

S("EMP-11", "Tarification — Prix, frais et total", "EMP", "Missions", "/client/missions/:id/tarification", "Client", "P0", "Table de valeur",
  intent="L'écran financier du client : un tableau à trois lignes sans ambiguïté possible. C'est l'écran le plus contrôlé "
         "du produit — toute divergence est un défaut critique.",
  zones=[
    Z("price", "Le triplet FIN (plein écran)", 6, "PRIX PRESTATAIRE (--price or) + FRAIS SAAS LE LABEUR (taux + montant, texte clair) = TOTAL CLIENT (--display-1, sceau or discret à droite). Alignement tabulaire à droite, séparateurs en pointillés."),
    Z("list", "Ce que couvre chaque ligne", 4, "Trois cartes explicatives : ce que reçoit le prestataire · ce que finance le frais SaaS (hébergement sécurisé, preuves R2, modération des litiges, conformité) · ce que paie le client au total, tout compris."),
    Z("timeline", "Échéancier appliqué", 3, "Barre d'échéances : 40 % à la signature, 60 % à la validation finale (paramétrable). Chaque échéance avec sa date et son montant exact, total vérifié = total client."),
    Z("cta", "Actions", 1, "« Simuler un autre prix » (ouvre le curseur de simulation) · « Valider cette tarification » or."),
  ],
  comps=[("C-05 PriceBreakdown", "variante souveraine : c'est ici que le composant est défini"),
         ("Curseur de simulation", "déplace le prix prestataire, recalcule le total en direct"),
         ("Badge de conformité", "« Affichage conforme FIN v1 » en Mono discret"),
         ("Lien frais", "ouvre FIN-02 (détail et justification des frais)")],
  states=[("Lecture", "Chiffres tabulaires, aucun tremblement au scroll."),
          ("Simulation", "le total se recalcule en 80 ms ; jamais de valeur intermédiaire fausse affichée."),
          ("Échéancier invalide", "si la somme des échéances ≠ total client → blocage clay + écart affiché en clair."),
          ("Devise étrangère", "conversion affichée avec taux daté et source ; le contrat reste libellé en devise d'origine.")],
  motion=[("Compteur", "interpolation tnum 240 ms"),
          ("Validation", "sceau or qui s'imprime sur le total, haptique heavy, 480 ms"),
          ("Écart d'échéancier", "les deux nombres fautifs se rapprochent visuellement (trait de liaison clay)")],
  rules=["INV-1 sans exception : trois lignes, cet ordre, ces libellés exacts, dans toute langue.",
         "Le frais SaaS est affiché en pourcentage ET en montant absolu, avec sa base de calcul explicite.",
         "Aucune mention « frais de service inclus » floue : le mot « Total Client » est le seul admis pour la troisième ligne."],
  tokens=["--display-1", "--price", "--gold-500", "--gold-300", "--mono", "--text-hi"],
  api=["GET /v1/missions/:id/pricing", "POST /v1/missions/:id/pricing/simulate", "POST /v1/missions/:id/pricing/validate"],
  tech="Composant C-05 unique, testé par snapshot automatisé : tout écran qui affiche un montant importe ce composant, "
       "jamais un montage local. Un test e2e parcourt les 120 canons et vérifie la présence des trois lignes si montant.",
  a11y=["Lecture vocale ordonnée : « Prix prestataire 250 000 francs, plus frais SaaS LE LABEUR 25 000 francs, égale total client 275 000 francs. »",
        "Les séparateurs visuels sont décoratifs (aria-hidden) ; la structure est une liste de définitions."],
  canon="Tarification FIN (client)", chrome={"appbar": "Tarification", "glyph": "◈"}),

S("EMP-12", "Aperçu avant publication", "EMP", "Missions", "/client/missions/:id/apercu", "Client", "P0", "Répétition générale",
  intent="Voir exactement ce que verront les prestataires, plus le cadre contractuel complet. C'est la dernière porte "
         "avant l'engagement : rien d'invisible ne doit échapper au client.",
  zones=[
    Z("hero", "Aperçu miroir", 5, "Rendu exact de la fiche publique (comme PRE-07) : titre, catégorie, lieu, livrables, prix prestataire mis en avant. Bandeau « VUE PRESTATAIRE » en caps."),
    Z("price", "Rappel FIN", 3, "Triplet complet en version compacte, avec mention « le prestataire verra : 250 000 F » — clarification explicite."),
    Z("list", "Liste de contrôle de publication", 4, "7 points à confirmer : objet, lieu/dates, livrables, preuves, prix, échéancier, clauses. Chaque point avec son statut et un lien d'édition direct."),
    Z("cta", "Publication", 1, "« Publier maintenant » or · « Programmer la publication » fantôme · « Enregistrer et quitter » texte."),
  ],
  comps=[("Aperçu miroir", "iframe/composant partagé avec PRE-07 (rendu strictement identique)"),
         ("Checklist", "lignes cochables avec édition en place"),
         ("Bandeau de rôle", "rappelle à qui s'adresse cet aperçu")],
  states=[("Prêt", "Checklist 7/7 émeraude, CTA or armé."),
          ("Incomplet", "points manquants en ambre, CTA désarmé, lien direct vers l'étape fautive."),
          ("Aperçu prestataire", "bascule d'affichage : les frais SaaS et le total client sont masqués (le prestataire ne les voit jamais dans sa fiche)."),
          ("Programmée", "sélecteur date/heure, rappel des heures calmes (pas de publication 22:00-07:00 par défaut).")],
  motion=[("Bascule aperçu", "flip 3D Y 8° spring heavy, 480 ms, avec ombre qui s'inverse"),
          ("Checklist", "cochage = tracé émeraude progressif 240 ms"),
          ("Publication", "CTA se remplit d'or, sceau, puis transition vers EMP-13")],
  rules=["L'aperçu prestataire masque STRICTEMENT les frais SaaS et le total client : le prestataire ne voit que son prix.",
         "Aucune publication automatique sans action explicite du client (pas de « publier par défaut après 24 h »).",
         "Les missions contenant des données personnelles (adresse exacte) affichent un avertissement de minimisation : l'adresse complète n'est révélée qu'au candidat sélectionné."],
  tokens=["--gold-500", "--emerald-500", "--surface-3", "--glass-2", "--caps"],
  api=["GET /v1/missions/:id/preview", "GET /v1/missions/:id/public-render", "POST /v1/missions/:id/publish"],
  tech="Le rendu prestataire est un composant partagé (package `packages/mission-view`) utilisé par PRE-07 et EMP-12 : "
       "une seule implémentation, donc zéro divergence.",
  canon="Aperçu de publication", chrome={"appbar": "Aperçu", "glyph": "◈"}),

S("EMP-13", "Mission publiée", "EMP", "Missions", "/client/missions/:id/publiee", "Client", "P1", "Célébration sobre",
  intent="Confirmer la publication et orienter immédiatement vers la suite utile : attente de candidatures, matching automatique, "
         "partage du lien. Un seul moment de récompense dans tout le produit — et il est sobre.",
  zones=[
    Z("verdict", "Sceau de publication", 3, "Sceau émeraude « Mission publiée » + référence M-2026-0142 en Mono. Aucun confetti : un anneau qui se referme, une fois."),
    Z("kpi", "Prochaines étapes factuelles", 3, "3 tuiles : « Candidatures attendues sous 2 h » (indicatif, jamais garanti) · « Matching lancé » avec lien vers EMP-18 · « Lien de partage » copiable."),
    Z("list", "Premières candidatures", 3, "Si des candidats matchent déjà : les 2 meilleurs profils en cartes compactes avec score, lien EMP-16."),
    Z("cta", "Actions", 2, "« Voir les candidatures » (or, devient l'action principale) · « Copier le lien » fantôme · « Retour au dashboard » texte."),
  ],
  comps=[("C-04 StatusSeal", "émeraude, 96 px, une seule pulsation"),
         ("Carte candidat compacte", "C-09 en version réduite"),
         ("Bouton copier", "confirmation « Copié » 1 200 ms, haptique light")],
  states=[("Publiée", "Sceau + tuiles + candidats éventuels."),
          ("Publiée sans candidature", "texte factuel : « Aucune candidature pour l'instant. Le matching s'exécute toutes les 30 min. »"),
          ("Partage", "lien court traçable (source=link), jamais de tracking intrusif."),
          ("Annulation", "possibilité de dépublier dans les 60 s (undo), ensuite dépublication = archivage avec motif.")],
  motion=[("Sceau", "une pulsation émeraude 1 200 ms puis extinction"),
          ("Tuiles", "stagger 60 ms"),
          ("Undo", "barre d'annulation qui se vide en 60 s (durée affichée)")],
  rules=["Aucun engagement de résultat sur les candidatures : « attendues » avec un indicateur, jamais une promesse.",
         "La dépublication est possible mais journalisée ; toute candidature déjà reçue reste consultable (aucune perte).",
         "Le lien de partage ne révèle aucune donnée personnelle du client."],
  tokens=["--emerald-500", "--grad-emerald", "--gold-500", "--surface-2", "--mono"],
  api=["POST /v1/missions/:id/publish (idempotent)", "GET /v1/missions/:id/matches?limit=2", "POST /v1/missions/:id/share-link"],
  tech="Publication idempotente (clé d'idempotence par mission+version). Le lien de partage est signé, révocable, sans données personnelles.",
  canon="Confirmation de publication", chrome={"appbar": "Publiée", "glyph": "◈"}),

S("EMP-14", "Détail mission (client)", "EMP", "Missions", "/client/missions/:id", "Client", "P0", "Dossier maître",
  intent="Le dossier central d'une mission : tout ce qui s'est passé, dans l'ordre, avec les preuves. C'est la source unique "
         "de vérité en cas de désaccord — et le document qu'on peut montrer à un juge.",
  zones=[
    Z("hero", "En-tête de dossier", 3, "Titre, référence Mono, sceau de statut, dates clés, prestataire sélectionné (avatar + lien profil), montant total client."),
    Z("timeline", "Frise d'exécution", 4, "C-06 complet : publication → candidature retenue → contrats signés → jalons d'exécution → validations → paiement. Chaque point avec preuve liée (document R2, photo, OTP)."),
    Z("list", "Actions contextuelles", 3, "Selon l'état : examiner les candidatures · valider une preuve · ouvrir un litige · déclarer un paiement · télécharger le dossier complet (PDF, avec hash)."),
    Z("table", "Registre financier de la mission", 3, "Tableau : échéance, montant, état (en attente / payé / contesté), preuve. Total vérifié = total client."),
    Z("cta", "Action prioritaire", 1, "Une seule action mise en avant selon l'état (ex. « Valider la preuve de livraison »)."),
  ],
  comps=[("C-06 TimelineTrack", "variante dossier : chaque point ouvre sa preuve"),
         ("C-05 PriceBreakdown", "compact en en-tête, complet en section financière"),
         ("Export de dossier", "PDF horodaté + hash, servi depuis R2 via URL signée courte"),
         ("C-11 DocumentCardR2", "preuves avec vignettes et versions")],
  states=[("Publique", "Candidatures en cours, CTA = examiner les candidatures."),
          ("En cours d'exécution", "Frise active, CTA = valider la preuve attendue."),
          ("Litige", "Bandeau clay, actions gelées, CTA = suivre le litige (EMP-49)."),
          ("Clôturée", "Lecture seule, export de dossier mis en avant, récapitulatif FIN et réputation.")],
  motion=[("Frise", "point actif pulsé 2 400 ms ; progression qui se trace 420 ms à l'arrivée d'un jalon"),
          ("Partage élément", "depuis la liste (EMP-05) : morph de carte vers en-tête"),
          ("Export", "sceau or au succès du PDF, haptique medium")],
  rules=["Toute preuve est horodatée et hashée ; aucune pièce ne peut être modifiée après validation (nouvelle version R2 uniquement).",
         "Le dossier exportable contient : dates, parties, montants FIN, preuves, décisions — rien de plus, rien de moins.",
         "Un litige fige les paiements et les validations mais jamais l'accès en lecture."],
  tokens=["--surface-1", "--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/missions/:id", "GET /v1/missions/:id/timeline", "GET /v1/missions/:id/report.pdf", "POST /v1/missions/:id/dispute"],
  tech="La timeline est reconstruite à partir du journal d'événements append-only (event store). Chaque entrée porte son "
       "identifiant d'événement Mono, ce qui rend le dossier auditable ligne à ligne.",
  canon="Mission — fiche dossier (client)", chrome={"appbar": "Mission", "glyph": "◈"}),

S("EMP-15", "Modifier une mission", "EMP", "Missions", "/client/missions/:id/modifier", "Client", "P1", "Édition sous contrainte",
  intent="Modifier une mission sans casser les engagements déjà pris. L'UI applique la règle : ce qui est libre se modifie, "
         "ce qui est engagé passe par un avenant (version R2) avec accord du prestataire.",
  zones=[
    Z("list", "Champs modifiables par état", 4, "Encore publique : tout est libre (le changement de prix re-déclenche la qualification). Après sélection : le périmètre et les dates exigent un avenant, le titre reste libre."),
    Z("form", "Éditeur avec verrouillage", 5, "Champs verrouillés affichés en lecture (cadenas ardoise + raison), champs libres éditables en verre. Chaque champ porte sa règle : « libre », « avenant requis », « re-qualification requise »."),
    Z("kpi", "Impact de la modification", 3, "Encart d'impact : « Ce changement ré-ouvre la qualification (délai ~5 min) » ou « Un avenant R2 sera envoyé au prestataire pour accord »."),
    Z("cta", "Validation", 2, "« Enregistrer les modifications » or · « Annuler » fantôme. Si avenant : « Envoyer l'avenant » avec aperçu du diff."),
  ],
  comps=[("Champ verrouillé", "cadenas + raison + lien « pourquoi ? »"),
         ("Vue de diff", "avant/après en deux colonnes, changements surlignés or"),
         ("Bandeau de conséquence", "ambre si re-qualification, émeraude si simple édition")],
  states=[("Libre", "Tous champs éditables, sauvegarde optimiste."),
          ("Avenant requis", "les champs engagés sont cadenassés ; l'édition passe en mode proposition (R2)."),
          ("Re-qualification", "si le périmètre change : bandeau ambre, publication suspendue pendant la revue."),
          ("Conflit", "édition concurrente (deux onglets) → 409 SYS-06 avec comparaison des deux versions.")],
  motion=[("Déverrouillage", "cadenas qui s'ouvre 240 ms, champ qui s'illumine d'un rim or"),
          ("Diff", "lignes ajoutées/supprimées en glissement 60 ms"),
          ("Envoi d'avenant", "fly-to du document vers l'icône contrats, 480 ms")],
  rules=["Aucune modification silencieuse d'un engagement : tout changement de périmètre, date ou prix après sélection exige un avenant signé.",
         "Le changement de catégorie après sélection est interdit (il invaliderait la qualification initiale) — archive + nouvelle mission obligatoire.",
         "Chaque version de mission est conservée et consultable (Mono, version v1, v2…)."],
  tokens=["--amber-500", "--gold-500", "--surface-2", "--mono", "--slate-500"],
  api=["PATCH /v1/missions/:id", "POST /v1/missions/:id/amendments", "GET /v1/missions/:id/diff"],
  tech="Modèle d'édition optimiste avec ETag/If-Match. Les avenants réutilisent le moteur de contrat (version R2) et le "
       "flux de signature existant — aucun code parallèle.",
  canon="Mission — édition & avenants", chrome={"appbar": "Modifier", "glyph": "◈"}),
]
