# -*- coding: utf-8 -*-
"""FAMILLE 02 · CLIENT — EMP-46 → EMP-60"""
from ..model import S, Z, CHROME_APP

SCREENS = [

S("EMP-46", "Reçu & preuve de paiement", "EMP", "Exécution & Paiements", "/client/paiements/:id/recu", "Client", "P1", "Preuve scellée",
  intent="Un reçu qui vaut comme preuve : montants exacts, parties, dates, référence de transaction, empreinte. Utilisable "
         "devant un comptable ou un juge sans retraitement.",
  zones=[
    Z("doc", "Reçu papier-numérique", 5, "Document type facture : en-tête LE LABEUR, parties, mission (réf Mono), triplet FIN, méthode, référence de transaction, date/heure serveur, mention d'exécution."),
    Z("sign", "Scellement", 3, "Empreinte SHA-256 du document (Mono, copiable), QR de vérification pointant vers la page publique de vérification, horodatage serveur."),
    Z("cta", "Diffusion", 2, "« Télécharger le PDF » or outline · « Partager le lien de vérification » fantôme · « Ajouter à mon comptable » (export)."),
  ],
  comps=[("Document A4", "rendu fidèle, impression propre (fond blanc en mode export)"),
         ("QR de vérification", "généré côté serveur, cible publique signée"),
         ("Empreinte", "Mono tronquée + bouton copier")],
  states=[("Émis", "disponible immédiatement au paiement confirmé (jamais avant)."),
          ("Remboursé", "mention « remboursé le … » + nouvelle empreinte liée."),
          ("Annulé", "cas rare (erreur PSP) : mention explicite et ligne négative au ledger.")],
  motion=[("Émission", "sceau or → émeraude, une fois, haptique medium"),
          ("Téléchargement", "aucune animation parasite : progression natif du navigateur")],
  rules=["Un reçu n'est jamais émis pour un paiement non confirmé par le PSP (webhook) ou confirmé par double attestation (hors plateforme).",
         "Le reçu est immuable : une correction produit un nouveau document référençant l'ancien.",
         "Le QR ne contient aucune donnée personnelle : seulement un identifiant de vérification."],
  tokens=["--gold-500", "--emerald-500", "--mono", "--glass-1"],
  api=["GET /v1/payments/:id/receipt.pdf", "GET /v1/verify/:token (public)"],
  tech="PDF/A généré côté serveur avec police embarquée, stocké en R2 (object lock 10 ans). Page de vérification publique "
       "qui recalcule l'empreinte et affiche conforme/non conforme.",
  canon="Paiements — historique & export", variant_of="EMP-45", chrome={"appbar": "Reçu", "glyph": "◈"}),

S("EMP-47", "Plan de paiement (échéancier)", "EMP", "Exécution & Paiements", "/client/paiements/plan", "Client", "P1", "Ingénierie des échéances",
  intent="Définir ou réviser l'échéancier d'une mission : combien d'échéances, quel pourcentage, liées à quels jalons. "
         "Toute modification après signature passe par un avenant (traçable).",
  zones=[
    Z("form", "Constructeur d'échéancier", 5, "Lignes d'échéances : libellé, % ou montant, jalon déclencheur, date maximale. Ajouter/supprimer/réordonner. Somme contrôlée en direct."),
    Z("price", "Contrôle de somme", 4, "Barre de vérification : somme des échéances = Total client. Écart affiché en temps réel (clay si ≠ 0), avec le triplet FIN rappelé."),
    Z("list", "Modèles réutilisables", 2, "Trois modèles : 40/60 classique · 30/40/30 par jalons · 100 % à la validation finale. Aucun modèle « 10 % de plus au client » : le frais SaaS est déjà dans le total."),
    Z("cta", "Valider", 2, "« Appliquer l'échéancier » or · « Enregistrer comme modèle » fantôme (limité à 10)."),
  ],
  comps=[("Lignes réordonnables", "drag + poignées, poids affiché"),
         ("Contrôle de somme", "jauge or→clay si écart"),
         ("Modèles", "cartes compactes avec aperçu de la répartition")],
  states=[("Équilibré", "somme = total, jauge émeraude."),
          ("Déséquilibré", "écart en clair (« il manque 12 000 F »), CTA désarmé."),
          ("Échéance passée", "avertissement si une échéance est datée dans le passé."),
          ("Après signature", "mode avenant : aperçu du diff + envoi pour accord du prestataire.")],
  motion=[("Ajout d'échéance", "insertion 240 ms, jauge qui se rééquilibre par spring soft"),
          ("Drag", "spring snap, poids recalculés en direct")],
  rules=["La somme des échéances DOIT égaler le total client : le système refuse l'incohérence, il ne l'arrondit jamais.",
         "Toute modification après signature exige l'avenant signé des deux parties (INV-3).",
         "Les échéances liées à un jalon ne sont payables qu'après validation de la preuve de ce jalon (EMP-38)."],
  tokens=["--gold-500", "--clay-500", "--emerald-500", "--mono", "--glass-2"],
  api=["PUT /v1/contracts/:id/payment-plan", "POST /v1/contracts/:id/payment-plan/amendment", "GET /v1/payment-plans/templates"],
  tech="Le service financier valide l'échéancier (contraintes de somme, de dates, de jalons) avant de l'écrire. "
       "Le contrôle de somme est binaire : sauf accord contraire explicite, l'incohérence est rejetée côté serveur.",
  canon="Paiements — échéancier", chrome={"appbar": "Échéancier", "glyph": "◈"}),

S("EMP-48", "Litige de paiement", "EMP", "Exécution & Paiements", "/client/paiements/:id/litige", "Client", "P0", "Contestation financière",
  intent="Contester une ligne financière précisément : montant, calcul, imputation. L'écran sépare ce qui relève d'une "
         "erreur de calcul (résolu vite) de ce qui relève d'un désaccord sur le travail (litige contractuel).",
  zones=[
    Z("price", "Ligne contestée", 4, "Détail complet de l'échéance contestée : triplet FIN, calcul, éléments déclencheurs. Le montant contesté est affiché en clay, le reste en neutre."),
    Z("form", "Nature de la contestation", 4, "Catégories : erreur de calcul · échéance non due · déjà payée (hors plateforme) · montant erroné · frais incompris. Chacune avec son flux attendu et son délai."),
    Z("kpi", "Traitement attendu", 3, "Erreur de calcul → correction sous 24 h par LE LABEUR. Désaccord contractuel → médiation (EMP-39). Déjà payée → vérification croisée (EMP-44)."),
    Z("cta", "Envoyer", 2, "« Soumettre la contestation » or · « Annuler » fantôme."),
  ],
  comps=[("Bloc de calcul", "lignes de calcul numérotées, reproductibles"),
         ("Radios de nature", "avec icône et délai annoncé"),
         ("Encart de réorientation", "si la nature choisie ne correspond pas, suggestion du bon flux")],
  states=[("Erreur réelle", "bandeau émeraude : « Erreur confirmée, correction en cours », remboursement/ajustement automatique."),
          ("Désaccord", "clay : renvoi vers le litige contractuel, pré-rempli avec les faits."),
          ("Contestation abusive", "rejetée avec motif et comptage visible."),
          ("Résolue", "historique : contestation, décision, correction, empreinte.")],
  motion=[("Soumission", "sceau or outline (contestation enregistrée)"),
          ("Correction", "la ligne contestée se recompose : ancien montant barré, nouveau en or")],
  rules=["Toute erreur de calcul confirmée est corrigée sans procédure : LE LABEUR assume l'erreur et rembourse/ajuste.",
         "Une contestation ne suspend pas automatiquement le paiement : seul un litige (EMP-39) le fait, sur décision explicite.",
         "Les frais SaaS ne peuvent être contestés que sur leur base de calcul, jamais sur leur existence (affichés et acceptés à la création)."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono"],
  api=["POST /v1/payments/:id/disputes {nature, facts}", "GET /v1/payments/:id/recalculation"],
  tech="Moteur de recalcul côté serveur (rejoue le calcul financier) : une erreur de calcul est détectée automatiquement et "
       "déclenche une correction compensatoire inscrite au ledger (jamais une suppression).",
  canon="Paiement — contestation", chrome={"appbar": "Contestation", "glyph": "◈"}),

S("EMP-49", "Litige — dossier complet", "EMP", "Litiges & Remplacement", "/client/litiges/:id", "Client", "P0", "Dossier contradictoire",
  intent="Le dossier de litige dans son intégralité : faits, pièces des deux parties, analyses automatiques, étapes. "
         "Un écran conçu pour être équitable — donc rassurant pour les deux côtés.",
  zones=[
    Z("hero", "En-tête de dossier", 3, "Référence L-2026-0007 (Mono), mission liée, parties, montant en jeu, étape actuelle, échéances."),
    Z("chat", "Faits & échanges", 5, "Chronologie des faits (déclaration, réponses, ajouts) + fil de messages modéré. Pièces jointes horodatées et hashées."),
    Z("table", "Analyse des pièces", 4, "Table des pièces : type, partie qui la produit, horodatage, verdict automatique (conforme / contestable / insuffisante) — l'humain décide, la machine constate."),
    Z("cta", "Actions du client", 2, "« Ajouter un élément » or outline · « Répondre au fil » fantôme · « Accepter la médiation » or si proposée."),
  ],
  comps=[("C-13 DisputeThread", "strict, horodaté, rôles identifiables"),
         ("C-11 DocumentCardR2", "pièces avec verdict automatique"),
         ("Bandeau d'équité", "« Les deux parties voient les mêmes pièces »"),
         ("Échéancier de procédure", "compte à rebours de l'étape en cours")],
  states=[("Instruction", "les deux parties peuvent ajouter des éléments."),
          ("Médiation proposée", "carte de proposition avec montant/conditions et délai 72 h."),
          ("Décision imminente", "bandeau : « la modération rendra sa décision le JJ à HH:MM »."),
          ("Recours", "une seule révision possible, formulaire dédié, 7 jours après décision."),
          ("Clos", "archive complète, exécution financière visible.")],
  motion=[("Ouverture", "dossier qui se déplie 560 ms, pièces qui s'alignent"),
          ("Nouvelle pièce", "insertion 240 ms + mise en évidence 3 s"),
          ("Décision", "bascule sobre, aucun effet festif — un litige n'est pas un succès")],
  rules=["Le dossier est intégralement consultable par les deux parties (aucune pièce cachée, sauf signalement anonyme prétraité).",
         "Aucune décision sans phase contradictoire complète : les délais sont des droits.",
         "Les analyses automatiques sont indicatives et affichées comme telles (jamais présentées comme des verdicts)."],
  tokens=["--clay-500", "--amber-500", "--mono", "--glass-2", "--text-mid"],
  api=["GET /v1/disputes/:id/full", "POST /v1/disputes/:id/evidence", "POST /v1/disputes/:id/messages", "GET /v1/disputes/:id/deadlines"],
  tech="Dossier assemblé depuis l'event store + pièces R2. Le rendu est identique côté client, prestataire et modération, "
       "à la projection des champs près (le client ne voit pas les notes internes de modération).",
  canon="Litige — fiche & pièces", chrome={"appbar": "Litige", "glyph": "◈"}),

S("EMP-50", "Litige — pièces et preuves", "EMP", "Litiges & Remplacement", "/client/litiges/:id/preuves", "Client", "P1", "Galerie de vérité",
  intent="Voir toutes les pièces du litige côte à côte, avec leur statut et leur origine. En 30 secondes, chacun comprend "
         "sur quoi la décision va se fonder.",
  zones=[
    Z("list", "Galerie de pièces", 5, "Vignettes : photos (zoom), PDF (aperçu), vidéos (lecteur 90 s), relevés système (Jalons, horodatages, OTP). Chaque pièce avec son verdict automatique et sa partie émettrice."),
    Z("table", "Table de synthèse", 4, "Ligne par pièce : type · émis par · date · hash court · verdict. Tri par pertinence (calculée, expliquée)."),
    Z("kpi", "Cohérence", 3, "Indicateurs : pièces des deux parties présentes ? ✔ · horodatages cohérents ? ✔ · contradictions détectées ? (2 signalées, avec lien)."),
    Z("cta", "Actions", 1, "« Ajouter une pièce » or outline · « Télécharger le lot » (ZIP signé, pour usage externe/justice)."),
  ],
  comps=[("Galerie média", "grille 2 colonnes, zoom, navigation clavier"),
         ("Verdict de pièce", "glyphe + libellé (conforme / contestable / insuffisante)"),
         ("Détecteur de contradictions", "les deux pièces liées sont surlignées ensemble"),
         ("Export ZIP", "hash du lot affiché")],
  states=[("Équilibré", "pièces des deux parties présentes."),
          ("Déséquilibré", "« Le prestataire n'a produit aucune pièce » — signalé, non préjudiciable par principe, mais visible."),
          ("Contradiction", "deux pièces en conflit liées par un trait pointillé clay."),
          ("Lot exporté", "notification avec lien signé 24 h.")],
  motion=[("Galerie", "chargement progressif, pas de layout shift"),
          ("Zoom", "ouverture plein écran 420 ms, fermeture par glissement vertical"),
          ("Contradictions", "trait qui se trace entre les deux cartes 420 ms")],
  rules=["Aucune pièce ne peut être retirée après soumission (ajout uniquement) : l'intégrité du dossier est un droit.",
         "Les verdicts automatiques sont visibles des deux parties (transparence) mais annotés « indicatif ».",
         "Le lot exportable sert l'accès à la justice : il ne peut être restreint, même en cas de blocage de compte."],
  tokens=["--mono", "--clay-500", "--amber-500", "--glass-1"],
  api=["GET /v1/disputes/:id/evidence", "GET /v1/disputes/:id/evidence/export.zip", "POST /v1/disputes/:id/evidence"],
  tech="Pièces en R2 avec horodatage serveur et empreinte ; le ZIP d'export est généré côté serveur avec un manifeste signé "
       "(liste des empreintes) pour garantir l'usage juridique.",
  canon="Litige — fiche & pièces", variant_of="EMP-49", chrome={"appbar": "Pièces", "glyph": "◈"}),

S("EMP-51", "Litige — proposition de résolution", "EMP", "Litiges & Remplacement", "/client/litiges/:id/resolution", "Client", "P0", "Porte de sortie",
  intent="Proposer une sortie honorable aux deux parties : montant ajusté, travaux complémentaires, annulation partielle. "
         "L'écran explique précisément ce que l'acceptation emporte.",
  zones=[
    Z("hero", "Proposition en clair", 4, "Carte de résolution : type (ajustement de prix · exécution complémentaire · résiliation amiable) + montant ou périmètre + motif. Rendu comme un mini-contrat."),
    Z("price", "Impact FIN exact", 4, "Avant / après : prix prestataire, frais SaaS recalculés, total client final. Les deltas signés (+/−) en or/ardoisе, chiffres tnum."),
    Z("list", "Ce que l'acceptation emporte", 3, "Conséquences listées : dégel des paiements · renonciation au recours sur ces faits · clôture du litige · impact réputation (neutre, aucune pénalité automatique)."),
    Z("cta", "Décider", 2, "« Accepter la résolution » or · « Refuser et continuer la procédure » fantôme."),
  ],
  comps=[("Carte de résolution", "structure de mini-contrat, sections numérotées"),
         ("Table avant/après", "deltas signés, tnum"),
         ("Checklist de conséquences", "chaque ligne avec son effet juridique expliqué en clair")],
  states=[("Proposée", "délai 72 h affiché, compte à rebours Mono."),
          ("Acceptée par vous", "attente d'acceptation par l'autre partie (48 h)."),
          ("Acceptée par les deux", "émeraude, exécution automatique (paiement ajusté, clôture)."),
          ("Refusée", "retour en procédure, la proposition est archivée (elle pourra être reprise à l'amiable)."),
          ("Expirée", "retour en procédure, mention claire — aucune acceptation tacite possible.")],
  motion=[("Ouverture", "carte 560 ms spring heavy, ton neutre"),
          ("Acceptation", "double acceptation → double sceau emboîté émeraude"),
          ("Refus", "bascule sobre ardoise, aucune animation punitive")],
  rules=["Aucune acceptation tacite : une proposition expirée est expirée. L'argent ne se décide pas par défaut.",
         "La résolution acceptée devient une écriture contractuelle (avenant R2 du contrat) avec empreinte.",
         "Les frais SaaS sont recalculés sur le montant final, jamais sur le montant initial contesté."],
  tokens=["--emerald-500", "--gold-500", "--clay-500", "--mono", "--glass-3"],
  api=["GET /v1/disputes/:id/resolutions", "POST /v1/disputes/:id/resolutions/:rid/accept", "POST /v1/disputes/:id/resolutions/:rid/refuse"],
  tech="Les résolutions sont des objets contractuels à part entière : elles génèrent un avenant R2, des écritures compensatoires "
       "au ledger et une clôture de litige transactionnelle.",
  canon="Litige — résolution & clôture", chrome={"appbar": "Résolution", "glyph": "◈"}),

S("EMP-52", "Litige — escalade & revue admin", "EMP", "Litiges & Remplacement", "/client/litiges/:id/escalade", "Client", "P1", "Appel à l'humain",
  intent="Quand le désaccord persiste : escalader vers la modération LE LABEUR, avec un dossier complet et des attentes "
         "claires (délais, critères, décision exécutoire).",
  zones=[
    Z("form", "Demande d'escalade", 4, "Motif d'escalade (médiation échouée · pièce nouvelle décisive · délai dépassé · décision contestée) + argumentaire structuré + pièces additionnelles."),
    Z("list", "Ce que la modération examinera", 4, "Checklist des critères : conformité au contrat · cohérence des preuves · respect des procédures · équité. Chaque critère avec son poids indicatif (public)."),
    Z("timeline", "Délais opposables", 3, "Instruction sous 5 jours ouvrés · décision motivée · exécution sous 72 h. Aucun délai ne peut être modifié sans en informer les parties."),
    Z("cta", "Envoyer", 2, "« Soumettre à la modération » or · « Retirer la demande » fantôme."),
  ],
  comps=[("Argumentaire structuré", "champs quoi/quand/quel droit/pourquoi, pas de zone libre fourre-tout"),
         ("Checklist de critères", "transparence sur la grille d'analyse"),
         ("C-06 TimelineTrack", "variante procédure contradictoire")],
  states=[("En instruction", "position en file affichée (rang approximatif, jamais fictif)."),
          ("Pièce demandée", "la modération peut demander une pièce précise sous 72 h."),
          ("Décision rendue", "texte motivé + exécution + recours unique (7 jours)."),
          ("Retirée par le client", "historique conservé, aucune conséquence.")],
  motion=[("Soumission", "sceau or outline (dossier transmis)"),
          ("Décision", "bascule sobre, texte qui se révèle paragraphe par paragraphe (lecture guidée)")],
  rules=["La modération est indépendante du support commercial : l'écran le dit explicitement (confiance).",
         "Aucune décision sans motifs écrits ; la grille d'analyse est publique et stable.",
         "Les décisions sont exécutoires dans le système (paiements, réputation, contrats) : LE LABEUR ne renvoie pas les parties à un autre tribunal interne."],
  tokens=["--violet-500", "--clay-500", "--gold-500", "--mono", "--surface-2"],
  api=["POST /v1/disputes/:id/escalate", "GET /v1/disputes/:id/moderation-queue", "GET /v1/moderation/criteria (public)"],
  tech="Escalade crée une tâche dans la file de modération (ADM-26) avec SLA surveillé par jobs cron ; toute violation de "
       "SLA déclenche une alerte interne et une information aux parties.",
  canon="Litige — escalade & attente", chrome={"appbar": "Escalade", "glyph": "◈"}),

S("EMP-53", "Litige — attente de décision", "EMP", "Litiges & Remplacement", "/client/litiges/:id/attente", "Client", "P1", "Attente habitée",
  intent="Rendre l'attente supportable et utile : où en est l'instruction, ce que fait la modération maintenant, ce que le "
         "client peut préparer. Aucune page blanche anxiogène.",
  zones=[
    Z("timeline", "Instruction en cours", 4, "Étapes internes rendues visibles (analyse des pièces, audition écrite des parties, rédaction de la décision) avec horodatages réels."),
    Z("list", "Préparer sa position", 4, "Suggestions concrètes : pièces manquantes utiles, points de droit à expliciter, questions souvent posées par la modération."),
    Z("kpi", "Délais restants", 3, "Jours ouvrés restants (Mono), date prévisionnelle de décision, rappel des référés possibles (blocage de paiement déjà actif)."),
    Z("cta", "Actions", 1, "« Ajouter une pièce » or outline · « Voir le dossier complet » fantôme."),
  ],
  comps=[("C-06 TimelineTrack", "variante instruction"),
         ("Cartes de préparation", "conseils factuels, jamais de promesse de résultat"),
         ("Compteur de délais", "Mono, jours ouvrés, jours fériés pris en compte")],
  states=[("Dans les délais", "neutre, échéance affichée."),
          ("Retard de la modération", "ambre + annonce honnête : « retard, décision sous 48 h supplémentaires » (SLA tenu par LE LABEUR, pas par les parties)."),
          ("Pièce supplémentaire demandée", "action prioritaire mise en avant."),
          ("Décision imminente", "annonce à J-1.")],
  motion=[("Étapes", "progression qui se trace à chaque étape franchie"),
          ("Retard", "bascule ambre, ton sobre")],
  rules=["LE LABEUR assume ses délais : un retard de modération est affiché et éventuellement compensé (geste commercial tracé).",
         "Aucune pression sur les parties pendant l'instruction : pas de relance automatique de « acceptez la résolution ».",
         "L'attente n'empêche aucun accès : toutes les pièces restent consultables."],
  tokens=["--amber-500", "--slate-500", "--mono", "--glass-1"],
  api=["GET /v1/disputes/:id/instruction", "GET /v1/disputes/:id/sla"],
  tech="Vue dérivée de la file de modération avec projection limitée (le client voit l'étape, pas les notes internes). "
       "Le calcul des jours ouvrés passe par le calendrier public de la plateforme.",
  canon="Litige — escalade & attente", variant_of="EMP-52", chrome={"appbar": "Attente", "glyph": "◈"}),

S("EMP-54", "Décision de modération (vue client)", "EMP", "Litiges & Remplacement", "/client/litiges/:id/decision", "Client", "P0", "Verdict argumenté",
  intent="Recevoir une décision qui explique, pas qui assène : motivations, pièces retenues, effet exécutoire, recours "
         "unique. Un écran écrit pour être relu — et éventuellement produit devant un tiers.",
  zones=[
    Z("verdict", "Verdict", 4, "Sceau selon l'issue (émeraude : conforme à votre demande · ambre : partage · clay : rejet) + phrase de décision en --title-1, sans jargon."),
    Z("doc", "Motivation écrite", 6, "Texte structuré : faits retenus · pièces décisives · règles appliquées (renvois aux clauses du contrat) · calcul financier si applicable. Chaque assertion est liée à une pièce."),
    Z("price", "Exécution financière", 3, "Ce qui va être payé, remboursé ou ajusté, avec montants tnum et dates d'exécution. Triplet FIN recalculé si ajustement."),
    Z("cta", "Suite", 2, "« Télécharger la décision » (PDF signé) or outline · « Demander une révision » fantôme (unique, 7 jours) · « Clôturer » texte."),
  ],
  comps=[("Texte motivé", "typographie de lecture (Inter 16/26), renvois numérotés"),
         ("Liens vers pièces", "CL-01, CL-02… numérotés et cliquables"),
         ("Bandeau d'exécution", "dit exactement ce qui se passe ensuite, sans ambiguïté")],
  states=[("Favorable", "émeraude atténué, exécution immédiate."),
          ("Partage", "ambre, exécution détaillée ligne par ligne."),
          ("Rejet", "clay sobre, motivations complètes, recours expliqué."),
          ("Révision demandée", "bandeau violet, seconde décision définitive annoncée.")],
  motion=[("Révélation", "verdict puis motivation en deux temps de 420 ms (le jugement avant l'explication)"),
          ("Exécution", "lignes de montants qui se stabilisent en tnum")],
  rules=["Toute décision est motivée par écrit, liée à des pièces et à des clauses : aucun « verdict d'autorité ».",
         "La décision est exécutée automatiquement dans le système (ledger, réputation, contrats) sous 72 h maximum.",
         "Le PDF signé est téléchargeable et vérifiable via QR comme les reçus."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--mono", "--glass-1"],
  api=["GET /v1/disputes/:id/decision", "GET /v1/disputes/:id/decision.pdf", "POST /v1/disputes/:id/revision"],
  tech="Décision rédigée dans l'outil de modération (ADM-29) avec structure contrainte (faits/pièces/règles/finances). "
       "Publication côté parties en lecture seule, PDF/A généré et hashé.",
  canon="Litige — décision & clôture", chrome={"appbar": "Décision", "glyph": "◈"}),

S("EMP-55", "Litige clôturé", "EMP", "Litiges & Remplacement", "/client/litiges/:id/cloture", "Client", "P1", "Après le conflit",
  intent="Clore sans laisser de rancœur procédurale : récapitulatif, effets appliqués, et leçons visibles (ce qui aurait pu "
         "l'éviter — pédagogie, pas reproche).",
  zones=[
    Z("verdict", "Sceau de clôture", 3, "Sceau ardoise « Litige clos » + date + issue en une phrase."),
    Z("table", "Effets appliqués", 4, "Table : paiement ajusté · réputation · contrat (résilié/terminé) · échéances supprimées. Chaque ligne avec sa référence de ledger (Mono)."),
    Z("list", "Prévention", 3, "Conseils contextuels issus de ce dossier : ex. « une clause de preuve hebdomadaire aurait réduit le risque ». Proposés, jamais imposés."),
    Z("cta", "Actions", 1, "« Télécharger l'archive complète » or outline · « Relancer une mission avec ce prestataire » fantôme (si relation réparable)."),
  ],
  comps=[("Table d'effets", "références ledger copiables"),
         ("Cartes de prévention", "conseils factuels"),
         ("Archive complète", "ZIP signé : dossier entier, pièces, décisions")],
  states=[("Clos normalement", "ardoise neutre."),
          ("Clos avec révision", "mention de la seconde décision, définitive."),
          ("Clos, réputation impactée", "si l'issue impose une écriture de réputation : affichée et explicable."),
          ("Réouverture impossible", "mention claire : seuls des faits nouveaux graves peuvent ouvrir un dossier neuf.")],
  motion=[("Clôture", "sceau ardoise qui s'imprime 640 ms, aucune célébration"),
          ("Archive", "génération asynchrone, notification")],
  rules=["Aucune écriture de réputation n'est appliquée sans motivation liée à la décision (INV-5 : ledger append-only, correction visible).",
         "L'archive complète est disponible sans limite de temps et sans condition (accès à la justice).",
         "Le dossier clos peut être cité en référence lors d'une future mission entre les mêmes parties (lien de confiance, ou de prudence)."],
  tokens=["--slate-500", "--clay-500", "--mono", "--surface-1"],
  api=["GET /v1/disputes/:id/closure", "GET /v1/disputes/:id/archive.zip"],
  tech="Clôture transactionnelle : application des effets (ledger, réputation, contrat), scellement du dossier (hash global), "
       "archivage R2 froid.",
  canon="Litige — décision & clôture", variant_of="EMP-54", chrome={"appbar": "Clôturé", "glyph": "◈"}),

S("EMP-56", "Remplacement requis", "EMP", "Litiges & Remplacement", "/client/missions/:id/remplacement", "Client", "P0", "Reconstruire vite",
  intent="Déclencher un remplacement quand le prestataire ne peut plus exécuter (défaillance, accord mutuel, force majeure). "
         "L'écran préserve le travail déjà fait et cadre la bascule contractuelle.",
  zones=[
    Z("hero", "État du remplacement", 3, "Sceau clay-or (transition) + motif + état du contrat actuel (suspendu, résilié à venir, remplacé)."),
    Z("timeline", "Reprise du travail", 4, "Ce qui est déjà fait et validé · ce qui reste · ce qui doit être refait. Chaque élément avec sa preuve liée, transférable au remplaçant."),
    Z("kpi", "Conditions", 3, "Prix ajusté possible ? (le remplaçant peut coûter plus cher : l'écart est affiché et assumé) · délais recalculés · pénalités suspendues pendant la transition."),
    Z("cta", "Continuer", 2, "« Trouver un remplaçant » or (mène EMP-58) · « Résilier sans remplacement » fantôme (clôture propre)."),
  ],
  comps=[("Carte de reprise", "travail validé / restant / à refaire"),
         ("Bloc de conditions", "prix et délais recalculés, transparence totale"),
         ("C-11 DocumentCardR2", "preuves transférables (référencées, pas dupliquées)")],
  states=[("Déclenché par le prestataire", "notification motivée, droit d'opposition 72 h côté client."),
          ("Déclenché par accord mutuel", "émeraude atténué : sortie amiable, pas de pénalité."),
          ("Déclenché par défaillance", "clay : procédure de constat, preuves, éventuelles pénalités."),
          ("Force majeure", "ardoise : constat documenté, suspension des obligations, délais étendus.")],
  motion=[("Déclenchement", "sceau de transition (or inversé) 640 ms"),
          ("Reprise", "les éléments validés migrent visuellement vers la carte du remplaçant")],
  rules=["Le prestataire sortant est payé pour le travail validé avant la bascule : aucun remplacement ne l'annule (INV-1).",
         "Les clauses de confidentialité restent opposables au prestataire sortant (accès aux données révoqué).",
         "Le client ne peut pas déclencher un remplacement pour échapper à un litige en cours : la procédure suit son cours."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono"],
  api=["POST /v1/missions/:id/replacement {reason}", "GET /v1/missions/:id/handover"],
  tech="Le remplacement crée un dossier de passation : inventaire des livrables/preuves, gel du contrat sortant, ouverture "
       "d'une recherche de remplaçant priorisée.",
  canon="Remplacement — déclenchement", chrome={"appbar": "Remplacement", "glyph": "◈"}),

S("EMP-57", "Remplacement — causes & conditions", "EMP", "Litiges & Remplacement", "/client/missions/:id/remplacement/conditions", "Client", "P1", "Droit de la bascule",
  intent="Poser noir sur blanc les règles du remplacement : qui paie quoi, ce qui est repris, ce qui est perdu, ce qui reste "
         "dû. Un écran juridique, lisible et sans piège.",
  zones=[
    Z("list", "Causes du remplacement", 4, "Liste des causes retenues avec pièces justificatives (défaillance constatée, accord mutuel, force majeure) et leurs conséquences juridiques."),
    Z("price", "Règlement financier de la transition", 5, "Trois blocs : dû au prestataire sortant (travail validé) · nouveau budget (remplaçant) · frais SaaS sur chaque partie. Triplet FIN par contrat, jamais fusionné."),
    Z("kpi", "Ce qui survit et ce qui meurt", 3, "Survit : preuves, jalons validés, dossier mission. Meurt : contrat sortant, accès aux documents du client, obligations de confidentialité maintenues."),
    Z("cta", "Valider", 2, "« J'ai compris, continuer » or · « Voir le détail juridique » fantôme (clauses)."),
  ],
  comps=[("Bilan financier double", "deux triplets FIN côte à côte (sortant / entrant)"),
         ("Tableau survit/meurt", "deux colonnes symétriques"),
         ("Liens de clauses", "renvois article par article")],
  states=[("Informative", "lecture seule, avant acceptation."),
          ("Contestée", "si le client ou le prestataire conteste une cause : renvoi litige."),
          ("Validée", "les conditions deviennent opposables, horodatées."),
          ("Amiable", "variante émeraude atténuée, sans constat de faute.")],
  motion=[("Lecture", "sections révélées au scroll, calculs qui se stabilisent"),
          ("Validation", "sceau or, ton neutre")],
  rules=["Deux contrats, deux triplets FIN distincts : le remplacement ne fusionne JAMAIS les montants (traçabilité comptable).",
         "Le prestataire sortant conserve ses droits acquis et ses preuves de réputation.",
         "La confidentialité survit au remplacement : sanction contractuelle si violation (blocage possible)."],
  tokens=["--gold-500", "--clay-500", "--mono", "--glass-1"],
  api=["GET /v1/missions/:id/replacement/terms", "POST /v1/missions/:id/replacement/acknowledge"],
  tech="Document de bascule généré depuis le modèle contractuel (clauses versionnées), signé par les deux parties. "
       "Les révocations d'accès sont appliquées immédiatement côté serveur (pas d'attente de signature).",
  canon="Remplacement — déclenchement", variant_of="EMP-56", chrome={"appbar": "Conditions", "glyph": "◈"}),

S("EMP-58", "Remplacement — sélection du remplaçant", "EMP", "Litiges & Remplacement", "/client/missions/:id/remplacement/selection", "Client", "P0", "Vivier d'urgence",
  intent="Trouver rapidement un remplaçant compétent, en tenant compte du contexte (urgence, passation, travail déjà réalisé). "
         "Le matching intègre cette réalité : disponibilité immédiate et capacité de reprise.",
  zones=[
    Z("kpi", "Cadre de la recherche", 3, "Urgence affichée (jours restants), périmètre restant, compétence de reprise exigée. Bandeau d'information : les candidats savent qu'il s'agit d'une reprise."),
    Z("list", "Candidats prioritaires", 5, "C-09 avec indicateur de reprise : « disponible sous 48 h », « déjà intervenu sur des missions similaires », « a déjà repris des chantiers ». Score de reprise distinct du score de matching standard."),
    Z("ring", "Décomposition du score de reprise", 3, "Facteurs : disponibilité immédiate (×2), expérience de reprise (×1,5), proximité (×1,5), adéquation au périmètre restant (×2). Explicable comme EMP-19."),
    Z("cta", "Sélectionner", 2, "« Proposer la reprise » or · « Publier une offre de reprise » fantôme (visible des prestataires disponibles)."),
  ],
  comps=[("Badge de reprise", "indicateurs spécifiques, distincts du score standard"),
         ("C-10 MatchScoreRing", "variante reprise, teinte or plus froide"),
         ("Bandeau de transparence", "les candidats savent qu'ils reprennent un dossier existant")],
  states=[("Vivier disponible", "liste de candidats avec score de reprise ≥ 60."),
          ("Vivier pauvre", "bandeau ambre + options : élargir la zone, republier, differer le périmètre."),
          ("Aucun candidat", "proposition de résilier sans remplacement (sortie propre) ou de revoir les exigences."),
          ("Reprise proposée", "transition vers confirmation (EMP-59).")],
  motion=[("Recherche", "progression réelle du run de reprise, badge de fraîcheur"),
          ("Sélection", "carte qui se soulève et vole vers la confirmation")],
  rules=["Le score de reprise est distinct et expliqué : il ne remplace jamais la décision humaine.",
         "Les candidats voient l'état réel de la mission (travail réalisé, litige éventuel) : aucune dissimulation pour attirer.",
         "Le prix du remplaçant peut différer : l'écart est affiché clairement au client avant acceptation."],
  tokens=["--gold-500", "--clay-500", "--violet-500", "--mono"],
  api=["POST /v1/missions/:id/replacement/matching", "GET /v1/missions/:id/replacement/candidates", "POST /v1/missions/:id/replacement/propose"],
  tech="Run de matching dédié avec facteurs de reprise (disponibilité < 72 h, historique de reprises réussies, proximité). "
       "Mêmes garanties d'explicabilité que EMP-19.",
  canon="Remplacement — sélection", chrome={"appbar": "Remplaçant", "glyph": "◈"}),

S("EMP-59", "Remplacement — confirmation", "EMP", "Litiges & Remplacement", "/client/missions/:id/remplacement/confirmation", "Client", "P1", "Bascule scellée",
  intent="Acter la bascule : ancien contrat clos selon les conditions validées, nouveau contrat prêt à signer. Tout est "
         "récapitulé en une page, avec les références croisées.",
  zones=[
    Z("verdict", "Sceau de bascule", 3, "Sceau double : sortant (ardoise) + entrant (or) reliés par un connecteur daté."),
    Z("table", "Récapitulatif de transition", 5, "Table : contrat sortant (statut, montant dû, preuves conservées) · contrat entrant (prix, échéancier, périmètre restant) · différences financières."),
    Z("timeline", "Étapes restantes", 3, "Signature entrante (48 h) → démarrage → engagements de reprise. Comptes à rebours Mono."),
    Z("cta", "Finaliser", 2, "« Générer le contrat de reprise » or · « Voir le dossier de passation » fantôme."),
  ],
  comps=[("Carte de filiation", "deux contrats reliés, références croisées"),
         ("Table de transition", "chiffres tnum, deltas signés"),
         ("Dossier de passation", "inventaire des preuves, accès temporaire du remplaçant aux pièces nécessaires")],
  states=[("Prête", "CTA or."),
          ("Signature en attente", "suivi du remplaçant, relance à 24 h."),
          ("Signée", "nouveau contrat actif, exécution reprise, notification des deux parties."),
          ("Échec de reprise", "retour à EMP-58 avec le dossier intact.")],
  motion=[("Bascule", "connecteur scellé, deux sceaux qui se rejoignent"),
          ("Activation", "émeraude pleine, haptique heavy une seule fois")],
  rules=["Le nouveau contrat reprend explicitement le périmètre restant : il ne peut pas inclure le travail déjà validé et payé.",
         "L'accès du remplaçant aux pièces du dossier est temporaire et limité au strict nécessaire (principe de minimisation).",
         "Les deux contrats restent visibles dans la chaîne de succession pour toujours."],
  tokens=["--gold-500", "--emerald-500", "--slate-500", "--mono"],
  api=["POST /v1/contracts/replacement {missionId, providerId}", "GET /v1/missions/:id/handover-dossier"],
  tech="Génération du contrat de reprise par le même moteur contractuel ; le dossier de passation s'appuie sur des liens de "
       "référence (aucune copie de pièce), révoqués à la fin de la mission.",
  canon="Remplacement — bascule", chrome={"appbar": "Confirmation", "glyph": "◈"}),

S("EMP-60", "Remplacement — contrat successeur", "EMP", "Litiges & Remplacement", "/client/contrats/:id/successeur", "Client", "P1", "Nouveau départ tracé",
  intent="Le contrat du remplaçant, mais avec la mémoire du précédent : il hérite du contexte (référence de succession), "
         "conserve le périmètre restant et interdit toute rémunération de l'existant.",
  zones=[
    Z("hero", "En-tête successeur", 3, "Référence C-2026-0035 « successeur de C-2026-0031 » (Mono) + état + parties."),
    Z("doc", "Clauses spécifiques à la reprise", 5, "Périmètre restant défini par exclusion (ce qui est déjà validé n'est pas repris) · obligations de continuité · accord de confidentialité hérité · clause de non-régression qualité."),
    Z("price", "Conditions financières de reprise", 3, "Triplet FIN du nouveau contrat · rappel du règlement du sortant (référence croisée) · échéancier recalé sur le temps restant."),
    Z("cta", "Actions", 2, "« Signer » or (si en attente) · « Voir l'exécution » fantôme (si actif) · « Voir le contrat d'origine » texte."),
  ],
  comps=[("Bloc de périmètre par exclusion", "liste des jalons validés « non repris », avec preuves"),
         ("Carte de filiation", "lien bidirectionnel"),
         ("C-05 PriceBreakdown", "triplet du nouveau contrat uniquement")],
  states=[("En signature", "CTA signer, rappel du délai de 48 h."),
          ("Actif", "exécution ouverte, livrables du périmètre restant attendus."),
          ("Terminé", "clôture, chaîne complète consultation."),
          ("Résilié", "cas rare : nouveau remplacement possible, la chaîne s'étend à trois contrats.")],
  motion=[("Ouverture", "folio qui s'ouvre, connecteur de filiation qui se trace vers le contrat d'origine"),
          ("Signature", "sceau or, haptique heavy")],
  rules=["Un contrat successeur ne rémunère jamais deux fois le même travail : le périmètre est défini par exclusion, preuve à l'appui.",
         "La chaîne de succession est immuable et complète : tout auditeur peut remonter à l'origine.",
         "Les délais contractuels sont recalculés sur la base du temps restant, jamais mécaniquement reportés."],
  tokens=["--gold-500", "--slate-500", "--emerald-500", "--mono"],
  api=["GET /v1/contracts/:id (successor)", "POST /v1/contracts/:id/sign", "GET /v1/contracts/:id/succession-chain"],
  tech="Moteur contractuel partagé, avec héritage explicite de la chaîne de succession et génération du périmètre par "
       "soustraction des jalons validés.",
  canon="Remplacement — bascule", variant_of="EMP-59", chrome={"appbar": "Successeur", "glyph": "◈"}),
]
