# -*- coding: utf-8 -*-
"""FAMILLE 02 · CLIENT — EMP-31 → EMP-45"""
from ..model import S, Z, CHROME_APP

SCREENS = [

S("EMP-31", "Contrat — signature client", "EMP", "Propositions & Contrats", "/client/contrats/:id/signer", "Client", "P0", "Cérémonie de signature",
  intent="Signer est un acte grave : l'écran le traite comme tel. Lecture guidée des clauses critiques, puis signature "
         "avec preuve complète (identité, horodatage, empreinte du document).",
  zones=[
    Z("doc", "Reprise des clauses critiques", 4, "Extraction des 6 clauses déterminantes (périmètre, livrables, prix, échéancier, pénalités, résiliation) avec leur résumé « En clair ». Le texte intégral reste accessible à tout moment."),
    Z("sign", "Zone de signature", 4, "Pad de signature (tracé lissé, pression ignorée) OU validation par OTP renforcée + phrase de consentement explicite. Le choix est proposé, jamais imposé."),
    Z("kpi", "Ce que la signature déclenche", 3, "Trois faits : engagement ferme · premier paiement exigible à la date X · travail autorisé à compter de la signature des deux parties."),
    Z("cta", "Signer", 2, "« Signer le contrat » or (désactivé jusqu'à la phrase de consentement cochée) · « Enregistrer pour plus tard » fantôme."),
  ],
  comps=[("Pad de signature", "Skia, lissage par spline, épaisseur stable selon vélocité"),
         ("Phrase de consentement", "« Je signe en connaissance de cause… » cochée manuellement (jamais pré-cochée)"),
         ("C-07 OTPField", "variante renforcée : 6 chiffres + code de contrat en Mono"),
         ("Horodatage serveur", "affiché avant validation (« heure serveur 14:32:07 UTC »)")],
  states=[("Lecture", "clauses repliables, progression de lecture visible (facultative mais affichée)."),
          ("Signature en cours", "tracé, bouton s'arme dès 40 points de tracé minimum."),
          ("OTP", "si validation forte choisie : champ + envoi sur le numéro vérifié."),
          ("Signé", "sceau demi-or « Signature client enregistrée », attente de l'autre partie."),
          ("Échec", "clay, jamais perdu : le tracé est conservé localement 5 min.")],
  motion=[("Ouverture", "folio qui s'affiche en deux temps 420 ms"),
          ("Signature", "tracé qui se lisse 120 ms après le lever du stylet/doigt"),
          ("Validation", "sceau demi qui s'imprime, haptique heavy")],
  rules=["Aucune signature sans phrase de consentement cochée explicitement et sans identité de signataire résolue côté serveur.",
         "Le contrat signé est immuable : l'empreinte SHA-256 du PDF signé est affichée et stockée.",
         "La signature du client seule ne rend rien exécutoire : le contrat devient Actif uniquement à la double signature (INV-3)."],
  tokens=["--gold-500", "--grad-gold", "--emerald-500", "--mono", "--glass-4"],
  api=["POST /v1/contracts/:id/sign {method, consent, signatureArtifact}", "GET /v1/contracts/:id/required-consents"],
  tech="Signature manuscrite vectorisée (SVG path) + horodatage serveur + empreinte du document. Le consentement est "
       "enregistré avec sa version de texte (preuve juridique). Aucun secret de clé côté client.",
  a11y=["Pad de signature accessible au clavier (mode « signer par OTP » toujours disponible en alternative).",
        "Les clauses critiques sont lisibles par lecteur d'écran avec leur résumé « en clair »."],
  canon="Contrat — signature", chrome={"appbar": "Signature", "glyph": "◈"}),

S("EMP-32", "Contrat actif", "EMP", "Propositions & Contrats", "/client/contrats/:id/actif", "Client", "P1", "Contrat en vigueur",
  intent="L'état contractuel vivant : la référence quotidienne du client. Ce contrat est actif, voici vos obligations "
         "en cours, l'échéancier et le prochain jalon de preuve.",
  zones=[
    Z("hero", "Bloc d'état actif", 3, "Sceau or plein + « Contrat actif depuis le 01/10 » + référence Mono."),
    Z("timeline", "Obligations en cours", 4, "Frise des obligations : prochaine échéance de paiement, prochain livrable attendu, prochaine preuve à valider."),
    Z("price", "Échéancier vivant", 3, "Prochaine échéance (montant, date) + reste à payer. Triplet FIN conservé en référence."),
    Z("cta", "Actions", 2, "« Voir l'exécution » or · « Télécharger le contrat » fantôme · « Ouvrir un litige » texte (clay, isolé)."),
  ],
  comps=[("C-04 StatusSeal", "or"),
         ("C-06 TimelineTrack", "obligations datées"),
         ("C-05 PriceBreakdown", "version compacte d'échéancier")],
  states=[("Actif sain", "or, aucune alerte."),
          ("Échéance à 48 h", "ambre sur la ligne concernée."),
          ("Retard client", "clay : « Votre échéance du 05/10 est dépassée de 2 jours » + action payer/traiter immédiatement."),
          ("Suspendu (litige)", "clay froid, exécution gelée, CTA = suivre le litige.")],
  motion=[("Entrée", "sceau + frise, 2 temps de 240 ms"),
          ("Alerte", "pulsation ambre 2 400 ms uniquement sur la ligne concernée")],
  rules=["INV-3 rappelé : un contrat actif prouve ses deux signatures en un tap (audit).",
         "Le client ne peut pas suspendre unilatéralement un contrat : seul un litige ou un cas de force majeure documenté le peut.",
         "L'échéancier affiché ici est celui du contrat, pas un simulateur."],
  tokens=["--gold-500", "--amber-500", "--clay-500", "--mono"],
  api=["GET /v1/contracts/:id/state", "GET /v1/contracts/:id/obligations"],
  tech="Vue d'état dérivée du contrat + du calendrier d'obligations. Recalcul des alertes à chaque ouverture (aucun état "
       "périmé affiché).",
  canon="Contrat — folio & états", variant_of="EMP-29", chrome={"appbar": "Contrat actif", "glyph": "◈"}),

S("EMP-33", "Contrat terminé", "EMP", "Propositions & Contrats", "/client/contrats/:id/termine", "Client", "P1", "Clôture prouvée",
  intent="Clore proprement : toutes les obligations remplies, toutes les preuves validées, tout est payé. L'écran sert de "
         "récapitulatif final et d'invitation à évaluer — sans jamais forcer l'évaluation par du chantage à la réputation.",
  zones=[
    Z("verdict", "Sceau de clôture", 3, "Sceau émeraude « Exécution complète » + dates début/fin + durée réelle vs prévue."),
    Z("kpi", "Bilan chiffré", 4, "Prix prestataire versé · Frais SaaS · Total client · deltas éventuels (avenants). Chiffres tnum alignés."),
    Z("list", "Bilan de preuves", 3, "Liste des livrables validés avec liens vers les pièces R2 et l'OTP de réception du salaire."),
    Z("cta", "Suite", 2, "« Évaluer le prestataire » or (facultatif, jamais bloquant) · « Télécharger le dossier » fantôme · « Republier une mission similaire » texte."),
  ],
  comps=[("C-04 StatusSeal", "émeraude pleine"),
         ("Table de bilan", "chiffres tnum, colonnes alignées"),
         ("Carte preuve", "chaque livrable avec hash et date de validation")],
  states=[("Terminé propre", "tout validé, émeraude."),
          ("Terminé avec réserve", "une réserve non soldée → bandeau ambre et lien litige."),
          ("Terminé après litige", "clay atténué, mention « clôturé par décision de modération » + lien décision."),
          ("Évaluation en attente", "rappel discret, jamais bloquant ; expire en 30 jours.")],
  motion=[("Clôture", "sceau émeraude qui s'imprime une fois, 640 ms"),
          ("Bilan", "chiffres qui se stabilisent en tnum 240 ms")],
  rules=["L'évaluation est toujours facultative et réciproquement aveugle (le client ne voit l'avis du prestataire qu'après avoir soumis le sien, ou après 14 jours).",
         "Le dossier final inclut l'OTP de réception : c'est la preuve de paiement la plus forte du système.",
         "Aucune ligne de bilan ne peut être masquée : le client voit exactement ce qu'il a payé et ce que le prestataire a reçu."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--glass-1"],
  api=["GET /v1/contracts/:id/closure", "POST /v1/reviews {contractId}"],
  tech="Le dossier de clôture est généré côté serveur (PDF/A + JSON signé) : il est reproductible à l'identique des années plus tard.",
  canon="Contrat — folio & états", variant_of="EMP-29", chrome={"appbar": "Contrat terminé", "glyph": "◈"}),

S("EMP-34", "Contrat résilié", "EMP", "Propositions & Contrats", "/client/contrats/:id/resilie", "Client", "P1", "Sortie encadrée",
  intent="Quand un contrat se termine mal ou trop tôt : qui a résilié, pourquoi, ce qui est dû au prorata, ce qui reste "
         "en litige. Rien n'est caché, tout est calculé.",
  zones=[
    Z("hero", "Motif & auteur de la résiliation", 3, "Sceau clay + « Résilié par le client le 06/10 » (ou par le prestataire) + motif catégorisé."),
    Z("price", "Sortie financière", 4, "Calcul du dû au prorata : travail réalisé (validé) · montant dû · frais SaaS correspondants · total client ajusté. Lignes FIN maintenues dans l'ordre canonique."),
    Z("timeline", "Déroulé de la résiliation", 3, "Notification → délai de opposition (72 h) → clôture ou litige. Horodatages Mono."),
    Z("cta", "Actions", 1, "« Payer le dû » or · « Consulter les preuves » fantôme · « Ouvrir un litige sur le décompte » texte clay."),
  ],
  comps=[("Tableau de prorata", "lignes de calcul explicites, aucune boîte noire"),
         ("Sceau clay", "résiliation, halo froid"),
         ("C-11 DocumentCardR2", "preuves du travail réalisé")],
  states=[("Résiliation amiable", "émeraude atténué : « sortie amiable, sans litige »."),
          ("Résiliation avec litige", "clay, paiement gelé, renvoi EMP-49."),
          ("Résiliation pour faute", "procédure contradictoire : motifs, réponses, décision."),
          ("Annulée", "si la résiliation est retirée dans la fenêtre de 72 h : retour à Actif.")],
  motion=[("Sceau clay", "contre-forge 640 ms"),
          ("Calcul de prorata", "lignes qui s'affichent une par une 120 ms")],
  rules=["Toute résiliation implique un décompte écrit, contestable pendant 72 h, révisable par la modération.",
         "Le prestataire est payé pour le travail validé, jamais en dessous (INV-1 : son prix reste sa rémunération).",
         "Les frais SaaS associés au travail réalisé restent dus : ils portent sur la valeur produite, pas sur le temps."],
  tokens=["--clay-500", "--gold-500", "--mono", "--slate-500"],
  api=["GET /v1/contracts/:id/termination", "POST /v1/contracts/:id/termination/oppose", "POST /v1/payments/:id/pay"],
  tech="Le décompte est produit par le service financier (moteur de prorata), versionné et rejouable : le même dossier "
       "redonne exactement les mêmes montants.",
  canon="Contrat — folio & états", variant_of="EMP-29", chrome={"appbar": "Résiliation", "glyph": "◈"}),

S("EMP-35", "Contrat remplacé", "EMP", "Propositions & Contrats", "/client/contrats/:id/remplace", "Client", "P2", "Succession tracée",
  intent="Expliquer une substitution : le contrat A est remplacé par le contrat B avec un autre prestataire. Le lien de "
         "filiation est affiché pour que le dossier reste lisible des mois plus tard.",
  zones=[
    Z("hero", "Chaîne de succession", 3, "Deux cartes reliées : contrat initial (clay atténué) → contrat successeur (or). Flèche de filiation avec date et motif."),
    Z("list", "Motif & conditions", 4, "Le motif du remplacement (défaillance, accord mutuel, force majeure) et les conditions de reprise (travail déjà réalisé, preuves transférées, prix ajusté)."),
    Z("price", "Bilan financier de la succession", 3, "Ce qui a été payé au premier prestataire, ce qui reste dû, le nouveau triplet FIN."),
    Z("cta", "Navigation", 2, "« Ouvrir le contrat successeur » or · « Voir le dossier initial » fantôme."),
  ],
  comps=[("Carte de filiation", "deux cartes + connecteur daté"),
         ("Reprise de preuves", "pièces transférées avec mention d'origine"),
         ("Badge de succession", "« successeur de C-2026-0031 » en Mono")],
  states=[("Succession en cours", "contrat B non encore signé : mention d'attente."),
          ("Succession achevée", "les deux contrats consultables, chaîne complète."),
          ("Succession contestée", "litige en cours sur le transfert → clay + renvoi modération.")],
  motion=[("Filiation", "connecteur qui se trace 420 ms entre les deux cartes"),
          ("Bascule", "flip léger entre initial et successeur 240 ms")],
  rules=["Le contrat initial n'est jamais supprimé ni masqué : la chaîne de succession est complète et immuable.",
         "Les preuves produites sous le contrat initial restent attachées au dossier mission, quel que soit le prestataire.",
         "Aucun prix rétroactif : la succession ne renégocie pas le travail déjà validé."],
  tokens=["--gold-500", "--clay-500", "--mono", "--surface-2"],
  api=["GET /v1/contracts/:id/succession", "GET /v1/contracts/:id/successor"],
  tech="Modèle de contrats chaînés (previous_contract_id / successor_contract_id) : la filiation est une donnée de premier "
       "niveau, pas une note libre.",
  canon="Contrat — folio & états", variant_of="EMP-29", chrome={"appbar": "Succession", "glyph": "◈"}),

S("EMP-36", "Historique des versions de contrat", "EMP", "Propositions & Contrats", "/client/contrats/:id/historique", "Client", "P2", "Chronologie documentaire",
  intent="Un index de toutes les versions d'un contrat, avec leurs empreintes, auteurs et états de signature. Utile pendant "
         "un litige, indispensable pour un audit.",
  zones=[
    Z("list", "Chronologie des versions", 5, "Chaque version : numéro (v1, R2…), date, auteur (qui a demandé), état (signée, rejetée, en vigueur), empreinte SHA-256 tronquée en Mono."),
    Z("table", "Table de diff cumulé", 3, "Ce qui a changé entre v1 et la version en vigueur : lignes de synthèse (prix, dates, périmètre)."),
    Z("cta", "Actions", 1, "« Ouvrir une version » · « Exporter l'historique » (PDF + JSON signé)."),
  ],
  comps=[("Ligne de version", "badge d'état + empreinte Mono + action"),
         ("Export", "PDF horodaté, hash affiché"),
         ("C-11 DocumentCardR2", "pièces liées à chaque version")],
  states=[("Une seule version", "état sobre, mention « aucune révision à ce jour »."),
          ("Versions multiples", "tri antéchronologique, diff cumulé activé."),
          ("Version rejetée", "badge clay, toujours consultable.")],
  motion=[("Dépliage", "accordéon hauteur animée 240 ms"),
          ("Export", "sceau or bref")],
  rules=["Aucune version n'est supprimable, y compris rejetée ou erronée — le document d'audit est append-only.",
         "L'empreinte affichée permet de vérifier l'intégrité du PDF téléchargé (l'outil de vérification est public)."],
  tokens=["--mono", "--slate-500", "--gold-500", "--clay-500"],
  api=["GET /v1/contracts/:id/versions?include=rejected", "GET /v1/contracts/:id/versions/export"],
  tech="Journal de versions côté serveur + pièces R2 immuables (object lock). L'export est signé et horodaté.",
  canon="Contrat — versions & révisions", variant_of="EMP-30", chrome={"appbar": "Historique", "glyph": "◈"}),

S("EMP-37", "Exécution — suivi client", "EMP", "Exécution & Paiements", "/client/missions/:id/execution", "Client", "P0", "Poste de contrôle",
  intent="Suivre le travail en cours : où en est chaque livrable, quelle preuve est attendue, ce qui requiert une validation "
         "du client. Le client ne doit jamais découvrir un retard par un litige.",
  zones=[
    Z("timeline", "Jalons & livrables", 5, "Frise détaillée : chaque jalon avec état (à venir, en cours, preuve déposée, validée, refusée), date prévue vs réelle, écart en jours."),
    Z("list", "Preuves en attente d'action", 4, "File des preuves déposées par le prestataire, en attente de validation client : aperçu, horodatage, action « valider » ou « demander une correction » (avec motif)."),
    Z("kpi", "Santé d'exécution", 3, "Avancement %, jours de marge, alertes (retard imputé au client vs au prestataire)."),
    Z("cta", "Actions", 2, "« Valider la preuve » or · « Demander une correction » fantôme · « Contacter via le fil mission » (message horodaté, jamais hors plateforme)."),
  ],
  comps=[("C-06 TimelineTrack", "variante exécution avec écarts de date"),
         ("Carte de preuve", "aperçu + horodatage + géo si applicable"),
         ("Indicateur de marge", "jauge or/ambre/clay selon jours restants"),
         ("Fil de mission", "messages asynchrones horodatés, pièces jointes limitées")],
  states=[("À l'heure", "or, marge positive."),
          ("Retard mineur (< 2 j)", "ambre, imputation affichée (client/prestataire)."),
          ("Retard significatif", "clay + proposition d'actions (avenant de date, résiliation amiable, litige)."),
          ("Preuve refusée", "le motif est obligatoire (≥ 20 caractères) et l'historique du refus reste visible.")],
  motion=[("Jalon validé", "le point passe émeraude avec une onde 420 ms"),
          ("Preuve refusée", "carte qui recule en E1 + apparition du champ motif 240 ms"),
          ("Retard", "indicateur qui glisse d'or vers clay en 640 ms")],
  rules=["Le client ne peut pas refuser une preuve sans motif écrit ; un refus abusif répété est visible dans l'audit.",
         "Toute demande de correction ouvre un droit de réponse du prestataire (24 h) avant qu'un retard ne soit imputé.",
         "Aucune communication hors plateforme n'est autorisée : le fil mission est la seule preuve admissible."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--gold-500", "--surface-1"],
  api=["GET /v1/missions/:id/execution", "POST /v1/evidence/:id/approve", "POST /v1/evidence/:id/reject {reason}", "GET /v1/missions/:id/thread"],
  tech="Flux d'exécution temps réel (SSE) avec reprise par curseur. Les preuves sont téléversées directement vers R2 "
       "via URL présignée (aucun octet ne transite par l'API applicative).",
  canon="Exécution — suivi & validation client", chrome=CHROME_APP),

S("EMP-38", "Exécution — validation de preuve", "EMP", "Exécution & Paiements", "/client/evidence/:id", "Client", "P0", "Verdict de preuve",
  intent="Valider ou refuser une preuve en pleine connaissance : voir la pièce, sa date, son origine, les exigences du "
         "contrat — et savoir exactement ce que le verdict déclenche (paiement, prochaine étape).",
  zones=[
    Z("doc", "Pièce présentée", 5, "Visionneuse : photo plein écran (zoom), PDF paginé, vidéo ≤ 90 s. Métadonnées affichées : horodatage serveur, géolocalisation (si exigée), auteur, hash R2 court."),
    Z("list", "Conformité aux exigences", 4, "Checklist automatique des critères contractuels : type de preuve conforme · horodatage dans la fenêtre · géo dans la zone · livrable correspondant. Chaque critère ✓ / ✗ / ⚠ avec explication."),
    Z("kpi", "Conséquence du verdict", 3, "« Valider » → jalon coché, échéance de paiement suivante déclenchée le JJ/MM. « Refuser » → le prestataire a 24 h pour corriger, le paiement reste gelé."),
    Z("cta", "Décision", 2, "« Valider la preuve » or · « Demander une correction » fantôme (motif obligatoire) — jamais de bouton « refuser définitivement » : la correction est le chemin normal."),
  ],
  comps=[("Visionneuse média", "zoom 4× fluide, pas de téléchargement forcé"),
         ("Checklist de conformité", "résultats objectifs, générés par le moteur de règles"),
         ("Bandeau de conséquence", "dit ce que la décision produit, chiffres à l'appui"),
         ("Historique des versions", "si la preuve a déjà été refusée/corrigée : v1, v2…")],
  states=[("Conforme", "checklist verte, CTA valider or."),
          ("Non conforme", "critères en échec listés ; CTA valider reste disponible mais un encart avertit de l'écart (le client garde le dernier mot, tracé)."),
          ("Pièce illisible", "bouton « demander une meilleure pièce » avec suggestion de cadrage."),
          ("Déjà validée", "lecture seule, mention de la date et de l'auteur de la validation.")],
  motion=[("Ouverture", "visionneuse en plein écran 420 ms, fond noir absolu"),
          ("Verdict", "trace émeraude sur la checklist 240 ms, sceau bref, haptique medium"),
          ("Correction", "compteur 24 h qui démarre visiblement (Mono)")],
  rules=["Aucune validation automatique sans action humaine, même si tous les critères automatiques sont verts (sauf contrat en mode « auto-validation » explicitement activé par les deux parties).",
         "Une preuve validée ne peut plus être refusée : seule une contestation formelle (litige) le permet.",
         "Le refus est un droit encadré : motif obligatoire, droit de réponse, et comptage des refus abusifs."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--mono", "--glass-4"],
  api=["GET /v1/evidence/:id", "POST /v1/evidence/:id/approve", "POST /v1/evidence/:id/reject", "GET /v1/evidence/:id/versions"],
  tech="Analyse automatique côté serveur (EXIF, géo, distance à la zone, durée vidéo) pour produire la checklist : le client "
       "juge, la machine constate. Les vidéos passent par le pipeline R2 + transcodage (flux HLS court).",
  canon="Exécution — suivi & validation client", variant_of="EMP-37", chrome={"appbar": "Preuve", "glyph": "◈"}),

S("EMP-39", "Litige — ouverture", "EMP", "Litiges & Remplacement", "/client/missions/:id/litige/nouveau", "Client", "P0", "Acte de conflit",
  intent="Ouvrir un litige est grave : l'écran doit décourager les abus par la clarté (conséquences immédiates, gel des "
         "paiements) tout en rendant le recours accessible et juste.",
  zones=[
    Z("form", "Motif & catégorie", 4, "Motifs structurés : travail non conforme · non-exécution · retard grave · comportement · désaccord financier · autre. Description factuelle guidée (faits, dates, preuves)."),
    Z("list", "Preuves à joindre", 4, "Pièces attendues selon le motif (ex. photos de non-conformité, échanges du fil mission, relevé de jalons). Suggestions automatiques parmi les pièces existantes."),
    Z("kpi", "Conséquences immédiates", 3, "« Les paiements non encore versés sont gelés. » · « Le prestataire dispose de 48 h pour répondre. » · « La modération examine sous 5 jours ouvrés. »"),
    Z("cta", "Ouverture", 2, "« Ouvrir le litige » clay (double confirmation) · « Tenter une résolution amiable d'abord » or (option mise en avant)."),
  ],
  comps=[("Radios de motif", "squircle clay à sélection"),
         ("Éditeur de faits", "champs structurés : quoi, quand, où, impact (pas de zone de texte libre fourre-tout)"),
         ("Sélecteur de preuves", "pièces existantes + ajout, avec compteur de pertinence"),
         ("Bandeau de conséquence", "gel des paiements, délais, droits des deux parties")],
  states=[("Ouverture", "avertissement clair + confirmation par saisie du mot « LITIGE » si montant > 500 000 F."),
          ("Résolution amiable proposée", "option or : médiation assistée avant escalade (48 h)."),
          ("Litige mineur", "procédure allégée : médiation automatique, décision à J+3."),
          ("Ouvert", "transition vers EMP-40.")],
  motion=[("Ouverture", "sheet glass-4, montée 560 ms spring heavy"),
          ("Confirmation", "sceau clay imprimé, haptique rigid"),
          ("Amiable", "au contraire : sceau émeraude atténué, ton apaisé")],
  rules=["Le gel des paiements commence à l'ouverture, jamais rétroactivement sur des paiements déjà versés (ceux-là passent par la contestation).",
         "Un litige ouvert interdit la clôture du contrat tant qu'il n'est pas résolu.",
         "Les litiges abusifs répétés (≥ 2 rejetés en 6 mois) entraînent une revue de réputation client (ADM-34)."],
  tokens=["--clay-500", "--clay-600", "--amber-500", "--glass-4", "--mono"],
  api=["POST /v1/missions/:id/disputes {category, facts, evidenceIds}", "GET /v1/disputes/templates?category="],
  tech="Création de litige transactionnelle : gel des échéances, notification des deux parties, création d'un dossier de "
       "modération. Toutes les pièces sont copiées par référence (pas dupliquées) avec empreinte.",
  canon="Litige client — ouverture", chrome={"appbar": "Litige", "glyph": "◈"}),

S("EMP-40", "Litige — suivi client", "EMP", "Litiges & Remplacement", "/client/missions/:id/litige", "Client", "P0", "Fil de médiation",
  intent="Suivre le litige sans angoisse : où en est le dossier, ce qui est attendu de vous, ce qui se passera et quand. "
         "Chaque étape est horodatée, chaque décision motivée.",
  zones=[
    Z("timeline", "Étapes du litige", 4, "Ouverture → réponse du prestataire (48 h) → médiation (J+3) → décision (J+5) → exécution de la décision. Étape active pulsée, retards affichés honnêtement."),
    Z("chat", "Fil contradictoire", 5, "Messages des deux parties + modérateur, pièces jointes horodatées. Le client peut ajouter des éléments tant que le dossier est ouvert."),
    Z("price", "Montants gelés", 3, "Rappel FIN : ce qui est gelé, ce qui a déjà été payé, ce qui reste. Aucune ligne masquée."),
    Z("cta", "Actions", 2, "« Ajouter un élément » fantôme · « Accepter une médiation » or si une proposition est ouverte · « Demander une révision » texte."),
  ],
  comps=[("C-13 DisputeThread", "fil structuré, rôles identifiés, horodatage Mono"),
         ("C-06 TimelineTrack", "variante procédure avec échéances légales"),
         ("Carte de proposition de résolution", "montant et conditions, accepter/refuser"),
         ("Bandeau modération", "« Dossier examiné par [alias] · agent LE LABEUR »")],
  states=[("Attente réponse", "compte à rebours 48 h, partie adverse notifiée."),
          ("Réponse reçue", "bandeau émeraude atténué, nouveaux éléments disponibles."),
          ("Médiation", "proposition de résolution affichée, délai d'acceptation 72 h."),
          ("Décision rendue", "texte de décision + voies de recours (révision unique) + exécution."),
          ("Clôturé", "archive consultable, paiements dégelés ou ajustés selon décision.")],
  motion=[("Nouvel élément", "insertion 240 ms spring soft, léger surlignage 3 s"),
          ("Décision", "carte de décision qui s'imprime 640 ms, ton neutre — aucune célébration")],
  rules=["La procédure est contradictoire : aucune décision sans que les deux parties aient pu répondre.",
         "Les délais sont affichés et opposables (SLA modération).",
         "Un seul recours (révision) par litige : la décision finale est exécutoire dans le système."],
  tokens=["--clay-500", "--amber-500", "--emerald-500", "--glass-2", "--mono"],
  api=["GET /v1/disputes/:id", "POST /v1/disputes/:id/messages", "POST /v1/disputes/:id/resolution/accept", "POST /v1/disputes/:id/revision"],
  tech="Dossier de litige immuable côté messages (append-only), états pilotés par une machine dédiée avec SLA surveillés "
       "(jobs de contrôle). Les pièces ajoutées hors délai sont acceptées mais signalées comme tardives.",
  canon="Litige client — suivi", chrome={"appbar": "Litige", "glyph": "◈"}),

S("EMP-41", "Paiements — échéances", "EMP", "Exécution & Paiements", "/client/paiements", "Client", "P0", "Calendrier de l'argent",
  intent="Voir tout ce qui doit être payé, quand, combien, et à qui. Un calendrier sans surprise, avec le triplet FIN "
         "toujours lisible et l'état exact de chaque échéance.",
  zones=[
    Z("kpi", "Encours & prochain", 3, "Total encore dû (--display-1 or) · prochaine échéance (date, montant) · échéances en retard (clay) s'il y en a."),
    Z("timeline", "Calendrier des échéances", 5, "Groupé par semaine : chaque ligne (montant, mission, prestataire, échéance, état : à venir / due / payée / contestée / gelée)."),
    Z("price", "Détail d'une échéance (panneau)", 4, "Au tap : triplet FIN complet, décomposition (40 % / 60 %), référence de contrat, preuve liée (OTP, validation de jalon)."),
    Z("cta", "Payer", 2, "« Payer maintenant » or sur l'échéance due · « Déclarer un paiement hors plateforme » fantôme (EMP-43) · « Voir l'historique » texte."),
  ],
  comps=[("Ligne d'échéance", "montant tnum, badge d'état, mission liée"),
         ("C-05 PriceBreakdown", "panneau coulissant avec le triplet exact"),
         ("Badge de gel", "clay + raison (litige) jamais muet"),
         ("Rappels", "puce ambre à J-3, jamais de spam quotidien")],
  states=[("À jour", "aucune échéance due, encours futur seulement."),
          ("Due aujourd'hui", "bord droit or, CTA payer immédiat."),
          ("En retard", "clay, compteur de jours, mention des intérêts éventuels (plafonnés, réciproques)."),
          ("Gelée", "ardoise/clay, motif affiché (litige en cours), dégel automatique à la décision."),
          ("Payée", "émeraude, preuve liée accessible.")],
  motion=[("Paiement", "sceau or→émeraude, compteur qui se stabilise, haptique heavy"),
          ("Retard", "bord qui glisse vers clay 640 ms lors du franchissement de date"),
          ("Panneau", "sheet 420 ms, backdrop verre 3")],
  rules=["INV-1 : même ici, le triplet complet est accessible en un tap, jamais masqué.",
         "Le retard client est imputé visiblement et peut affecter la réputation client : transparence symétrique.",
         "Aucun paiement ne peut être effectué sur une échéance gelée : le bouton est désactivé avec explication."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--display-1", "--mono"],
  api=["GET /v1/payments/schedules?role=client", "POST /v1/payments/:id/pay", "GET /v1/payments/:id/breakdown"],
  tech="Échéancier calculé par le service financier à partir du contrat (règles d'échéances versionnées). Les paiements "
       "passent par le PSP avec idempotence stricte (clé = échéance + tentative).",
  canon="Paiements client — échéances", chrome=CHROME_APP),

S("EMP-42", "Paiement — échéance en détail", "EMP", "Exécution & Paiements", "/client/paiements/:id", "Client", "P1", "Reçu avant l'acte",
  intent="Le détail d'une échéance : ce qu'on paie, pourquoi maintenant, à qui, avec quelle preuve de la contrepartie. "
         "C'est l'écran qui légitime le paiement.",
  zones=[
    Z("price", "Triplet FIN plein", 5, "Prix prestataire · Frais SaaS (taux + montant) · Total client — avec mention « déjà réglé 40 % » le cas échéant et solde restant."),
    Z("list", "Justification du déclenchement", 4, "Quel jalon contractuel déclenche cette échéance : preuve validée le JJ/MM à HH:MM, référence du jalon, extrait de clause."),
    Z("doc", "Preuves liées", 3, "Pièces justificatives : preuve d'exécution validée, OTP de réception (si solde final), facture générée (PDF, hash)."),
    Z("cta", "Payer", 2, "« Payer 110 000 F » or (montant dans le libellé : jamais « payer » nu) · « Télécharger la facture » fantôme."),
  ],
  comps=[("C-05 PriceBreakdown", "variante échéance avec solde progressif"),
         ("Carte de déclenchement", "lien vers le jalon et sa preuve"),
         ("Facture", "PDF conforme, numérotée, hashée")],
  states=[("À venir", "CTA désactivé avec date d'activation (« payable à partir du 12/10 »)."),
          ("Due", "CTA or armé, montant dans le libellé."),
          ("Payée", "reçu affiché, téléchargeable, mention de la méthode (carte, mobile money, virement déclaré)."),
          ("Contestée", "clay, renvoi vers le litige, paiement bloqué.")],
  motion=[("Entrée", "triplet qui s'affiche le premier, justification ensuite (ordre de lecture imposé)"),
          ("Paiement", "anneau de progression réel du PSP, jamais une fausse barre")],
  rules=["Le libellé du bouton contient toujours le montant exact : aucune action financière anonyme.",
         "La facture est générée au paiement, jamais avant (pas de facture pour un impayé).",
         "Un paiement partiel n'existe pas : les échéances sont atomiques (sauf échéancier à jalons multiples défini au contrat)."],
  tokens=["--gold-500", "--price", "--mono", "--emerald-500"],
  api=["GET /v1/payments/:id", "POST /v1/payments/:id/pay", "GET /v1/payments/:id/invoice.pdf"],
  tech="Le PSP est appelé côté serveur (payment intent) ; le client ne manipule jamais de clé. Le webhook de confirmation "
       "est la seule source de vérité du paiement (jamais le retour de navigation).",
  canon="Paiements client — échéances", variant_of="EMP-41", chrome={"appbar": "Échéance", "glyph": "◈"}),

S("EMP-43", "Déclaration de paiement externe (hors plateforme)", "EMP", "Exécution & Paiements", "/client/paiements/declaration", "Client", "P0", "Déclaration sous serment",
  intent="Quand un arrangement hors plateforme existe malgré tout, LE LABEUR ne l'ignore pas : il l'enregistre. Le client "
         "déclare un paiement effectué directement au prestataire — avec preuves — et le système l'intègre au dossier.",
  zones=[
    Z("form", "Objet de la déclaration", 4, "Mission & échéance concernées · montant versé (prix prestataire uniquement — le frais SaaS reste dû à LE LABEUR) · date du versement · moyen (mobile money, espèces, virement) · référence de transaction."),
    Z("list", "Preuves obligatoires", 4, "Justificatif de transfert (capture, reçu, relevé), attestation du prestataire (case à faire confirmer par lui), description factuelle."),
    Z("kpi", "Conséquences & transparence", 3, "« Le frais SaaS de 25 000 F reste dû. » · « Le prestataire devra confirmer la réception. » · « Une déclaration non confirmée sous 72 h est signalée à la modération. »"),
    Z("cta", "Déclarer", 2, "« Soumettre la déclaration » or · « Annuler » fantôme."),
  ],
  comps=[("Champ montant", "tnum, limite au montant de l'échéance (jamais au-delà)"),
         ("Téléverseur de preuves", "URL présignée R2, types acceptés affichés, taille max 10 Mo par pièce"),
         ("Bloc de confirmation prestataire", "état : en attente / confirmé / contesté, avec horodatage"),
         ("Avertissement", "callout clay : le hors-plateforme réduit les protections (pas de médiation automatique)")],
  states=[("Brouillon", "champs partiels, avertissement affiché."),
          ("Soumise", "statut « en attente de confirmation du prestataire » (72 h)."),
          ("Confirmée", "émeraude clair : l'échéance passe « payée (hors plateforme) », le frais SaaS reste dû, rappel de règlement."),
          ("Contestée", "clay : renvoi ADM-18 (réconciliation) et litige possible."),
          ("Non confirmée à 72 h", "ambre : relance + signalement automatique à la modération.")],
  motion=[("Soumission", "sceau or atténué (ce n'est pas un succès plein : c'est une déclaration)"),
          ("Confirmation prestataire", "bascule émeraude avec onde 420 ms"),
          ("Contestation", "bascule clay immédiate, haptique rigid")],
  rules=["Une déclaration de paiement externe ne supprime JAMAIS l'obligation de frais SaaS (les services rendus — preuves, médiation, contrats — ont été fournis).",
         "La confirmation du prestataire est requise ; à défaut, la modération tranche sur pièces.",
         "Toute fausse déclaration est un motif de blocage (PUB-09) : le texte le dit à l'utilisateur avant soumission."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono", "--glass-3"],
  api=["POST /v1/payments/external-declarations", "GET /v1/payments/external-declarations/:id", "POST /v1/payments/external-declarations/:id/confirm"],
  tech="Circuit à double confirmation (client déclare, prestataire confirme). Les pièces sont stockées en R2 avec horodatage "
       "et empreinte ; le rapprochement est réconcilié côté ADM-18 avec les relevés du PSP quand ils existent.",
  canon="Paiement externe — déclaration", chrome={"appbar": "Déclaration", "glyph": "◈"}),

S("EMP-44", "Vérification de la déclaration", "EMP", "Exécution & Paiements", "/client/paiements/declarations/:id/verification", "Client", "P1", "Contrôle croisé",
  intent="Montrer au client l'état réel du contrôle sur sa déclaration : qui doit confirmer, ce qui bloque, et ce qui se "
         "passe en cas de désaccord. Rien de nébuleux dans un flux d'argent.",
  zones=[
    Z("timeline", "Étapes de vérification", 4, "Déclaration soumise → Preuves analysées (horodatage, cohérence) → Confirmation du prestataire → Rapprochement → Clôture. Auteur et heure de chaque étape."),
    Z("table", "Contrôles automatiques", 4, "Table : contrôle · résultat · détail. Ex. cohérence du montant avec l'échéance ✓ · horodatage de la capture cohérent ⚠ · référence de transaction dupliquée ✕."),
    Z("kpi", "Sortie de secours", 3, "Si le prestataire ne confirme pas : options (relancer, demander une médiation, retirer la déclaration et payer par la plateforme)."),
    Z("cta", "Actions", 1, "« Relancer la confirmation » fantôme · « Basculer en paiement plateforme » or."),
  ],
  comps=[("C-06 TimelineTrack", "variante vérification"),
         ("Tableau de contrôles", "glyphes ✓ ⚠ ✕ + explication"),
         ("Bouton de bascule", "retour au paiement standard, protéger l'utilisateur")],
  states=[("En attente", "prestataire non confirmé, compte à rebours visible."),
          ("Confirmée", "émeraude, clôture, rappel du frais SaaS dû."),
          ("Contestée", "clay, renvoi réconciliation ADM-18 (le client voit le numéro de dossier)."),
          ("Rapprochée", "si un relevé PSP confirme : émeraude pleine, dossier clos.")],
  motion=[("Étapes", "progression qui se trace 420 ms à chaque validation"),
          ("Bascule", "transition propre vers le tunnel de paiement standard")],
  rules=["Aucune déclaration n'est acceptée sans preuve jointe ; le contrôle automatique liste ses échecs.",
         "Le client peut toujours revenir au paiement par la plateforme — c'est l'option mise en avant en cas de blocage.",
         "Tout doublon de référence de transaction est détecté et signalé (anti-fraude)."],
  tokens=["--mono", "--amber-500", "--emerald-500", "--clay-500"],
  api=["GET /v1/payments/external-declarations/:id/verification", "POST /v1/payments/external-declarations/:id/relaunch"],
  tech="Moteur de vérification : analyse EXIF/horodatage des captures, contrôle de cohérence avec l'échéance, détection de "
       "doublons de référence. Les résultats sont produits côté serveur et exposés en lecture seule.",
  canon="Paiement externe — vérification", variant_of="EMP-43", chrome={"appbar": "Vérification", "glyph": "◈"}),

S("EMP-45", "Historique des paiements (client)", "EMP", "Exécution & Paiements", "/client/paiements/historique", "Client", "P1", "Comptabilité lisible",
  intent="Retrouver n'importe quel paiement en dix secondes : par mission, par prestataire, par période, avec les factures "
         "et les preuves. C'est aussi le document qu'on donne à son comptable.",
  zones=[
    Z("chips", "Filtres de période", 2, "Ce mois · Trimestre · Année · Tout · Période personnalisée. Filtres secondaires : mission, prestataire, méthode, état."),
    Z("table", "Table de paiements", 6, "Colonnes : date, mission (réf Mono), prestataire, prix prestataire, frais SaaS, total client, méthode, état, preuve. Chiffres tnum alignés, tri possible."),
    Z("kpi", "Synthèse de période", 3, "Total client payé · dont frais SaaS · nombre d'échéances en retard (avec montant). Export CSV/PDF disponible."),
    Z("cta", "Export & litige", 2, "« Exporter (CSV / PDF) » or outline · « Contester un paiement » texte."),
  ],
  comps=[("Table dense", "densité --caption, entêtes collants, tri multi-colonnes"),
         ("Export comptable", "CSV normalisé + PDF signé, hash affiché"),
         ("C-12 LedgerRow", "détail d'une ligne en panneau"),
         ("Badge de méthode", "carte, mobile money, virement, hors plateforme (marqué clay atténué)")],
  states=[("Vide", "« Aucun paiement enregistré à ce jour. »"),
          ("Chargé", "pagination par curseur, 50 lignes."),
          ("Retard", "lignes dues en ambre, ligne d'alerte en tête."),
          ("Export en cours", "génération asynchrone, notification à la fin, lien signé valable 24 h.")],
  motion=[("Tri", "lignes qui se réordonnent par FLIP 240 ms"),
          ("Export", "progression réelle, jamais supérieure à 100 % avant le lien")],
  rules=["Les écritures sont append-only : un remboursement apparaît comme une ligne négative, jamais comme une suppression.",
         "Chaque ligne renvoie à sa preuve (facture, OTP, déclaration confirmée).",
         "L'export contient exactement les mêmes chiffres que l'écran : une divergence est un bug P0."],
  tokens=["--surface-1", "--mono", "--gold-500", "--clay-500", "--table"],
  api=["GET /v1/payments?role=client&cursor=&from=&to=", "GET /v1/payments/export.csv", "GET /v1/payments/summary"],
  tech="Lecture depuis un registre d'écritures (append-only) avec vues matérialisées pour les synthèses. Exports générés "
       "en tâche de fond, servis via R2 (URL signée 24 h).",
  canon="Paiements — historique & export", chrome=CHROME_APP),
]
