# -*- coding: utf-8 -*-
"""FAMILLE 02 · CLIENT — EMP-16 → EMP-30"""
from ..model import S, Z, CHROME_APP

SCREENS = [

S("EMP-16", "Candidatures reçues", "EMP", "Candidats & Matching", "/client/missions/:id/candidatures", "Client", "P0", "File de profils",
  intent="Examiner les candidatures sans perdre le fil : chaque ligne donne assez d'information pour décider en 8 secondes "
         "— score, compétences clés satisfaites, disponibilité, prix demandé s'il diffère.",
  zones=[
    Z("chips", "Tri & segments", 2, "Tri par : Score de matching · Candidature récente · Prix · Disponibilité. Segments : Toutes · Or (score ≥ 80) · À examiner · Écartées."),
    Z("list", "Lignes de candidats", 6, "C-09 : avatar halo, nom, score en anneau, chips de compétences (or = obligatoire satisfaite), phrase de motivation tronquée à 2 lignes, disponibilité, action rapide (voir, écarter, présélectionner)."),
    Z("kpi", "Synthese de file", 2, "14 candidatures · médiane de score 74 · 3 profils ≥ 80. La médiane est affichée, jamais la moyenne (moins trompeuse)."),
    Z("cta", "Comparer & filtrer", 1, "« Comparer la sélection » (jusqu'à 3) · « Filtres » (EMP-20) en fantôme."),
  ],
  comps=[("C-09 CandidateRow", "score, chips, action rapide, swipe pour écarter"),
         ("C-10 MatchScoreRing", "anneau 0-100, or ≥ 80, émeraude si 100/100 sur obligatoires"),
         ("Sélection multiple", "cases squircle, compteur flottant « Comparer (2) »"),
         ("Swipe", "droite = présélectionner, gauche = écarter avec motif facultatif")],
  states=[("File vide", "« Aucune candidature pour l'instant. » + options : élargir la zone, ajuster le prix, booster la visibilité (traçable, non payant caché)."),
          ("Écartées", "repliées en bas, récupérables (undo illimité tant que la mission est ouverte)."),
          ("Candidat incomplet", "bandeau ardoise « Profil en cours de vérification » : la candidature n'est jamais bloquée pour autant."),
          ("Présélection", "anneau or qui se ferme, compteur de sélection.")],
  motion=[("Entrée de liste", "stagger 60 ms plafonné à 8"),
          ("Swipe", "spring snap + fond contextuel (émeraude à droite, ardoise à gauche)"),
          ("Score", "anneau qui se remplit 420 ms à l'apparition (une seule fois par session)")],
  rules=["Un candidat écarté n'est jamais notifié automatiquement : la notification est une décision explicite du client.",
         "Le score de matching n'est jamais le seul critère : l'UI invite à ouvrir le détail du profil (EMP-17) avant sélection.",
         "Aucune donnée discriminatoire n'est affichée (âge, photo d'identité, nationalité) : uniquement ce qui est professionnellement pertinent."],
  tokens=["--surface-1", "--gold-500", "--emerald-500", "--text-mid", "--squircle-22"],
  api=["GET /v1/missions/:id/applications?sort=&segment=", "POST /v1/applications/:id/shortlist", "POST /v1/applications/:id/dismiss"],
  tech="Liste virtualisée avec score pré-calculé côté serveur (matching run). Les actions rapides sont optimistes et "
       "réversibles ; chaque geste est journalisé dans le dossier mission.",
  canon="Candidatures — file client", chrome=CHROME_APP),

S("EMP-17", "Profil candidat (vu par le client)", "EMP", "Candidats & Matching", "/client/candidats/:id", "Client", "P0", "Dossier humain",
  intent="Voir le travailleur derrière la candidature : compétences prouvées, réputation contractuelle, historique réel, "
         "et les limites honnêtes (ce qu'il n'a pas fait, ce qu'il ne peut pas faire).",
  zones=[
    Z("hero", "Identité professionnelle", 3, "Avatar halo, nom, métier principal, ancienneté sur LE LABEUR, statut de vérification (identité ✓, pièces ✓), note de fiabilité globale."),
    Z("kpi", "Preuves de fiabilité", 3, "Missions menées à terme · Taux de respect des délais · Litiges (avec issue). Chiffres tnum, méthodologie accessible en un tap."),
    Z("ring", "Score de matching pour CETTE mission", 3, "Anneau + décomposition : obligations satisfaites (n/n), compétences souhaitées (k/n), proximité géographique, disponibilité, adéquation de prix. Chaque composante pondérée et affichée."),
    Z("list", "Sections du dossier", 4, "Compétences & habilitations (pièces vérifiées, dates d'expiration) · Expériences similaires (missions passées anonymisées si le client le demande) · Preuves d'exécution (échantillons consentis) · Langues · Zone d'intervention."),
    Z("cta", "Décision", 1, "« Retenir ce candidat » or · « Poser une question » fantôme · « Écarter » texte (avec motif facultatif)."),
  ],
  comps=[("C-10 MatchScoreRing", "décomposition obligatoire, jamais un score opaque"),
         ("Carte preuve", "échantillons de travaux passés, consentis par le prestataire uniquement"),
         ("Badge de vérification", "pièces R2 vérifiées, avec date de vérification et type"),
         ("Carte réputation", "lien vers la méthodologie (public)")],
  states=[("Score élevé", "anneau or/émeraude, encart « pourquoi ce candidat matche » déplié."),
          ("Score faible", "l'UI explique l'écart (ex. « hors zone : 42 km ») sans dévaloriser la personne."),
          ("Pièces expirées", "bandeau ambre « habilitation expirée le 12/09 » — bloquant pour les catégories réglementées."),
          ("Demande de question", "fil de discussion asynchrone rattaché à la candidature, horodaté.")],
  motion=[("Entrée", "hero → preuves → score → sections, stagger 60 ms"),
          ("Décomposition du score", "barres qui se remplissent 420 ms une seule fois"),
          ("Retenir", "carte qui se soulève en E3 puis vole vers la file de sélection")],
  rules=["Aucune information de contact direct (téléphone, e-mail, adresse) n'est révélée avant engagement contractuel.",
         "Les échantillons de travaux ne sont visibles qu'avec le consentement explicite du prestataire (paramètre de profil).",
         "Les motifs d'écartement ne sont jamais transmis automatiquement au candidat (protection contre l'humiliation, et conformité)."],
  tokens=["--emerald-500", "--gold-500", "--surface-2", "--glass-2", "--mono"],
  api=["GET /v1/providers/:id/public-profile", "GET /v1/providers/:id/match-breakdown?mission=:mid", "POST /v1/applications/:id/questions"],
  tech="Le profil public est une projection (deny-by-default) : le serveur n'envoie que les champs autorisés. "
       "Aucune donnée brute de pièce d'identité n'est jamais transmise au client, seulement le statut de vérification.",
  canon="Profil candidat (vue client)", chrome=CHROME_APP),

S("EMP-18", "Résultats de matching", "EMP", "Candidats & Matching", "/client/missions/:id/matching", "Client", "P1", "Classement explicable",
  intent="Proposer le meilleur ordre possible sans jamais masquer la mécanique. La liste classe, explique, et laisse toujours "
         "le dernier mot au client.",
  zones=[
    Z("ring", "Bandeau de run", 2, "« Run de matching #42 · règles v7 · 18 candidats évalués · 06:12 » en Mono. Statut du dernier run (terminé, en cours, échoué avec relance)."),
    Z("list", "Classement des candidats", 6, "Lignes triées par score, avec pour chacune 3 raisons visibles (ex. « 5/5 obligations », « dans la zone », « disponible dès lundi »)."),
    Z("kpi", "Distribution du run", 3, "Mini-histogramme des scores (barres fines or) + compte par tranche. Aide le client à voir s'il y a un vivier réel."),
    Z("cta", "Actions", 1, "« Relancer le matching » fantôme (limité à 1×/heure) · « Voir l'explication complète » (EMP-19) or outline."),
  ],
  comps=[("C-10 MatchScoreRing", "compact 32 px en ligne"),
         ("Raison de classement", "chip avec facteur + poids, lien vers EMP-19"),
         ("Histogramme", "barres 8 px, or pour les tranches 80+"),
         ("Badge de fraîcheur", "« actualisé il y a 12 min » — le matching vieillit, et on le dit")],
  states=[("Run terminé", "classement affiché, badge de fraîcheur."),
          ("Run en cours", "squelette + progression réelle par étapes (pré-filtre, scoring, re-classement post-contraintes)."),
          ("Run échoué", "bandeau clay + cause lisible (« source de disponibilité indisponible ») + bouton relancer."),
          ("Vivier pauvre", "encart ambre factuel + suggestions concrètes (élargir la zone de 10 km, ajuster le prix, assouplir 1 exigence souhaitée).")],
  motion=[("Classement", "les lignes se réordonnent visuellement par spring soft (FLIP), une seule fois à l'arrivée du run"),
          ("Score", "compteurs tnum qui montent 240 ms"),
          ("Relance", "icône de run qui tourne 640 ms, haptique light")],
  rules=["Le classement est un conseil, jamais une décision : aucune sélection automatique, même avec un score parfait.",
         "Les règles de matching sont versionnées ; un changement de version est affiché avec son effet (« +12 profils éligibles »).",
         "Le nombre de candidats évalués est toujours affiché : un score sans base de comparaison est trompeur."],
  tokens=["--violet-500", "--gold-500", "--surface-1", "--mono", "--glass-1"],
  api=["GET /v1/missions/:id/matches", "POST /v1/missions/:id/matching/runs", "GET /v1/matching/runs/:runId"],
  tech="Les runs de matching sont des jobs idempotents exécutés côté serveur (queue + worker). L'UI ne calcule rien : "
       "elle affiche le run, sa version de règles et son horodatage. Rafraîchissement SSE pendant un run actif.",
  canon="Matching — classement & run", chrome=CHROME_APP),

S("EMP-19", "Explication du classement", "EMP", "Candidats & Matching", "/client/missions/:id/matching/explication", "Client", "P0", "Rayons X du score",
  intent="Transparence totale : pourquoi ce candidat est 1er et cet autre 7e. Chaque point de score est tracé jusqu'à sa règle. "
         "C'est un écran de confiance — il protège aussi LE LABEUR de toute accusation de traitement opaque.",
  zones=[
    Z("ring", "Décomposition par candidat", 4, "Anneau central + 6 axes pondérés : obligations (×3), souhaitées (×1), proximité (×1,5), disponibilité (×1,5), prix (×1), historique de fiabilité (×1,5). Poids et contributions affichés en absolu."),
    Z("table", "Matrice comparative", 5, "Tableau : candidats en colonnes (3 max), facteurs en lignes, valeurs et contributions. Cellules actives surlignées or ; les manques en clay pâle, jamais rouges agressifs."),
    Z("list", "Règles appliquées", 3, "Liste des règles du ruleset v7 avec, pour chacune, son effet mesuré ce run-ci (« écart de prix : a redistribué 3 positions »)."),
    Z("cta", "Sortie", 1, "« Retour au classement » · « Contester un critère » (feedback produit tracé, alimente la revue des règles)."),
  ],
  comps=[("C-10 MatchScoreRing", "variante étendue avec contributions signées"),
         ("Matrice", "C-02 compacte en cellules, chiffres Mono tabulaires"),
         ("Barres de contribution", "positives or, négatives ardoise — jamais de rouge"),
         ("Traçabilité", "run id + ruleset version en pied, copiables")],
  states=[("Comparaison 1 candidat", "vue par axes dépliée, explication en prose par facteur."),
          ("Comparaison 3 candidats", "matrice complète, colonnes épinglées."),
          ("Règles modifiées", "bandeau violet « ruleset v8 en test » avec effet simulé (shadow scoring)."),
          ("Données manquantes", "cellule explicite « non renseigné » — jamais devinée.")],
  motion=[("Ouverture", "anneau → axes → matrice, 3 temps de 240 ms"),
          ("Survol de cellule", "infobulle verre 3 avec la formule exacte du calcul"),
          ("Contestation", "encart qui se déplie 240 ms, envoi avec haptique medium")],
  rules=["Chaque score est reproductible : formule, poids, données d'entrée et version de règles sont consultables.",
         "Un candidat n'est jamais pénalisé par une donnée qu'il n'a pas fournie volontairement (les champs manquants sont neutres, pas négatifs).",
         "Aucune donnée discriminatoire n'entre dans le scoring ; un test d'audit vérifie les corrélations interdites (ADM-11)."],
  tokens=["--violet-500", "--gold-500", "--slate-500", "--mono", "--glass-2", "--table",],
  api=["GET /v1/matching/runs/:runId/explain?providers=:a,:b,:c", "GET /v1/matching/rulesets/v7", "POST /v1/matching/feedback"],
  tech="Le service d'explication rejoue le run de façon déterministe à partir des mêmes entrées (même seed, mêmes données "
       "versionnées) et renvoie les contributions par facteur. Aucun recalcul approximatif côté client.",
  canon="Matching — explication", chrome=CHROME_APP),

S("EMP-20", "Filtres & recherche avancée", "EMP", "Candidats & Matching", "/client/missions/:id/filtres", "Client", "P1", "Tiroir de précision",
  intent="Affiner un vivier sans se noyer : filtres composables, résultat compté en direct, réinitialisation évidente. "
         "Les filtres discriminatoires sont absents par construction, pas seulement interdits.",
  zones=[
    Z("form", "Filtres composables", 5, "Score minimum (curseur 0-100) · Distance maximale (curseur km, cartographié) · Disponibilité (date) · Compétences (inclusion/exclusion) · Prix demandé (fourchette) · Langue. Chaque filtre affiche le compte de résultats en direct."),
    Z("kpi", "Compteur de vivier", 3, "« 9 candidats correspondent » avec jauge or→clay selon la taille (vivier sain ≥ 5)."),
    Z("list", "Filtres enregistrés", 2, "Deux modèles fournis (« Urgent proche », « Meilleure fiabilité ») + modèles personnels."),
    Z("cta", "Validation", 2, "« Appliquer » or (retour à EMP-16 filtré) · « Réinitialiser tout » fantôme."),
  ],
  comps=[("Curseur double", "fourchette de prix, tnum aux extrémités"),
         ("Cartographie de distance", "cercle ajustable sur mini-carte (proxy serveur)"),
         ("Chips de compétences", "inclusion (or) / exclusion (ardoise barré)"),
         ("Compteur live", "debounce 120 ms, jamais de valeur provisoire affichée")],
  states=[("Vivier vide", "bandeau ambre + cause dominante (« distance < 5 km élimine 14 candidats ») et suggestion de relâchement."),
          ("Filtre impossible", "combinaison contradictoire (ex. exclusion ET inclusion de la même compétence) bloquée avec explication."),
          ("Modèles", "charger/appliquer/supprimer, limités à 10."),
          ("Conflit avec tri", "le tri appliqué après filtres est rappelé en clair.")],
  motion=[("Curseurs", "déplacement fluide, haptique light aux crans"),
          ("Compteur", "chiffres tnum qui glissent verticalement 120 ms en changement"),
          ("Application", "tiroir qui se replie, liste qui se recompose par FLIP spring soft")],
  rules=["Aucun filtre ne peut reposer sur une caractéristique protégée ou un proxy discriminant (nom, origine déduite, âge).",
         "Les filtres appliqués sont affichés sous forme de chips persistantes au-dessus de la liste (aucun filtre fantôme).",
         "Les modèles enregistrés ne contiennent jamais de données personnelles, seulement des critères."],
  tokens=["--surface-3", "--gold-500", "--clay-500", "--amber-500", "--squircle-14"],
  api=["POST /v1/missions/:id/applications/search", "GET /v1/filters/presets", "POST /v1/filters/presets"],
  tech="Recherche côté serveur avec facettes ; les compteurs par facette sont précalculés dans le même run pour garantir "
       "la cohérence (un compteur qui contredit le résultat est un bug P1).",
  canon="Candidatures — filtres avancés", chrome={"appbar": "Filtres", "glyph": "◈"}),

S("EMP-21", "Sélection d'un candidat", "EMP", "Candidats & Matching", "/client/missions/:id/selection", "Client", "P0", "Engagement imminent",
  intent="Choisir officiellement. L'écran récapitule l'intégralité de ce qui est sur le point d'être engagé — prix, livrables, "
         "dates, preuves, obligations réciproques — avant la proposition formelle.",
  zones=[
    Z("hero", "Candidat retenu", 3, "Carte candidat élargie : photo/avatar halo, score, compétences obligatoires satisfaites, pièces vérifiées et leurs dates d'expiration."),
    Z("list", "Ce que vous engagez", 4, "Blocs contractuels : périmètre & livrables · dates & durée · prix prestataire · échéancier proposé · conditions d'accès · pénalités réciproques. Chaque bloc avec « modifier » vers l'étape correspondante."),
    Z("price", "Rappel FIN complet", 3, "Prix Prestataire + Frais SaaS = Total Client, version compacte, jamais omise."),
    Z("cta", "Engager", 2, "« Envoyer la proposition » or (mène à EMP-23) · « Prévenir les candidats non retenus » (case à cocher, désactivée par défaut — l'envoi est un choix)."),
  ],
  comps=[("Récapitulatif contractuel", "sections repliables, chacune avec son état de complétude"),
         ("C-05 PriceBreakdown", "compact mais intégral"),
         ("Alerte d'expiration", "pièces qui expirent pendant la mission → avertissement ambre"),
         ("Case de courtoisie", "notification aux non-retenus, jamais imposée")],
  states=[("Prêt", "Tous blocs conformes, CTA or."),
          ("Pièce expirée", "bloc ambre bloquant pour catégories réglementées, remplacement proposé."),
          ("Prix négocié", "si le candidat a demandé un autre prix : affichage des deux, écart en clair, décision explicite requise."),
          ("Conflit de disponibilité", "le candidat s'est engagé ailleurs entre-temps (409) → alternatives proposées.")],
  motion=[("Entrée", "candidat → blocs → prix → CTA, stagger 60 ms"),
          ("Pièce expirée", "pulsation ambre discrète jusqu'à résolution"),
          ("Envoi", "sceau or bref + transition vers EMP-23 avec partage élément (carte candidat qui vole vers la proposition)")],
  rules=["La sélection n'est pas un contrat : le rappel est explicite (« la proposition devra être acceptée pour engager »).",
         "Aucun prélèvement n'a lieu à la sélection : le premier montant est appelé à la signature du contrat (EMP-31).",
         "Si le prix demandé diffère, la différence s'affiche en clair — aucune négociation cachée dans les coulisses du système."],
  tokens=["--gold-500", "--amber-500", "--emerald-500", "--display-2", "--glass-2"],
  api=["POST /v1/missions/:id/select {applicationId}", "GET /v1/missions/:id/engagement-summary", "POST /v1/applications/:id/decline"],
  tech="La sélection ouvre une transaction serveur : verrou sur la mission (évite la double sélection concurrente), "
       "création de la proposition, notification au candidat. Idempotence garantie par clé mission+version.",
  canon="Sélection & proposition (émission)", chrome=CHROME_APP),

S("EMP-22", "Confirmation de sélection", "EMP", "Candidats & Matching", "/client/missions/:id/selection/confirmee", "Client", "P1", "Verrou posé",
  intent="Confirmer que la sélection est enregistrée et que la balle est dans le camp du prestataire. Dire précisément "
         "ce qui se passe ensuite, et ce qui se passe si rien ne se passe.",
  zones=[
    Z("verdict", "Sceau de sélection", 3, "Sceau or « Proposition envoyée » + nom du candidat + référence de proposition P-2026-0088 (Mono)."),
    Z("timeline", "Ce qui suit", 4, "Trois temps : proposition envoyée (maintenant) → réponse du candidat (attendu sous 48 h) → contrat à signer. Avec les délais et leurs conséquences."),
    Z("kpi", "Réserves & options", 3, "Si le candidat ne répond pas : « relance automatique à 24 h », « sélection d'un autre profil possible sans perdre la proposition »."),
    Z("cta", "Actions", 2, "« Suivre la proposition » or · « Informer les autres candidats » fantôme · « Retour aux missions » texte."),
  ],
  comps=[("C-04 StatusSeal", "or, une pulsation"),
         ("C-06 TimelineTrack", "délais explicites, compte à rebours Mono"),
         ("Bandeau de tranquillité", "« Vous pouvez retirer la proposition tant qu'elle n'est pas acceptée »")],
  states=[("Envoyée", "attente avec compte à rebours."),
          ("Vue par le candidat", "émeraude discrète : « Proposition consultée il y a 12 min »."),
          ("Refusée", "transition vers EMP-21 avec le prochain meilleur profil suggéré (sans automatisme)."),
          ("Expirée", "48 h dépassées : proposition expirée, relance possible.")],
  motion=[("Sceau", "fermeture or 480 ms"),
          ("Compte à rebours", "chiffres Mono qui glissent"),
          ("Retrait", "fly-to inverse de la carte (retour vers la file)")],
  rules=["La proposition est un acte tracé : chaque changement d'état est horodaté et visible des deux parties.",
         "L'expiration n'est jamais silencieuse : notification à l'échéance moins 6 h.",
         "Le client conserve toujours la possibilité de retirer une proposition non acceptée."],
  tokens=["--gold-500", "--grad-gold", "--emerald-500", "--mono", "--glass-1"],
  api=["GET /v1/propositions/:id", "POST /v1/propositions/:id/withdraw", "GET /v1/propositions/:id/status"],
  tech="Machine à états de proposition (draft → sent → viewed → accepted/declined/expired/withdrawn) avec transitions "
       "journalisées. Les notifications de délai sont programmées côté queue (jobs cron).",
  canon="Sélection — confirmation & suivi", chrome={"appbar": "Proposition envoyée", "glyph": "◈"}),

S("EMP-23", "Propositions reçues & envoyées", "EMP", "Propositions & Contrats", "/client/propositions", "Client", "P1", "Registre des propositions",
  intent="Suivre toutes les propositions en cours : qui a proposé quoi à qui, où en est chaque négociation, et ce qui "
         "exige une action du client.",
  zones=[
    Z("chips", "Segments", 2, "Envoyées · Reçues (candidats demandant des ajustements) · Acceptées · Refusées · Expirées."),
    Z("list", "Lignes de proposition", 6, "Carte : candidat, mission liée, prix proposé vs demandé, état (envoyée, vue, contre-proposée), échéance 48 h en Mono, action rapide."),
    Z("kpi", "Compteurs", 2, "3 en attente · 1 contre-proposition à examiner · délai médian de réponse 6 h."),
  ],
  comps=[("Carte proposition", "reprise du modèle de carte contrat, variante proposition"),
         ("Badge de contre-proposition", "or, avec l'écart de prix"),
         ("Compte à rebours", "Mono, ambre < 6 h")],
  states=[("Vide", "état vide + rappel : les propositions naissent d'une sélection (EMP-21)."),
          ("Contre-proposition", "mise en avant, CTA examiner."),
          ("Expirée", "grisée, relance possible (1×)."),
          ("Acceptée", "transition directe vers le contrat (EMP-29), sceau émeraude.")],
  motion=[("Filtres", "morphing du surlignage 240 ms"),
          ("Nouvelle contre-proposition", "pop du badge + bandeau sticky 3 s")],
  rules=["Une proposition expirée ne peut être « ressuscitée » : il faut en émettre une nouvelle (traçabilité contractuelle).",
         "Les contre-propositions affichent toujours l'écart en montant ET en pourcentage, jamais en flou.",
         "Aucune proposition ne peut exister sans mission liée : l'orphelin est un bug P0."],
  tokens=["--surface-1", "--gold-500", "--mono", "--amber-500"],
  api=["GET /v1/propositions?segment=", "POST /v1/propositions/:id/relaunch"],
  tech="Vue unifiée client/prestataire du même agrégat ; seule la projection des champs change selon le rôle.",
  canon="Propositions — registre", chrome=CHROME_APP),

S("EMP-24", "Détail & négociation d'une proposition", "EMP", "Propositions & Contrats", "/client/propositions/:id", "Client", "P0", "Table de négociation",
  intent="Négocier proprement : ce qui est demandé, ce que cela change au total, et une réponse en un geste (accepter, "
         "contre-proposer, refuser avec motif). Aucune négociation hors plateforme.",
  zones=[
    Z("hero", "Objet de la négociation", 3, "Candidat, mission, état, échéance. Si contre-proposition : bloc « ce qui est demandé » en or (ex. « +15 000 F, motif : déplacement supplémentaire »)."),
    Z("price", "Impact sur le triplet FIN", 4, "Re-calcul : Prix Prestataire 265 000 F + Frais SaaS 26 500 F = Total Client 291 500 F. L'ancien total est barré proprement, le nouveau en or."),
    Z("chat", "Fil de négociation", 4, "Messages courts horodatés (Mono), pièces jointes limitées aux éléments objectifs (photos de site, relevé de distance). Aucun partage de contact."),
    Z("cta", "Répondre", 2, "« Accepter » or · « Contre-proposer » fantôme (ouvre un formulaire structuré) · « Refuser » texte (motif facultatif mais recommandé)."),
  ],
  comps=[("Diff de prix", "ancien barré + nouveau, tnum"),
         ("Formulaire structuré", "contre-proposition avec motif catégorisé + montant"),
         ("Fil horodaté", "bulles sobres, pas de réactions, pas d'émojis"),
         ("Avertissement hors-plateforme", "rappelle que tout accord hors plateforme n'est pas couvert par LE LABEUR")],
  states=[("Lecture", "proposition initiale, CTA accepter."),
          ("Négociation en cours", "fil actif, compteur de tours (limite 6 pour éviter les boucles infinies)."),
          ("Limite de tours", "bandeau ambre : « 6 tours atteints — tranchez ou retirez la proposition. »"),
          ("Acceptée", "sceau émeraude, transition vers le contrat EMP-29.")],
  motion=[("Diff", "ancien total qui se barre 240 ms, nouveau qui s'inscrit 240 ms"),
          ("Nouveau message", "glissement depuis le bas 240 ms spring soft"),
          ("Acceptation", "double sceau (client + candidat) qui se rejoignent et s'emboîtent, 640 ms")],
  rules=["Tout échange de la négociation reste horodaté et attaché au dossier : il pourra être produit en cas de litige.",
         "Le client ne paie jamais plus que le total client affiché lors de l'acceptation : le montant accepté est gelé contractuellement.",
         "Interdiction des coordonnées directes : détection et blocage du texte (téléphone/e-mail) avec message pédagogique."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono", "--glass-2"],
  api=["GET /v1/propositions/:id/thread", "POST /v1/propositions/:id/messages", "POST /v1/propositions/:id/counter", "POST /v1/propositions/:id/accept"],
  tech="Fil de discussion chiffré au repos, rétention liée à la mission (5 ans). La détection de coordonnées est un filtre "
       "serveur (jamais client) pour éviter le contournement.",
  canon="Proposition — négociation & acceptation", chrome={"appbar": "Proposition", "glyph": "◈"}),

S("EMP-25", "Contre-proposition envoyée", "EMP", "Propositions & Contrats", "/client/propositions/:id/contre", "Client", "P2", "Attente symétrique",
  intent="Après une contre-proposition, dire clairement ce qui attend le candidat et ce que le client peut encore faire. "
         "Pas de vide anxiogène.",
  zones=[
    Z("verdict", "Sceau d'état", 3, "Sceau or « Contre-proposition envoyée » avec le nouveau triplet FIN en version compacte."),
    Z("timeline", "Attente & suite", 4, "Attente de réponse (48 h, relance auto à 24 h) → accord ou refus → contrat. Compte à rebours Mono."),
    Z("kpi", "Options du client", 3, "Modifier la contre-proposition tant qu'elle n'est pas lue (la modification redémarre le délai)."),
    Z("cta", "Actions", 1, "« Retirer la contre-proposition » fantôme · « Retour aux propositions » texte."),
  ],
  comps=[("Sceau d'état", "or, pas de pulsation"),
         ("Compte à rebours", "Mono"),
         ("Bandeau de règle", "« Une contre-proposition lue par le candidat est figée. »")],
  states=[("Non lue", "modifiable, badge « modifiable » visible."),
          ("Lue", "figée, mention claire et définitive."),
          ("Expirée", "retour au dernier état accepté ou caduc."),
          ("Refusée", "retour à EMP-24 avec la possibilité d'accepter la demande initiale.")],
  motion=[("Sceau", "480 ms or"),
          ("Changement d'état", "bascule sobre 240 ms, sans fanfare")],
  rules=["Une proposition lue et non répondue expire : le client ne peut pas bloquer indéfiniment un prestataire.",
         "Le gel après lecture est une protection des deux parties : il empêche les modifications surprises."],
  tokens=["--gold-500", "--mono", "--surface-1"],
  api=["GET /v1/propositions/:id", "POST /v1/propositions/:id/withdraw"],
  tech="Écran de statut léger, rendu immédiat depuis le cache local + revalidation serveur en arrière-plan.",
  canon="Proposition — état & attente", variant_of="EMP-24", chrome={"appbar": "Contre-proposition", "glyph": "◈"}),

S("EMP-26", "Propositions expirées", "EMP", "Propositions & Contrats", "/client/propositions/expirees", "Client", "P2", "Cimetière propre",
  intent="Ne rien laisser pourrir : les propositions sans réponse sont visibles, récapitulées, et peuvent être relancées une "
         "seule fois. La traçabilité est conservée pour l'audit.",
  zones=[
    Z("list", "Liste des expirées", 5, "Carte : candidat, mission, montant proposé, date d'expiration (Mono), raison (délai dépassé / retirée / refusée)."),
    Z("kpi", "Analyse", 3, "Statistique utile : « 60 % des expirations surviennent sans lecture » — indique un problème de notification, pas de désintérêt."),
    Z("cta", "Actions groupées", 2, "« Relancer la sélection » (1×) · « Archiver tout » fantôme."),
  ],
  comps=[("Carte expirée", "désaturée, sans halo"),
         ("Bouton relance unique", "désactivé après usage, avec raison")],
  states=[("Aucune", "état vide sobre."),
          ("Relançable", "CTA or outline."),
          ("Définitif", "CTA disparu, mention « relance déjà effectuée le 02/10 ».")],
  motion=[("Archivage", "lignes qui s'effacent en cascade 60 ms"),
          ("Relance", "sceau or bref")],
  rules=["Une relance unique par proposition : la pression répétée sur un travailleur est proscrite par charte.",
         "L'historique d'expiration est conservé 24 mois minimum pour l'audit."],
  tokens=["--slate-500", "--gold-500", "--text-lo"],
  api=["GET /v1/propositions?state=expired", "POST /v1/propositions/:id/relaunch"],
  tech="Vue dérivée (read model) des propositions expirées, alimentée par les jobs d'expiration.",
  canon="Propositions — expirations", chrome={"appbar": "Expirées", "glyph": "◈"}),

S("EMP-27", "Propositions acceptées & plan de suite", "EMP", "Propositions & Contrats", "/client/propositions/acceptees", "Client", "P1", "Passage au contrat",
  intent="Basculer de la négociation à l'engagement : pour les propositions acceptées, une seule action compte — générer "
         "et signer le contrat. Tout est prêt, il ne manque que la signature.",
  zones=[
    Z("verdict", "Sceau d'acceptation", 3, "Sceau émeraude « Proposition acceptée » par [candidat] — horodatage Mono."),
    Z("list", "File de contractualisation", 5, "Cartes : mission, candidat, triplet FIN gelé, échéancier prévu, bouton « Générer le contrat »."),
    Z("kpi", "Rappel de règle", 3, "« Aucun travail ne commence avant signature des deux parties. » — affiché ici pour éviter les malentendus de terrain."),
    Z("cta", "Action", 1, "« Générer le contrat » or (mène à EMP-29)."),
  ],
  comps=[("Carte de contractualisation", "état gelé, modifications impossibles"),
         ("Triplet FIN", "verrouillé avec cadenas ardoise = engageant"),
         ("Bandeau de règle", "callout gold, texte contractuel")],
  states=[("Prête", "CTA or."),
          ("Génération en cours", "spinner sobre + étapes réelles (assemblage des clauses, empreinte R2)."),
          ("Erreur de génération", "clay, cause lisible, reprise possible sans perte."),
          ("Déjà générée", "CTA « Ouvrir le contrat » + version R2.")],
  motion=[("Acceptation", "double sceau emboîté 640 ms"),
          ("Génération", "pages qui s'empilent 240 ms × n, jamais plus de 6 animations")],
  rules=["Le contrat reprend exactement la proposition acceptée : aucune clause ajoutée après acceptation.",
         "Le prix accepté ne peut plus changer : toute évolution passe par un avenant post-signature (R2)."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--glass-1"],
  api=["GET /v1/propositions?state=accepted", "POST /v1/contracts {propositionId}"],
  tech="La génération du contrat est un job serveur : assemblage de clauses versionnées + empreinte SHA-256 des pièces, "
       "stockage R2, notification des deux parties. L'UI ne fabrique jamais le PDF.",
  canon="Propositions — acceptation", chrome={"appbar": "Acceptées", "glyph": "◈"}),

S("EMP-28", "Retirer ou annuler une proposition", "EMP", "Propositions & Contrats", "/client/propositions/:id/retrait", "Client", "P2", "Sortie propre",
  intent="Permettre le retrait sans violence : la proposition redevient caduque, le candidat est informé avec courtoisie, "
         "et le motif est facultatif mais tracé côté plateforme.",
  zones=[
    Z("form", "Motif de retrait", 4, "Motifs normalisés : mission annulée · autre profil retenu · budget modifié · conditions non remplies · autre. Champ libre limité à 240 caractères."),
    Z("kpi", "Conséquences", 3, "« Le candidat sera notifié sans motif détaillé. » · « Votre taux de retrait est suivi (impact réputation client) » — transparence sur l'effet."),
    Z("cta", "Confirmation", 2, "« Retirer la proposition » clay outline · « Garder la proposition » or (l'action de conservation est mise en avant, pas la destructive)."),
  ],
  comps=[("Radios de motifs", "squircle, sélection or"),
         ("Texte libre", "compteur 240"),
         ("Hiérarchie de sécurité", "action destructive JAMAIS en or plein")],
  states=[("Ouverture", "focus sur l'action de conservation (anti-clic réflexe)."),
          ("Traitée", "sceau ardoise « Retirée » + undo 10 s."),
          ("Déjà acceptée", "retrait impossible : renvoi vers la résiliation contractuelle (EMP-34).")],
  motion=[("Ouverture", "sheet glass-3 montée 420 ms"),
          ("Retrait", "carte qui s'estompe et rejoint l'historique"),
          ("Undo", "barre 10 s, restauration par fly-to inverse")],
  rules=["Un retrait répété (≥ 3 sur 30 jours) déclenche une revue interne de réputation client (ADM-34).",
         "Le candidat n'accède jamais au motif détaillé : il reçoit une notification neutre et professionnelle.",
         "Une proposition acceptée ne peut pas être retirée — seule la résiliation contractuelle est possible."],
  tokens=["--clay-500", "--slate-500", "--surface-3", "--glass-3"],
  api=["POST /v1/propositions/:id/withdraw {reason}", "GET /v1/client/reputation/client-stats"],
  tech="Le retrait passe par la machine à états de proposition ; l'undo s'appuie sur un délai serveur de 10 s avant émission "
       "de la notification (fenêtre de rattrapage).",
  canon="Proposition — retrait", chrome={"appbar": "Retrait", "glyph": "◈"}),

S("EMP-29", "Contrat — fiche complète", "EMP", "Propositions & Contrats", "/client/contrats/:id", "Client", "P0", "Folio du contrat",
  intent="Le contrat est le document le plus important du produit. La fiche le présente intégralement : parties, clauses, "
         "pièces, signatures, versions. Il doit être lisible par un humain et vérifiable par un juge.",
  zones=[
    Z("hero", "En-tête de contrat", 3, "Référence C-2026-0031 (Mono), statut (Brouillon, En signature, Actif, Terminé, Résilié), parties, dates, sceau d'état."),
    Z("doc", "Corps du contrat", 6, "Clauses numérotées, sommaire, encarts « En clair » (résumé humain de chaque clause critique), pièces annexées (livrables, preuves, pièces d'habilitation)."),
    Z("sign", "Zone de signatures", 3, "Deux emplacements : client (état, horodatage, empreinte) et prestataire (état, horodatage, empreinte). Aucune signature ne vaut seule."),
    Z("price", "Conditions financières", 3, "Triplet FIN + échéancier détaillé + pénalités réciproques. Chiffres tnum."),
    Z("cta", "Actions selon l'état", 2, "En signature → « Signer » or · Actif → « Voir l'exécution » (EMP-37) · Terminé → « Télécharger le dossier » · Résilié → « Lire les motifs »."),
  ],
  comps=[("C-08 ContractFolio", "sommaires ancrés, pagination, révision R2"),
         ("C-11 DocumentCardR2", "pièces annexées avec hash"),
         ("Bloc signature", "double empreinte, horodatage, refus si pièce manquante"),
         ("Historique de versions", "v1 → R2 avec diff consultable")],
  states=[("Brouillon", "non engageant, bandeau ardoise « Projet — aucune valeur contractuelle »."),
          ("En signature", "un seul signataire : sceau demi-or, mention « en attente de la seconde signature »."),
          ("Actif", "sceau or complet, exécution ouverte, échéancier actif."),
          ("Terminé", "sceau émeraude « Exécution complète », récapitulatif de clôture."),
          ("Résilié", "sceau clay, motifs et conditions de sortie affichés, litige éventuel lié."),
          ("Remplacé", "sceau ardoise + lien vers le contrat successeur et la motivation du remplacement.")],
  motion=[("Ouverture", "folio qui se déplie 420 ms spring soft"),
          ("Signature complète", "les deux sceaux se rejoignent, émeraude, haptique heavy, une seule fois"),
          ("Changement d'état", "bascule sobre 240 ms, jamais de confetti")],
  rules=["INV-3 : aucun contrat actif sans double signature horodatée et empreinte des pièces.",
         "Le contrat est immuable après signature : toute évolution produit une version R2 signée, les deux versions restant accessibles.",
         "Les clauses critiques (périmètre, prix, échéancier, pénalités, résiliation) ne peuvent jamais être masquées par défaut."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono", "--glass-1"],
  api=["GET /v1/contracts/:id", "GET /v1/contracts/:id/versions", "GET /v1/contracts/:id/report.pdf", "POST /v1/contracts/:id/sign"],
  tech="Contrat généré côté serveur en PDF/A (archivage) + rendu HTML signable. Empreintes SHA-256 stockées avec chaque version, "
       "pièces en R2 avec URLs signées courtes. Signature : sceau cryptographique par partie (non répudiation).",
  canon="Contrat — folio & états", chrome={"appbar": "Contrat", "glyph": "◈"}),

S("EMP-30", "Contrat — version R2", "EMP", "Propositions & Contrats", "/client/contrats/:id/versions/:v", "Client", "P1", "Révision tracée",
  intent="Comparer deux versions d'un contrat sans avocat : qu'est-ce qui a changé, qui l'a demandé, quand, et quelles "
         "conséquences. Le diff est visuel, pas textuel brut.",
  zones=[
    Z("hero", "Sélecteur de versions", 2, "v1 ↔ R2 : deux pastilles, la version affichée en or. Horodatage et auteur de chaque version."),
    Z("doc", "Diff clause par clause", 6, "Deux colonnes : avant / après. Ajouts en émeraude soulignée, suppressions barrées clay, modifications en or. Chaque clause avec le motif de la révision (ex. « déplacement supplémentaire »)."),
    Z("list", "Impact", 3, "Conséquences : prix (avant → après), dates, périmètre. Renvoi vers la négociation d'origine (EMP-24)."),
    Z("cta", "Validation", 2, "« Accepter la révision R2 » or (re-signature) · « Refuser et revenir à v1 » fantôme (relance de négociation)."),
  ],
  comps=[("Vue de diff", "algorithme clause-level, jamais caractère-level (illisible)"),
         ("Badge de motif", "chaque révision a un motif catégorisé"),
         ("Horodatage Mono", "date, heure, fuseau")],
  states=[("Lecture", "diff affiché, navigation par clause modifiée (n/total)."),
          ("Révision acceptée", "sceau or, l'ancienne version passe en historique."),
          ("Révision refusée", "retour à la négociation, la version R2 est marquée rejetée et conservée."),
          ("Révision unilatérale interdite", "toute R2 doit être produite par accord mutuel (tracé).")],
  motion=[("Navigation de clause", "scroll ancré 420 ms ease-labeur-out"),
          ("Accepter", "sceau or qui valide les deux colonnes, haptique heavy")],
  rules=["Aucune révision unilatérale : une R2 naît d'une négociation tracée ou d'une décision de justice interne (litige).",
         "Le diff est toujours disponible pour les deux parties, y compris après clôture du contrat.",
         "Les versions rejetées ne sont jamais supprimées : elles constituent la preuve de la bonne foi des parties."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono", "--text-mid"],
  api=["GET /v1/contracts/:id/versions/:v/diff?from=:v0", "POST /v1/contracts/:id/versions/:v/accept", "POST /v1/contracts/:id/versions/:v/reject"],
  tech="Le diff est calculé côté serveur sur une structure de clauses normalisée (id de clause stable), pas sur du texte brut. "
       "Cela garantit un diff sémantique correct même en cas de reformatage.",
  canon="Contrat — versions & révisions", chrome={"appbar": "Versions", "glyph": "◈"}),
]
