# -*- coding: utf-8 -*-
"""FAMILLE 03 · PRESTATAIRE — PRE-46 → PRE-52"""
from ..model import S, Z
from .pre_a import CHROME_PRE

SCREENS = [

S("PRE-46", "Ledger de réputation", "PRE", "Remplacement & Réputation", "/prestataire/reputation/ledger", "Prestataire", "P0", "Livre de comptes de l'honneur",
  intent="Chaque écriture de réputation est traçable, datée, motivée, et jamais effaçable. Le travailleur peut auditer sa "
         "propre réputation ligne à ligne — un droit rare, ici un principe.",
  zones=[
    Z("table", "Écritures", 6, "Table : date, type d'écriture (mission menée, délai respecté, preuve refusée, litige gagné/perdu, correction), delta signé (+/−), solde après écriture, motif et référence de dossier (Mono)."),
    Z("kpi", "Synthèse", 3, "Score actuel · total des écritures positives · total des négatives · corrections en attente."),
    Z("list", "Filtres", 2, "Par type, par période, par delta (positives/négatives), par mission liée."),
    Z("cta", "Actions", 1, "« Contester une écriture » or outline · « Exporter mon ledger » (CSV signé) fantôme."),
  ],
  comps=[("C-12 LedgerRow", "delta signé, solde après, horodatage Mono"),
         ("Badge de motif", "chaque écriture porte sa raison catégorisée"),
         ("Export signé", "CSV + JSON avec empreinte, utilisable comme preuve")],
  states=[("Vide", "« Aucune écriture pour l'instant. » + explication de ce qui en génère."),
          ("Écriture contestée", "badge ambre « en cours d'examen », l'écriture reste visible."),
          ("Correction appliquée", "nouvelle ligne (jamais modification), delta compensatoire, lien vers l'originale."),
          ("Période longue", "pagination par mois, total par période.")],
  motion=[("Entrée", "lignes révélées 40 ms, solde qui se stabilise"),
          ("Contestation", "ligne qui s'illumine ambre discrètement"),
          ("Correction", "nouvelle ligne qui s'insère et pointe vers l'originale (trait pointillé)")],
  rules=["INV-5 : append-only strict. Aucune écriture n'est modifiée ou supprimée, même par un administrateur (les corrections sont des écritures nouvelles).",
         "Chaque écriture est accompagnée d'un motif lisible et d'une référence de dossier vérifiable.",
         "Aucune écriture ne peut être basée sur une donnée discriminatoire ou non vérifiable.",
         "Le ledger est exportable à tout moment, y compris en cas de blocage de compte."],
  tokens=["--mono", "--emerald-500", "--clay-500", "--amber-500", "--surface-1"],
  api=["GET /v1/reputation/me/ledger?cursor=", "POST /v1/reputation/entries/:id/contest", "GET /v1/reputation/me/ledger/export"],
  tech="Event store append-only avec hash chaîné (chaque entrée référence le hash de la précédente) : toute tentative de "
       "réécriture d'historique casse la chaîne et est détectée par audit automatique (ADM-36).",
  canon="Réputation — ledger", chrome=CHROME_PRE),

S("PRE-47", "Contester une écriture de réputation", "PRE", "Remplacement & Réputation", "/prestataire/reputation/contestation", "Prestataire", "P1", "Voix sur son honneur",
  intent="Permettre de contester une écriture injuste avec un cadre précis : quel fondement, quelles preuves, quel délai, "
         "et qui décide. Un droit d'appel réel, pas un formulaire creux.",
  zones=[
    Z("hero", "Écriture contestée", 3, "Rappel exact de l'écriture (date, motif, delta, référence de dossier) — affichée avant le formulaire pour éviter les erreurs."),
    Z("form", "Fondement de la contestation", 4, "Motifs : faits erronés · contexte non pris en compte · preuve non examinée · imputation injuste du retard. Faits et pièces à l'appui."),
    Z("kpi", "Procédure", 3, "« Examen humain sous 5 jours ouvrés par la modération. » · « Pendant l'examen, le score reste inchangé. » · « Issue : annulation compensatoire, maintien, ou modification motivée. »"),
    Z("cta", "Envoyer", 2, "« Soumettre la contestation » or · « Annuler » fantôme."),
  ],
  comps=[("Rappel d'écriture", "lecture seule, contraste élevé"),
         ("Formulaire de fondement", "motifs + faits + pièces"),
         ("Bandeau de procédure", "délais et effets"),
         ("Historique", "contestations précédentes du travailleur et leurs issues (traçabilité)")],
  states=[("Aucune contestation possible", "délai dépassé (90 jours) : explication honnête, sans faux espoir."),
          ("Reçue", "dossier créé, n° Mono, échéance affichée."),
          ("Acceptée", "écriture compensatoire ajoutée, delta positif, lien vers la contestation."),
          ("Rejetée", "motivation écrite obligatoire, recours unique possible.")],
  motion=[("Envoi", "sceau or outline 480 ms"),
          ("Issue", "nouvelle ligne de ledger qui apparaît avec trait de liaison vers l'écriture contestée")],
  rules=["Toute contestation reçoit une réponse motivée : un rejet sec est un défaut produit.",
         "Le délai de contestation est de 90 jours après l'écriture (suffisant, borné, annoncé).",
         "Les administrateurs ne peuvent pas modifier une écriture : ils ne peuvent qu'approuver une écriture compensatoire, elle-même tracée à leur nom."],
  tokens=["--amber-500", "--mono", "--glass-2", "--text-mid"],
  api=["POST /v1/reputation/entries/:id/contest {grounds, facts, evidenceIds}", "GET /v1/reputation/contests/me"],
  tech="Dossier de contestation ouvert côté service réputation ; traité par la file ADM-34/35 avec SLA surveillé. Toute "
       "décision produit une écriture compensatoire signée par l'agent (identifiant interne, jamais exposé publiquement).",
  canon="Réputation — contestation", chrome=CHROME_PRE),

S("PRE-48", "Documents — bibliothèque R2", "PRE", "Documents & Versions", "/prestataire/documents", "Prestataire", "P0", "Armoire professionnelle",
  intent="Centraliser ses pièces professionnelles (identité, habilitations, assurances, références) avec leur statut de "
         "vérification et leurs dates d'expiration. Un actif qui sert dans chaque candidature.",
  zones=[
    Z("kpi", "État du dossier", 3, "Pièces vérifiées (n/total) · expirations à venir (30/60 jours) · impact : « 2 missions réglementées vous sont actuellement inaccessibles » (factuel)."),
    Z("list", "Pièces classées", 6, "Catégories : Identité · Habilitations & permis · Assurances · Références & attestations · Diplômes. Chaque pièce : C-11 (vignette, hash court, statut, expiration, versions)."),
    Z("cta", "Actions", 2, "« Ajouter une pièce » or · « Voir une pièce » fantôme · « Quelles pièces pour quels métiers ? » (guide utile)."),
  ],
  comps=[("C-11 DocumentCardR2", "statut + expiration + version"),
         ("Alerte d'expiration", "ambre à J-60, clay à J-0"),
         ("Guide des pièces", "par métier, dit ce qui est exigé par la loi, jamais plus")],
  states=[("Vide", "liste des pièces recommandées selon le métier déclaré."),
          ("Vérification en cours", "puce ambre + délai (24-48 h)."),
          ("Pièce rejetée", "clay + motif précis + redépôt immédiat."),
          ("Expirée", "clay plein : impact sur les candidatures réglementées expliqué, chemin de renouvellement proposé."),
          ("Dossier complet", "émeraude, badge « dossier conforme » visible du client.")],
  motion=[("Entrée", "cartes par catégorie, stagger 60 ms"),
          ("Dépôt", "progression réelle par fichier"),
          ("Expiration", "bascule ambre/clay au franchissement, notification programmée")],
  rules=["Seuls les statuts de vérification sont exposés aux clients — jamais le contenu brut des pièces d'identité.",
         "Aucune pièce n'est exigée au-delà des obligations légales ou des exigences réelles d'une mission.",
         "Le travailleur peut supprimer une pièce non obligatoire à tout moment ; les pièces liées à un contrat en cours sont conservées jusqu'à sa clôture."],
  tokens=["--emerald-500", "--amber-500", "--clay-500", "--mono", "--surface-2"],
  api=["GET /v1/documents?owner=me", "POST /v1/documents", "DELETE /v1/documents/:id"],
  tech="Pièces stockées en R2 (chiffré au repos), métadonnées en PostgreSQL. Les vignettes sont générées et versionnées ; "
       "les URLs sont présignées à durée courte et liées à l'utilisateur.",
  canon="Documents — bibliothèque", chrome=CHROME_PRE),

S("PRE-49", "Dépôt d'une nouvelle version de pièce", "PRE", "Documents & Versions", "/prestataire/documents/:id/versions/nouvelle", "Prestataire", "P0", "Versions, jamais d'écrasement",
  intent="Mettre à jour une pièce (permis renouvelé, assurance reconduite) sans perdre l'historique : chaque dépôt crée une "
         "version R2 tracée. C'est la base d'un dossier professionnel solide.",
  zones=[
    Z("hero", "Pièce concernée", 3, "C-11 large : nom, type, version actuelle, date d'expiration, statut. Mention : « la nouvelle version remplacera l'ancienne pour les usages futurs, l'ancienne reste archivée »."),
    Z("form", "Nouveau dépôt", 5, "Sélection (appareil photo / fichier), qualité guidée (lisibilité, cadrage, recto/verso si nécessaire), métadonnées (date d'émission, date d'expiration, numéro si applicable)."),
    Z("kpi", "Ce que cela change", 3, "« Vos candidatures en cours utilisent automatiquement la version vérifiée la plus récente. » · « La vérification prend 24-48 h. » · « Vous pouvez continuer à postuler avec l'ancienne version valide le temps du contrôle. »"),
    Z("cta", "Déposer", 2, "« Téléverser la nouvelle version » or · « Annuler » fantôme."),
  ],
  comps=[("Téléverseur", "URL présignée R2, reprise sur coupure, tailles/types affichés"),
         ("Contrôle de lisibilité", "détection de flou/cadrage avant envoi"),
         ("Comparateur de versions", "aperçu ancienne vs nouvelle côte à côte")],
  states=[("Prêt", "fichier + métadonnées complets."),
          ("Téléversement", "progression réelle, reprise après coupure."),
          ("En vérification", "amba pulsé, l'ancienne version reste active."),
          ("Vérifiée", "émeraude, la nouvelle version devient de référence, l'ancienne est archivée."),
          ("Rejetée", "clay + motif précis (ex. recto manquant) + redépôt, l'ancienne version reste active si valide.")],
  motion=[("Comparateur", "glissement avant/après 240 ms"),
          ("Versement dans la pile", "la nouvelle version se pose sur l'ancienne (empilement visuel), haptique light"),
          ("Validation", "puce émeraude + onde")],
  rules=["Aucune version n'écrase jamais la précédente : le dossier est un empilement sourcé.",
         "La nouvelle version ne devient active qu'après vérification : aucune candidature ne peut être invalidée par un dépôt en cours.",
         "Les métadonnées (émission/expiration) sont sous la responsabilité du travailleur, et le système alerte automatiquement 60 jours avant l'expiration."],
  tokens=["--emerald-500", "--amber-500", "--mono", "--glass-2", "--clay-500"],
  api=["POST /v1/documents/:id/versions", "GET /v1/documents/:id/versions/compare", "GET /v1/uploads/r2/presign"],
  tech="Versionnage R2 (clé = document_id/vN), métadonnées versionnées en base, vérification humaine asynchrone (file ADM-37). "
       "L'activation de la version de référence est atomique.",
  canon="Documents — dépôt & vérification", chrome=CHROME_PRE),

S("PRE-50", "Vérification d'une pièce en cours", "PRE", "Documents & Versions", "/prestataire/documents/:id/verification", "Prestataire", "P1", "Contrôle transparent",
  intent="Pendant la vérification d'une pièce, dire ce qui est contrôlé, ce qui peut poser problème, et ce qui se passe. "
         "L'attente devient un moment de conformité, pas d'angoisse administrative.",
  zones=[
    Z("timeline", "Étapes de vérification", 4, "Dépôt reçu → lecture automatique (lisibilité, type, zone lisible) → vérification humaine si nécessaire → décision. Auteur et horodatage de chaque étape."),
    Z("list", "Ce qui est vérifié", 4, "Conformité du type documentaire · lisibilité · cohérence des dates (émission/expiration) · correspondance nom/prénom · cohérence avec le métier déclaré. Aucun critère caché."),
    Z("kpi", "Délais & alternatives", 3, "Délai réel moyen (affiché) · « votre ancienne version reste valide jusqu'au 12/10 » · possibilité de garder la pièce privée (non partagée avec les clients)."),
    Z("cta", "Actions", 1, "« Remplacer mon dépôt » fantôme (si erreur) · « Discuter avec le support » texte."),
  ],
  comps=[("C-06 TimelineTrack", "étapes de contrôle"),
         ("Carte de critères", "critères publics de vérification"),
         ("Badge de continuité", "l'ancienne version reste active — pas de trou de couverture")],
  states=[("Contrôle automatique", "rapide : secondes à minutes."),
          ("Contrôle humain", "24-48 h, position dans la file affichée si possible."),
          ("Validée", "émeraude, la pièce devient de référence."),
          ("Correction souhaitée", "ambre : point précis à corriger, redépôt immédiat."),
          ("Rejetée", "clay + motif détaillé + procédure de recours.")],
  motion=[("Étapes", "progression qui se trace"),
          ("Décision", "bascule sobre (émeraude/ambre/clay)")],
  rules=["Les critères de vérification sont publics et stables : aucune décision sur des critères non annoncés.",
         "Un rejet est toujours accompagné d'un motif actionnable (ce qu'il faut corriger, précisément).",
         "Aucune pièce n'est partagée avec un client sans le dépôt d'une candidature à une mission concernée."],
  tokens=["--violet-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/documents/:id/verification", "GET /v1/documents/verification-policy (public)"],
  tech="Pipeline de vérification : lecture automatique (OCR + heuristiques) puis file humaine. Journal d'audit complet, "
       "décisions signées par l'agent (ADM-38).",
  canon="Documents — dépôt & vérification", variant_of="PRE-49", chrome=CHROME_PRE),

S("PRE-51", "Pièce rejetée — correction", "PRE", "Documents & Versions", "/prestataire/documents/:id/rejet", "Prestataire", "P0", "Corriger et repartir",
  intent="Un rejet n'est pas une sanction : c'est une consigne. L'écran dit précisément ce qui ne va pas, montre un exemple "
         "conforme, et permet de corriger immédiatement — sans repartir de zéro.",
  zones=[
    Z("hero", "Motif du rejet", 4, "Carte clay avec motif catégorisé (photo floue, recto manquant, date incohérente, document non légalisé, nom divergent) + extrait de la pièce problématique annoté si l'outil le permet."),
    Z("kpi", "Exemple conforme", 4, "Modèle visuel du même type de pièce, conforme : cadrage, informations visibles, format. « Voici à quoi ressemble une version acceptée. »"),
    Z("list", "Corrections guidées", 3, "Checklist de correction : points à refaire, conseils (éclairage, fond, zoom), obligations légales éventuelles (légalisation, traduction)."),
    Z("cta", "Corriger", 2, "« Déposer une version corrigée » or · « Contester le rejet » fantôme (recours réel)."),
  ],
  comps=[("Carte de rejet", "motif + annotation sur la pièce"),
         ("Exemple conforme", "modèle visuel, non téléchargeable (pas de faux documents)"),
         ("Checklist de correction", "cochée avant redépôt possible"),
         ("Recours", "si le rejet est contesté : nouvel examen humain sous 48 h")],
  states=[("Rejetée", "clay, action immédiate possible."),
          ("Correction en cours", "nouveau dépôt lié au rejet (dossier unique)."),
          ("Corrigée", "émeraude dès validation, l'historique conserve le rejet initial (transparence)."),
          ("Recours accepté", "émeraude + écriture d'apaisement : « rejet annulé, motif : contrôle erroné »")],
  motion=[("Annotation", "cercle clay qui se dessine sur la zone problématique 420 ms"),
          ("Correction", "nouveau dépôt qui se pose sur le rejet, haptique light"),
          ("Validation", "sceau émeraude")],
  rules=["Un rejet doit toujours être actionnable : motif clair, exemple, chemin de correction. Un rejet non actionnable est un défaut produit P1.",
         "Les rejets erronés sont reconnus : ils génèrent une écriture d'apaisement (et une correction du processus si récurrents).",
         "Le travailleur peut demander un examen humain de tout rejet automatique."],
  tokens=["--clay-500", "--emerald-500", "--amber-500", "--mono"],
  api=["GET /v1/documents/:id/rejection", "POST /v1/documents/:id/rejection/correct", "POST /v1/documents/:id/rejection/contest"],
  tech="Machine d'états de document (draft → uploaded → in_review → verified/rejected → corrected). Les rejets fréquents sur "
       "un même critère déclenchent une revue du détecteur automatique (ADM-38).",
  canon="Documents — dépôt & vérification", variant_of="PRE-49", chrome=CHROME_PRE),

S("PRE-52", "Documents — historique des versions", "PRE", "Documents & Versions", "/prestataire/documents/:id/historique", "Prestataire", "P2", "Mémoire du dossier",
  intent="Voir la vie complète d'une pièce : versions successives, vérifications, rejets, corrections. Utile en cas de "
         "contrôle, de litige, ou simplement pour savoir ce qui a été présenté à quel client.",
  zones=[
    Z("list", "Chronologie des versions", 5, "Chaque version : numéro, date de dépôt, période de validité, statut de vérification, empreinte courte (Mono), usage (« utilisée pour la mission M-… du 12/09 »)."),
    Z("table", "Usages", 4, "Table : contrat/mission, date d'exposition au client, statut de la pièce à ce moment-là. Traçabilité de ce qui a été partagé, et quand."),
    Z("cta", "Actions", 1, "« Exporter l'historique » (PDF) · « Voir une version » fantôme."),
  ],
  comps=[("Ligne de version", "statut + empreinte + usage"),
         ("Log d'usage", "sait exactement ce que le client a vu"),
         ("Export", "PDF horodaté pour usage administratif")],
  states=[("Une version", "état simple."),
          ("Multi-versions", "tri antéchronologique, filtres."),
          ("Version expirée", "badge ardoise, conservée pour l'historique.")],
  motion=[("Dépliage", "accordéon 240 ms"),
          ("Export", "génération asynchrone + notification")],
  rules=["Le log d'usage est une garantie pour le travailleur : il sait exactement quelle version a été vue par quel client, et quand.",
         "Aucune version n'est supprimable, y compris rejetée : intégrité du dossier professionnel.",
         "L'export de l'historique est gratuit et illimité (droit d'accès aux données)."],
  tokens=["--mono", "--slate-500", "--emerald-500", "--surface-1"],
  api=["GET /v1/documents/:id/versions", "GET /v1/documents/:id/usages", "GET /v1/documents/:id/history.pdf"],
  tech="Historique dérivé du journal de documents (append-only) ; les usages sont journalisés lors des candidatures et "
       "contrats (référence de version figée).",
  canon="Documents — historique", chrome=CHROME_PRE),
]
