# -*- coding: utf-8 -*-
"""FAMILLE 03 · PRESTATAIRE / CANDIDAT — PRE-01 → PRE-15"""
from ..model import S, Z, CHROME_APP

CHROME_PRE = {"appbar": "LE LABEUR", "dock": ["Accueil", "Missions", "Candidatures", "Salaire", "Profil"], "glyph": "◉"}

SCREENS = [

S("PRE-01", "Dashboard prestataire", "PRE", "Accueil & Profil", "/prestataire", "Prestataire", "P0", "Tableau de bord du travailleur",
  intent="Répondre en 5 secondes à : combien vais-je gagner, qu'est-ce que je dois faire aujourd'hui, où en sont mes "
         "candidatures. Le revenu est l'information vitale : elle passe en premier.",
  zones=[
    Z("hero", "Salutation + disponibilité", 2, "« Bonjour, Yao. » + interrupteur de disponibilité (disponible / occupé / absent) avec effet immédiat sur le matching."),
    Z("kpi", "Trio vital du travailleur", 3, "À recevoir (or, --display-1) · candidatures actives · missions en cours. Chiffres tnum."),
    Z("list", "Actions du jour", 5, "Cartes priorisées : preuve à déposer (échéance Mono), échéance de salaire, candidature qui a reçu une réponse, mission qui démarre demain."),
    Z("timeline", "Prochains engagements", 3, "Frise : démarrages de mission, jalons de preuve, dates d'échéance salariale. Horodatage Mono."),
    Z("cta", "Actions", 1, "« Trouver des missions » or · « Voir mon argent » fantôme."),
  ],
  comps=[("Interrupteur de disponibilité", "trois états, haptique light, impact expliqué"),
         ("Carte d'action", "type + échéance + action unique"),
         ("C-04 StatusSeal", "statut des missions en cours"),
         ("C-06 TimelineTrack", "engagements datés")],
  states=[("Nouveau prestataire", "état vide : compléter le profil (score de complétude), première mission guidée."),
          ("Disponible", "halo émeraude discret, matching actif."),
          ("Indisponible", "état sobre, mention « le matching vous exclut temporairement » (honnêteté)."),
          ("Retard de salaire", "bandeau clay : montant dû + échéance dépassée + action « relancer ».")],
  motion=[("Entrée", "hero → revenu → actions → engagements, stagger 60 ms"),
          ("Interrupteur", "glissement 240 ms + halo émeraude transitoire"),
          ("Revenu", "compteur tnum qui se stabilise 240 ms (jamais de faux mouvement)")],
  rules=["Le montant affiché est le PRIX PRESTATAIRE, jamais le total client ni les frais SaaS (INV-1, vue prestataire).",
         "Aucune métrique de vanité (vues de profil) : uniquement des engagements réels.",
         "L'indisponibilité n'est jamais punitive : elle exclut du matching sans pénaliser la réputation."],
  tokens=["--emerald-500", "--gold-500", "--display-1", "--surface-0", "--amber-500"],
  api=["GET /v1/provider/dashboard", "PATCH /v1/provider/availability", "GET /v1/payments?role=provider&state=pending"],
  tech="RSC ou écran RN natif avec cache 30 s ; le revenu est calculé côté serveur (jamais dérivé localement). Les cartes "
       "d'action sont générées par le moteur d'échéances (source unique avec les notifications).",
  canon="Dashboard prestataire", chrome=CHROME_PRE),

S("PRE-02", "Notifications prestataire", "PRE", "Accueil & Profil", "/prestataire/notifications", "Prestataire", "P1", "Flux du travailleur",
  intent="Chaque notification est un événement de travail : candidature vue, mission attribuée, preuve à déposer, salaire "
         "déclaré, OTP attendu. Aucune notification ne doit créer d'angoisse sans action possible.",
  zones=[
    Z("chips", "Filtres", 2, "Action requise · Candidatures · Missions · Salaire · Système."),
    Z("list", "Liste chronologique", 6, "Carte d'événement : glyphe, titre, mission (Mono), horodatage relatif, action en une ligne."),
    Z("cta", "Contrôle", 1, "« Tout marquer comme lu » fantôme (jamais pour les actions requises)."),
  ],
  comps=[("Ligne d'événement", "glyphe + titre + action"),
         ("Badge d'urgence", "ambre si échéance < 48 h, clay si retard"),
         ("Swipe", "archiver / reporter")],
  states=[("Non lues", "ligne émeraude 2 px à gauche."),
          ("Vides", "« Aucune nouvelle. Votre travail est à jour. »"),
          ("Alerte salaire", "traitement prioritaire, bandeau clay en tête."),
          ("Rappel de preuve", "délai affiché, action directe vers le dépôt (PRE-30).")],
  motion=[("Apparition", "stagger 60 ms plafonné"),
          ("Réception live", "pop du badge 240 ms"),
          ("Archivage", "glissement + undo 5 s")],
  rules=["Aucune notification marketing : le flux est exclusivement professionnel et contractuel.",
         "Les notifications de salaire sont toujours accompagnées du montant exact en prix prestataire.",
         "Les rappels de preuve ne sont jamais plus de 2 par jour (respect de la vie personnelle)."],
  tokens=["--surface-1", "--emerald-500", "--clay-500", "--gold-500"],
  api=["GET /v1/notifications?role=provider", "GET /v1/notifications/stream (SSE)"],
  tech="Même socle que EMP-02 (service de notifications), avec gabarits spécifiques au rôle prestataire.",
  canon="Notifications — flux prestataire", variant_of="EMP-02", chrome=CHROME_PRE),

S("PRE-03", "Profil prestataire", "PRE", "Accueil & Profil", "/prestataire/profil", "Prestataire", "P0", "Vitrine de compétence",
  intent="Construire un profil qui vend honnêtement : compétences vérifiables, pièces contrôlées, zones d'intervention, "
         "tarif indicatif. Le profil est l'actif professionnel du travailleur — il doit pouvoir l'emporter avec lui.",
  zones=[
    Z("hero", "Identité & complétude", 3, "Avatar halo émeraude, métier principal, ancienneté, score de complétude avec détail des manques."),
    Z("kpi", "Fiabilité prouvée", 3, "Missions menées · délais respectés · litiges (avec issue). Chiffres tnum + méthodologie."),
    Z("list", "Sections du profil", 5, "Compétences (avec niveaux déclarés et pièces à l'appui) · Habilitations & certifications (R2, avec dates d'expiration) · Zones d'intervention · Disponibilité habituelle · Langues · Présentation libre (500 c.)."),
    Z("cta", "Actions", 2, "« Modifier » or discret · « Aperçu client » fantôme · « Exporter mon profil professionnel » (PDF portable)."),
  ],
  comps=[("Carte de compétence", "déclarée / vérifiée (pièce liée) — distinction visuelle stricte"),
         ("C-11 DocumentCardR2", "habilitations avec alerte d'expiration"),
         ("Barre de complétude", "segments, priorisation des manques"),
         ("Export portable", "PDF professionnel, contenu choisi par le travailleur")],
  states=[("Incomplet", "segments ambre + CTA compléter."),
          ("Pièce expirée", "bandeau clay : « habilitation expirée » + impact sur les candidatures réglementées."),
          ("Vérification en cours", "puce ambre pulsée, délai affiché."),
          ("Profil fort", "état serein : badges émeraude, mise en avant dans le matching (expliqué, non magique).")],
  motion=[("Complétude", "barre qui progresse par ressort soft"),
          ("Expiration", "puce qui bascule ambre à J-30, clay à J+0"),
          ("Export", "sceau émeraude bref")],
  rules=["Un niveau de compétence est toujours distingué de sa vérification : « déclaré » vs « vérifié (pièce) ». Jamais de flou.",
         "Le travailleur peut masquer certaines missions passées à l'aperçu client (droit à la vie privée), sauf obligations légales.",
         "Le profil exportable appartient au travailleur : export complet toujours accessible, même en cas de blocage de compte."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--surface-2", "--amber-500"],
  api=["GET /v1/provider/profile", "PATCH /v1/provider/profile", "GET /v1/provider/profile/export.pdf"],
  tech="Profil en JSONB avec champs versionnés ; l'aperçu client est une projection serveur (deny-by-default) réutilisant "
       "le composant partagé de EMP-17.",
  canon="Profil prestataire", chrome=CHROME_PRE),

S("PRE-04", "Paramètres prestataire", "PRE", "Accueil & Profil", "/prestataire/parametres", "Prestataire", "P1", "Réglages du travailleur",
  intent="Régler sa vie professionnelle : canaux de notification (le travailleur travaille, il ne veut pas de bruit), "
         "paiement, sécurité, confidentialité, accessibilité. Les réglages par défaut protègent le travailleur.",
  zones=[
    Z("list", "Rubriques", 6, "Notifications (canaux, heures calmes strictes 20:00-07:00 par défaut) · Paiement (mobile money, compte bancaire, préférences) · Sécurité (2FA, appareils) · Confidentialité (visibilité dans le matching, partage de profil) · Accessibilité (taille, contraste, réduction de mouvement) · Données."),
    Z("form", "Zone sensible", 3, "Faire une pause (suspendre la disponibilité 1-90 jours, sans pénalité) · Supprimer le compte (14 jours de réversibilité + export garanti)."),
    Z("cta", "Pied", 1, "Version, CGU acceptée + hash, identifiant de travailleur (Mono)."),
  ],
  comps=[("Ligne de réglage", "libellé + explication en langage simple"),
         ("Heures calmes", "par défaut activées : le produit protège le repos"),
         ("Pause professionnelle", "réglage inédit mais essentiel : suspendre sans perdre sa réputation")],
  states=[("Par défaut", "heures calmes actives, visibilité standard."),
          ("Pause active", "bandeau ardoise « en pause jusqu'au … », matching suspendu, aucune pénalité."),
          ("Support mobile money", "selon pays, moyens affichés avec frais éventuels (transparence)."),
          ("Suppression", "3 étapes avec export obligatoirement proposé avant.")],
  motion=[("Accordéons", "hauteur spring soft"),
          ("Pause", "sceau ardoise, aucune animation festive"),
          ("Toggle", "120 ms + halo transitoire")],
  rules=["L'export des données est proposé AVANT toute suppression : jamais de perte non consentie.",
         "Les heures calmes ne peuvent être désactivées que par action explicite, avec avertissement.",
         "La suppression d'un compte en cours de mission est bloquée jusqu'à clôture (protection du client et du travailleur)."],
  tokens=["--surface-2", "--emerald-500", "--slate-500", "--mono"],
  api=["GET/PATCH /v1/provider/settings", "POST /v1/provider/pause", "GET /v1/provider/export"],
  tech="Réglages serveur + miroir local. Les préférences de notification sont appliquées côté service d'envoi "
       "(les jobs respectent les heures calmes, fuseau du travailleur).",
  canon="Paramètres (prestataire)", chrome=CHROME_PRE),

S("PRE-05", "Missions disponibles", "PRE", "Missions & Candidatures", "/prestataire/missions", "Prestataire", "P0", "Marché du travail",
  intent="Trouver du travail qui vaut la peine : le prix prestataire est mis en avant, les conditions sont visibles d'emblée, "
         "et aucune mission ne peut cacher ce qu'elle paie ni ce qu'elle exige.",
  zones=[
    Z("chips", "Segments & tri", 2, "Segments : Recommandées · Nouvelles · Près de moi · Mieux payées · Courtes. Tri : pertinence, prix, distance, date de début."),
    Z("list", "Cartes mission", 6, "Carte : titre, catégorie, PRIX PRESTATAIRE en --title-3 or (+ mention « vous recevrez »), lieu & distance, durée, date de début, nombre de candidats (jamais caché), badges d'exigences (habilitation, permis)."),
    Z("kpi", "Contexte de marché", 2, "Bandeau informatif : « 12 nouvelles missions dans votre zone aujourd'hui » + fourchette médiane observée par catégorie."),
    Z("cta", "Affiner", 1, "« Filtres » (PRE-06) fantôme · « Actualiser » texte."),
  ],
  comps=[("Carte mission", "variante prestataire : prix dominant, frais SaaS jamais affichés"),
         ("Badge de distance", "calculée depuis la zone d'intervention déclarée"),
         ("Compteur de candidats", "affiché — le travailleur sait à quoi il se mesure"),
         ("Chips d'exigences", "or si impérative, ardoise si souhaitée")],
  states=[("Recommandées", "score de pertinence expliqué au tap (raison en une ligne)."),
          ("Vide", "« Aucune mission ne correspond. » + élargir la zone ou activer les notifications de marché."),
          ("Mission urgente", "badge « démarrage < 48 h » ambre."),
          ("Mission pourvue", "retirée de la liste avec fade — jamais laissée pour attirer du clic.")],
  motion=[("Liste", "stagger 60 ms, cartes qui montent 8 px"),
          ("Filtres", "recomposition FLIP 240 ms"),
          ("Nouvelle mission", "pop du badge + insertion en tête avec surbrillance 3 s")],
  rules=["Le prix affiché sur cette liste est TOUJOURS le prix prestataire intégral. Les frais SaaS n'apparaissent jamais ici (ils incombent au client).",
         "Le nombre de candidats est toujours visible : dissimuler la concurrence serait une manipulation.",
         "Aucune mission ne peut être « boostée » contre paiement pour apparaître devant les autres (pas de vente de visibilité)."],
  tokens=["--gold-500", "--emerald-500", "--surface-1", "--display-1", "--squircle-22"],
  api=["GET /v1/missions/available?segment=&sort=&cursor=", "GET /v1/missions/available/counters"],
  tech="Le flux est servi par un read model alimenté par l'événement de publication ; filtrage géospatial en SQL "
       "(PostGIS) indexé. Les missions pourvues sont retirées en moins de 5 s via SSE.",
  canon="Missions disponibles — marché", chrome=CHROME_PRE),

S("PRE-06", "Filtres de missions", "PRE", "Missions & Candidatures", "/prestataire/missions/filtres", "Prestataire", "P1", "Chasse au travail utile",
  intent="Trouver les missions qui valent le déplacement : distance, prix minimum, durée, horaires, exigences qu'on possède. "
         "Le filtre « prix minimum » est un outil de dignité — il est mis en avant.",
  zones=[
    Z("form", "Filtres", 5, "Prix prestataire minimum (curseur, or) · Distance max (cercle sur carte) · Durée maximum · Date de début · Catégories · Exigences (ne montrer que ce que je possède) · Horaires compatibles."),
    Z("kpi", "Résultat live", 3, "Compteur de missions correspondantes + salaire médian du lot filtré (tnum)."),
    Z("list", "Filtres enregistrés", 2, "Modèles : « Mi-temps Cotonou », « Missions courtes bien payées » + personnels."),
    Z("cta", "Appliquer", 2, "« Voir les missions » or · « Réinitialiser » fantôme."),
  ],
  comps=[("Curseur de prix", "or, affiche le seuil en clair et le nombre de missions exclues"),
         ("Cercle de distance", "carte statique, ajustable par poignée"),
         ("Chips catégories", "multi-sélection"),
         ("Filtre d'exigences", "« n'afficher que ce que je peux faire » — évite les candidatures inutiles")],
  states=[("Vide", "bandeau : « Votre prix minimum exclut 94 % des missions de cette catégorie » (fait, pas jugement)."),
          ("Filtres conflit", "combinaison impossible bloquée avec explication."),
          ("Modèle chargé", "application immédiate, résultat mis à jour."),
          ("Prix minimum élevé", "aucun jugement moral : juste l'information factuelle du marché.")],
  motion=[("Curseur", "haptique light aux paliers"),
          ("Compteur", "chiffres tnum glissants 120 ms"),
          ("Application", "tiroir qui se replie, liste qui se recompose")],
  rules=["Aucune incitation à accepter moins que son prix : LE LABEUR n'a aucun intérêt commercial à la baisse des prix.",
         "Les modèles de filtres ne collectent aucune donnée personnelle.",
         "Les filtres ne peuvent pas cibler des caractéristiques personnelles."],
  tokens=["--gold-500", "--surface-3", "--emerald-500", "--mono"],
  api=["POST /v1/missions/available/search", "GET /v1/filters/provider-presets"],
  tech="Recherche facettée côté serveur, compteurs calculés dans la même requête avec CTE pour éviter les incohérences.",
  canon="Missions disponibles — filtres", chrome={"appbar": "Filtres", "glyph": "◉"}),

S("PRE-07", "Détail mission (prestataire)", "PRE", "Missions & Candidatures", "/prestataire/missions/:id", "Prestataire", "P0", "La promesse en clair",
  intent="L'écran décisif de la candidature : ce que je vais faire, ce que je serai payé, ce que je dois produire, avec "
         "qui je m'engage. Le prix prestataire domine l'écran — c'est la première information lue.",
  zones=[
    Z("price", "Prix prestataire dominant", 5, "Bandeau haut : « VOUS RECEVREZ 250 000 F » en --display-1 or, suivie de la mention « le client paie 275 000 F au total (dont 25 000 F de frais SaaS LE LABEUR) » en --caption, transparence non punitive."),
    Z("hero", "Objet & client", 4, "Titre, catégorie, description structurée, profil du client (fiabilité, historique, taux de paiement à l'heure), ancienneté de la mission."),
    Z("list", "Conditions d'exécution", 5, "Lieu & distance · dates & durée · livrables & preuves attendues · compétences exigées (or) — et ce que je possède déjà (émeraude), honnêtement comparé."),
    Z("timeline", "Échéancier de paiement", 3, "Quand je serai payé : 40 % après signature, 60 % après validation finale. Dates estimées, mécanisme de l'OTP expliqué en une phrase."),
    Z("cta", "Postuler", 2, "« Postuler » or (mène à PRE-08) · « Enregistrer » fantôme · « Signaler une mission douteuse » texte (accès discret mais réel)."),
  ],
  comps=[("C-05 PriceBreakdown", "variante prestataire : prix d'abord, total client en mention secondaire"),
         ("Comparateur de compétences", "exigées vs possédées, avec les manques en ambre"),
         ("Carte client", "fiabilité, taux de paiement, litiges — données publiques du profil client"),
         ("Signalement", "flux confidentiel vers la modération")],
  states=[("Éligible", "toutes les exigences satisfaites, CTA or."),
          ("Exigence manquante", "bandeau ambre : « habilitation requise » + chemin pour l'obtenir (lien utile, jamais publicitaire)."),
          ("Mission pourvue", "bouton désactivé + explication « mission attribuée le … »."),
          ("Mission signalée", "bandeau ardoise « en cours d'examen » si d'autres signalements existent."),
          ("Client à risque", "si taux de retard de paiement élevé : avertissement factuel affiché avant candidature.")],
  motion=[("Entrée", "prix en premier (420 ms) puis conditions (stagger 60 ms) — l'ordre de lecture est imposé par le rythme"),
          ("Comparateur", "lignes qui se colorent une à une 120 ms"),
          ("Postuler", "CTA qui se remplit, haptique medium")],
  rules=["Le travailleur voit TOUJOURS ce que le client paie au total : la transparence est réciproque, et protège LE LABEUR de toute accusation de marge cachée.",
         "Aucune mission ne peut masquer une exigence impérative : elles sont affichées avant candidature, jamais découvertes après.",
         "Le taux de paiement à l'heure du client est public : le travailleur a le droit de savoir à qui il a affaire."],
  tokens=["--display-1", "--gold-500", "--emerald-500", "--surface-2", "--glass-2"],
  api=["GET /v1/missions/:id/provider-view", "POST /v1/missions/:id/report", "POST /v1/missions/:id/save"],
  tech="Vue prestataire = projection serveur du même agrégat mission. Les informations client sont agrégées (jamais de "
       "données personnelles). Mise en cache 60 s avec ETag.",
  canon="Mission — fiche prestataire", chrome={"appbar": "Mission", "glyph": "◉"}),

S("PRE-08", "Postuler à une mission", "PRE", "Missions & Candidatures", "/prestataire/missions/:id/postuler", "Prestataire", "P0", "Acte de candidature",
  intent="Postuler est un engagement : l'écran affiche exactement ce qui est envoyé, ce que cela implique, et ce qui se "
         "passera si la candidature est retenue. Rien de machinal.",
  zones=[
    Z("hero", "Rappel du cadre", 3, "Mission, prix prestataire (or), dates, exigences. Un résumé qui sert de contrat moral avant le message."),
    Z("form", "Message & pièces", 4, "Message de motivation (600 c., guidé par des questions : comment, quand, avec quelles compétences) · pièces utiles à joindre (habilitations, portfolio) · disponibilité confirmée (dates)."),
    Z("kpi", "Ce qui se passe ensuite", 3, "« Le client voit votre profil et votre message. » · « Vous serez notifié de la réponse. » · « Aucun engagement n'est pris avant contrat signé. »"),
    Z("cta", "Envoyer", 2, "« Envoyer ma candidature » or (libellé explicite) · « Enregistrer le brouillon » fantôme."),
  ],
  comps=[("Éditeur de message", "compteur, suggestions de structure, garde-fou anti-coordonnées"),
         ("Sélecteur de pièces", "pièces du profil, aperçu avant envoi"),
         ("Confirmation de disponibilité", "cases de dates, obligation d'engagement de principe"),
         ("Bandeau de clarté", "aucun frais pour candidater — dit explicitement")],
  states=[("Vide", "CTA désarmé jusqu'au message minimum (80 c.)."),
          ("Message contenant des coordonnées", "avertissement puis blocage : « la communication hors plateforme n'est pas protégée »."),
          ("Déjà postulé", "état explicite : « candidature envoyée le … » + possibilité de la modifier avant lecture."),
          ("Mission pourvue entre-temps", "409 : bandeau ardoise « la mission vient d'être attribuée », message conservé pour réutilisation.")],
  motion=[("Entrée", "cadre → message → conséquences, stagger 60 ms"),
          ("Envoi", "CTA qui se remplit, sceau or bref, haptique medium"),
          ("Brouillon", "point émeraude discret")],
  rules=["Postuler est gratuit et l'écran le dit : aucune monétisation de l'accès au travail (principe non négociable du produit).",
         "L'engagement de disponibilité est de bonne foi : un candidat qui se désiste sans motif après sélection laisse une trace dans son dossier.",
         "Aucune candidature ne peut être envoyée avec un message vide : le client doit pouvoir juger la personne."],
  tokens=["--gold-500", "--emerald-500", "--surface-2", "--glass-2", "--mono"],
  api=["POST /v1/missions/:id/applications {message, evidenceIds, availability}", "GET /v1/applications/draft?missionId="],
  tech="Brouillon local chiffré + envoi idempotent (clé mission+candidat). Détection d'insertion de coordonnées côté serveur "
       "(regex + heuristiques), message pédagogique, journalisation.",
  canon="Candidature — dépôt", chrome={"appbar": "Postuler", "glyph": "◉"}),

S("PRE-09", "Candidature envoyée", "PRE", "Missions & Candidatures", "/prestataire/candidatures/envoyee", "Prestataire", "P1", "Confirmation & suite",
  intent="Confirmer l'envoi et dire précisément ce qui va se passer : quand le client est notifié, sous quel délai une réponse "
         "est attendue, et ce que le travailleur peut faire en attendant.",
  zones=[
    Z("verdict", "Sceau d'envoi", 3, "Sceau or « Candidature envoyée » + référence de candidature A-2026-1142 (Mono)."),
    Z("timeline", "Suite prévisible", 4, "Lecture par le client (notification immédiate) → présélection éventuelle → réponse. Délai indicatif affiché (médiane réelle : 6 h)."),
    Z("kpi", "Pendant l'attente", 3, "Actions utiles : consulter d'autres missions similaires (sans spammer), vérifier ses pièces, compléter son profil. Jamais « relancer le client » : pas d'outil de harcèlement."),
    Z("cta", "Actions", 2, "« Voir mes candidatures » or outline · « Chercher des missions similaires » fantôme."),
  ],
  comps=[("C-04 StatusSeal", "or"),
         ("C-06 TimelineTrack", "états de candidature"),
         ("Encart anti-harcèlement", "« La relance du client n'est pas disponible : la plateforme fait le suivi. »")],
  states=[("Envoyée", "état simple."),
          ("Vue par le client", "bascule émeraude atténuée avec horodatage (le travailleur sait qu'on l'a lu — équité)."),
          ("Présélectionné", "transition vers PRE-10 avec notification push."),
          ("Refusée", "notification sobre, aucune justification du client n'est transmise (protection), mais le score de matching reste consultable.")],
  motion=[("Sceau", "or, une pulsation"),
          ("Suivi", "point de timeline qui s'allume à chaque étape franchie")],
  rules=["Aucun outil de relance directe du client : les relances automatiques sont le fait de la plateforme, à cadence bornée.",
         "Le travailleur ne voit pas la note de présélection interne du client : il voit l'état, pas les délibérations.",
         "En cas de refus, aucune raison détaillée n'est transmise (sauf si le client choisit volontairement d'en donner une)."],
  tokens=["--gold-500", "--emerald-500", "--mono", "--glass-1"],
  api=["GET /v1/applications/:id", "GET /v1/missions/available/similar?to=:mid"],
  tech="Écran de suivi léger, alimenté par la machine d'états de candidature (sent → viewed → shortlisted → selected/declined).",
  canon="Candidature — dépôt", variant_of="PRE-08", chrome={"appbar": "Envoyée", "glyph": "◉"}),

S("PRE-10", "Candidature — suivi détaillé", "PRE", "Missions & Candidatures", "/prestataire/candidatures/:id", "Prestataire", "P1", "Fil de sa candidature",
  intent="Savoir où en est sa candidature sans harceler : chaque étape est horodatée, chaque changement d'état visible. "
         "L'attente devient de l'information.",
  zones=[
    Z("hero", "État de la candidature", 3, "Mission, client, état actuel (envoyée, vue, présélectionnée, retenue, refusée), horodatage de chaque bascule."),
    Z("timeline", "Étapes", 4, "Frise détaillée avec délais indicatifs et délais réels passés. Aucune étape fantôme."),
    Z("chat", "Questions & réponses", 4, "Fil de discussion permise par le client (EMP-17) : le travailleur peut répondre aux questions, horodaté, sans échange de coordonnées."),
    Z("cta", "Actions", 2, "« Retirer ma candidature » fantôme · « Voir la mission » or outline."),
  ],
  comps=[("C-06 TimelineTrack", "états de candidature"),
         ("Fil Q/R", "limité aux questions du client, jamais de démarchage"),
         ("Badge de durée d'attente", "« en attente depuis 2 j » en Mono — honnête")],
  states=[("En attente", "délai de réponse indicatif."),
          ("Question reçue", "notification + réponse attendue sous 48 h (le travailleur n'est pas obligé)."),
          ("Retenue", "transition vers proposition PRE-11..16 (sceau émeraude)."),
          ("Refusée", "états sobres, aucune information humiliante."),
          ("Candidature retirée", "grisée, réactivable tant que la mission est ouverte.")],
  motion=[("Bascule d'état", "point de frise qui s'allume 420 ms"),
          ("Nouvelle question", "insertion 240 ms avec surlignage 3 s")],
  rules=["Toute étape est horodatée côté serveur : le travailleur peut vérifier qu'il n'a pas été oublié (équité perçue).",
         "Le refus n'ouvre pas de débat : pas de contestation possible sur une candidature (c'est une décision de sélection, pas un contrat).",
         "Le retrait est possible à tout moment avant sélection, sans motif obligatoire."],
  tokens=["--emerald-500", "--gold-500", "--slate-500", "--mono"],
  api=["GET /v1/applications/:id/full", "POST /v1/applications/:id/withdraw", "POST /v1/applications/:id/answers"],
  tech="Machine d'états de candidature partagée avec EMP-16/21. Les horodatages sont serveur, jamais locaux.",
  canon="Candidature — suivi", chrome=CHROME_PRE),

S("PRE-11", "Mes candidatures", "PRE", "Missions & Candidatures", "/prestataire/candidatures", "Prestataire", "P0", "Registre des candidatures",
  intent="Voir toutes ses candidatures et leur état d'un coup d'œil, trier par urgence, retirer celles qui n'ont plus de sens. "
         "C'est le poste de pilotage de la recherche de travail.",
  zones=[
    Z("chips", "Segments", 2, "Toutes · En attente · Présélectionnées · Retenues · Refusées · Retirées. Tri : plus récentes, plus anciennes, mieux payées."),
    Z("list", "Cartes candidature", 6, "Carte : mission, prix prestataire (or), état avec horodatage, jour d'attente, action rapide (voir, retirer)."),
    Z("kpi", "Compteurs utiles", 2, "« 5 candidatures actives · taux de vue 80 % · taux de présélection 20 % » — des chiffres pour progresser, pas pour culpabiliser."),
  ],
  comps=[("Carte candidature", "état + prix + délai d'attente"),
         ("Statistiques personnelles", "taux calculés sur 90 jours, avec définition accessible"),
         ("Retrait rapide", "swipe ou menu, avec undo")],
  states=[("Vide", "« Vous n'avez pas encore postulé. » + bouton vers le marché + conseil de complétude de profil."),
          ("Présélection", "mise en avant émeraude, action requise si question du client."),
          ("Refusées", "regroupées, consultables, jamais supprimées automatiquement."),
          ("Taux faible", "encart de progression factuel : « les candidatures avec message > 300 caractères sont 2× plus présélectionnées » (donnée mesurée sur la plateforme).")],
  motion=[("Segments", "morph du surlignage 240 ms"),
          ("Retrait", "carte qui glisse et pâlit, undo 5 s"),
          ("Présélection", "pop émeraude + badge")],
  rules=["Le taux de présélection est calculé et affiché avec sa méthode ; il n'est jamais comparé publiquement entre travailleurs.",
         "Aucune candidature n'est supprimée sans action explicite du travailleur.",
         "Les statistiques servent la progression : aucune mécanique de comparaison sociale punitive."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--surface-1"],
  api=["GET /v1/applications?provider=me&segment=", "GET /v1/applications/stats"],
  tech="Liste virtualisée ; les statistiques proviennent d'une vue matérialisée rafraîchie horairement (pas de calcul lourd à l'ouverture).",
  canon="Candidatures — registre prestataire", chrome=CHROME_PRE),

S("PRE-12", "Détail d'une candidature (dépôt)", "PRE", "Missions & Candidatures", "/prestataire/candidatures/:id/depot", "Prestataire", "P2", "Ce que j'ai envoyé",
  intent="Revoir exactement ce qui a été envoyé : message, pièces, disponibilité déclarée. Permet d'apprendre de ses candidatures "
         "et de réutiliser ce qui fonctionne.",
  zones=[
    Z("doc", "Contenu envoyé", 5, "Message intégral, pièces jointes avec aperçu, dates de disponibilité déclarées, horodatage d'envoi."),
    Z("kpi", "Réutilisation", 3, "« Réutiliser ce message » (copie dans une nouvelle candidature) · « Voir les candidatures similaires »."),
    Z("cta", "Actions", 2, "« Retirer » fantôme · « Retour à mes candidatures » texte."),
  ],
  comps=[("Vue du dépôt", "rendu identique à ce que le client voit (transparence totale)"),
         ("Bibliothèque de messages", "réutilisation, 10 max conservés")],
  states=[("Visible avant lecture", "modifiable encore."),
          ("Lue par le client", "figée, mention claire."),
          ("Retirée", "lecture seule.")],
  motion=[("Ouverture", "fenêtre qui se déplie 240 ms"),
          ("Réutilisation", "fly-to vers le bouton Postuler d'une autre mission")],
  rules=["Le travailleur voit strictement ce que le client voit de sa candidature — aucune copie divergente.",
         "Après lecture par le client, la candidature est figée (les captures d'écran et les incohérences nuisent à tout le monde)."],
  tokens=["--surface-2", "--mono", "--emerald-500"],
  api=["GET /v1/applications/:id/submission", "POST /v1/applications/messages/templates"],
  tech="Rendu partagé avec la vue client (même composant, même données).",
  canon="Candidature — suivi", variant_of="PRE-10", chrome={"appbar": "Dépôt", "glyph": "◉"}),

S("PRE-13", "Candidature — questions du client", "PRE", "Missions & Candidatures", "/prestataire/candidatures/:id/questions", "Prestataire", "P1", "Dialogue encadré",
  intent="Répondre aux questions d'un client avant sélection, sans donner ses coordonnées ni subir d'interrogatoire. "
         "Le cadre est posé : questions professionnelles uniquement.",
  zones=[
    Z("chat", "Questions & réponses", 5, "Fil structuré : question du client numérotée (Q1, Q2…), réponse du travailleur, horodatage. Questions hors cadre signalables."),
    Z("kpi", "Délai & effet", 3, "« Répondre sous 48 h augmente vos chances. » · « Vos réponses sont visibles uniquement par ce client. »"),
    Z("cta", "Répondre", 2, "« Envoyer ma réponse » or · « Signaler une question inappropriée » texte clay discret."),
  ],
  comps=[("Fil Q/R", "questions numérotées, réponses limitées à 800 c."),
         ("Signalement", "flux confidentiel, la question est gelée pendant l'examen"),
         ("Garde-fou", "filtre serveur : questions discriminatoires bloquées (« âge », « situation familiale »…)")],
  states=[("Question ouverte", "compte à rebours 48 h."),
          ("Répondu", "état clos, nouvelle question possible."),
          ("Question signalée", "gel de la question, examen humain (ADM)."),
          ("Non répondu (expiré)", "la candidature reste valide mais l'inaction est visible du client.")],
  motion=[("Nouvelle question", "insertion 240 ms + badge émeraude"),
          ("Envoi", "message qui se pose 240 ms spring soft, haptique light")],
  rules=["Aucune question ne peut porter sur une caractéristique protégée : le filtre serveur les bloque avant affichage.",
         "Les coordonnées sont filtrées dans les deux sens ; tout contournement volontaire est signalé à la modération.",
         "Le travailleur n'est jamais obligé de répondre : l'expiration n'entraîne aucune sanction de réputation."],
  tokens=["--emerald-500", "--clay-500", "--mono", "--glass-2"],
  api=["GET /v1/applications/:id/questions", "POST /v1/applications/:id/answers", "POST /v1/questions/:id/report"],
  tech="Même socle de messagerie encadrée que EMP-17/24 : filtrage serveur, horodatage, rétention liée à la mission.",
  canon="Candidature — questions & réponses", chrome=CHROME_PRE),

S("PRE-14", "Retirer une candidature", "PRE", "Missions & Candidatures", "/prestataire/candidatures/:id/retrait", "Prestataire", "P2", "Désengagement propre",
  intent="Se retirer proprement quand la situation a changé : motif facultatif, conséquences claires, aucune pénalité si c'est "
         "fait avant sélection. Le travailleur garde la maîtrise de son temps.",
  zones=[
    Z("form", "Motif de retrait", 4, "Motifs : mission finalement incompatible · autre engagement confirmé · distance · conditions modifiées · sans motif (possible). Champ libre 200 c."),
    Z("kpi", "Conséquences", 3, "« Avant sélection : aucune pénalité. » · « Après sélection : impact sur votre réputation de fiabilité. » — la règle est dite avant l'action."),
    Z("cta", "Confirmer", 2, "« Retirer ma candidature » clay outline · « Annuler » or (l'action de conservation en avant)."),
  ],
  comps=[("Radios de motif", "squircle, sélection or"),
         ("Règle affichée", "conséquence selon le moment du retrait")],
  states=[("Avant sélection", "avertissement neutre : aucune conséquence."),
          ("Après sélection", "avertissement clay + impact réputation expliqué, confirmation renforcée."),
          ("Retirée", "undo 10 s, candidature grisée réactivable.")],
  motion=[("Sheet", "montée 420 ms"),
          ("Retrait", "carte qui pâlit et rejoint les retirées"),
          ("Undo", "barre 10 s")],
  rules=["Retirer avant sélection n'a AUCUNE conséquence : le travailleur doit être libre de sa recherche.",
         "Retirer après sélection est possible mais impacte la réputation de fiabilité (gradation, jamais blocage immédiat).",
         "Le client est notifié immédiatement, sans motif détaillé si le travailleur n'en a pas donné."],
  tokens=["--clay-500", "--slate-500", "--surface-3"],
  api=["POST /v1/applications/:id/withdraw {reason?}", "GET /v1/applications/:id/withdraw-policy"],
  tech="Machine d'états de candidature + règle de réputation calculée côté serveur (politique versionnée).",
  canon="Candidature — retrait", chrome={"appbar": "Retrait", "glyph": "◉"}),

S("PRE-15", "Candidatures archivées", "PRE", "Missions & Candidatures", "/prestataire/candidatures/archive", "Prestataire", "P2", "Mémoire de recherche",
  intent="Conserver la trace de ses candidatures passées : utile pour comprendre ce qui marche, pour retrouver un client "
         "avec qui cela s'est bien passé, et pour réutiliser ses meilleurs messages.",
  zones=[
    Z("list", "Archive", 5, "Cartes compactes : mission, prix, issue (refusée, retirée, expirée), date. Filtre par catégorie et par issue."),
    Z("kpi", "Apprentissage", 3, "« Vos candidatures dans le BTP ont un taux de présélection de 34 % (contre 18 % en moyenne chez vous). »"),
    Z("cta", "Actions", 2, "« Réutiliser un message » · « Exporter mon historique de candidatures » (CSV, données personnelles)."),
  ],
  comps=[("Carte archivée", "désaturée, sobre"),
         ("Insights", "statistiques personnelles explicables"),
         ("Export CSV", "portabilité garantie")],
  states=[("Vide", "« Aucune archive pour l'instant. »"),
          ("Long", "pagination par mois, recherche plein texte sur les messages conservés."),
          ("Export", "génération asynchrone + lien signé")],
  motion=[("Chargement", "stagger 60 ms"),
          ("Filtres", "recomposition FLIP")],
  rules=["L'historique de candidatures appartient au travailleur : export toujours possible (portabilité).",
         "Les messages réutilisables sont stockés localement et côté serveur, jamais partagés avec des clients.",
         "Les refus ne sont pas assortis de notes (aucune donnée de jugement conservée)."],
  tokens=["--slate-500", "--emerald-500", "--mono"],
  api=["GET /v1/applications/archive", "GET /v1/applications/export.csv"],
  tech="Archive basée sur les candidatures clos depuis > 30 jours ; export asynchrone via job + R2 (URL signée 24 h).",
  canon="Candidatures — archive", chrome=CHROME_PRE),
]
