# -*- coding: utf-8 -*-
"""FAMILLE 03 · PRESTATAIRE — PRE-31 → PRE-45"""
from ..model import S, Z
from .pre_a import CHROME_PRE

SCREENS = [

S("PRE-31", "Validation d'exécution reçue", "PRE", "Exécution & Salaire", "/prestataire/missions/:id/validations", "Prestataire", "P1", "Travail reconnu",
  intent="Recevoir la reconnaissance du travail : quelle preuve a été validée, à quelle heure, et ce que cela déclenche "
         "concrètement (jalon franchi, montant acquis). Un moment de confirmation — sobre et digne.",
  zones=[
    Z("verdict", "Sceau de validation", 3, "Sceau émeraude « Preuve validée » + jalon concerné + horodatage Mono du client."),
    Z("list", "Effets immédiats", 4, "Trois lignes : jalon franchi (n/n) · montant acquis (prix prestataire, tnum) · prochaine échéance de salaire (date)."),
    Z("kpi", "Contexte", 3, "Si refus : le motif exact + conseil de correction + bouton redéposer. Si validation : la confidence du client (jamais publique) peut être affichée si elle existe."),
    Z("cta", "Suite", 1, "« Voir mon salaire » or · « Continuer la mission » fantôme."),
  ],
  comps=[("C-04 StatusSeal", "émeraude, une pulsation"),
         ("Ligne d'effet", "jalon / montant / échéance"),
         ("Encart de refus", "motif structuré + exemple de correction")],
  states=[("Validée", "émeraude, montant acquis mis à jour."),
          ("Validée avec réserve", "ambre : le client a validé mais signale un point mineur."),
          ("Refusée", "clay doux + motif obligatoire + chemin de correction."),
          ("Validation automatique", "si le client n'a pas répondu sous 72 h : validation tacite selon clause, tracée et affichée comme telle.")],
  motion=[("Sceau", "émeraude 480 ms + onde sur le jalon"),
          ("Montant", "compteur tnum qui se stabilise 240 ms")],
  rules=["La validation tacite (72 h sans réponse) est un droit du travailleur : elle est affichée comme telle et opposable.",
         "Un refus exige un motif structuré : impossible de refuser « en silence ».",
         "Le montant acquis ne peut jamais être réduit par un refus ultérieur : seules les preuves non validées restent en attente."],
  tokens=["--emerald-500", "--gold-500", "--clay-500", "--mono"],
  api=["GET /v1/missions/:id/validations", "POST /v1/evidence/:id/reupload"],
  tech="Événements de validation issus du flux d'exécution ; la validation tacite est un job serveur idempotent (72 h), "
       "jamais une règle du client.",
  canon="Exécution — validation reçue", chrome=CHROME_PRE),

S("PRE-32", "Paiement attendu (salaire)", "PRE", "Exécution & Salaire", "/prestataire/salaire", "Prestataire", "P0", "Mon argent",
  intent="L'écran le plus important du travailleur : ce qu'on me doit, ce qui va tomber, quand. Le prix prestataire domine, "
         "les mécanismes sont expliqués, et aucune ligne n'est opaque.",
  zones=[
    Z("price", "Revenu en tête", 6, "« Vous recevrez 250 000 F » en --display-1 or + répartition par mission + échéancier : 40 % déjà dû (100 000 F) · 60 % à la validation finale (150 000 F)."),
    Z("timeline", "Calendrier des versements", 4, "Chaque versement attendu : montant, mission, origine (échéance contractuelle / validation), date prévue, état (à venir, déclaré par le client, vérifié, à confirmer par OTP, reçu)."),
    Z("list", "Mécanismes expliqués", 3, "Trois cartes : comment le client paie (plateforme ou déclaration externe) · pourquoi l'OTP existe (preuve de réception) · ce qui se passe en cas de retard (relance automatique + intérêts éventuels)."),
    Z("cta", "Actions", 1, "« Voir le détail d'un versement » or · « Signaler un paiement non reçu » fantôme."),
  ],
  comps=[("C-05 PriceBreakdown", "variante prestataire : une seule ligne de valeur (mon prix)"),
         ("C-06 TimelineTrack", "versements datés"),
         ("Badge OTP attendu", "émeraude pulse si l'action est requise"),
         ("Carte d'explication", "pédagogie financière, pas de jargon")],
  states=[("À venir", "dates et états clairs."),
          ("Déclaré par le client", "ambre : « le client déclare vous avoir payé — confirmez la réception » (action)."),
          ("En vérification", "violet : contrôle de la déclaration en cours."),
          ("OTP attendu", "émeraude pulsé : action requise du travailleur (confirmer la réception)."),
          ("Reçu", "émeraude pleine + reçu téléchargeable."),
          ("En retard", "clay : montant, jours de retard, relance automatique déjà effectuée.")],
  motion=[("Entrée", "revenu d'abord (420 ms), puis calendrier"),
          ("OTP attendu", "pulsation émeraude 2 400 ms jusqu'à action — jamais plus d'une ligne pulsée"),
          ("Réception", "sceau émeraude + onde, haptique heavy")],
  rules=["INV-4 : la réception du salaire est acquise après OTP confirmé ; avant cela l'échéance reste ouverte, jamais « payée ».",
         "Le travailleur ne paie jamais de frais : aucune déduction sur le prix prestataire, en aucun cas.",
         "Le retard de paiement déclenche automatiquement une relance côté plateforme ; le travailleur n'a rien à faire."],
  tokens=["--display-1", "--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/payments?role=provider&state=pending", "GET /v1/payments/expected", "POST /v1/payments/:id/dispute-not-received"],
  tech="Vue financière prestataire construite sur le ledger (append-only) avec projection par rôle : le travailleur ne voit "
       "que ses montants, jamais les frais SaaS ni le total client.",
  canon="Salaire — attendu & échéances", chrome=CHROME_PRE),

S("PRE-33", "Échéances de salaire", "PRE", "Exécution & Salaire", "/prestataire/salaire/echeances", "Prestataire", "P1", "Calendrier personnel",
  intent="Le calendrier précis de ses versements, semaine par semaine, avec les jalons qui les déclenchent. Le travailleur "
         "peut planifier son mois — un besoin vital.",
  zones=[
    Z("timeline", "Calendrier", 5, "Groupé par semaine : versement, montant (tnum), mission, condition de déclenchement (« après validation du jalon 2 »), état."),
    Z("kpi", "Totaux", 3, "Encaissé ce mois · attendu ce mois · en retard (clay). Projection à 30 jours (indicative, basée sur les contrats signés)."),
    Z("cta", "Actions", 1, "« Voir une échéance » or outline · « Toujours prévenir avant versement » (notification opt-in) fantôme."),
  ],
  comps=[("Ligne d'échéance", "montant + condition"),
         ("Totaux", "tnum, cadres sobres"),
         ("Badge de condition", "« condition remplie » / « en attente de validation »")],
  states=[("Normal", "calendrier peuplé."),
          ("Retard", "lignes clay en tête avec compteur de jours."),
          ("Gros mois", "si > 3 versements : récapitulatif en tête."),
          ("Aucun contrat", "état vide + lien vers les missions disponibles.")],
  motion=[("Défilement", "en-têtes de semaine collants (verre 3)"),
          ("Retard", "ligne qui glisse en tête avec fade")],
  rules=["Aucune projection ne masque un retard existant : le futur et le problème sont affichés ensemble.",
         "La condition de déclenchement est toujours citée : le travailleur sait exactement ce qui doit arriver.",
         "Les montants sont en prix prestataire net, sans déduction possible."],
  tokens=["--gold-500", "--clay-500", "--emerald-500", "--mono"],
  api=["GET /v1/payments/schedules?role=provider", "GET /v1/payments/projection?days=30"],
  tech="Moteur de calendrier partagé avec EMP-41 (règles d'échéances) ; projection calculée serveur, jamais estimée côté client.",
  canon="Salaire — attendu & échéances", variant_of="PRE-32", chrome=CHROME_PRE),

S("PRE-34", "Salaire déclaré par le client", "PRE", "Exécution & Salaire", "/prestataire/salaire/:id/declare", "Prestataire", "P0", "Confirmer ou contester",
  intent="Le client déclare avoir payé (souvent hors plateforme) : le travailleur doit confirmer ou contester. C'est un "
         "point de bascule anti-fraude — l'écran est clair sur les conséquences de chaque choix.",
  zones=[
    Z("hero", "Déclaration du client", 4, "Carte : montant déclaré (prix prestataire, or), date, moyen (mobile money, espèces, virement), référence de transaction, pièce jointe du client."),
    Z("list", "Ce qui est attendu de moi", 4, "« Confirmer que vous avez bien reçu cet argent » ou « Contester si vous n'avez rien reçu ». Délai : 72 h. Conséquences affichées : confirmation → clôture de l'échéance ; contestation → dossier de réconciliation (ADM-18)."),
    Z("kpi", "Preuve requise", 3, "« Si vous confirmez, votre confirmation devient la preuve (horodatée). » · « Ne confirmez jamais sans avoir vérifié votre compte. » — avertissement anti-fraude explicite."),
    Z("cta", "Décider", 2, "« J'ai bien reçu cet argent » émeraude · « Je n'ai rien reçu » clay outline (double confirmation)."),
  ],
  comps=[("Carte de déclaration", "montant + moyen + référence"),
         ("Double confirmation de contestation", "saisie du montant pour éviter l'erreur de clic"),
         ("C-11 DocumentCardR2", "pièce jointe du client (capture/reçu)"),
         ("Bandeau anti-fraude", "rappels: vérifier le compte réel, jamais de confirmation de courtoisie")],
  states=[("À confirmer", "action requise, 72 h, notification prioritaire."),
          ("Confirmée", "émeraude, échéance clôturée, reçu généré."),
          ("Contestée", "clay, dossier de réconciliation ouvert (n° de dossier affiché), protection du travailleur engagée."),
          ("Expirée (72 h)", "la plateforme escalade automatiquement en vérification (déclaration non confirmée = doute).")],
  motion=[("Confirmation", "sceau émeraude + onde, haptique heavy"),
          ("Contestation", "sceau clay, haptique rigid, dossier créé en 480 ms"),
          ("À confirmer", "pulsation émeraude douce 2 400 ms")],
  rules=["Une confirmation vaut preuve : l'écran l'annonce explicitement, et le texte du bouton est sans ambiguïté (« J'ai bien reçu cet argent »).",
         "Une contestation fausse et répétée expose à une revue de compte (protection du système contre la fraude inverse).",
         "Aucune confirmation tacite : l'absence de réponse escalade vers une vérification humaine, jamais vers un « payé » implicite."],
  tokens=["--emerald-500", "--clay-500", "--gold-500", "--mono", "--glass-3"],
  api=["GET /v1/payments/:id/external-claim", "POST /v1/payments/:id/external-claim/confirm", "POST /v1/payments/:id/external-claim/contest"],
  tech="Circuit à trois états (claim → confirm/contest → reconcile) avec service de réconciliation côté ADM-18. Toutes les "
       "actions sont idempotentes et horodatées serveur.",
  canon="Salaire — déclaré par le client", chrome=CHROME_PRE),

S("PRE-35", "Vérification d'un paiement déclaré", "PRE", "Exécution & Salaire", "/prestataire/salaire/:id/verification", "Prestataire", "P1", "Contrôle en cours",
  intent="Après contestation, montrer ce qui se passe : le dossier est entre les mains de la réconciliation, voici les "
         "étapes, les délais, et ce qui me protège. Le travailleur n'est jamais laissé sans nouvelles.",
  zones=[
    Z("timeline", "Procédure", 4, "Déclaration client → contestation prestataire → vérification croisée (relevés, pièces) → décision → exécution. Auteur et horodatage de chaque étape."),
    Z("list", "Ce qui est examiné", 4, "Pièces du client (captures, références) · cohérence des horodatages · éventuels relevés de plateforme de paiement · historique du client (récurrence)."),
    Z("kpi", "Mes protections", 3, "« Pendant la vérification, l'échéance n'est ni payée ni annulée. » · « Vous ne pouvez pas être pénalisé pour une contestation légitime. » · Délai : 5 jours ouvrés."),
    Z("cta", "Actions", 1, "« Ajouter une pièce » or outline (relevé de compte, capture) · « Voir le dossier » fantôme."),
  ],
  comps=[("C-06 TimelineTrack", "procédure de réconciliation"),
         ("Carte de protections", "droits du travailleur affichés"),
         ("Zone d'ajout de pièces", "relevés bancaires/mobile money, captures")],
  states=[("Instruction", "compte à rebours des 5 jours."),
          ("Pièce demandée", "action prioritaire, 48 h pour répondre."),
          ("Décision : fondée", "paiement confirmé, clôture, éventuel signalement du client."),
          ("Décision : non fondée", "clay : le montant reste dû, le client est en défaut (impact réputation client)."),
          ("Fraude établie", "dossier transmis, compte client bloqué (PUB-09), priorité de paiement pour le travailleur.")],
  motion=[("Étapes", "progression tracée 420 ms"),
          ("Décision", "bascule sobre (ce n'est pas une victoire, c'est une régularisation)")],
  rules=["Une contestation légitime ne peut jamais nuire au travailleur : c'est un principe affiché.",
         "L'échéance reste ouverte et protégée pendant toute la vérification (jamais requalifiée en « payée »).",
         "En cas de fraude établie, LE LABEUR indemnise le travailleur selon sa politique de garantie (documentée publiquement)."],
  tokens=["--violet-500", "--clay-500", "--emerald-500", "--mono"],
  api=["GET /v1/reconciliations/:id/provider-view", "POST /v1/reconciliations/:id/evidence"],
  tech="Dossier de réconciliation partagé avec ADM-18 ; projection prestataire limitée (pas de données clients sensibles).",
  canon="Salaire — vérification & réconciliation", chrome=CHROME_PRE),

S("PRE-36", "Alerte : salaire en retard", "PRE", "Exécution & Salaire", "/prestataire/salaire/retard", "Prestataire", "P0", "Le retard, traité",
  intent="Quand un paiement est en retard : dire les faits, dire ce que la plateforme fait déjà (relance automatique), dire "
         "ce que le travailleur peut faire, et dire ce qui arrive au client. Le travailleur n'est jamais seul face à l'impayé.",
  zones=[
    Z("hero", "État du retard", 4, "Sceau clay + montant dû (--display-2, or barré d'un trait clay) + jours de retard (Mono) + mission & client concernés."),
    Z("timeline", "Actions déjà engagées", 4, "Frise : rappel automatique J+1 ✓ · relance formelle J+3 ✓ · notification d'impact réputation client J+5 ✓ · escalade modération J+7 ◔. La plateforme agit — visiblement."),
    Z("kpi", "Mes options", 3, "« Signaler un paiement non reçu » · « Demander une médiation » · « Continuer la mission ? » (choix explicite : poursuivre ou suspendre, droits affichés)."),
    Z("cta", "Actions", 2, "« Demander la médiation » or · « Suspendre ma prestation » clay outline (droit de suspension légitime) · « Voir le client » fantôme."),
  ],
  comps=[("Compteur de retard", "Mono, jours calendaires"),
         ("Frise d'escalade", "étapes automatiques horodatées"),
         ("Droit de suspension", "expliqué : suspension légitime sans pénalité après J+5"),
         ("Impact client affiché", "réputation, blocage possible — le travailleur voit la contre-pression du système")],
  states=[("J+1 à J+3", "relance automatique en cours."),
          ("J+4 à J+7", "escalade, médiation proposée."),
          ("J+8 et plus", "impact réputation client appliqué, blocage de nouvelles missions possible pour le client."),
          ("Résolu", "émeraude : paiement reçu, dossier clos, historique conservé.")],
  motion=[("Apparition", "sceau clay, puis frise qui se trace"),
          ("Résolution", "barré clay qui se remplace par émeraude, haptique heavy"),
          ("Retard qui s'aggrave", "compteur qui avance visiblement à chaque jour")],
  rules=["Le retard de paiement est un manquement grave : la plateforme applique une contre-pression automatique (réputation, blocage) sans que le travailleur ait à la demander.",
         "Le droit de suspension de la prestation après J+5 est légitime et sans pénalité contractuelle (clause dédiée).",
         "Aucun intérêt de retard ne profite à LE LABEUR : tout intérêt éventuel est versé au travailleur."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono", "--display-2"],
  api=["GET /v1/payments/overdue?provider=me", "POST /v1/disputes {type: non-payment}", "POST /v1/contracts/:id/suspend"],
  tech="Moteur de relance automatique (jobs cron, cadence J+1/J+3/J+5/J+7) avec journalisation ; l'escalade modération crée "
       "une tâche prioritaire (ADM-18/26).",
  canon="Salaire — retard & relance", chrome=CHROME_PRE),

S("PRE-37", "Relance & contestation de paiement", "PRE", "Exécution & Salaire", "/prestataire/salaire/:id/relance", "Prestataire", "P1", "Voix du travailleur",
  intent="Formuler une contestation structurée quand l'argent n'arrive pas : faits, preuves, demande précise. L'écran "
         "transforme la colère légitime en dossier solide.",
  zones=[
    Z("form", "Objet de la contestation", 4, "Type : salaire non reçu · montant incorrect · échéance non déclenchée alors que le jalon est validé · déclaration client erronée. Montant contesté (tnum)."),
    Z("list", "Preuves utiles", 4, "Relevé de compte (période), capture de la plateforme de paiement, historique de versements, validation du jalon concerné (lien direct)."),
    Z("chat", "Message structuré", 3, "Faits chronologiques guidés (quoi, quand, quoi reçu, quoi attendu) — gabarit proposé, ton professionnel."),
    Z("cta", "Envoyer", 2, "« Soumettre la contestation » or · « Annuler » fantôme."),
  ],
  comps=[("Formulaire typé", "radios + montant + faits"),
         ("Sélecteur de preuves", "pièces existantes + ajout"),
         ("Gabarat de message", "structure factuelle recommandée"),
         ("Bandeau de délais", "réponse sous 5 jours ouvrés")],
  states=[("Prête", "CTA armé si faits + montant présents."),
          ("Soumise", "dossier créé (n° Mono), suivi disponible (PRE-35)."),
          ("Irrecevable", "si la contestation concerne un montant non dû : explication factuelle, pas de rejet sec."),
          ("Résolue", "paiement reçu / correction appliquée, dossier clos avec récap.")],
  motion=[("Envoi", "sceau or outline, haptique medium"),
          ("Résolution", "bascule émeraude sobre")],
  rules=["Toute contestation reçoit une réponse chiffrée et écrite : jamais de rejet sans explication.",
         "Le travailleur peut contester même si la mission est terminée : les délais de contestation courent à partir de l'échéance impayée (2 ans).",
         "Aucune conséquence de réputation pour une contestation de paiement légitime."],
  tokens=["--clay-500", "--gold-500", "--mono", "--glass-2"],
  api=["POST /v1/payments/:id/contests", "GET /v1/payments/:id/contests"],
  tech="Dossier de contestation lié au ledger ; les jobs SLA surveillent la réponse sous 5 jours ouvrés.",
  canon="Salaire — retard & relance", variant_of="PRE-36", chrome=CHROME_PRE),

S("PRE-38", "OTP — confirmation de réception du salaire", "PRE", "Exécution & Salaire", "/prestataire/salaire/:id/otp", "Prestataire", "P0", "Le sceau de réception",
  intent="L'écran le plus solennel du produit côté travailleur : confirmer la réception du salaire par un code à 6 chiffres. "
         "Cette confirmation est une preuve (INV-4) — elle clôt l'échéance et protège les deux parties.",
  zones=[
    Z("hero", "Contexte de la confirmation", 3, "Montant reçu (--display-1 or), mission, échéance concernée, moyen de paiement réel (mobile money / compte). « Confirmez que vous avez bien reçu cet argent. »"),
    Z("form", "Champ OTP 6 cases", 4, "Saisie auto-avance, autofill SMS/email natif, chiffres Mono 28 px, refus du collage partiel invalide. Code reçu par SMS sur le numéro vérifié."),
    Z("sign", "Scellement de la preuve", 3, "Après validation : empreinte de preuve 12 caractères (Mono, copiable), horodatage serveur, mention « cette confirmation vaut preuve de paiement (INV-4) »."),
    Z("cta", "Valider", 2, "« Confirmer la réception » émeraude (armé à 6 chiffres) · « Je n'ai pas reçu le code » fantôme (renvoi, puis support) · « Contester » texte clay."),
  ],
  comps=[("C-07 OTPField", "6 cases squircle, caret or, auto-submit"),
         ("C-04 StatusSeal", "émeraude pleine à la validation + empreinte 12 c."),
         ("Encart de lourdeur", "explique ce que la confirmation emporte (preuve, clôture, anti-fraude)"),
         ("Compte à rebours", "validité du code 10 min, renvoi possible après 45 s")],
  states=[("Saisie", "cases se remplissent, haptique light par chiffre."),
          ("Code incorrect", "6 cases vibrent, compteur d'essais (3/5), message non divulgatif."),
          ("Code expiré", "cases vidées en cascade, renvoi proposé."),
          ("Confirmé", "sceau émeraude plein écran 640 ms, empreinte affichée 3 s, haptique heavy, reçu généré."),
          ("Contestation", "si le travailleur n'a rien reçu : bascule vers PRE-36 (retard) ou PRE-34 (déclaration).")],
  motion=[("Validation", "expansion du sceau depuis le centre du champ, halo émeraude 0.14 → 0 sur 2 400 ms"),
          ("Erreur", "shake synchronisé des 6 cases 120 ms"),
          ("Empreinte", "caractères révélés un à un 40 ms — moment cérémoniel")],
  rules=["INV-4 : l'échéance n'est « payée » qu'après cette confirmation. Aucun raccourci, aucune validation par défaut.",
         "Le code n'est jamais affiché, jamais journalisé en clair, et expire en 10 minutes (usage unique).",
         "Le travailleur ne doit JAMAIS confirmer par courtoisie : l'écran le dit explicitement avant saisie.",
         "En cas d'erreur de confirmation, la correction passe par une contestation tracée (jamais par une suppression silencieuse)."],
  tokens=["--emerald-500", "--grad-emerald", "--gold-500", "--mono", "--glass-4"],
  api=["POST /v1/payments/:id/salary-otp/request", "POST /v1/payments/:id/salary-otp/verify", "GET /v1/payments/:id/proof"],
  tech="OTP dédié (distinct de l'OTP d'authentification) : portée limitée à l'échéance, HMAC côté serveur, anti-rejeu, "
       "journal d'audit. La preuve générée est signée et stockée au ledger.",
  a11y=["Chaque case est annoncée « chiffre n sur 6 » ; la validation est annoncée avec l'empreinte de preuve lue par segments."],
  canon="Salaire — OTP de réception", chrome={"appbar": "Confirmation", "glyph": "◉"}),

S("PRE-39", "Reçu de salaire & preuve", "PRE", "Exécution & Salaire", "/prestataire/salaire/:id/recu", "Prestataire", "P1", "Mon dû, scellé",
  intent="Le document que le travailleur garde : montant reçu, mission, période, référence, empreinte, QR de vérification. "
         "Utile pour soi, pour un employeur, pour un dossier de crédit.",
  zones=[
    Z("doc", "Reçu de salaire", 5, "Document : nom du travailleur, mission (réf Mono), client (nom ou raison sociale), montant reçu (prix prestataire), période, moyen, date de versement, référence de transaction."),
    Z("sign", "Preuve", 3, "Empreinte SHA-256 (Mono copiable) · QR de vérification publique · mention de la confirmation OTP (empreinte 12 c.)."),
    Z("cta", "Diffusion", 2, "« Télécharger le PDF » or outline · « Attestation de revenus » (document séparé, cumul sur 12 mois) fantôme."),
  ],
  comps=[("Document A4", "impression propre"),
         ("Attestation de revenus", "agrégat annuel, généré à la demande, signé"),
         ("QR", "vérification publique sans données personnelles")],
  states=[("Émis", "disponible dès la confirmation OTP ou la validation de la déclaration."),
          ("Régularisé", "si un ajustement a eu lieu : nouveau reçu référençant l'ancien."),
          ("Annulé", "cas de fraude avérée : mention explicite + ligne négative au ledger.")],
  motion=[("Émission", "sceau émeraude → or, 480 ms"),
          ("Attestation", "génération asynchrone avec notification")],
  rules=["Le reçu ne mentionne JAMAIS le total client ni les frais SaaS : il documente la rémunération du travailleur, rien d'autre.",
         "L'attestation de revenus est un droit : elle est générée gratuitement, sans condition, sur 12 mois glissants.",
         "Les documents sont conservés 10 ans (obligations sociales et fiscales)."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--glass-1"],
  api=["GET /v1/payments/:id/receipt.pdf", "GET /v1/provider/income-statement.pdf?year="],
  tech="PDF/A généré serveur, R2 avec object lock, QR pointant vers /verify/:token (public, sans donnée personnelle).",
  canon="Salaire — reçu & preuve (prestataire)", chrome=CHROME_PRE),

S("PRE-40", "Remplacement — notification", "PRE", "Remplacement & Réputation", "/prestataire/missions/:id/remplacement", "Prestataire", "P0", "Être remplacé",
  intent="Apprendre qu'on est remplacé — ou qu'on doit l'être — avec dignité : les faits, les droits, et l'argent dû pour "
         "le travail déjà réalisé. Un écran dur, mais jamais humiliant.",
  zones=[
    Z("hero", "Notification du remplacement", 4, "« Vous êtes remplacé sur cette mission » ou « Vous demandez un remplacement » (selon l'auteur). Faits datés, cause catégorisée, ton neutre et factuel."),
    Z("price", "Ce qui vous est dû", 4, "Décompte du travail validé : jalons × montants, total à recevoir (prix prestataire, or), date de versement, procédure OTP rappelée."),
    Z("kpi", "Vos droits", 3, "« Contester la cause sous 72 h » · « Les preuves du travail validé vous restent attachées » · « Votre réputation n'est impactée que si la faute est établie — la procédure le dira »."),
    Z("cta", "Actions", 2, "« Contester la cause » clay outline · « Accepter et clôturer ma part » or · « Voir le décompte » fantôme."),
  ],
  comps=[("Carte de décompte", "lignes explicites"),
         ("Bandeau de droits", "contestation, preuves, réputation"),
         ("Sceau de transition", "or inversé, sobre"),
         ("C-11 DocumentCardR2", "preuves du travail validé")],
  states=[("À votre initiative", "le travailleur déclenche : ton neutre, procédure de sortie propre."),
          ("À l'initiative du client — faute alléguée", "clay : procédure contradictoire, droit de réponse 72 h."),
          ("À l'initiative du client — accord mutuel", "émeraude atténué : sortie amiable, paiement sous 5 jours."),
          ("Force majeure", "ardoise : constat, aucune faute de part et d'autre."),
          ("Contestée", "dossier de médiation ouvert, paiement du travail validé restant dû.")],
  motion=[("Apparition", "sceau or inversé 640 ms, aucune animation punitive"),
          ("Décompte", "lignes révélées une à une 120 ms"),
          ("Contestation", "formulaire qui se déplie 240 ms")],
  rules=["Le travail validé est payé même en cas de remplacement pour faute : la sanction ne peut porter que sur le travail non réalisé.",
         "Aucune écriture de réputation n'est appliquée avant la fin de la procédure contradictoire (72 h minimum).",
         "Le travailleur conserve l'accès à ses preuves et à son historique de mission après le remplacement."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono"],
  api=["GET /v1/replacements/:id/provider-view", "POST /v1/replacements/:id/contest", "POST /v1/replacements/:id/accept"],
  tech="Même dossier de remplacement que EMP-56, projection prestataire (montants dus uniquement, motifs complets).",
  canon="Remplacement — notification & droits", chrome=CHROME_PRE),

S("PRE-41", "Remplacement — conditions & reprise", "PRE", "Remplacement & Réputation", "/prestataire/missions/:id/remplacement/conditions", "Prestataire", "P1", "Passer la main",
  intent="Organiser la passation de son propre travail : ce qui est repris par le successeur, ce qui reste le sien, ce qui "
         "doit être expliqué. Le travailleur sortant garde la maîtrise de son savoir-faire.",
  zones=[
    Z("list", "Inventaire de passation", 5, "Travail validé (avec preuves) · travail en cours (état exact, ce qui reste) · éléments à transmettre (documents, accès, contacts) · éléments qui ne sont PAS transmis (méthodes personnelles, savoir-faire non contractualisé)."),
    Z("kpi", "Périmètre de transmission", 3, "« Vous n'êtes pas obligé de transmettre vos méthodes personnelles. » · « Les documents du client doivent être rendus (obligation légale). »"),
    Z("cta", "Actions", 2, "« Valider la passation » or · « Signaler un bien manquant » fantôme (outil fourni par le client, matériel)."),
  ],
  comps=[("Inventaire à trois colonnes", "validé / en cours / à transmettre"),
         ("Distinction stricte", "propriété du travailleur vs propriété du client"),
         ("Checklist de transmission", "cocher au fur et à mesure")],
  states=[("À préparer", "inventaire initial."),
          ("En cours", "checklist partiellement cochée."),
          ("Validée", "émeraude, le remplaçant prend le relais, paiement du sortant déclenché."),
          ("Litige sur matériel/documents", "dossier médiation lié.")],
  motion=[("Transmission", "lignes qui passent émeraude au cochage"),
          ("Validation", "sceau émeraude + onde")],
  rules=["Le savoir-faire personnel non contractualisé n'est jamais transmissible : la distinction est affichée explicitement.",
         "Les documents et données du client doivent être restitués : le système les révoque automatiquement à la clôture de la passation.",
         "La passation validée déclenche le paiement du travail validé sans délai supplémentaire."],
  tokens=["--emerald-500", "--slate-500", "--gold-500", "--mono"],
  api=["GET /v1/replacements/:id/handover/provider", "POST /v1/replacements/:id/handover/ack"],
  tech="Dossier de passation partagé (EMP-56) ; les accès révoqués sont appliqués côté serveur dès la signature de la passation.",
  canon="Remplacement — transition & sortie", chrome=CHROME_PRE),

S("PRE-42", "Remplacement — acceptation ou contestation", "PRE", "Remplacement & Réputation", "/prestataire/remplacements/:id/decision", "Prestataire", "P0", "Se défendre ou accepter",
  intent="Un espace propre pour répondre à une décision grave : accepter les faits, contester avec preuves, ou demander la "
         "médiation. Chaque voie est clairement décrite avec ses conséquences.",
  zones=[
    Z("form", "Trois voies", 4, "J'accepte le remplacement et la cause · Je conteste la cause (faits nouveaux, preuves) · Je demande la médiation (désaccord sur l'interprétation du contrat)."),
    Z("doc", "Pièces à l'appui", 4, "Preuves du travail réalisé, échanges avec le client, preuves d'obstacles signalés, validations acquises. Sélection depuis le dossier mission."),
    Z("kpi", "Ce que chaque voie implique", 3, "Accepter → clôture rapide, paiement du validé, réputation impactée seulement si faute reconnue · Contester → instruction humaine 5 jours · Médiation → proposition de sortie mutuelle."),
    Z("cta", "Décider", 2, "« Envoyer ma décision » or · « Annuler » fantôme."),
  ],
  comps=[("Radios de voie", "descriptions complètes, pas de piège"),
         ("Sélecteur de preuves", "pièces du dossier"),
         ("Compte à rebours", "72 h affichées")],
  states=[("À décider", "compte à rebours actif."),
          ("Accepté", "clôture, décompte appliqué."),
          ("Contesté", "instruction humaine, paiement du validé protégé."),
          ("Médiation", "proposition mutuelle sous 3 jours."),
          ("Expiré", "l'acceptation tacite de la cause est actée — signalée clairement 12 h avant.")],
  motion=[("Sélection de voie", "carte qui se soulève, description qui se déplie 240 ms"),
          ("Envoi", "sceau or outline, haptique medium")],
  rules=["L'expiration à 72 h entraîne l'acceptation de la cause : avertissement explicite à J-12 h (jamais de piège).",
         "La contestation protège le paiement du travail validé : il n'est jamais conditionné à l'issue de la procédure.",
         "Le travailleur peut être accompagné : commande de pièces, explication des clauses, jamais d'avocat interne mais un service d'explication gratuit."],
  tokens=["--clay-500", "--emerald-500", "--amber-500", "--mono"],
  api=["POST /v1/replacements/:id/decision {choice, evidenceIds, statement}", "GET /v1/replacements/:id/deadline"],
  tech="Machine d'états de contestation avec SLA serveur ; l'expiration déclenche la transition (job idempotent) après double "
       "notification (J-12 h, J-2 h).",
  canon="Remplacement — décision prestataire", chrome=CHROME_PRE),

S("PRE-43", "Remplacement — transition & sortie", "PRE", "Remplacement & Réputation", "/prestataire/remplacements/:id/transition", "Prestataire", "P1", "Sortie organisée",
  intent="Organiser la sortie concrète : ce que je dois rendre, ce qu'on doit me payer, ce que je garde. Une sortie nette "
         "évite les conflits futurs.",
  zones=[
    Z("timeline", "Étapes de sortie", 4, "Passation validée → restitution des accès (automatique) → décompte final → paiement → clôture. Horodatages Mono."),
    Z("list", "Checklist de sortie", 4, "Rendre les documents du client ✓ (automatique) · Restituer le matériel éventuel (si fourni) · Confirmer l'absence de copie de données · Clôturer les accès aux plateformes du client."),
    Z("price", "Décompte final", 3, "Montant validé + éventuel prorata (travail en cours accepté par le client) + date de versement. Prix prestataire uniquement."),
    Z("cta", "Actions", 2, "« Valider ma sortie » or · « Déclarer un bien non restitué de mon côté » cliff (transparence) · « Voir mes preuves » fantôme."),
  ],
  comps=[("C-06 TimelineTrack", "sortie orchestrée"),
         ("Checklist d'actions", "cochable, certaines automatiques (tracées)"),
         ("Table de décompte", "montants explicites")],
  states=[("En cours", "étapes progressives."),
          ("Paiement en attente", "montant dû + date, relance automatique si retard."),
          ("Clôturée", "émeraude, dossier archivé, empreinte finale."),
          ("Litige de sortie", "clay : matériel non restitué ou décompte contesté → médiation.")],
  motion=[("Progression", "points de sortie qui s'allument 420 ms"),
          ("Clôture", "sceau émeraude sobre")],
  rules=["La restitution des accès est automatique et immédiate : aucune dépendance à la bonne volonté des parties.",
         "La sortie n'est jamais conditionnée à la signature d'un document de non-concurrence non prévu au contrat.",
         "Le décompte final est versé selon les mêmes règles que tout paiement (OTP de réception)."],
  tokens=["--emerald-500", "--slate-500", "--gold-500", "--mono"],
  api=["GET /v1/replacements/:id/exit/provider", "POST /v1/replacements/:id/exit/ack", "POST /v1/replacements/:id/asset-report"],
  tech="Orchestrateur de sortie : révocations (accès, clés, partages), calcul final, génération du reçu, archivage du dossier.",
  canon="Remplacement — transition & sortie", variant_of="PRE-41", chrome=CHROME_PRE),

S("PRE-44", "Remplacement — reprise d'un travail (vue entrant)", "PRE", "Remplacement & Réputation", "/prestataire/remplacements/:id/reprise", "Prestataire", "P1", "Reprendre un chantier",
  intent="Quand on est le remplaçant : voir exactement ce qu'on reprend, dans quel état, et à quelles conditions. Le "
         "travailleur ne doit jamais accepter une reprise à l'aveugle.",
  zones=[
    Z("hero", "Contexte de la reprise", 3, "Mission, client, raison du remplacement (transparence), état du travail (validé / en cours / restant), contraintes de délai."),
    Z("list", "Ce que je reprends", 5, "Périmètre restant défini par exclusion (jalons validés non repris, avec preuves) · livrables attendus · preuves déjà acceptées · risques identifiés (accès au site, matériel, délais courts)."),
    Z("price", "Mes conditions", 4, "Prix proposé pour le périmètre restant, échéancier recalé, éventuel ajustement lié à la reprise. Le prix est affiché sans jugement comparatif."),
    Z("cta", "Décider", 2, "« Accepter la reprise » or · « Demander un ajustement » fantôme · « Refuser » texte (sans pénalité)."),
  ],
  comps=[("Tableau d'état du travail", "validé / en cours / restant avec preuves"),
         ("Carte de risques", "liste factuelle, pas de dissuasion"),
         ("Bandeau de transparence", "motif du remplacement affiché (accord mutuel, défaillance, force majeure)")],
  states=[("Prête", "informations complètes, CTA or."),
          ("Dossier incomplet", "certains éléments manquants (preuves, inventaire) : signalés, décision informée."),
          ("Refusée", "aucune pénalité, la proposition part au candidat suivant."),
          ("Acceptée", "contrat de reprise généré (PRÉ-voir EMP-60 côté client).")],
  motion=[("Entrée", "état du travail révélé en premier, prix ensuite"),
          ("Acceptation", "sceau or + génération du contrat")],
  rules=["Le remplaçant voit la raison réelle du remplacement : travailler sur un dossier qu'on croit sain serait une tromperie.",
         "Le périmètre est défini par exclusion, jamais par approximation : aucun double paiement possible.",
         "Refuser une reprise n'a aucune conséquence de réputation."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/replacements/:id/reprise/provider-view", "POST /v1/replacements/:id/reprise/accept", "POST /v1/replacements/:id/reprise/negotiate"],
  tech="Vue dédiée du dossier de remplacement pour le candidat entrant, avec projection du périmètre par soustraction des "
       "jalons validés (même moteur que le contrat successeur EMP-60).",
  canon="Remplacement — reprise (entrant)", chrome=CHROME_PRE),

S("PRE-45", "Ma réputation — synthèse", "PRE", "Remplacement & Réputation", "/prestataire/reputation", "Prestataire", "P0", "Ce que le travail a construit",
  intent="Montrer sa réputation professionnelle comme un actif : score, composantes explicables, tendance, et ce qu'il faut "
         "faire pour l'améliorer. Jamais de score opaque ni de mystère.",
  zones=[
    Z("ring", "Score de réputation", 4, "Anneau principal 0-100 + décomposition : fiabilité de délais (35 %), qualité des preuves (20 %), satisfaction client (25 %), litiges (20 %). Chaque composante avec sa note et sa méthode."),
    Z("kpi", "Chiffres de carrière", 4, "Missions menées · taux de validation au premier dépôt · clients récurrents · délai moyen de réponse. Tous tnum, tous sourcés."),
    Z("timeline", "Tendance", 3, "Évolution sur 12 mois (courbe sobre) + événements marquants (missions réussies, corrections, contestations gagnées)."),
    Z("cta", "Actions", 1, "« Comment améliorer mon score » (conseils actionnables) · « Voir le ledger complet » (PRE-46)."),
  ],
  comps=[("C-10 MatchScoreRing", "variante réputation, décomposition obligatoire"),
         ("Courbe de tendance", "or, événements en points cliquables"),
         ("Carte de méthode", "comment chaque composante est calculée, avec fenêtre temporelle")],
  states=[("Nouveau profil", "score absent : « pas encore de réputation — voici comment la construire » (jamais un score 0 pénalisant)."),
          ("Établi", "score + tendance."),
          ("En baisse", "explication automatique des causes (retard, refus, litiges) + plan d'action."),
          ("Exemplaire", "badge émeraude « fiabilité vérifiée » avec critères publics.")],
  motion=[("Anneau", "remplissage 640 ms à l'ouverture, une seule fois"),
          ("Tendance", "courbe qui se trace 420 ms"),
          ("Événement", "point qui pulse au survol, infobulle verre 3")],
  rules=["INV-5 : la réputation est un ledger append-only ; toute correction est une écriture compensatoire visible, jamais une suppression.",
         "Un travailleur sans historique n'a jamais de score négatif : l'absence de note n'est pas une mauvaise note.",
         "Les critères de calcul sont publics et stables : tout changement de formule est annoncé et rétroactif de façon transparente."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--glass-2"],
  api=["GET /v1/reputation/me", "GET /v1/reputation/me/breakdown", "GET /v1/reputation/methodology (public)"],
  tech="Calcul par service de réputation à partir du ledger (événements de contrats, validations, litiges). Versionné : "
       "chaque score est reproductible avec sa formule et sa fenêtre.",
  canon="Réputation — synthèse", chrome=CHROME_PRE),
]
