# -*- coding: utf-8 -*-
"""FAMILLE 03 · PRESTATAIRE — PRE-16 → PRE-30"""
from ..model import S, Z, CHROME_APP
from .pre_a import CHROME_PRE

SCREENS = [

S("PRE-16", "Propositions reçues", "PRE", "Propositions & Contrats", "/prestataire/propositions", "Prestataire", "P0", "Offres reçues",
  intent="Recevoir une offre est un moment de valeur : l'écran met en avant le montant, le nom du client, et le délai pour "
         "répondre. Une proposition est une marque de confiance — elle doit être traitée comme telle.",
  zones=[
    Z("chips", "Segments", 2, "À examiner · Acceptées · Refusées · Expirées."),
    Z("list", "Cartes proposition", 6, "Carte : client (fiabilité, ancienneté), mission, PRIX PRESTATAIRE en or --title-2, dates, délai de réponse 48 h en Mono (ambre < 6 h), état."),
    Z("kpi", "Contexte", 2, "« 2 propositions vous attendent · délai médian de réponse : 4 h » — encourage la réactivité sans la forcer."),
  ],
  comps=[("Carte proposition", "prix dominant, client lisible"),
         ("Compte à rebours", "Mono, ambre si < 6 h"),
         ("Badge de contre-proposition", "si vous avez négocié : écart affiché")],
  states=[("Vide", "État vide + conseil : compléter son profil augmente les propositions reçues."),
          ("Urgent", "bandeau ambre en tête de liste."),
          ("Expirée", "grisée, motif de l'expiration, aucune culpabilisation."),
          ("Acceptée", "transition vers contrat (PRE-21).")],
  motion=[("Entrée", "stagger 60 ms"),
          ("Urgence", "pulsation ambre 2 400 ms sur le compte à rebours uniquement"),
          ("Acceptation", "sceau émeraude, transition vers le folio")],
  rules=["Aucune proposition n'est envoyée sans intention sérieuse du client : 3 propositions expirées sans réponse d'un client déclenchent une revue interne.",
         "Le prix affiché est intégral, frais SaaS jamais déduits : le travailleur ne paie rien à LE LABEUR (principe produit).",
         "Le délai de réponse est affiché et respecté ; l'expiration est notifiée 6 h avant."],
  tokens=["--gold-500", "--emerald-500", "--display-2", "--mono"],
  api=["GET /v1/propositions?provider=me&segment=", "GET /v1/propositions/counters"],
  tech="Même agrégat proposition que EMP-23, projection prestataire. Comptes à rebours calculés serveur pour éviter toute "
       "divergence d'horloge.",
  canon="Propositions reçues — registre", chrome=CHROME_PRE),

S("PRE-17", "Détail d'une proposition", "PRE", "Propositions & Contrats", "/prestataire/propositions/:id", "Prestataire", "P0", "Offre sous la loupe",
  intent="Examiner une offre en toute connaissance : le montant, mais aussi le client, les conditions d'exécution, les "
         "preuves attendues et les pénalités réciproques. Le travailleur doit pouvoir dire non en confiance.",
  zones=[
    Z("price", "Montant mis en avant", 5, "« Vous recevrez 250 000 F » --display-1 or + échéancier prévu (40 % signature / 60 % validation) avec dates estimées et explication de l'OTP."),
    Z("hero", "Client & contexte", 4, "Profil client détaillé : fiabilité de paiement, historique de contrats, litiges (avec issues), ancienneté. Aucune donnée personnelle."),
    Z("list", "Conditions complètes", 4, "Périmètre & livrables · dates & durée · preuves attendues (types et délais) · pénalités de retard (réciproques, plafonnées) · clause de résiliation · frais de déplacement éventuels."),
    Z("cta", "Répondre", 2, "« Accepter » or · « Contre-proposer » fantôme · « Refuser » texte."),
  ],
  comps=[("C-05 PriceBreakdown", "variante prestataire : prix seul en avant, total client en mention informative"),
         ("Carte client détaillée", "fiabilité, taux de paiement, historique"),
         ("Récapitulatif des clauses", "extraits avec résumé « en clair »")],
  states=[("À examiner", "compte à rebours visible."),
          ("Client à risque", "avertissement factuel si taux de retard > 20 % : « ce client a payé en retard 2 fois sur 5 contrats »."),
          ("Contre-proposition en cours", "bandeau or avec l'état de la négociation."),
          ("Expirée", "lecture seule, mention claire.")],
  motion=[("Entrée", "prix en premier, puis client, puis conditions (ordre de lecture imposé)"),
          ("Contre-proposition", "sheet 420 ms avec formulaire structuré")],
  rules=["Toutes les clauses contraignantes sont visibles AVANT acceptation : aucune découverte après coup.",
         "La réciprocité des pénalités est vérifiée : si le client a des pénalités, le travailleur en a aussi (équité algorithmique).",
         "Le client ne peut pas exiger de travail bénévole : toute demande hors périmètre est signalable."],
  tokens=["--display-1", "--gold-500", "--emerald-500", "--clay-500", "--glass-2"],
  api=["GET /v1/propositions/:id/provider-view", "POST /v1/propositions/:id/accept", "POST /v1/propositions/:id/counter"],
  tech="Projection prestataire de l'agrégat proposition. Les statistiques client proviennent d'une vue agrégée publique.",
  canon="Proposition reçue — détail & réponse", chrome=CHROME_PRE),

S("PRE-18", "Accepter une proposition", "PRE", "Propositions & Contrats", "/prestataire/propositions/:id/acceptation", "Prestataire", "P0", "Engagement explicite",
  intent="Accepter est un engagement : l'écran énumère ce que le travailleur s'engage à faire, ce qu'il recevra, et ce qui "
         "se passe s'il ne peut plus. Consentement plein, informé, horodaté.",
  zones=[
    Z("list", "Ce que j'accepte", 4, "Liste explicite : exécuter les livrables listés · fournir les preuves définies · respecter les dates · prévenir en cas d'impossibilité · respecter la confidentialité."),
    Z("price", "Ce que je recevrai", 4, "Prix prestataire + échéancier + mécanisme de l'OTP expliqué en clair (« vous confirmerez la réception de votre salaire par un code »)."),
    Z("kpi", "Conséquences d'un échec", 3, "Ce qui arrive en cas de non-exécution : procédure contradictoire, impact réputation, remboursement au client. Dit avant, jamais après."),
    Z("cta", "Accepter", 2, "« J'accepte — générer le contrat » or (désarmé jusqu'à la case de lecture cochée) · « Contre-proposer plutôt » fantôme."),
  ],
  comps=[("Checklist d'acceptation", "chaque point avec sa conséquence en cas de manquement"),
         ("Case de lecture", "« J'ai lu les conditions et l'échéancier » cochée manuellement"),
         ("Explication de l'OTP", "encart émeraude, 3 étapes illustrées")],
  states=[("Prêt", "CTA or armé après lecture."),
          ("Conflit de dates", "si le travailleur a une autre mission sur les mêmes dates : blocage avec proposition d'ajustement."),
          ("Capacité dépassée", "si 3 missions simultanées : avertissement de charge (santé du travailleur prise en compte)."),
          ("Accepté", "génération du contrat, transition PRE-21 avec sceau or.")],
  motion=[("Entrée", "checklist révélée ligne à ligne 60 ms"),
          ("Acceptation", "sceau or qui s'imprime, haptique medium — acte grave, geste sobre")],
  rules=["Aucune acceptation sans case de lecture explicite : le consentement ne doit jamais être un réflexe de tap.",
         "Les pénalités éventuelles sont plafonnées et réciproques ; toute clause abusive est bloquée par le moteur contractuel.",
         "Un conflit de dates détecté n'est jamais ignoré par le système : le double engagement est un risque majeur pour les deux parties."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--grad-gold", "--mono"],
  api=["POST /v1/propositions/:id/accept {consent, availabilityConfirmed}", "GET /v1/provider/calendar/conflicts?mission=:mid"],
  tech="Acceptation transactionnelle : vérification de disponibilité, création du contrat en brouillon, notification au client.",
  canon="Proposition reçue — détail & réponse", variant_of="PRE-17", chrome={"appbar": "Accepter", "glyph": "◉"}),

S("PRE-19", "Contre-proposer", "PRE", "Propositions & Contrats", "/prestataire/propositions/:id/contre", "Prestataire", "P1", "Négocier ses conditions",
  intent="Négocier sans agressivité : demander un ajustement de montant, de délai ou de périmètre, avec un motif clair. "
         "L'écran rend la contre-proposition respectable — c'est un droit, pas une faveur.",
  zones=[
    Z("form", "Nature de la demande", 4, "Type : ajustement de prix · délai supplémentaire · périmètre réduit · conditions de déplacement. Montant ou durée demandés en chiffres clairs (tnum)."),
    Z("list", "Motif structuré", 4, "Motifs guidés : déplacement réel supérieur · complexité sous-estimée · équipement supplémentaire · indisponibilité partielle. Champ libre limité à 400 c."),
    Z("chat", "Message au client", 3, "Message professionnel, gabarit proposé (« Bonjour, la mission … »), garde-fou anti-coordonnées."),
    Z("cta", "Envoyer", 2, "« Envoyer ma contre-proposition » or · « Annuler » fantôme."),
  ],
  comps=[("Formulaire structuré", "montant/durée + motif catégorisé + message"),
         ("Aperçu", "ce que le client verra exactement"),
         ("Limiteur de tours", "compteur de tours (6) affiché dès le premier échange")],
  states=[("Première contre-proposition", "compteur 1/6."),
          ("Tours avancés", "au 5e tour : message de recentrage « deux options restent : accepter ou retirer »."),
          ("Refusée", "retour à la proposition initiale, possibilité d'accepter telle quelle."),
          ("Acceptée", "contrat généré au nouveau montant.")],
  motion=[("Saisie", "chiffres tnum, recalcul local de l'aperçu"),
          ("Envoi", "message qui part (fly-to) 480 ms")],
  rules=["La négociation reste sur la plateforme : tout accord hors plateforme n'est pas couvert et l'écran le rappelle.",
         "Le nombre de tours est limité à 6 : au-delà, la proposition se termine (accepter ou retirer).",
         "Le travailleur peut négocier librement : aucune sanction de réputation pour une contre-proposition."],
  tokens=["--gold-500", "--emerald-500", "--mono", "--surface-2"],
  api=["POST /v1/propositions/:id/counter {type, amount?, durationDays?, motive, message}", "GET /v1/propositions/:id/provider-preview"],
  tech="Même moteur de négociation que EMP-24 (agrégat partagé) ; les motifs catégorisés alimentent l'analyse de marché "
       "anonymisée (ADM-10) pour améliorer les fourchettes indicatives.",
  canon="Proposition reçue — détail & réponse", variant_of="PRE-17", chrome={"appbar": "Négocier", "glyph": "◉"}),

S("PRE-20", "Historique des propositions", "PRE", "Propositions & Contrats", "/prestataire/propositions/historique", "Prestataire", "P2", "Mémoire de carrière",
  intent="Retrouver les offres passées, les clients avec qui la collaboration a été bonne, et les montants négociés. "
         "Cet historique constitue une base de négociation pour l'avenir.",
  zones=[
    Z("list", "Historique", 5, "Lignes : client, mission, montant accepté (ou proposition), issue (menée à terme, refusée, expirée), dates."),
    Z("kpi", "Statistiques", 3, "« Taux d'acceptation : 68 % · montant médian : 180 000 F · clients récurrents : 4 »."),
    Z("cta", "Actions", 1, "« Exporter » (CSV/PDF, portabilité) · « Revoir mes négociations » (filtre)."),
  ],
  comps=[("Ligne d'historique", "montant tnum + issue"),
         ("Statistiques explicables", "définitions accessibles en un tap"),
         ("Badge client récurrent", "relation durable mise en avant — valorise la confiance")],
  states=[("Vide", "« Aucune proposition passée. »"),
          ("Riche", "filtres par client, catégorie, période."),
          ("Export", "asynchrone, notification")],
  motion=[("Filtres", "FLIP 240 ms"),
          ("Statistiques", "compteurs tnum stables")],
  rules=["L'historique est exportable intégralement : c'est la carrière du travailleur, elle lui appartient.",
         "Les montants sont affichés en prix prestataire (jamais le total client, qui n'est pas sa rémunération).",
         "Aucune comparaison publique avec d'autres travailleurs."],
  tokens=["--slate-500", "--gold-500", "--mono"],
  api=["GET /v1/propositions/history?provider=me", "GET /v1/propositions/stats"],
  tech="Read model dédié (propositions + issues) rafraîchi à chaque transition d'état.",
  canon="Propositions — historique prestataire", chrome=CHROME_PRE),

S("PRE-21", "Contrat reçu (prestataire)", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id", "Prestataire", "P0", "Folio du travailleur",
  intent="Lire son contrat sans être juriste : chaque clause importante a son résumé, chaque devoir a sa contrepartie affichée "
         "en face. Le contrat est le même pour les deux parties — la présentation s'adapte au rôle.",
  zones=[
    Z("hero", "En-tête de contrat", 3, "Référence C-2026-0031 (Mono), statut (En signature, Actif, Terminé, Résilié), parties, dates, sceau d'état."),
    Z("doc", "Corps & clauses", 6, "Clauses numérotées avec résumés « en clair ». Symétrie affichée : « Votre obligation / Contrepartie du client » en deux colonnes pour les 4 clauses clés."),
    Z("sign", "Signature", 3, "Emplacement prestataire : état, horodatage, empreinte. Rappel : contrat actif uniquement à la double signature."),
    Z("price", "Rémunération", 3, "Prix prestataire, échéancier, mécanisme de paiement (mobile money/compte), OTP expliqué."),
    Z("cta", "Actions", 2, "« Signer » or (si en attente) · « Télécharger mon exemplaire » fantôme · « Demander une clarification » texte (message au support, réponse sous 24 h)."),
  ],
  comps=[("C-08 ContractFolio", "variante prestataire avec symétrie des obligations"),
         ("Colonnes symétriques", "« je dois / il doit » — clarté relationnelle"),
         ("Explication OTP", "encart émeraude, déjà vu à PRE-18 mais permanent ici"),
         ("C-11 DocumentCardR2", "pièces annexées")],
  states=[("En signature", "demi-sceau, mention « en attente de la seconde signature »."),
          ("Actif", "sceau or, exécution ouverte."),
          ("Terminé", "sceau émeraude, dossier de clôture lié."),
          ("Résilié", "clay, motifs et droits (paiement du travail validé)."),
          ("Remplacé", "ardoise, lien vers le contrat successeur et les conditions de sortie.")],
  motion=[("Ouverture", "folio 420 ms"),
          ("Signature complète", "double sceau emboîté, émeraude, haptique heavy"),
          ("Clarification", "message qui part vers le support, accusé de réception 1 200 ms")],
  rules=["Le prestataire voit exactement le même contrat que le client (aucune mention cachée) — c'est la base de la confiance contractuelle.",
         "Une clause incompréhensible peut être signalée et expliquée en langage clair par la plateforme (service, pas faveur).",
         "Le prix prestataire ne peut jamais être réduit par une clause : le moteur contractuel refuse les clauses léonines."],
  tokens=["--gold-500", "--emerald-500", "--mono", "--glass-1", "--text-mid"],
  api=["GET /v1/contracts/:id/provider-view", "POST /v1/contracts/:id/sign", "POST /v1/contracts/:id/clarification"],
  tech="Même document contractuel que EMP-29, projeté pour le rôle prestataire. La symétrie des obligations est générée "
       "à partir de la structure de clauses (paires obligatoires).",
  a11y=["Résumés « en clair » lus avant le texte de clause (ordre de lecture optimisé pour les lecteurs d'écran)."],
  canon="Contrat prestataire — folio & états", chrome=CHROME_PRE),

S("PRE-22", "Contrat — lecture guidée", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/lecture", "Prestataire", "P2", "Comprendre avant de signer",
  intent="Un mode lecture qui prend le travailleur par la main : 6 questions qu'il doit pouvoir se poser, avec les réponses "
         "tirées littéralement du contrat. Aucune clause cachée, aucune surprise.",
  zones=[
    Z("list", "Questions clés", 5, "Six cartes : que dois-je faire exactement ? quand ? combien je reçois et quand ? que se passe-t-il si je suis en retard ? que se passe-t-il si le client ne paie pas ? comment le contrat se termine-t-il ?"),
    Z("doc", "Réponse sourcée", 4, "Chaque réponse affiche l'extrait du contrat surligné + le numéro de clause (lien vers le folio complet)."),
    Z("cta", "Suite", 1, "« J'ai compris — voir le contrat complet » or · « Poser une question » fantôme."),
  ],
  comps=[("Cartes question", "question en langage humain, réponse citée"),
         ("Surlignage de clause", "lien direct vers PRE-21 ancré"),
         ("Compteur de compréhension", "6/6 quand toutes les cartes sont lues (facultatif mais affiché)")],
  states=[("Lecture", "progression visible, repliable."),
          ("Clause manquante", "si une question n'a pas de réponse contractuelle : « non précisé — la règle par défaut s'applique » (et dire laquelle)."),
          ("Terminé", "CTA or outline activé.")],
  motion=[("Cartes", "dépliage 240 ms, extrait qui s'illumine"),
          ("Ancrage", "scroll fluide vers la clause 420 ms")],
  rules=["Chaque réponse est extraite littéralement du contrat et référencée : aucune paraphrase non sourcée.",
         "En absence de clause, la règle par défaut du droit du travail local est citée explicitement.",
         "Ce mode est facultatif mais recommandé : l'écran de signature le propose systématiquement."],
  tokens=["--emerald-500", "--gold-500", "--text-mid", "--glass-1"],
  api=["GET /v1/contracts/:id/guided-reading?lang=fr"],
  tech="Le service génère les réponses par extraction sur la structure de clauses (pas par LLM en production : résultat "
       "déterministe et auditable).",
  canon="Contrat prestataire — folio & états", variant_of="PRE-21", chrome={"appbar": "Lecture", "glyph": "◉"}),

S("PRE-23", "Contrat — révision R2 côté prestataire", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/versions/:v", "Prestataire", "P1", "Révision sous contrôle",
  intent="Voir ce qui change dans le contrat avant de l'accepter : diff visuel clause par clause, impact sur la rémunération "
         "et les dates, motif de la révision. Le travailleur ne signe jamais un texte qu'il n'a pas vu changer.",
  zones=[
    Z("doc", "Diff clause à clause", 6, "Avant/après en deux colonnes ; ajouts émeraude, suppressions barrées clay, modifications or. Navigation par clause modifiée (n/N)."),
    Z("price", "Impact sur ma rémunération", 4, "Montant avant → après (delta signé), échéancier modifié, dates recalculées. Si le prix baisse : encart clay « baisse de 12 000 F — motif : réduction de périmètre »."),
    Z("cta", "Décider", 2, "« Accepter la révision » or · « Refuser » fantôme (relance de négociation) · « Demander une explication » texte."),
  ],
  comps=[("Vue de diff", "sémantique, par clause"),
         ("Delta financier", "avant/après, tnum"),
         ("Bandeau de motif", "chaque révision porte son motif"),
         ("Avertissement de délai", "la révision expire en 72 h si pas de réponse")],
  states=[("Lecture", "navigation par clause."),
          ("Acceptée", "sceau or, l'ancienne version passe en historique."),
          ("Refusée", "retour en négociation, version R2 marquée rejetée."),
          ("Expirée", "retour à la version précédente, mention claire.")],
  motion=[("Ouverture", "deux colonnes qui se déploient 420 ms"),
          ("Acceptation", "sceau or, haptique heavy (acte contractuel)")],
  rules=["Aucune révision ne peut être acceptée tacitement : l'expiration revient à la version précédente.",
         "Une baisse de prix doit toujours être motivée par une réduction de périmètre : le moteur contractuel vérifie la cohérence.",
         "Toutes les versions restent accessibles pour toujours (preuve de bonne foi)."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/contracts/:id/versions/:v/provider-view", "POST /v1/contracts/:id/versions/:v/accept", "POST /v1/contracts/:id/versions/:v/reject"],
  tech="Même moteur de diff que EMP-30 ; projection prestataire des impacts financiers (prix prestataire uniquement).",
  canon="Contrat — révision (prestataire)", chrome=CHROME_PRE),

S("PRE-24", "Signature du contrat (prestataire)", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/signer", "Prestataire", "P0", "Le geste qui engage",
  intent="La signature du travailleur est un acte aussi grave que celui du client : l'écran est sobre, cérémoniel et protège "
         "le travailleur (rappel de ses droits, du mécanisme de paiement, du droit de refus).",
  zones=[
    Z("list", "Rappel des protections", 4, "« Vous êtes payé pour le travail validé. » · « Un litige ne peut pas vous retirer un travail déjà accepté. » · « Vos pièces restent les vôtres. » · « Vous pouvez refuser sans pénalité de réputation avant signature. »"),
    Z("sign", "Pad de signature", 4, "Tracé lissé ou OTP renforcé ; phrase de consentement explicite ; horodatage serveur affiché avant validation."),
    Z("price", "Rappel de rémunération", 3, "Prix prestataire + échéancier, une dernière fois, juste avant la signature."),
    Z("cta", "Signer", 2, "« Signer mon contrat » or (armé après consentement) · « Refuser maintenant » clay discret (possible avant signature, sans conséquence)."),
  ],
  comps=[("Pad de signature", "Skia"),
         ("Phrase de consentement", "cochée manuellement"),
         ("Bandeau de refus sans pénalité", "essentiel : la liberté de refus avant signature"),
         ("Sceau demi → complet", "à la double signature")],
  states=[("Prêt", "CTA or armé après consentement."),
          ("Signé par vous", "demi-sceau or, attente du client."),
          ("Double signature", "contrat actif, émeraude, exécution ouverte."),
          ("Refus avant signature", "proposition annulée proprement, aucune pénalité, notification au client.")],
  motion=[("Signature", "tracé qui se lisse 120 ms"),
          ("Validation", "demi-sceau imprimé, haptique heavy"),
          ("Activation", "les deux sceaux se rejoignent : émeraude pleine, 640 ms, une seule fois")],
  rules=["Refuser de signer n'entraîne AUCUNE pénalité de réputation : c'est un droit fondamental affiché sur l'écran.",
         "Aucune signature ne peut précéder le rappel des protections : l'ordre du contenu est imposé.",
         "La signature du travailleur est horodatée et empreintée au même niveau que celle du client (INV-3)."],
  tokens=["--gold-500", "--emerald-500", "--grad-gold", "--glass-4", "--mono"],
  api=["POST /v1/contracts/:id/sign {method, consent, artifact}", "POST /v1/contracts/:id/refuse"],
  tech="Identique à EMP-31 côté mécanique (signature vectorisée + horodatage + empreinte). Le contrat ne devient actif qu'à "
       "la seconde signature, quelle que soit l'ordre.",
  canon="Contrat — signature prestataire", chrome={"appbar": "Signature", "glyph": "◉"}),

S("PRE-25", "Contrat actif (prestataire)", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/actif", "Prestataire", "P1", "Poste de travail",
  intent="L'état quotidien du contrat : ce qui est attendu de moi aujourd'hui, mon prochain jalon, mon prochain paiement. "
         "Le travailleur doit pouvoir planifier sa semaine en un regard.",
  zones=[
    Z("hero", "État actif", 3, "Sceau or « Contrat actif » + mission + client + dates."),
    Z("timeline", "Mes obligations datées", 4, "Frise personnelle : prochain livrable, prochaine preuve à déposer, prochaine échéance de paiement (avec montant)."),
    Z("price", "Mon argent", 3, "Reste à recevoir · prochain versement · statut du versement précédent. Prix prestataire uniquement."),
    Z("cta", "Actions", 2, "« Déposer une preuve » or · « Voir la mission » fantôme · « Signaler un empêchement » texte."),
  ],
  comps=[("C-06 TimelineTrack", "obligations personnelles"),
         ("Carte de paiement", "montant + date + mécanisme OTP"),
         ("Bouton de signalement d'empêchement", "prévient le client avant le retard (dignité et transparence)")],
  states=[("À jour", "aucune alerte, or sobre."),
          ("Jalon proche", "ambre à J-2 sur la ligne concernée."),
          ("Empêchement signalé", "ardoise, message au client, proposition de re-planification (avenant si accepté)."),
          ("Salaire en retard", "clay : montant dû + relance automatique de la plateforme déjà effectuée (le travailleur n'a rien à faire).")],
  motion=[("Entrée", "sceau + obligations 240 ms"),
          ("Alerte", "pulsation ambre uniquement sur la ligne concernée")],
  rules=["Le signalement d'empêchement est un droit et un devoir : il protège le travailleur d'un retard imputé injustement.",
         "Le travailleur n'est jamais obligé de relancer son paiement : la plateforme le fait automatiquement.",
         "Aucune tâche non prévue au contrat ne peut être demandée ici (le contrat est la seule source)."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/contracts/:id/provider-state", "POST /v1/contracts/:id/impediment"],
  tech="Vue d'état dérivée du contrat + calendrier d'obligations, identique à EMP-32 mais projetée pour le prestataire.",
  canon="Contrat prestataire — folio & états", variant_of="PRE-21", chrome=CHROME_PRE),

S("PRE-26", "Avenant reçu", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/avenants/:aid", "Prestataire", "P1", "Changement proposé",
  intent="Un avenant modifie les règles du jeu : l'écran montre précisément ce qui change, pourquoi, et ce que cela signifie "
         "en argent et en charge de travail. Le travailleur peut refuser — et le contrat reste en l'état.",
  zones=[
    Z("doc", "Diff de l'avenant", 5, "Comparaison clause par clause du contrat en vigueur vs version proposée ; changement principal mis en exergue (prix, dates, périmètre)."),
    Z("price", "Impact chiffré", 4, "Avant/après : montant, durée, nombre de livrables. Deltas signés en or/ardoise, tnum."),
    Z("kpi", "Droits du travailleur", 3, "« Vous pouvez refuser : le contrat actuel reste en vigueur. » · « Votre refus n'entraîne aucune pénalité sauf clause contraire valide. » · « Délai de réponse : 72 h. »"),
    Z("cta", "Décider", 2, "« Accepter l'avenant » or · « Refuser » fantôme · « Proposer une alternative » texte."),
  ],
  comps=[("Diff contractuel", "sémantique, par clause"),
         ("Bandeau de droits", "refus sans pénalité, délai"),
         ("Alternative", "contre-proposition structurée (montant/durée/périmètre)")],
  states=[("À examiner", "compte à rebours 72 h."),
          ("Accepté", "nouvelle version en vigueur, sceau or, horodatage."),
          ("Refusé", "contrat inchangé, mention de l'échec de la négociation."),
          ("Expiré", "le contrat reste en vigueur, l'avenant est caduc (jamais appliqué par défaut).")],
  motion=[("Ouverture", "deux versions côte à côte 420 ms"),
          ("Acceptation", "sceau or + version mise à jour dans l'historique"),
          ("Refus", "bascule sobre, aucune animation punitive")],
  rules=["Aucun avenant ne s'applique sans acceptation explicite : l'expiration est un refus par défaut, jamais une acceptation tacite.",
         "Le travailleur peut toujours négocier un avenant plutôt que de le refuser en bloc.",
         "Les avenants refusés sont archivés et visibles des deux parties (transparence sur l'historique de la relation)."],
  tokens=["--gold-500", "--emerald-500", "--clay-500", "--mono"],
  api=["GET /v1/contracts/:id/amendments/:aid/provider-view", "POST /v1/contracts/:id/amendments/:aid/accept", "POST /v1/contracts/:id/amendments/:aid/refuse"],
  tech="Même moteur d'avenant que EMP-15/30 ; l'échéance de réponse est surveillée par un job (notification à J-12 h).",
  canon="Contrat — révision (prestataire)", variant_of="PRE-23", chrome=CHROME_PRE),

S("PRE-27", "Résiliation vue prestataire", "PRE", "Propositions & Contrats", "/prestataire/contrats/:id/resiliation", "Prestataire", "P1", "Sortie protégée",
  intent="Voir la fin d'un contrat en connaissant ses droits : ce qui est dû pour le travail réalisé, les délais, et la "
         "possibilité de contester un décompte. Le travailleur ne termine jamais un contrat les mains vides.",
  zones=[
    Z("hero", "Motif & auteur", 3, "Sceau clay + qui a résilié + motif + date d'effet."),
    Z("price", "Ce qui m'est dû", 4, "Décompte détaillé : jalons validés × montants, prorata éventuel, total à recevoir, date de versement prévue. Prix prestataire uniquement."),
    Z("timeline", "Étapes", 3, "Notification → délai de contestation 72 h → versement → clôture. Horodatages Mono."),
    Z("cta", "Actions", 2, "« Contester le décompte » clay outline · « Accepter et clôturer » or · « Voir mes preuves » fantôme."),
  ],
  comps=[("Table de décompte", "lignes de calcul explicites"),
         ("Sceau clay", "sobre, pas dramatique"),
         ("Lien vers litige", "si désaccord persistant")],
  states=[("Amiable", "émeraude atténué : sortie sans litige, paiement sous 5 jours."),
          ("Pour motif", "clay : motifs détaillés, droit de réponse."),
          ("Contestée", "dossier de médiation, paiement gelé mais dû tracé."),
          ("Clôturée", "paiement versé, archivage du dossier, avis réciproque possible.")],
  motion=[("Contre-forge", "640 ms, sceau clay"),
          ("Décompte", "lignes révélées 120 ms une à une")],
  rules=["Le travail validé est TOUJOURS payé, quelle que soit la raison de la résiliation (hors fraude établie par décision).",
         "Toute résiliation ouvre un droit de contestation de 72 h côté prestataire.",
         "Les preuves déposées restent accessibles au travailleur même après résiliation (son travail lui appartient)."],
  tokens=["--clay-500", "--gold-500", "--emerald-500", "--mono"],
  api=["GET /v1/contracts/:id/termination/provider-view", "POST /v1/contracts/:id/termination/contest"],
  tech="Même service de décompte que EMP-34, projection prestataire (montants perçus uniquement).",
  canon="Contrat prestataire — folio & états", variant_of="PRE-21", chrome=CHROME_PRE),

S("PRE-28", "Exécution — suivi prestataire", "PRE", "Exécution & Salaire", "/prestataire/missions/:id/execution", "Prestataire", "P0", "Poste de travail actif",
  intent="Exécuter proprement : voir ce qui est attendu, déposer les preuves au bon format, suivre les validations. L'écran "
         "est un guide de travail, pas un formulaire administratif.",
  zones=[
    Z("timeline", "Jalons & livrables", 5, "Frise personnelle : chaque jalon avec son état (à faire, en cours, preuve déposée, validée, refusée) et son exigence de preuve résumée."),
    Z("list", "Prochaines actions", 4, "Cartes d'action concrètes : « Déposer la photo du chantier avant vendredi 18:00 » avec bouton direct, format attendu, exemple visuel."),
    Z("kpi", "Avancement & salaire", 3, "Progression % · montant acquis à ce stade (prix prestataire proportionnel) · prochaine échéance de paiement."),
    Z("cta", "Agir", 2, "« Déposer une preuve » or · « Signaler un obstacle » fantôme (météo, accès au site, matériel manquant)."),
  ],
  comps=[("C-06 TimelineTrack", "variante travail, orientée actions"),
         ("Carte d'action concrète", "quoi, quand, comment, avec exemple"),
         ("Compteur de salaire acquis", "montant proportionnel validé, tnum"),
         ("Signalement d'obstacle", "typé, notifie le client sans accusation")],
  states=[("À jour", "aucune action en retard."),
          ("Action imminente", "ambre à J-2, rappel unique."),
          ("Preuve refusée", "clay doux + motif du client + bouton « redéposer » immédiat."),
          ("Obstacle signalé", "ardoise : le client est notifié, le délai est suspendu pendant la résolution (traçable).")],
  motion=[("Actions", "cartes qui montent 8 px à l'apparition"),
          ("Preuve déposée", "onde émeraude sur le jalon 420 ms"),
          ("Obstacle", "bandeau qui se déplie 240 ms, ton neutre")],
  rules=["Un obstacle signalé suspend le délai d'exécution dès qu'il est constaté (protection du travailleur).",
         "Le compteur de salaire acquis ne peut jamais reculer : une validation acquise l'est définitivement (INV-5).",
         "Chaque demande de preuve indique son format et son exemple : interdiction de refuser une preuve pour un format non précisé."],
  tokens=["--emerald-500", "--gold-500", "--amber-500", "--mono"],
  api=["GET /v1/missions/:id/provider-execution", "POST /v1/missions/:id/obstacles", "GET /v1/missions/:id/earned"],
  tech="Flux d'exécution partagé (EMP-37) avec projection prestataire. Les obstacles créent un événement qui suspend le "
       "calcul des échéances (moteur de délais).",
  canon="Exécution — suivi prestataire", chrome=CHROME_PRE),

S("PRE-29", "Jalons & preuves attendues", "PRE", "Exécution & Salaire", "/prestataire/missions/:id/jalons", "Prestataire", "P1", "Cahier des preuves",
  intent="Savoir exactement ce qui prouve le travail : liste des preuves attendues, formats acceptés, délais, et exemples. "
         "Aucun refus ne doit jamais surprendre le travailleur.",
  zones=[
    Z("list", "Catalogue des preuves", 5, "Carte par preuve : type (photo horodatée, PDF signé, vidéo 90 s, jalon double), moment attendu, délai après exécution, exemple visuel, critères de validité."),
    Z("kpi", "Récapitulatif", 3, "« 4 preuves attendues · 1 déposée · 0 refusée » + poids de chaque preuve dans la validation finale."),
    Z("cta", "Actions", 1, "« Déposer maintenant » or sur la preuve due · « Poser une question sur une preuve » fantôme."),
  ],
  comps=[("Carte de preuve", "type + format + exemple + critères"),
         ("Indicateur de poids", "certaines preuves conditionnent des échéances de paiement"),
         ("Aide contextuelle", "conseils de prise de vue, de scan, de cadrage")],
  states=[("Toutes dues", "état normal de début de mission."),
          ("Partiellement déposées", "progression visible, aucune culpabilisation."),
          ("Preuve refusée", "explication du refus + exemple corrigé."),
          ("Toutes validées", "émeraude, échéance de paiement déclenchée.")],
  motion=[("Dépliage", "carte de preuve 240 ms"),
          ("Validation", "puce qui passe émeraude avec onde")],
  rules=["Aucune preuve ne peut être exigée sans exemple et sans critères : un refus pour « qualité insuffisante » non définie est un défaut produit.",
         "Les preuves demandées doivent être proportionnées : le moteur contractuel limite le nombre de preuves par jalon (max 3).",
         "Le travailleur garde la propriété intellectuelle de ses livrables, sauf cession explicite et rémunérée."],
  tokens=["--emerald-500", "--gold-500", "--mono", "--glass-1"],
  api=["GET /v1/missions/:id/evidence-requirements", "POST /v1/evidence {requirementId, files}"],
  tech="Les exigences de preuve sont définies à la création de mission (EMP-08) et immuables après signature (hors avenant).",
  canon="Preuve — dépôt & exigences", chrome=CHROME_PRE),

S("PRE-30", "Dépôt d'une preuve", "PRE", "Exécution & Salaire", "/prestataire/evidence/nouvelle", "Prestataire", "P0", "Dépôt de preuve",
  intent="Déposer une preuve en 30 secondes depuis le terrain : appareil photo intégré, horodatage automatique, géoloc si "
         "exigée, envoi résilient en cas de réseau faible. C'est l'écran le plus utilisé du produit en conditions réelles.",
  zones=[
    Z("form", "Capture ou sélection", 5, "Trois voies : appareil photo (flux direct avec guide de cadrage), galerie (vérification d'horodatage EXIF), fichier PDF. Chaque voie affiche les critères de validité avant capture."),
    Z("list", "Conformité avant envoi", 4, "Checklist live : horodatage dans la fenêtre ✓ · géolocalisation dans la zone ✓ (si exigée) · lisibilité (détection de flou) ⚠ · format conforme ✓. Le travailleur corrige AVANT d'envoyer."),
    Z("kpi", "Résilience réseau", 3, "« Envoi en attente de réseau : votre preuve est conservée localement. » · Barre de progression réelle par morceaux (upload partiel R2)."),
    Z("cta", "Envoyer", 2, "« Envoyer la preuve » or (désarmé si non conforme, avec explication exacte) · « Enregistrer localement » fantôme."),
  ],
  comps=[("Appareil photo intégré", "guides de cadrage, détection de flou en direct"),
         ("Checklist de conformité", "résultats instantanés, avant envoi"),
         ("File d'attente locale", "reprise après coupure réseau, chiffrée"),
         ("Upload multipart", "réel, avec reprise")],
  states=[("Hors-ligne", "dépôt possible, envoi en file, mention claire d'attente."),
          ("Non conforme", "critère en échec, chemin de correction proposé (rephotographier ici)."),
          ("Envoi en cours", "progression réelle (%), possibilité de pause/reprise."),
          ("Déposée", "émeraude, horodatage, hash, notification client."),
          ("Refusée par le client", "motif + suggestion de correction, redépôt immédiat possible."),
          ("Obstacle technique", "clay + contact support avec identifiant de dépôt.")],
  motion=[("Capture", "obturateur simulé 120 ms (satisfaction discrète)"),
          ("Checklist", "lignes qui se colorent à mesure 120 ms"),
          ("Envoi", "progression réelle ; à 100 %, onde émeraude, haptique medium")],
  rules=["Une preuve refusée peut toujours être redéposée : le compteur de refus n'a aucune limite punitive, seul le motif doit être fondé.",
         "L'horodatage est double : appareil + serveur ; en cas d'écart > 10 min, la preuve est marquée « à vérifier » (jamais rejetée d'office).",
         "Les données de géolocalisation sont limitées au strict nécessaire et jamais conservées au-delà de la mission."],
  tokens=["--emerald-500", "--gold-500", "--amber-500", "--clay-500", "--glass-3"],
  api=["POST /v1/evidence", "POST /v1/uploads/r2/presign", "GET /v1/evidence/:id/validation-preview"],
  tech="Skia/Camera native + uploads R2 presignés multipart avec reprise ; file locale chiffrée (MMKV + chiffrement) pour "
       "les zones à réseau faible. La validation de conformité est serveur (source de vérité) et rejouée côté client pour "
       "l'aide immédiate.",
  a11y=["Alternatives clavier : sélection de fichier et import photo disponibles sans appareil photo.",
        "La checklist de conformité est annoncée vocalement à chaque changement d'état."],
  canon="Preuve — dépôt & exigences", variant_of="PRE-29", chrome=CHROME_PRE),
]
