# -*- coding: utf-8 -*-
"""FAMILLE 01 · PUBLIC / ONBOARDING — PUB-01 → PUB-10"""
from ..model import S, Z, CHROME_PUB

SCREENS = [

S("PUB-01", "Splash", "PUB", "Ouverture", "/", "Public", "P1", "Splash cinétique",
  intent="Première image de LE LABEUR : un sceau d'or se forge dans le noir OLED. Aucune action, une promesse : "
         "le travail sera cadré, prouvé, payé. Sert aussi de préchauffage silencieux (fonts, tokens, session).",
  zones=[
    Z("canvas", "Champ particulaire naissant", 3, "Champ GLSL à 120 fps : poussière d'or en dérive brownienne, densité 120 particules, guidée par l'orientation de l'appareil."),
    Z("hero", "Sceau LE LABEUR — forge", 4, "Sceau central : anneau conique or (#FFB800 → #C98F1F) qui se referme en 640 ms, glyphe ◈ en Inter / Space Grotesk exposé par masque. Halo de respiration 2 400 ms."),
    Z("cta", "Zone d'entrée invisible", 1, "Aucun bouton visible : le premier tap n'importe où interrompt la forge et pousse vers PUB-02. Skip discret en --caps si la session est déjà restaurée."),
  ],
  comps=[("C-15 ParticleCanvas", "densité 120, alpha 0.10, mix-mode screen"),
         ("C-14 KineticText", "wordmark clip-path reveal, lettre par lettre, 40 ms/lettre"),
         ("C-04 StatusSeal", "variante « Forge » : anneau conique animé, pas de label"),
         ("préchargement", "fonts critiques, tokens JSON, ping de session /v1/me")],
  states=[("Session restaurée", "Sceau 480 ms puis fondu direct vers EMP-01/PRE-01/ADM-01 selon rôle."),
          ("Session absente", "Sceau 1 600 ms → PUB-02. Fond reste noir pur jusqu'au premier pixel utile."),
          ("Mode avion / offline", "Champ particulaire ralenti, micro-texte --caption : « Connexion recherchée… » puis SYS-02."),
          ("prefers-reduced-motion", "Sceau statique doré + fade 120 ms, particules figées à alpha 0.06.")],
  motion=[("Forge du sceau", "spring heavy (180/28/1.2) sur le tracé conique, 640 ms, ease-anticipate final"),
          ("Halo respiration", "opacité 0.16 → 0.06, 2 400 ms, sinus, jamais au-delà de 0.20"),
          ("Sortie", "scale 1 → 1.06 + fade 240 ms, ease-labeur-out ; l'écran suivant apparaît en dessous (cross-fade croisé)")],
  rules=["Aucun texte marketing en LaunchScreen natif (iOS/Android) : la forge est la première image animée.",
         "Temps total MAX 1 600 ms avant PUB-02 : au-delà, on coupe la forge même inachevée.",
         "Le sceau ne tourne jamais en boucle infinie : trois tours max, puis pause plastique."],
  tokens=["--surface-0", "--gold-500", "--gold-600", "--grad-gold", "--gold-aura", "--display-1"],
  api=["GET /v1/health", "GET /v1/me (silencieux, si refresh token présent)"],
  tech="Native splash → React Native (Skia) ou RSC route / pour le web. Les tokens sont injectés en CSS vars server-side "
       "(zéro flash). La forge est un Skia Canvas hors thread JS (UI thread natif) : aucune frame perdue pendant le bootstrap JS.",
  a11y=["role=progressbar silencieux, label « Ouverture de LE LABEUR »", "Le tap n'importe où est doublé d'un bouton invisible focalisable « Continuer »."],
  canon="Splash / Boot", chrome=CHROME_PUB),

S("PUB-02", "Accueil public", "PUB", "Ouverture", "/accueil", "Public", "P0", "Vitrine narrative",
  intent="Vendre la vérité du produit sans mentir : qualification juridique des missions, prix affiché sans ambiguïté, "
         "paiement prouvé par OTP. Trois promesses, trois preuves visuelles, une seule action qui convertit.",
  zones=[
    Z("hero", "Promesse cinétique", 3, "« Le travail, cadré, prouvé, payé. » en --display-2, révélation mot à mot liée au scroll. Fond : particules d'or montantes lentes."),
    Z("kpi", "Trio de preuves", 3, "Trois GlassTile : « Qualification juridique 100% humaine en revue », « Prix prestataire affiché en clair », « Salaire confirmé par OTP »."),
    Z("list", "Déroulé en 3 actes", 4, "Cartes narratives : 1) Je publie une mission cadrée → 2) Je choisis un candidat → 3) Le contrat, le salaire, la preuve. Chaque carte ouvre une démo visuelle (écran produit en miniature, non interactif)."),
    Z("price", "Vitrine du modèle financier", 3, "Exemple chiffré réel : Prix Prestataire 250 000 F + Frais SaaS 25 000 F = Total Client 275 000 F. Chiffres Inter tnum, séparateur or en tirets."),
    Z("cta", "Double entrée", 2, "Bouton principal neumorphique « Créer mon compte » (orr) + ghost « J'ai déjà un compte ». Liens CGU en pied, --caption."),
  ],
  comps=[("C-15 ParticleCanvas", "champ montant lent, 90 particules, respect du scroll"),
         ("C-14 KineticText", "titres exposés par ClipPath au scroll"),
         ("C-02 SquircleCard", "cartes narratives, élévation E1 → E2 au scroll-snap"),
         ("C-05 PriceBreakdown", "variante « vitrine » en lecture seule")],
  states=[("Premium (par défaut)", "Or actif, halos à 0.14."),
          ("Connexion lente", "Squelettes de cartes narratives, hero déjà peint (LCP < 800 ms)."),
          ("Prefers-contrast", "Verre remplacé par --surface-3 opaque, halo désactivé.")],
  motion=[("Stagger d'entrée", "hero → preuves → actes → prix → CTA, 60 ms × 4 blocs, spring soft"),
          ("Parallaxe de particules", "profondeur 0.94/1.06, facteur scroll 0.15"),
          ("CTA neumorphique", "enfoncement 2 px + ombres internes sur press, spring snap")],
  rules=["Le trio de preuves est factuel et vérifiable : aucune statistique inventée (nombre d'utilisateurs, etc.).",
         "Le bloc prix reprend EXACTEMENT le format canonique FIN (3 lignes, ordre immuable).",
         "Aucun mur de connexion : la vitrine est consultable sans compte."],
  tokens=["--surface-0", "--surface-2", "--gold-500", "--text-hi", "--glass-2", "--grad-gold"],
  api=["GET /v1/public/story?locale=fr", "GET /v1/public/stats (agrégats vérifiés uniquement)"],
  tech="Next.js RSC + streaming : le hero est du HTML statique, les cartes narratives en Server Components, "
       "l'interactivité des CTA en îlots clients. Polices en WOFF2 subset FR, preload du hero.",
  canon="Accueil public", chrome=CHROME_PUB),

S("PUB-03", "Choix de profil (Client vs Prestataire)", "PUB", "Onboarding", "/onboarding/profil", "Public", "P0", "Bifurcation héroïque",
  intent="Le choix le plus structurant du produit : Client/Employeur ou Prestataire/Candidat. L'UI doit rendre le choix "
         "irréversible mais réparable (± 30 jours, via ADMIN), et visuellement évident.",
  zones=[
    Z("hero", "Question fondatrice", 2, "« Comment allez-vous travailler sur LE LABEUR ? » en --title-1, sous-titre factuel : le profil détermine vos écrans, vos droits et vos engagements."),
    Z("kpi", "Deux cartes miroir", 6, "Carte CLIENT (sceau or) : publier, qualifier, choisir, payer, recevoir un salaire exécuté. Carte PRESTATAIRE (sceau émeraude) : candidater, s'engager, exécuter, prouver, encaisser. Séléction = anneau conique + rim-light renforcé + haptique heavy."),
    Z("cta", "Validation différée", 1, "Bouton « Continuer » désactivé (--slate-500) tant qu'aucune carte n'est choisie. Le libellé change dynamiquement : « Continuer en tant que Client »."),
  ],
  comps=[("C-02 SquircleCard", "cartes miroir superellipse 28, hauteur 320, listes d'avantages avec glyphes"),
         ("C-04 StatusSeal", "or vs émeraude, glyphes distincts (◈ vs ◉)"),
         ("NeoPressButton", "désactivé → armé, morph de couleur or"),
         ("notice légale", "encart --callout : « Modifiable une fois dans les 30 jours via le support. »")],
  states=[("Aucun choix", "Cartes au repos symétriques, CTA désactivé."),
          ("Sélection Client", "Carte prestataire se désature à 40%, halo or 0.16, CTA or armé."),
          ("Sélection Prestataire", "Symétrique en émeraude, CTA émeraude."),
          ("Double tap accidentel", "Verrou 400 ms + micro-secousse (spring pop) pour empêcher le changement impulsif.")],
  motion=[("Hybridation du choix", "spring snap sur l'anneau, la carte non choisie recule (translateZ -12)"),
          ("Morph du CTA", "couleur et libellé interpolés 240 ms ease-labeur-inout"),
          ("Haptique", "heavy sur sélection, light sur re-sélection")],
  rules=["Le choix écrit immédiatement le rôle (claim dans le token de session) — un seul profil actif par compte.",
         "Les deux cartes ont la même surface et le même poids visuel : aucun nudge commercial vers l'un des rôles.",
         "Le changement de rôle après 30 jours passe exclusivement par ADM-02 (journalisé, motif obligatoire)."],
  tokens=["--gold-500", "--emerald-500", "--surface-2", "--glass-3", "--squircle-28", "--spring-heavy"],
  api=["POST /v1/onboarding/role {role}", "GET /v1/onboarding/role-policy"],
  tech="Écran RSC + deux îlots clients (sélecteur, CTA). Le préchargement de PUB-04/05 est déclenché dès l'arrivée : le choix n'entraîne jamais d'attente.",
  canon="Choix de profil", chrome=CHROME_PUB),

S("PUB-04", "Connexion", "PUB", "Authentification", "/connexion", "Public", "P0", "Formulaire verre & or",
  intent="Entrer en 15 secondes. Email + mot de passe ou lien magique, sans friction, avec la même rigueur de sécurité "
         "qu'une banque : messages d'erreur non divulgatifs, throttling apparent.",
  zones=[
    Z("hero", "Retour de flatterie", 1, "« Bon retour. » --title-1, sous-ligne : l'e-mail sert uniquement à ouvrir votre espace de travail."),
    Z("form", "Champs verre", 5, "E-mail (clavier email, autocorrect off), Mot de passe (toggle œil, force en barre émeraude/or), option « Rester connecté 30 jours »."),
    Z("cta", "Actions", 2, "« Se connecter » pleine largeur or ; séparateur « ou » ; « Recevoir un lien magique » ; lien « Mot de passe oublié » → PUB-07."),
    Z("list", "Confiance discrète", 2, "Trois micro-lignes : chiffrement TLS 1.3 · session révocable depuis EMP/PRE-04 · aucune revente de données."),
  ],
  comps=[("Champ verre", "état focus = rim or 2 px + label flottant"),
         ("NeoPressButton", "or, press = enfoncement 2 px"),
         ("jauge mot de passe", "segments 4, émeraude dès 3 critères satisfaits"),
         ("bandeau erreur", "clay, hauteur animée, jamais divulgatif (« identifiants invalides »)")],
  states=[("Inactif", "CTA désactivé jusqu'à e-mail valide + 1 caractère."),
          ("Envoi", "Bouton → spinner or 3 points, champs verrouillés 1.5 s max, puis libération même en cas de lenteur."),
          ("Échec 401", "Secousse horizontale 8 px spring pop, haptique rigid, bandeau clay, compteur de tentatives invisible."),
          ("Throttle 429", "Bandeau ambre « Trop de tentatives. Réessayez dans 60 s. » + compte à rebours Mono."),
          ("Lien magique envoyé", "Vue de confirmation plein écran, sceau émeraude, consigne « vérifiez aussi les indésirables ».")],
  motion=[("Entrée", "champs stagger 60 ms, spring soft ; autofocus e-mail sans zoom iOS (font ≥ 16 px)"),
          ("Erreur", "shake X ±8 px, spring pop, 3 oscillations, haptique rigid"),
          ("Sortie succès", "fondu verre + expansion du sceau émeraude depuis le bouton")],
  rules=["Aucun indice de validité d'e-mail (anti-énumération) ; les messages restent génériques.",
         "Le lien magique expire en 15 min et ne s'affiche jamais illisible : adresse masquée a•••@domaine.tld.",
         "Après 5 échecs : CAPTCHA invisible + délai croissant (429 → SYS-08)."],
  tokens=["--glass-2", "--stroke-mid", "--gold-500", "--clay-500", "--emerald-500", "--text-lo"],
  api=["POST /v1/auth/login", "POST /v1/auth/magic-link", "GET /v1/auth/throttle-status"],
  tech="Formulaire en îlot client, validation zod partagée client/serveur (même schéma, une seule source). "
       "Le mot de passe n'est jamais loggé ; autocomplete natif respecté (username/current-password).",
  a11y=["label explicites + aria-describedby pour chaque aide", "Le message d'erreur est annoncé en role=alert, focus renvoyé sur le premier champ fautif."],
  canon="Authentification (connexion)", chrome=CHROME_PUB),

S("PUB-05", "Inscription", "PUB", "Authentification", "/inscription", "Public", "P0", "Formulaire progressif",
  intent="Créer un compte en deux temps, jamais en un mur : identité (nom, e-mail, téléphone) puis mot de passe, "
         "avec reconnaissance du pays (Togo/Bénin/etc.) et indicatif téléphonique intelligent.",
  zones=[
    Z("hero", "Rassurance", 1, "« Ouvrons votre espace de travail. » + rappel du profil choisi en PUB-03 (chip or/émeraude)."),
    Z("form", "Identité puis secret", 6, "Nom complet · E-mail · Téléphone (sélecteur indicatif +229/228…, formatage live) · Mot de passe + confirmation avec jauge commune."),
    Z("list", "Consentements", 2, "Case CGU/Confidentialité (obligatoire, lien → PUB-08) · case facultative communications produit (jamais pré-cochée)."),
    Z("cta", "Création", 1, "« Créer mon compte » or ; dessous : « Déjà inscrit ? Se connecter »."),
  ],
  comps=[("C-03 NeoPressButton", "armé seulement si CGU cochées + mdp valide + téléphone parse OK"),
         ("Champ téléphone", "libphonenumber : drapeau, indicatif, masque de saisie, validation à la volée"),
         ("jauge mot de passe", "4 segments, critères listés (12 c., majuscule, chiffre, symbole)"),
         ("carte d'erreur", "une erreur par champ, jamais de bloc global illisible")],
  states=[("Partiel", "Progression silencieuse en haut (barre fine or 2 px)."),
          ("E-mail existant", "Bandeau ambre non divulgatif : « Si ce compte existe, connectez-vous ou réinitialisez. » + lien PUB-04/07."),
          ("Validation échouée", "Champ fautif rim clay, secousse, focus automatique."),
          ("Succès", "Transition vers PUB-06 (OTP) avec sceau or→émeraude, haptique medium.")],
  motion=[("Révélation du formulaire", "deux blocs (identité, secret) séparés par 240 ms"),
          ("Morph téléphone", "drapeau et masque interpolés 120 ms sur changement de pays"),
          ("Sortie", "poussée verticale -24 px + fade 240 ms vers OTP")],
  rules=["Un numéro = un compte (contrainte anti-fraude, vérifiée ensuite par OTP).",
         "Le mot de passe fait ≥ 12 caractères ; aucune question de sécurité secrète (obsolète).",
         "Les CGU ne sont jamais pré-cochées ; l'horodatage du consentement est journalisé (preuve)."],
  tokens=["--glass-2", "--gold-500", "--emerald-500", "--stroke-mid", "--caps"],
  api=["POST /v1/auth/register", "GET /v1/geo/phone-policy", "POST /v1/legal/consent"],
  tech="Wizard à deux champs d'état, autosave local (AsyncStorage) contre la perte de saisie. "
       "La validation zod est la même que côté API (paquet partagé packages/contracts).",
  canon="Authentification (inscription)", chrome=CHROME_PUB),

S("PUB-06", "Vérification OTP", "PUB", "Authentification", "/verifier-otp", "Public", "P0", "Sceau de vérité",
  intent="Prouver que le téléphone et l'e-mail appartiennent bien à la personne. L'OTP est le premier sceau émeraude "
         "de l'expérience : il doit être vécu comme une validation, pas comme un péage.",
  zones=[
    Z("hero", "Contexte", 1, "« Dernière étape. » + destination masquée (+229 6# ## ## 41) et e-mail partiel. Bouton « Modifier » discret."),
    Z("form", "Champ OTP 6 cases", 4, "Saisie auto-avance, autofill iOS/Android (one-time-code), coller accepté, chiffres Mono 28 px. Recherche automatique de code par SMS natif."),
    Z("timeline", "Échéances visibles", 2, "Compte à rebours Mongo 10:00 (renvoi possible) ; après 3 renvois, délai exponentiel affiché honnêtement."),
    Z("cta", "Actions", 2, "« Vérifier » (s'active à 6 chiffres) ; « Renvoyer le code » fantôme ; lien « Changer de numéro » retour PUB-05."),
  ],
  comps=[("C-07 OTPField", "6 cases squircle 14, caret or, auto-submit à 6 chiffres"),
         ("C-04 StatusSeal", "émeraude à la validation, avec empreinte 12 caractères affichée 1.5 s"),
         ("chrono Mono", "JetBrains Mono, tabular, zéro serif"),
         ("bandeau sécurité", "--callout : « LE LABEUR ne vous demandera jamais ce code par téléphone. »")],
  states=[("Saisie", "Cases se remplissent, caret glisse, haptique light à chaque chiffre"),
          ("Code faux", "6 cases vibrent ensemble (spring pop), rim clay, haptique rigid, compteur d'essais restant 2/5"),
          ("Succès", "Sceau émeraude plein écran 480 ms, haptique heavy, redirection vers l'espace selon rôle"),
          ("Expiré", "Cases se vident en cascade 40 ms, message ambre, bouton renvoi mis en avant")],
  motion=[("Validation", "expansion du sceau depuis le centre du champ, scale 0.8 → 1.0 spring heavy, halo émeraude 0.14 → 0"),
          ("Erreur", "shake 6 cases synchronisé 12 px, 3 cycles, 120 ms"),
          ("Auto-remplissage", "les cases se remplissent de gauche à droite à 40 ms/chiffre")],
  rules=["6 chiffres exactement, valides 10 minutes, usage unique ; tout code consommé est révoqué.",
         "5 échecs = verrouillage 15 min + alerte sécurité interne (ADM-50).",
         "L'écran n'affiche JAMAIS le code ; il ne voyage que chiffré et n'est jamais journalisé en clair."],
  tokens=["--emerald-500", "--grad-emerald", "--gold-500", "--surface-2", "--squircle-14", "--mono"],
  api=["POST /v1/auth/otp/verify", "POST /v1/auth/otp/resend", "GET /v1/auth/otp/status"],
  tech="Shoulder-surfing : le code est masqué après 3 s d'inactivité (cases estompées). Autofill natif branché sur "
       "l'événement one-time-code ; saisie possible au pavé numérique sans fermeture de clavier.",
  a11y=["Chaque case a un aria-label « chiffre n sur 6 »", "role=status pour le chrono de renvoi, role=alert pour l'échec."],
  canon="Vérification OTP", chrome=CHROME_PUB),

S("PUB-07", "Récupération de compte", "PUB", "Authentification", "/recuperation", "Public", "P1", "Chemin de retour",
  intent="Ne jamais perdre un utilisateur légitime. Deux voies : lien magique par e-mail, ou code par SMS si le téléphone "
         "est vérifié. L'écran reste muet sur l'existence d'un compte (anti-énumération).",
  zones=[
    Z("hero", "Apaisement", 2, "« Reprenons ensemble. » Explication claire : la récupération ne modifie rien tant que vous n'êtes pas prouvé."),
    Z("form", "Identifiant", 3, "Champ e-mail ou téléphone (détection automatique du type), puis choix du canal si les deux existent."),
    Z("list", "Canaux", 3, "Deux tuiles : Lien magique par e-mail (icône enveloppe or) · Code SMS (icône bouclier émeraude, seulement si numéro vérifié)."),
    Z("cta", "Envoi", 2, "« Envoyer le lien de récupération » ; après envoi : vue de confirmation neutre valable qu'un compte existe ou non."),
  ],
  comps=[("Champ mixte", "e-mail ou téléphone avec détection live du format"),
         ("tuiles canal", "GlassTile cliquables, état sélectionné à anneau"),
         ("vue de confirmation", "sceau or discret, consigne de vérification spam, bouton retour connexion")],
  states=[("Neutre", "Champ vide, tuiles grisées jusqu'à identifiant valide."),
          ("Prêt", "Tuile recommandée mise en avant (celle du canal le moins risqué)."),
          ("Envoyé", "Confirmation neutre + minuteur de renvoi 60 s."),
          ("Aucun canal vérifié", "Message factuel + sortie « contacter le support » (ADM-02 passe la main).")],
  motion=[("Révélation des canaux", "stagger 60 ms après validation du champ"),
          ("Envoi", "avion en papier stylisé or, trajectoire courbe 640 ms, puis disparition"),
          ("Anti-brute force", "délais affichés en Mono, jamais de fausse barre")],
  rules=["Réponse identique (temps, message) que le compte existe ou non — protection contre l'énumération.",
         "Le lien expire en 15 min, usage unique ; toute réinitialisation invalide les sessions existantes (journalisé).",
         "Aucun SMS sur numéro non vérifié : le canal SMS n'apparaît que si phone_verified = true."],
  tokens=["--gold-500", "--emerald-500", "--glass-2", "--text-mid", "--mono"],
  api=["POST /v1/auth/recovery/start", "POST /v1/auth/recovery/confirm", "GET /v1/auth/recovery/channels"],
  tech="Écran double voie rendu RSC + îlot de formulaire. La vue de confirmation est un état interne, pas une route, "
       "pour éviter le flash de navigation et les fuites d'information dans l'historique.",
  canon="Récupération de compte", chrome=CHROME_PUB),

S("PUB-08", "CGU / Confidentialité", "PUB", "Légal", "/legal", "Public", "P1", "Document lisible",
  intent="Le droit ne doit pas être illisible. Rendu lecteur : titres clairs, résumés humains en encarts, texte intégral "
         "dépliable, version et hash affichés (preuve d'opposabilité).",
  zones=[
    Z("hero", "En-tête de version", 2, "« Conditions Générales — v3.2 » avec date d'entrée en vigueur, hash SHA-256 court en Mono, sélecteur de document (CGU · Confidentialité · Mentions · Cookies)."),
    Z("doc", "Corps du document", 6, "Sections numérotées, sommaire ancré à gauche, encarts « En clair » en --callout (résumé humain de chaque article critique)."),
    Z("cta", "Actions", 2, "« Accepter la version en vigueur » (or) quand un consentement est requis ; sinon « Télécharger le PDF » et « Copier le lien de version »."),
  ],
  comps=[("lecteur documentaire", "TOC collant, surlignage de la section active, ancres partageables"),
         ("encart « En clair »", "verre 1, bord gauche or 2 px"),
         ("badge de version", "Mono, hash tronqué a91f…c3"),
         ("export", "PDF généré côté serveur, empreinte R2 journalisée")],
  states=[("Lecture", "Couleurs pleines, TOC déployée sur desktop, tiroir sur mobile."),
          ("Consentement requis", "CTA or persistant en bas, scroll non obligatoire (jamais de dark pattern de scroll forcé)."),
          ("Version obsolète", "Bandeau ambre : « Une nouvelle version est en vigueur depuis le JJ/MM » + diff des articles modifiés."),
          ("Hors-ligne", "Dernière version en cache affichée avec mention d'horodatage.")],
  motion=[("Ancres", "défilement fluide 420 ms ease-labeur-out, levée du surlignage après 800 ms"),
          ("Tiroir TOC", "spring soft, backdrop verre 3"),
          ("Diff de version", "surlignage or des paragraphes modifiés, 2 pulses puis stabilisation")],
  rules=["Toute acceptation est horodatée avec la version ET le hash : c'est la preuve contractuelle.",
         "Aucun consentement groupé : CGU, communications produit et cookies ont des cases distinctes.",
         "Les résumés « En clair » n'ont jamais valeur juridique : mention explicite sous chaque encart."],
  tokens=["--surface-1", "--glass-1", "--gold-500", "--text-mid", "--callout", "--mono"],
  api=["GET /v1/legal/documents?locale=fr", "GET /v1/legal/documents/:id/version", "POST /v1/legal/consent"],
  tech="Côté web : contenu en RSC, indexation SEO propre. Côté mobile : même source MDX convertie, cache local versionné. "
       "Le PDF est servi depuis R2 avec URL signée courte.",
  canon="Légal (CGU/Confidentialité)", chrome=CHROME_PUB),

S("PUB-09", "Compte bloqué", "PUB", "Accès", "/compte-bloque", "Public", "P0", "Porte fermée, porte de sortie",
  intent="Un blocage est une décision, pas une panne. L'écran explique le motif (sans divulguer les détections de sécurité), "
         "la durée, et donne une voie de contestation réelle.",
  zones=[
    Z("hero", "Verdict de blocage", 3, "Sceau clay (╳) + « Votre compte est suspendu. » --title-1 ; sous-titre précisant le type : sécurité, litige en cours, manquement contractuel."),
    Z("timeline", "État de la mesure", 3, "Trois temps : mesure prononcée (date) → révision en cours (si appel) → échéance ou décision. Points horodatés Mono."),
    Z("list", "Ce qui reste possible", 3, "Tuiles : Télécharger mes données (conformité) · Consulter mes contrats et preuves · Déposer une contestation (formulaire → ADM-26)."),
    Z("cta", "Sortie", 1, "« Déposer une contestation » (or si voie ouverte) · « Se déconnecter » (ghost)."),
  ],
  comps=[("C-04 StatusSeal", "variante clay, glyphe ╳, halo froid"),
         ("bloc motifs", "liste des raisons génériques (jamais les règles de détection)"),
         ("bouton contestation", "ouvre un formulaire structuré avec preuve jointe R2"),
         ("badge d'échéance", "Mono, « révision prévue le … »")],
  states=[("Blocage automatique", "Motif : sécurité. Contestation possible sous 72 h."),
          ("Blocage sur litige", "Motif : litige ouvert. Renvoi vers EMP/PRE-49, montants gelés affichés en FIN."),
          ("Blocage définitif", "Motif : manquement grave après décision ADM. Contestation écrite uniquement."),
          ("Blocage levé", "Historique conservé ; l'écran devient consultable en lecture seule depuis les paramètres.")],
  motion=[("Entrée du verdict", "sceau clay qui se referme en sens inverse (contre-forge), 640 ms"),
          ("Particules", "dérive descendante, densité 60, alpha 0.06"),
          ("Cohérence", "aucun élément doré pulsant : pas de récompense dans un écran de sanction")],
  rules=["Aucun outil de contournement n'est suggéré ; l'écran ne révèle ni seuils ni signatures de détection.",
         "Les données restent exportables (droit à la portabilité) sauf ordre contraire journalisé.",
         "Le délai de traitement d'une contestation est affiché ; il est contractuel côté support."],
  tokens=["--clay-500", "--clay-600", "--surface-1", "--text-mid", "--mono", "--squircle-28"],
  api=["GET /v1/account/block-status", "POST /v1/account/appeal", "GET /v1/account/export"],
  tech="Écran partagé avec SYS-03 (403) : même composant StateGuard, contenu injecté par le motif renvoyé par l'API. "
       "Le formulaire d'appel accepte photos/PDF → R2, avec hash affiché avant envoi.",
  canon="Compte bloqué", chrome=CHROME_PUB),

S("PUB-10", "Maintenance", "PUB", "Système", "/maintenance", "Public", "P0", "Fenêtre annoncée",
  intent="Quand LE LABEUR est en maintenance planifiée, l'écran doit dire quoi, quand, et ce qui reste possible "
         "(preuves sauvegardées, paiements en cours gelés mais tracés).",
  zones=[
    Z("hero", "Fenêtre & raison", 3, "« LE LABEUR revient à 14:30. » Compte à rebours Mono ; motif factuel (migration PostgreSQL, montée Cluster Hyperdrive)."),
    Z("timeline", "Opérations en cours", 4, "Frise des étapes techniques traduites en langage humain : sauvegardes ✓ · migration contracts ◔ · reprise des queues ○. Pas de jargon creux."),
    Z("list", "Ce qui n'est pas perdu", 3, "Encarts : vos preuves et pièces R2 sont intactes · les paiements en cours reprendront dans l'ordre · les échéances du jour sont reportées au lendemain (jamais de pénalité)."),
    Z("cta", "Suivre", 2, "« Me prévenir à la reprise » (notification push/e-mail) · « Voir l'état des services » → page statut."),
  ],
  comps=[("compte à rebours Mono", "synchro serveur, jamais basée sur l'horloge locale seule"),
         ("frise d'opérations", "glyphes ✓ ◔ ○, émeraude/or/ardoise"),
         ("carte d'engagement", "« aucun délai perdu » : politique de report affichée"),
         ("CTA notification", "opt-in explicite, une seule fois")],
  states=[("Planifiée", "Compte à rebours > 0, annonce à l'avance (bandeau dans les autres écrans)."),
          ("En cours", "Étape active pulsée, progression réelle (pas de fausse barre)."),
          ("Dépassement", "Message honnête : « Cela prend plus de temps que prévu. » + nouvelle estimation."),
          ("Reprise", "Transition vers PUB-02 avec sceau émeraude et rappel des échéances reportées.")],
  motion=[("Compte à rebours", "tick 1 s, chiffres Mono qui glissent verticalement 120 ms"),
          ("Frise", "révélation séquentielle 240 ms, pulsation douce sur l'étape active"),
          ("Reprise", "sceau émeraude éclos du centre, puis redirection")],
  rules=["Aucune maintenance silencieuse : la fenêtre est annoncée au minimum 24 h avant (sauf urgence sécurité).",
         "Les échéances contractuelles touchées par une fenêtre planifiée sont automatiquement reportées et tracées (INV-3).",
         "L'écran reste accessible même si le reste de l'API est fermé : il est servi par le Worker edge statique."],
  tokens=["--surface-0", "--gold-500", "--emerald-500", "--mono", "--text-mid", "--glass-1"],
  api=["GET /v1/status/window", "GET /v1/status/services", "POST /v1/notify/maintenance-resume"],
  tech="Servi statiquement par le Worker Cloudflare (indépendant de l'API PostgreSQL) pour rester disponible "
       "précisément quand le reste tombe. Contenu rafraîchi par KV (TTL 30 s).",
  canon="Maintenance", chrome=CHROME_PUB),
]
