# -*- coding: utf-8 -*-
"""FAMILLE 05a · WEBRTC & TEMPS RÉEL — RTC-01 → RTC-08"""
from ..model import S, Z

CHROME_RTC = {"appbar": "SESSION", "glyph": "◉"}

SCREENS = [

S("RTC-01", "Pré-appel — vérification", "RTC", "Sessions temps réel", "/appel/:id/preparation", "Client/Prestataire", "P0", "Se préparer",
  intent="Avant un appel important (entrevue, médiation), vérifier matériel, réseau et contexte : caméra, micro, haut-parleur, "
         "qualité de connexion, objet de l'appel, et consentement à l'enregistrement. Trois minutes de préparation évitent un rendez-vous raté.",
  zones=[
    Z("hero", "Objet de l'appel", 3, "Type (entrevue · point d'exécution · médiation), mission liée (réf Mono), interlocuteur (rôle, pas de nom si non engagé), créneau, durée prévue."),
    Z("media", "Auto-vérification", 5, "Aperçu local (caméra), onde de niveau micro en direct, test haut-parleur (ton court), sélection périphérique si desktop. Aucune image n'est transmise : tout est local."),
    Z("kpi", "État réseau & consentement", 4, "Latence estimée, perte, type de relais (direct/TURN) · consentement d'enregistrement : état des deux parties, conséquence si refus (aucun enregistrement)."),
    Z("cta", "Entrer", 2, "« Rejoindre la session » or (armé si micro et réseau OK) · « Rejoindre sans caméra » fantôme · « Reporter » texte."),
  ],
  comps=[("C-16 CallSurface", "aperçu local uniquement"),
         ("Jauge micro", "onde réelle, sensibilité visualisée"),
         ("Test audio", "ton court, une seule fois, volume limité"),
         ("Bloc consentement", "état des deux parties, refus respecté par construction")],
  states=[("Prêt", "tout est vert, CTA or."),
          ("Micro indisponible", "clay : cause probable (permission, périphérique occupé) + chemin de correction."),
          ("Réseau faible", "ambre : avertissement franc, options (rejoindre en audio seul, décaler)."),
          ("Interlocuteur absent", "ardoise : présence détectée de l'autre partie, temps d'attente."),
          ("Sans consentement croisé", "violet : enregistrement désactivé, mention explicite — la session reste possible.")],
  motion=[("Jauge micro", "onde 60 fps, lissage 120 ms"),
          ("Test audio", "ton 480 ms, fondu d'entrée/sortie"),
          ("Entrée en session", "aperçu qui s'agrandit vers le plein écran, 420 ms")],
  rules=["Aucun flux n'est transmis avant l'entrée en session : la vérification est strictement locale (le dit explicitement).",
         "L'enregistrement n'existe que si les DEUX parties consentent : l'état est affiché en permanence pendant la session.",
         "Un rapport de pré-appel est proposé et mis en avant si la qualité réseau est insuffisante — jamais d'appel raté par surprise."],
  tokens=["--cyan-500", "--emerald-500", "--amber-500", "--clay-500", "--glass-2"],
  api=["GET /v1/calls/:id/precheck", "POST /v1/calls/:id/consent {recording}", "POST /v1/calls/:id/join"],
  tech="Vérification locale (getUserMedia + WebRTC stats) ; le serveur ne reçoit qu'un état agrégé (qualité estimée), jamais "
       "d'image. TURN/STUN sont utilisés automatiquement selon le réseau.",
  canon="RTC — pré-appel", chrome=CHROME_RTC),

S("RTC-02", "Invitation & sonnerie", "RTC", "Sessions temps réel", "/appel/:id/invitation", "Client/Prestataire", "P1", "Recevoir l'appel",
  intent="Une invitation claire et non intrusive : qui appelle, pour quelle mission, à quel sujet, avec quels interlocuteurs. "
         "Refuser doit être facile — un appel professionnel n'est pas un piège.",
  zones=[
    Z("hero", "Contexte de l'invitation", 4, "Appelant (rôle + fiabilité), type d'appel, mission liée, objet résumé, créneau. Photo d'identité si relation contractuelle existante."),
    Z("kpi", "Conditions", 3, "Consentement d'enregistrement demandé par l'appelant (oui/non) · durée prévue · possibilité de rejoindre en audio seulement."),
    Z("cta", "Répondre", 3, "« Rejoindre » émeraude (gros bouton) · « Rejoindre en audio seul » fantôme · « Refuser » clay outline avec motifs (indisponible · reporter · sans motif)."),
  ],
  comps=[("C-16 CallSurface", "variante invitation, fond verre 3"),
         ("Bouton d'acceptation", "grande cible, une seule action principale"),
         ("Motifs de refus", "trois options, aucune justification obligatoire"),
         ("Sonnerie", "discrète, respect des heures calmes (hors urgence média)")],
  states=[("Sonnerie", "durée limitée (45 s), notification système si app en arrière-plan."),
          ("Refus", "notification neutre à l'appelant, aucun motif si non fourni."),
          ("Déjà en appel", "bandeau : « vous êtes déjà en session » → basculer ou refuser."),
          ("Appel annulé par l'appelant", "état sobre, aucune culpabilisation."),
          ("Reporté", "proposition d'un nouveau créneau, message horodaté.")],
  motion=[("Sonnerie", "pulsation douce du halo, 1 Hz, jamais agressive"),
          ("Répondre", "bouton qui s'agrandit vers la session (shared element) 420 ms"),
          ("Refuser", "fondu sobre 240 ms")],
  rules=["Refuser un appel n'entraîne jamais de pénalité de réputation ; les motifs sont facultatifs et confidentiels.",
         "Aucun appel ne peut être organisé hors du contexte d'une mission ou d'un dossier : le rattachement est obligatoire.",
         "Les heures calmes s'appliquent aux invitations ; seules les mises en relation déjà acceptées peuvent sonner hors plages.",
         "L'appelant ne voit jamais si l'invitation a été « vue mais refusée » : la discrétion est un droit."],
  tokens=["--emerald-500", "--cyan-500", "--clay-500", "--glass-3", "--mono"],
  api=["GET /v1/calls/:id/invitation", "POST /v1/calls/:id/accept {audioOnly}", "POST /v1/calls/:id/decline {reason?}"],
  tech="Service de signalisation (WebSocket) + notifications push avec priorité média. La sonnerie respecte les "
       "préférences utilisateur (heures calmes) sauf exception « relation en cours d'appel ».",
  canon="RTC — invitation", chrome=CHROME_RTC),

S("RTC-03", "Connexion en cours", "RTC", "Sessions temps réel", "/appel/:id/connexion", "Client/Prestataire", "P1", "L'attente expliquée",
  intent="Pendant l'établissement de la connexion (négociation ICE, relais TURN, médias), montrer l'état réel : étapes "
         "franchies, latence, estimation honnête. L'attente technique ne doit jamais ressembler à une panne.",
  zones=[
    Z("media", "Écran d'établissement", 5, "Fond noir absolu, halo cyan respirant, texte d'étape : « établissement du canal sécurisé… », « négociation des relais… », « activation des flux… ». Aucun faux compte à rebours."),
    Z("kpi", "Transparence technique", 3, "Type de connexion tentée (direct, TURN), latence mesurée en direct, durée d'établissement (Mono). Résumé accessible en un tap « détails »."),
    Z("cta", "Contrôle", 2, "« Annuler » fantôme · « Rejoindre en audio seul » (si le média vidéo échoue) · « Diagnostic réseau » texte (RTC-07)."),
  ],
  comps=[("Halo d'établissement", "cyan, respiration 2 400 ms"),
         ("Liste d'étapes", "réelles, données par la couche WebRTC"),
         ("Bouton de repli audio", "offert dès que la vidéo pose problème")],
  states=[("Établissement', 1-3 s", "étapes qui défilent, halo actif."),
          ("Relais nécessaire", "mention « passage par un relais sécurisé » — honnête sur la latence supplémentaire."),
          ("Échec vidéo", "proposition audio seul, formulée clairement."),
          ("Échec total", "clay : cause probable (réseau, permission), alternatives (replanifier, appel téléphonique de secours encadré), incident créé automatiquement.")],
  motion=[("Halo", "respiration douce, jamais de spinner agressif"),
          ("Étape franchie", "point qui passe émeraude 240 ms"),
          ("Bascule audio", "vidéo qui s'éteint en fondu, interface qui se réorganise 420 ms")],
  rules=["Aucun compte à rebours factice : l'attente réelle est affichée, même si elle est longue.",
         "Au-delà de 15 s d'établissement, l'utilisateur reçoit une explication et une option de repli — jamais un écran muet.",
         "Un échec de connexion génère automatiquement un diagnostic (RTC-07) et une trace exploitée par ADM-61."],
  tokens=["--cyan-500", "--emerald-500", "--clay-500", "--mono", "--glass-1"],
  api=["GET /v1/calls/:id/connection-state", "POST /v1/calls/:id/downgrade {audioOnly: true}", "POST /v1/calls/:id/cancel"],
  tech="États fournis directement par la pile WebRTC (ICE candidates, DTLS, media). Aucune simulation : l'UI est un miroir "
       "de l'état réel, mis à jour par événements.",
  canon="RTC — connexion", chrome=CHROME_RTC),

S("RTC-04", "Session active", "RTC", "Sessions temps réel", "/appel/:id", "Client/Prestataire", "P0", "La conversation",
  intent="L'appel en cours : le contenu est roi, l'interface s'efface. Contrôles accessibles mais discrets, indicateurs "
         "honnêtes, fonctions d'aide (partage de pièce, note horodatée) intégrées sans encombrer.",
  zones=[
    Z("media", "Flux principal", 7, "Vidéo plein cadre ou grille (max 4 participants). PIP local déplaçable en coin. Aucun cadre, aucune ombre : le contenu occupe l'écran."),
    Z("kpi", "Bandeau de session", 2, "Objet de l'appel + mission (Mono) · durée · indicateur réseau (3 barres) · état d'enregistrement (si consenti, affiché en permanence). Bouton « détails » pour les métriques."),
    Z("cta", "Contrôles", 2, "Barre basse verre 3 : micro, caméra, partage d'écran (si autorisé), note rapide, raccrocher. Chaque contrôle : icône + état, cibles 44 px."),
  ],
  comps=[("C-16 CallSurface", "gestion des pistes, redondance, reconnexion"),
         ("PIP local", "déplaçable, magnétisme aux coins"),
         ("Bandeau d'enregistrement", "persistant, non masquable, avec mention de consentement des deux parties"),
         ("Note rapide", "création d'une note horodatée rattachée à la mission, visible après l'appel"),
         ("Partage de pièce", "envoyer un document du dossier à l'interlocuteur pendant l'appel (traçé)")],
  states=[("Normal", "interface minimale, indicateurs sobres."),
          ("Réseau dégradé", "une barre, bandeau ambre discret + suggestion « passer en audio »."),
          ("Reconnexion", "bandeau « reconnexion en cours » avec compte à rebours réel, la session tient si possible."),
          ("Un participant seul", "message sobre « en attente de l'autre participant » + invitation à vérifier."),
          ("Enregistrement consenti", "point rouge discret + double consentement affiché.")],
  motion=[("Contrôles", "barre qui s'efface après 4 s d'inactivité, revient au tap (timing 240 ms)"),
          ("PIP", "magnétisme, spring snap"),
          ("Reconnexion", "bascule sobre, sans clignotement")],
  rules=["Aucun masquage de l'état d'enregistrement : si l'enregistrement est actif, l'indicateur est visible en permanence pour tous.",
         "Les notes prises pendant l'appel sont horodatées et rattachées à la mission : elles pourront servir de preuve (et sont visibles des deux parties si partagées).",
         "Le partage d'écran est désactivé par défaut et nécessite un accord explicite de l'autre partie.",
         "Aucun filtre, arrière-plan virtuel ou effet n'est disponible : le produit ne maquille pas les personnes.",
         "L'appel n'est jamais enregistré sans les deux consentements, même en cas de litige."],
  tokens=["--surface-0", "--cyan-500", "--emerald-500", "--clay-500", "--glass-3"],
  api=["POST /v1/calls/:id/tracks {audio, video}", "POST /v1/calls/:id/notes", "POST /v1/calls/:id/share {documentId}", "POST /v1/calls/:id/hangup"],
  tech="SFU (LiveKit/mediasoup) avec redondance, TURN pour réseaux restrictifs, reprise de session (ICE restart) et gestion "
       "fine de la bande passante. Les métriques sont poussées en continu vers ADM-61.",
  a11y=["Tous les contrôles ont un libellé vocal et un état énoncé (micro actif/coupé).",
        "Une transcription temps réel optionnelle est disponible (agentivité : utile pour les personnes sourdes)."],
  canon="RTC — session active", chrome=CHROME_RTC),

S("RTC-05", "Fin de session & résumé", "RTC", "Sessions temps réel", "/appel/:id/fin", "Client/Prestataire", "P1", "Après l'appel",
  intent="Clore une session proprement : durée, participants, décisions prises, prochaines étapes, et — si consenti — "
         "l'accès à l'enregistrement. L'appel doit servir le dossier, pas disparaître.",
  zones=[
    Z("verdict", "Bilan de session", 3, "Durée réelle, type, participants (rôles), qualité moyenne (indicateur), enregistrement (oui/non, consentement)."),
    Z("list", "Décisions & suites", 4, "Points convenus saisis pendant l'appel (notes horodatées) + actions créées automatiquement : « envoyer la pièce demandée », « planifier la prochaine étape », « déposer une preuve »."),
    Z("doc", "Enregistrement & pièces", 3, "Si consenti : accès à l'enregistrement (lecture, téléchargement), partagé aux deux parties, avec empreinte et durée de conservation affichée."),
    Z("cta", "Actions", 2, "« Rattacher au dossier » or (note de synthèse) · « Partager un résumé » fantôme (aux deux parties) · « Signaler un problème » texte."),
  ],
  comps=[("Carte de bilan", "chiffres tnum, indicateurs"),
         ("Notes converties en actions", "chaque note peut devenir une action assignée"),
         ("Lecteur d'enregistrement", "horodaté, chapitrage par note"),
         ("Empreinte d'enregistrement", "hash Mono, conservation selon politique affichée")],
  states=[("Sans enregistrement", "état normal (majorité des cas), aucune gêne."),
          ("Avec enregistrement", "accès conforme, mention de la durée de conservation (30 jours par défaut, prolongation sur litige)."),
          ("Appel interrompu", "bilan partiel conservé, cause affichée, note de reprise proposée."),
          ("Appel en litige", "si un litige est ouvert peu après : l'enregistrement est conservé automatiquement jusqu'à résolution.")],
  motion=[("Bilan", "carte qui se déplie 420 ms"),
          ("Actions", "création visible d'une action (fly-to vers la liste)"),
          ("Lecteur", "chapitres cliquables, saut doux 240 ms")],
  rules=["Le résumé est envoyé aux deux parties (ou à aucune) : jamais un résumé unilatéral que l'autre ne verrait pas.",
         "L'enregistrement, s'il existe, est accessible aux deux parties à égalité — jamais à une seule.",
         "La conservation des enregistrements est limitée par défaut (30 jours) et prolongée automatiquement en cas de litige.",
         "Les notes privées ne sont possibles que si elles sont explicitement marquées « privées » — et elles ne peuvent pas servir de preuve unilatérale."],
  tokens=["--emerald-500", "--gold-500", "--cyan-500", "--mono", "--glass-1"],
  api=["GET /v1/calls/:id/summary", "POST /v1/calls/:id/actions", "GET /v1/calls/:id/recording", "POST /v1/calls/:id/report"],
  tech="Résumé assemblé depuis le service d'appels (métadonnées) et les notes ; la synthèse est rédigée par les participants "
       "(aucune transcription automatique n'est utilisée comme décision). L'enregistrement est stocké en R2 chiffré avec accès contrôlé.",
  canon="RTC — fin de session", chrome=CHROME_RTC),

S("RTC-06", "Sessions historiques", "RTC", "Sessions temps réel", "/appels", "Client/Prestataire", "P2", "Journal des appels",
  intent="Retrouver toutes ses sessions passées : avec qui, à quel sujet, quand, et quelles suites. Utile pour un dossier "
         "de litige, une réquisition, ou simplement pour se souvenir.",
  zones=[
    Z("list", "Liste des sessions", 6, "Carte par session : date, type, mission (Mono), participants (rôles), durée, qualité, enregistrement disponible, suites créées."),
    Z("kpi", "Synthèse", 2, "Sessions 30 jours · durée totale · qualité moyenne · enregistrements conservés."),
    Z("cta", "Actions", 1, "« Ouvrir une session » or · « Filtrer » fantôme (par mission, type, période)."),
  ],
  comps=[("Carte de session", "durée et qualité, accès au résumé"),
         ("Badge d'enregistrement", "présent si disponible et consenti"),
         ("Lien mission", "rattachement systématique")],
  states=[("Vide", "« Aucun appel pour l'instant. » + explication des contextes d'appel."),
          ("Long", "pagination par mois."),
          ("Session liée à un litige", "badge clay + accès prioritaire (preuve potentielle)."),
          ("Enregistrement purgé", "mention claire « enregistrement expiré le … » (done ce qui a existé).")],
  motion=[("Liste", "stagger 60 ms"),
          ("Ouverture", "panneau latéral 240 ms")],
  rules=["L'historique des appels est conservé avec leurs métadonnées (jamais le contenu sans consentement).",
         "Chaque session est rattachée à une mission ou un dossier : aucun appel « orphelin ».",
         "Le travailleur peut voir la qualité de ses appels passés : information utile pour choisir ses créneaux et réseaux."],
  tokens=["--surface-1", "--cyan-500", "--mono", "--text-lo"],
  api=["GET /v1/calls/history?cursor=", "GET /v1/calls/:id/summary"],
  tech="Read model des sessions ; purge des enregistrements automatique, métadonnées conservées 24 mois minimum.",
  canon="RTC — sessions historiques", chrome=CHROME_RTC),

S("RTC-07", "Diagnostic réseau & qualité", "RTC", "Sessions temps réel", "/appel/:id/diagnostic", "Client/Prestataire", "P1", "Comprendre la mauvaise qualité",
  intent="Aider l'utilisateur à comprendre et améliorer la qualité : type de connexion, latence, perte, relais utilisé, "
         "et conseils actionnables (Wi-Fi, position, fermeture d'applications). Sans jargon, sans blâmer.",
  zones=[
    Z("kpi", "Indicateurs", 4, "Latence (ms, aller-retour) · perte de paquets (%) · gigue (ms) · type de connexion (direct / relais TURN) · bande passante estimée. Chaque valeur avec sa bande de qualité."),
    Z("list", "Conseils actionnables", 4, "Recommandations contextuelles : « passez du mobile au Wi-Fi », « rapprochez-vous du routeur », « fermez les applications gourmandes », « réduisez la vidéo en 360p » (option réelle et applicable en un tap)."),
    Z("timeline", "Qualité pendant l'appel", 3, "Courbe de qualité sur la session, avec annotations des événements (changement de réseau, activation du relais)."),
    Z("cta", "Actions", 1, "« Passer en 360p » or · « Continuer en audio seul » fantôme · « Envoyer le diagnostic au support » texte (rapport technique expurgé)."),
  ],
  comps=[("Bandes de qualité", "bonne/dégradée/mauvaise, pas de jargon"),
         ("Conseils contextuels", "appliqués aux conditions réelles détectées"),
         ("Courbe de session", "événements annotés"),
         ("Rapport expurgé", "le support reçoit des métriques, sans contenu ni identité")],
  states=[("Bonne qualité", "état serein, conseils masqués (pas de bruit)."),
          ("Dégradée", "ambre : conseils affichés, options de repli proposées."),
          ("Mauvaise", "clay : proposition d'audio seul, de replanification, ou d'appel téléphonique encadré."),
          ("Relais imposé", "explication : « votre réseau bloque les connexions directes » (fait, non culpabilisant).")],
  motion=[("Courbe", "tracé 420 ms à l'ouverture"),
          ("Changement de qualité", "bande qui glisse progressivement, jamais brutale")],
  rules=["Le diagnostic est accessible depuis la session active sans l'interrompre.",
         "Les conseils sont fondés sur des mesures réelles : aucun conseil générique affiché sans lien avec les données.",
         "Le rapport envoyé au support est expurgé (aucun contenu média, aucune identité de l'autre participant)."],
  tokens=["--cyan-500", "--amber-500", "--clay-500", "--mono"],
  api=["GET /v1/calls/:id/diagnostics", "POST /v1/calls/:id/quality/profile {preset}", "POST /v1/calls/:id/diagnostics/send"],
  tech="Statistiques WebRTC (RTT, jitter, packet loss, bitrate, candidate pairs) exposées par la pile ; les conseils sont "
       "dérivés par règles simples côté client, avec envoi serveur pour l'analyse d'incident.",
  canon="RTC — diagnostic", chrome=CHROME_RTC),

S("RTC-08", "Enregistrement & consentement", "RTC", "Sessions temps réel", "/appel/:id/consentement", "Client/Prestataire", "P0", "Consentir ou refuser",
  intent="Gérer le consentement d'enregistrement d'une session : demander, accepter, refuser, révoquer. Le consentement "
         "est un droit vivant — il peut être retiré et l'enregistrement s'arrête immédiatement.",
  zones=[
    Z("hero", "Demande de consentement", 4, "Qui demande (rôle), pourquoi (option : trace de la médiation, preuve en cas de désaccord), durée de conservation proposée, qui pourra le consulter (les deux parties uniquement)."),
    Z("list", "Ce que cela implique", 4, "Points explicites : enregistrement audio+vidéo · accès limité aux deux parties · conservation 30 jours (prolongée en cas de litige) · révocation possible à tout moment · aucune utilisation par la plateforme pour autre chose."),
    Z("kpi", "État actuel", 3, "Votre consentement : accordé/refusé · Consentement de l'autre partie (affiché en état, sans pression) · Enregistrement : actif/inactif."),
    Z("cta", "Décider", 2, "« J'accepte l'enregistrement » émeraude · « Je refuse » clay outline (aucune justification) · « Révoquer mon consentement » (si déjà accordé) texte."),
  ],
  comps=[("Bloc de consentement", "deux états symétriques, aucune pression visuelle"),
         ("Indicateur d'enregistrement", "point rouge persistant pendant la session, visible des deux côtés"),
         ("Bouton de révocation", "immédiat, l'enregistrement s'arrête et le fichier partiel est supprimé ou conservé selon politique affichée")],
  states=[("En attente", "enregistrement inactif jusqu'aux deux accords."),
          ("Accordé mutuellement", "enregistrement actif, indicateur permanent pour tous."),
          ("Refus", "enregistrement impossible, session normale, aucune conséquence relationnelle affichée."),
          ("Révocation", "arrêt immédiat, choix explicite sur le sort du fichier partiel (supprimer par défaut)."),
          ("Litige ouvert après coup", "prolongation automatique de conservation annoncée si un litige est ouvert ensuite.")],
  motion=[("Accord", "sceau émeraude sobre 480 ms"),
          ("Révocation", "l'indicateur s'éteint, confirmation de destruction 480 ms"),
          ("Refus", "fondu sobre, aucune animation punitive")],
  rules=["Le refus d'enregistrement n'a aucune conséquence : ni dans la session, ni dans le dossier, ni dans la réputation.",
         "La révocation est un droit immédiat, exercé sans motivation, dont l'effet est visible par les deux parties.",
         "L'enregistrement ne peut jamais servir à autre chose qu'à la trace de la session (aucune analyse automatisée de contenu, aucun entraînement).",
         "La conservation est bornée et affichée ; en cas de litige ouvert ensuite, la prolongation est automatique et annoncée."],
  tokens=["--emerald-500", "--clay-500", "--surface-2", "--mono", "--glass-4"],
  api=["GET /v1/calls/:id/consent", "POST /v1/calls/:id/consent {recording: true|false}", "POST /v1/calls/:id/consent/revoke"],
  tech="Le consentement est un objet d'état partagé, vérifié côté serveur à chaque segment d'enregistrement (le pipeline "
       "refuse d'écrire sans double consentement actif). La révocation coupe l'écriture en moins de 1 s.",
  a11y=["Le refus est une cible de même taille que l'acceptation : aucun dark pattern de consentement."],
  canon="RTC — consentement", chrome=CHROME_RTC),
]
