# -*- coding: utf-8 -*-
"""FAMILLE 05b · ÉTATS SYSTÈME — SYS-01 → SYS-15
Tous les écrans de cette famille sont produits par le composant C-19 StateGuard :
glyphe + phrase factuelle + action de sortie + identifiant de corrélation copiable.
"""
from ..model import S, Z

CHROME_SYS = {"glyph": "▤"}

def _guard(desc):
    return [
        ("C-19 StateGuard", "gabarit unique : glyphe, titre factuel, explication, sortie, trace_id"),
        ("Code de corrélation", "Mono copiable, lié à la requête serveur (jamais un identifiant secret)"),
        ("Action de sortie", "la plus utile, jamais générique : réessayer, revenir, se reconnecter, contacter"),
    ]

SCREENS = [

S("SYS-01", "Chargement", "SYS", "États système", "/etat/chargement", "Système", "P2", "Attente habitée",
  intent="Habiller l'attente sans mentir : squelettes à la forme exacte du contenu, progression réelle quand elle existe, "
         "jamais de spinner nu ni de fausse barre.",
  zones=[
    Z("list", "Squelettes fidèles", 5, "Squelettes à la teinte et à la géométrie du contenu attendu (cartes mission, tables, folio de contrat). Aucun gris générique : surfaces basalte avec shimmer très discret."),
    Z("kpi", "Progression réelle (si connue)", 3, "Quand le serveur expose une progression (upload, génération PDF), elle est affichée en % réel. Sinon, aucun pourcentage inventé."),
    Z("canvas", "Particules à densité minimale", 2, "Dérive lente, densité 40, alpha 0.06 : signe de vie sans distraction."),
  ],
  comps=_guard("Attente"),
  states=[("Court (< 300 ms)", "rien n'est affiché : le squelette n'apparaît qu'au-delà de 300 ms (anti-flash)."),
          ("Standard", "squelettes + shimmer 1 600 ms."),
          ("Long (> 8 s)", "message d'honnêteté : « cela prend plus de temps que prévu » + option de sortie."),
          ("Échec du chargement", "bascule vers le code d'erreur approprié (SYS-09, SYS-02).")],
  motion=[("Shimmer", "balayage 1 600 ms, opacité 0.03 → 0.06, jamais clignotant"),
          ("Remplacement", "cross-fade squelettes → contenu 240 ms"),
          ("Particules", "60 fps, suspendues si la page n'est pas visible")],
  rules=["Aucun squelette ne doit avoir une forme différente du contenu final (pas de surprise de layout).",
         "Aucun indicateur de progression factice : % réel ou rien.",
         "L'écran est annulable : l'utilisateur peut revenir en arrière pendant le chargement."],
  tokens=["--surface-1", "--surface-2", "--text-lo", "--glass-1"],
  api=["(transverse — aucun endpoint propre)"],
  tech="Composant partagé par toutes les familles (C-19 variante chargement) ; le shimmer est désactivé sous "
       "prefers-reduced-motion (squelette statique).",
  canon="SYS — chargement", chrome=CHROME_SYS),

S("SYS-02", "Hors-ligne", "SYS", "États système", "/etat/hors-ligne", "Système", "P0", "Travailler sans réseau",
  intent="Quand le réseau disparaît, LE LABEUR ne s'arrête pas : montrer ce qui reste disponible, ce qui est conservé, et "
         "ce qui repartira automatiquement. Le travailleur en zone rurale doit pouvoir continuer à préparer ses preuves.",
  zones=[
    Z("hero", "État hors-ligne", 3, "Glyphe réseau barré ardoise + « Vous êtes hors ligne. » + temps depuis la dernière synchronisation (Mono)."),
    Z("list", "Ce qui fonctionne quand même", 4, "Consultable : missions en cours, contrats signés, preuves déjà déposées. Préparables hors-ligne : dépôt de preuve (ci-joint média + file d'envoi), notes. Interdit (dit clairement) : paiements, signatures, candidatures."),
    Z("kpi", "File d'envoi", 3, "N éléments en attente · taille estimée · « ils partiront automatiquement au retour du réseau » · bouton « réessayer maintenant »."),
    Z("cta", "Actions", 1, "« Réessayer » or · « Gérer la file d'envoi » fantôme (voir, supprimer un brouillon) · « Continuer hors-ligne » texte."),
  ],
  comps=_guard("Hors-ligne"),
  states=[("Détection", "bascule en moins de 2 s après perte de connexion."),
          ("File non vide", "compteur visible en permanence dans la barre d'état applicative."),
          ("Reconnexion", "bandeau émeraude : « réseau retrouvé, envoi de 3 éléments… » avec progression réelle."),
          ("Échec d'envoi au retour", "clay : élément conservé, motif affiché, aucune perte silencieuse.")],
  motion=[("Bascule", "fondu 240 ms vers l'état hors-ligne, aucune secousse"),
          ("Reconnexion", "bandeau émeraude qui descend 240 ms, puis disparaît après 3 s"),
          ("File", "éléments qui s'égrènent au fur et à mesure de l'envoi")],
  rules=["Aucun média capturé hors-ligne n'est jamais perdu : la file locale est chiffrée et persistante.",
         "Les actions engageantes (paiement, signature, candidature) sont explicitement indisponibles hors-ligne — on ne prend pas d'engagement sans confirmation serveur.",
         "Au retour du réseau, chaque élément en attente est envoyé avec sa clé d'idempotence : aucun doublon possible."],
  tokens=["--slate-500", "--amber-500", "--emerald-500", "--mono"],
  api=["GET /v1/health/heartbeat (sonde locale)", "POST /v1/sync/batch {queue}"],
  tech="Détection via heartbeat + events réseau natifs ; file d'attente locale chiffrée (preuves, brouillons) avec reprise "
       "et idempotence côté serveur.",
  canon="SYS — hors-ligne", chrome=CHROME_SYS),

S("SYS-03", "401 — Session expirée", "SYS", "États système", "/etat/401", "Système", "P0", "Se reconnecter sans perdre son travail",
  intent="Une session expirée n'est jamais une punition : l'écran protège le travail en cours, explique pourquoi, et "
         "ramène l'utilisateur exactement là où il était.",
  zones=[
    Z("hero", "État 401", 3, "Glyphe clé ardoise + « Votre session a expiré. » + raison factuelle (inactivité, changement d'appareil, révoquée)."),
    Z("list", "Protection du travail en cours", 4, "« Nous avons conservé votre brouillon », « votre dépôt de preuve est en file d'attente », « votre candidature n'a pas été envoyée » : rien n'est perdu, et l'écran le garantit explicitement."),
    Z("kpi", "Retour au contexte", 3, "« Vous reviendrez ici après connexion » avec l'écran de destination affiché (nom + type de contenu), et la garantie que la position est mémorisée."),
    Z("cta", "Actions", 2, "« Se reconnecter » or (retour PUB-04 avec e-mail pré-rempli) · « Se reconnecter ailleurs » fantôme (code par e-mail)."),
  ],
  comps=_guard("401"),
  states=[("Expiration par inactivité", "route standard, brouillons conservés."),
          ("Session révoquée (sécurité)", "clay atténué : « session fermée par sécurité » + explication (appareil retiré, mot de passe changé)."),
          ("Multi-appareils", "si connexion sur un autre appareil : mention claire, aucune alarme."),
          ("Retour réussi", "restitution exacte du contexte, y compris brouillons et files.")],
  motion=[("Entrée", "fondu 240 ms, jamais de redirection brutale"),
          ("Retour", "retour au contexte avec un bref surlignage 640 ms de l'élément en cours")],
  rules=["Aucune perte de saisie : les brouillons vivent localement et sont restaurés après reconnexion.",
         "La destination de retour est affichée AVANT la reconnexion : l'utilisateur sait où il atterrit.",
         "Une révocation de session par sécurité est expliquée (jamais silencieuse)."],
  tokens=["--slate-500", "--emerald-500", "--mono", "--surface-2"],
  api=["POST /v1/auth/refresh", "GET /v1/auth/session/context"],
  tech="Intercepteur HTTP : au 401, l'écran est monté avec le contexte de navigation sérialisé ; le refresh silencieux est "
       "tenté d'abord (l'écran ne s'affiche que s'il échoue).",
  canon="SYS — 401", chrome=CHROME_SYS),

S("SYS-04", "403 — Accès refusé", "SYS", "États système", "/etat/403", "Système", "P0", "Refus expliqué",
  intent="Dire pourquoi l'accès est refusé et comment y accéder légitimement : permission manquante, rôle inadapté, "
         "ressource verrouillée. Jamais un code brut, jamais un mur.",
  zones=[
    Z("hero", "État 403", 3, "Glyphe cadenas clay atténué + « Vous n'avez pas accès à cet écran. » + raison précise (rôle, permission, verrou)."),
    Z("list", "Voies légitimes", 4, "Selon le cas : demander un accès (si un responsable existe) · changer de profil · demander au propriétaire de la ressource · consulter une version publique de l'information si elle existe."),
    Z("kpi", "Ce qui reste accessible", 3, "Rappel des pages équivalentes autorisées : « vous pouvez consulter vos propres contrats », « vos candidatures », etc."),
    Z("cta", "Actions", 1, "« Demander un accès » or (formulaire simple, réponse sous 48 h) · « Retour à mon espace » fantôme."),
  ],
  comps=_guard("403"),
  states=[("Rôle insuffisant", "explication factuelle (ex. écran réservé à l'administration LE LABEUR)."),
          ("Ressource verrouillée", "si un autre agent traite le dossier : indicateur de verrou avec délai."),
          ("Accès révoqué", "après un changement de rôle : mention de la date de révocation."),
          ("Demande envoyée", "suivi de la demande visible (statut, échéance).")],
  motion=[("Entrée", "fondu 240 ms"),
          ("Demande", "envoi sobre, accusé de réception 1 200 ms")],
  rules=["Un refus d'accès est toujours expliqué et propose une voie : jamais de cul-de-sac.",
         "Aucun détail d'implémentation (noms de routes internes, identifiants techniques) n'est exposé.",
         "Les demandes d'accès sont tracées et ont un délai de réponse affiché."],
  tokens=["--clay-500", "--slate-500", "--mono", "--surface-2"],
  api=["POST /v1/access-requests {resource, motive}", "GET /v1/access-requests/me"],
  tech="Le routeur applicatif distingue 401 (non authentifié) et 403 (authentifié sans droit) : deux écrans différents, "
       "jamais le même message générique.",
  canon="SYS — 403", chrome=CHROME_SYS),

S("SYS-05", "404 — Introuvable", "SYS", "États système", "/etat/404", "Système", "P1", "Le vide utile",
  intent="Quand une ressource n'existe pas (ou plus), ne pas laisser l'utilisateur dans un couloir vide : expliquer, "
         "proposer les chemins les plus probables, et offrir un signalement si cela ressemble à un bug.",
  zones=[
    Z("hero", "État 404", 3, "Glyphe chemin interrompu ardoise + « Cette page n'existe pas ou a été déplacée. » Mention : si l'objet est un contrat ou une mission, il peut avoir été archivé (et non supprimé)."),
    Z("list", "Chemins probables", 4, "Suggestions contextuelles selon l'URL tentée : « vos missions », « vos contrats », « vos documents », « votre salaire » — ordonnées par proximité avec l'intention."),
    Z("kpi", "Signalement", 3, "« Ce lien s'est-il cassé à la suite d'une erreur ? » → signalement avec l'URL d'origine (aucune donnée personnelle transmise à l'utilisateur, la trace reste interne)."),
    Z("cta", "Actions", 1, "« Retour à mon espace » or · « Signaler le lien » fantôme."),
  ],
  comps=_guard("404"),
  states=[("Ressource jamais existée", "message neutre."),
          ("Ressource archivée", "si détectable : « ce contrat est archivé, le voici » avec lien (meilleure UX qu'un 404)."),
          ("Ressource purgée", "mention de la rétention (contenu supprimé selon politique, trace conservée)."),
          ("Lien cassé interne", "si le référent de l'URL est une page produite par LE LABEUR : signalement pré-rempli.")],
  motion=[("Entrée", "fondu 240 ms"),
          ("Suggestions", "stagger 60 ms")],
  rules=["Quand la ressource existe mais est archivée, l'écran propose un accès direct au lieu d'un 404 sec (principe de courtoisie technique).",
         "Aucun contenu de la ressource inexistante n'est révélé par message d'erreur (anti-énumération).",
         "Les signalements de liens cassés alimentent la qualité (revue hebdomadaire)."],
  tokens=["--slate-500", "--mono", "--surface-1"],
  api=["GET /v1/navigation/suggestions?from=", "POST /v1/reports/broken-link"],
  tech="Middleware de résolution : avant d'afficher 404, recherche d'un équivalent (slug obsolète, ressource archivée) via "
       "table de redirections.",
  canon="SYS — 404", chrome=CHROME_SYS),

S("SYS-06", "409 — Conflit", "SYS", "États système", "/etat/409", "Système", "P0", "Brancher sans écraser",
  intent="Quand deux modifications se heurtent (vous et un autre appareil, vous et la partie adverse, job concurrent), "
         "montrer les deux versions et laisser choisir — jamais d'écrasement silencieux.",
  zones=[
    Z("hero", "État 409", 3, "Glyphe éclair à deux branches (violet) + « Cette information a changé pendant que vous travailliez. » + horodatage des deux versions (Mono)."),
    Z("doc", "Comparaison des versions", 5, "Deux colonnes : votre version (locale, horodatée) et version serveur (actuelle), différences surlignées. Sélecteur par bloc : garder l'un, garder l'autre, fusionner."),
    Z("kpi", "Conséquences", 3, "« Fusionner » : le système rejoue la validation ; « écraser » : réservé aux champs non contractuels ; « abandonner » : votre saisie est conservée en brouillon."),
    Z("cta", "Décider", 2, "« Fusionner mes changements » or (par défaut, sûr) · « Conserver la version serveur » fantôme (avec copie de votre saisie en brouillon) · « Reprendre ma saisie » texte."),
  ],
  comps=_guard("409"),
  states=[("Conflit de champ", "résolution bloc par bloc."),
          ("Conflit de statut", "si l'objet a changé d'état (ex. mission déjà pourvue) : explication + nouvelles options."),
          ("Conflit d'action", "ex. double sélection de candidat : l'écran explique la course et propose l'alternative la plus proche."),
          ("Conflit résolu", "émeraude : état fusionné affiché, horodatage serveur mis à jour.")],
  motion=[("Comparaison", "deux colonnes qui se déploient 420 ms"),
          ("Fusion", "différences qui se résolvent ligne à ligne 120 ms, sceau émeraude bref")],
  rules=["Aucun écrasement silencieux de saisie utilisateur : la version locale est TOUJOURS conservée (au minimum en brouillon).",
         "Les champs contractuels (prix, dates, périmètre) ne peuvent jamais être écrasés sans action explicite.",
         "Le conflit est expliqué en langage humain : « quelqu'un d'autre a modifié ceci à 14:02 »."],
  tokens=["--violet-500", "--emerald-500", "--amber-500", "--mono", "--glass-2"],
  api=["GET /v1/conflicts/:id", "POST /v1/conflicts/:id/resolve {strategy, perField}"],
  tech="Verrous optimistes via ETag/If-Match : le serveur renvoie 409 avec les deux versions ; la fusion est rejouée côté "
       "serveur pour garantir la validité (jamais une fusion purement client).",
  canon="SYS — 409", chrome=CHROME_SYS),

S("SYS-07", "422 — Données invalides", "SYS", "États système", "/etat/422", "Système", "P1", "Corriger précisément",
  intent="Quand le serveur rejette des données, l'écran ne dit jamais « erreur » : il pointe chaque champ fautif, explique "
         "la règle, et conserve tout ce qui était valide. La correction doit être un jeu d'enfant.",
  zones=[
    Z("hero", "État 422", 3, "Glyphe formulaire ambre + « Certaines informations doivent être corrigées. » + compteur : « 2 champs à corriger »."),
    Z("form", "Champs en cause", 5, "Chaque champ : valeur actuelle conservée, règle violée expliquée en langage clair (et non un code), exemple corrigé si utile, focus direct au tap."),
    Z("list", "Ce qui a été conservé", 3, "Rappel : tous les autres champs sont intacts, le brouillon est enregistré, la validation n'a rien modifié côté serveur."),
    Z("cta", "Actions", 1, "« Corriger maintenant » or (focus sur le premier champ fautif) · « Enregistrer en brouillon » fantôme."),
  ],
  comps=_guard("422"),
  states=[("Erreurs de saisie", "liste par champ, messages spécifiques."),
          ("Règle métier violée", "ex. échéance avant date de début : explication du pourquoi (et non seulement du quoi)."),
          ("Pièce jointe invalide", "type/taille/lisibilité : correction possible avec aperçu."),
          ("Après correction", "nouvelle tentative automatique proposée, avec confirmation visuelle.")],
  motion=[("Entrée", "fondu 240 ms, scroll automatique fluide vers le premier champ fautif 420 ms"),
          ("Correction", "validation champ par champ, coche émeraude 240 ms")],
  rules=["Toute erreur 422 est traduite en langage humain, avec la règle énoncée : jamais de code d'erreur brut présenté à l'utilisateur.",
         "Aucune donnée valide n'est perdue lors d'un rejet : conservation intégrale.",
         "Les messages ne doivent jamais culpabiliser (« saisie invalide ») mais guider (« la date doit être postérieure au 12/10 »)."],
  tokens=["--amber-500", "--emerald-500", "--mono", "--glass-1"],
  api=["POST /v1/* (validation partagée zod) — un 422 renvoie la carte des erreurs par champ"],
  tech="Le même schéma de validation (zod) tourne côté client et serveur : le 422 est le filet de sécurité, jamais la "
       "première ligne de défense. Les messages sont définis dans le schéma partagé (une seule source).",
  canon="SYS — 422", chrome=CHROME_SYS),

S("SYS-08", "429 — Trop de requêtes", "SYS", "États système", "/etat/429", "Système", "P0", "Ralentir avec dignité",
  intent="Dire honnêtement qu'il faut attendre, combien de temps, et pourquoi — sans masquer la cause ni humilier "
         "l'utilisateur. Un throttling bien expliqué n'est pas vécu comme une punition.",
  zones=[
    Z("hero", "État 429", 3, "Glyphe sablier ambre + « Trop de tentatives. » + compte à rebours réel (Mono, minuteur serveur). Raison factuelle : trop de tentatives de connexion, d'envois, ou de requêtes."),
    Z("list", "Ce qui est possible maintenant", 4, "Options réelles : attendre (compte à rebours), utiliser un autre moyen (code par e-mail plutôt que SMS), réduire la cadence (limite affichée)."),
    Z("kpi", "Transparence des limites", 3, "Limites affichées : « 5 tentatives par minute », « 10 candidatures par heure » — les utilisateurs connaissent les règles."),
    Z("cta", "Actions", 1, "« Réessayer automatiquement à la fin du délai » or (coché par défaut) · « Utiliser un autre moyen » fantôme."),
  ],
  comps=_guard("429"),
  states=[("Limite courte (< 60 s)", "compte à rebours, réessai automatique proposé."),
          ("Limite longue", "blocage temporaire avec cause, possibilité de contact support si jugé injuste."),
          ("Limite de sécurité", "si détection d'abus : clay, explication minimale requise (sans révéler les seuils de détection)."),
          ("Fin de limite", "bascule émeraude automatique, l'action reprend sans re-tap.")],
  motion=[("Compte à rebours", "chiffres Mono qui décrémentent, seconde par seconde"),
          ("Fin de blocage", "bascule émeraude 240 ms, action relancée automatiquement si l'option est cochée")],
  rules=["Le compte à rebours affiché est le temps serveur réel : jamais une estimation locale (horloges différentes).",
         "Les limites publiques (candidatures, messages) sont documentées dans l'interface ; seuls les seuils anti-abus restent confidentiels.",
         "Un utilisateur bloqué à tort peut contester : la voie est toujours disponible."],
  tokens=["--amber-500", "--clay-500", "--emerald-500", "--mono"],
  api=["Headers Retry-After, X-RateLimit-* exposés et affichés", "POST /v1/support/rate-limit-appeal"],
  tech="Le serveur renvoie Retry-After ; l'UI ne fait jamais de backoff aveugle. Les retentatives automatiques respectent "
       "l'en-tête (jitter inclus) et sont annulables.",
  canon="SYS — 429", chrome=CHROME_SYS),

S("SYS-09", "500 — Erreur serveur", "SYS", "États système", "/etat/500", "Système", "P0", "L'erreur assumée",
  intent="Quand LE LABEUR échoue, il le dit, il ne blâme pas l'utilisateur, et il donne les moyens de reprendre : trace de "
         "corrélation, état de la donnée, prochaines étapes. L'incident est aussi de notre côté, et ça se voit.",
  zones=[
    Z("hero", "État 500", 3, "Glyphe engrenage clay + « Une erreur de notre côté. » + identification de corrélation copiable (Mono) pour le support."),
    Z("list", "Sécurités", 4, "« Aucune de vos données n'a été perdue ou modifiée. » · « Aucun paiement n'a été déclenché » · « Votre brouillon est intact » — selon le contexte, affirmé uniquement si c'est vrai (vérifié côté serveur)."),
    Z("kpi", "Reprise", 3, "« Réessayer » relance exactement l'action échouée (idempotence garantie). Statut public : si le service est dégradé, bandeau avec lien vers la page de statut."),
    Z("cta", "Actions", 2, "« Réessayer » or · « Copier l'identifiant d'erreur » fantôme · « Contacter le support » texte (pré-rempli avec l'identifiant)."),
  ],
  comps=_guard("500"),
  states=[("Erreur transitoire", "réessai automatique proposé après 2 s, avec option manuelle."),
          ("Erreur persistante", "bandeau « nous sommes informés » (l'incident est déjà ouvert automatiquement côté ops)."),
          ("Service dégradé global", "bannière globale sur l'application, cohérente avec PUB-10 et ADM-63."),
          ("Résolution", "notification in-app : « le problème est résolu, vous pouvez reprendre ».")],
  motion=[("Entrée", "fondu 240 ms, aucun effet dramatique"),
          ("Réessai", "bouton qui se remplit de clay→or, progression réelle"),
          ("Résolution", "bandeau émeraude 3 s")],
  rules=["L'identifiant de corrélation est toujours fourni et copiable : le support doit pouvoir retrouver l'incident en une seconde.",
         "L'écran n'affirme une sécurité des données que si le serveur l'a vérifié : aucune promesse non fondée.",
         "Chaque 500 crée automatiquement un événement d'observabilité exploité par ADM-49/62."],
  tokens=["--clay-500", "--clay-600", "--mono", "--surface-1"],
  api=["GET /v1/status/public (bandeau)", "POST /v1/support/ticket {traceId}"],
  tech="Le serveur renvoie un trace_id lié à la trace distribuée ; l'écran l'expose. Le réessai utilise la clé d'idempotence "
       "d'origine, ce qui rend tout doublon impossible.",
  canon="SYS — 500", chrome=CHROME_SYS),

S("SYS-10", "Maintenance en cours", "SYS", "États système", "/etat/maintenance", "Système", "P0", "Fermer proprement",
  intent="Pendant une maintenance, dire ce qui est en cours, ce qui est sauvegardé, et quand le service revient. Les "
         "utilisateurs doivent retrouver l'application dans l'état où ils l'ont laissée.",
  zones=[
    Z("hero", "Fenêtre de maintenance", 3, "« LE LABEUR revient à 14:30. » Compte à rebours Mono (serveur), raison factuelle (migration, montée de version)."),
    Z("timeline", "Progression des opérations", 4, "Étapes réelles fournies par l'outillage de déploiement : sauvegardes ✓ · migration en cours ◔ · vérifications ○. Aucune barre fantôme."),
    Z("list", "Ce qui est préservé", 3, "Preuves et pièces intactes · paiements en cours repris dans l'ordre · échéances du jour reportées automatiquement · files d'envoi locales conservées."),
    Z("cta", "Actions", 2, "« Me prévenir à la reprise » or (push/e-mail) · « Voir la page de statut » fantôme."),
  ],
  comps=_guard("maintenance"),
  states=[("Planifiée", "annonce à l'avance (bandeau préalable dans l'app)."),
          ("En cours", "progression réelle par étape."),
          ("Dépassement", "message honnête + nouvelle estimation, jamais de silence."),
          ("Reprise", "retour à l'écran précédent, rappel des échéances reportées.")],
  motion=[("Compte à rebours", "chiffres Mono qui glissent verticalement 120 ms"),
          ("Étapes", "validation séquentielle 240 ms"),
          ("Reprise", "sceau émeraude bref puis retour au contexte")],
  rules=["Aucune maintenance silencieuse pour les services critiques (paiement, OTP) : annonce préalable obligatoire.",
         "Les échéances contractuelles touchées sont reportées automatiquement, sans pénalité pour aucune partie.",
         "L'écran est servi statiquement par le bord : il reste disponible même quand l'API est arrêtée."],
  tokens=["--slate-500", "--gold-500", "--mono", "--glass-1"],
  api=["GET /v1/status/window", "POST /v1/notify/resume"],
  tech="Page statique au bord (Worker + KV). Les étapes de maintenance sont publiées par l'outillage de déploiement en "
       "temps réel (webhook interne).",
  canon="SYS — maintenance", chrome=CHROME_SYS),

S("SYS-11", "502 — Passerelle défaillante", "SYS", "États système", "/etat/502", "Système", "P1", "Un maillon en panne",
  intent="Quand un service tiers (PSP, SMS, fournisseur) échoue derrière la plateforme, l'utilisateur ne doit pas voir une "
         "erreur technique générique : il doit savoir ce qui est touché, ce qui continue, et ce qui sera rejoué.",
  zones=[
    Z("hero", "État 502", 3, "Glyphe maillon brisé clay + « Un service externe ne répond pas. » + service touché en langage humain (« le service de paiement », « l'envoi de codes »)."),
    Z("list", "Ce qui continue & ce qui attend", 4, "Reprises automatiques : les paiements confirmés seront traités · les codes seront renvoyés · rien n'est perdu. Ce qui est suspendu : nouvelles confirmations de paiement par ce canal."),
    Z("kpi", "Rejeu", 3, "« Votre action est en file (réf. Mono), elle repartira automatiquement. » · dernière erreur il y a X minutes · incident ouvert côté plateforme (visible dans le statut public)."),
    Z("cta", "Actions", 1, "« Être notifié quand c'est rétabli » or · « Utiliser un autre moyen » fantôme (ex. autre canal de paiement)."),
  ],
  comps=_guard("502"),
  states=[("Panne brève", "file d'attente, rejeu automatique, aucune action requise."),
          ("Panne longue", "notification aux personnes concernées + alternatives proposées."),
          ("Bascule fournisseur", "si un second fournisseur existe : bascule automatique, mention explicite."),
          ("Rétabli", "rejeu en cours avec progression réelle, notification finale.")],
  motion=[("Entrée", "fondu sobre"),
          ("Rejeu", "progression réelle des éléments traités, un par un")],
  rules=["L'utilisateur n'est jamais tenu responsable d'une panne d'un fournisseur : le message est neutre et factuel.",
         "Aucune action engageante n'est déclarée échouée si elle est en file : elle est « en attente », état distinct et honnête.",
         "Les alternatives de canal sont proposées uniquement si elles sont réellement disponibles."],
  tokens=["--clay-500", "--amber-500", "--mono", "--surface-2"],
  api=["GET /v1/integrations/health", "POST /v1/notify/integration-recovered"],
  tech="Le pattern circuit breaker + file de rejeu est côté serveur ; l'UI lit un état d'intégration agrégé (jamais de "
       "détail d'infrastructure ou de clé).",
  canon="SYS — 502", chrome=CHROME_SYS),

S("SYS-12", "503 — Service indisponible", "SYS", "États système", "/etat/503", "Système", "P0", "Sursis annoncé",
  intent="Un service saturé qui refuse proprement : dire que la capacité est atteinte, préserver la file, et donner un "
         "délai réaliste. Refuser proprement vaut mieux que servir mal.",
  zones=[
    Z("hero", "État 503", 3, "Glyphe porte close ambre + « Service momentanément saturé. » + estimation de reprise réaliste (basée sur la file réelle)."),
    Z("list", "Priorités en cours", 4, "Ce qui est traité en priorité : OTP de salaire · paiements · contrats en signature · le reste est mis en file avec l'ordre affiché."),
    Z("kpi", "Ma position", 3, "Si l'action est mise en file : position (rang réel, jamais inventé), taille de la file, débit observé."),
    Z("cta", "Actions", 1, "« Me notifier à mon tour » or · « Annuler ma demande » fantôme."),
  ],
  comps=_guard("503"),
  states=[("Saturation brève", "mise en file, traitement automatique, notification."),
          ("Saturation longue", "proposition de décaler l'action (ex. envoyer la candidature plus tard) sans pénalité."),
          ("Priorité travailleur", "les demandes liées au salaire passent devant : affiché explicitement."),
          ("Retour à la normale", "traitement de la file avec progression visible.")],
  motion=[("Entrée", "fondu sobre, aucun roulement d'erreur"),
          ("File", "position qui se met à jour doucement, jamais de saut brutal")],
  rules=["Les files sont ordonnées par impact humain (salaire, preuve, candidature) et non par ordre d'arrivée brute.",
         "Aucune action n'est perdue : elle est soit exécutée, soit en file avec position réelle, soit annulée par l'utilisateur.",
         "La plateforme ne demande jamais de « réessayer plus tard » en boucle : elle propose une file ou une notification."],
  tokens=["--amber-500", "--gold-500", "--emerald-500", "--mono"],
  api=["GET /v1/queue/position {ticket}", "POST /v1/notify/queue-turn"],
  tech="Admission control côté bord (Worker) : au-delà d'un seuil, les requêtes non critiques sont mises en file avec ticket ; "
       "les critiques (OTP, paiement) gardent un couloir prioritaire.",
  canon="SYS — 503", chrome=CHROME_SYS),

S("SYS-13", "504 — Délai dépassé", "SYS", "États système", "/etat/504", "Système", "P1", "Le temps long",
  intent="Quand une opération dépasse le temps de réponse acceptable (génération PDF, calcul lourd, export), basculer "
         "proprement en traitement asynchrone : le travail continue, l'utilisateur est notifié.",
  zones=[
    Z("hero", "État 504", 3, "Glyphe horloge violet + « Cette opération prend plus de temps que prévu. » + nature de l'opération (export, génération, analyse)."),
    Z("list", "Traitement en arrière-plan", 4, "« Nous continuons en arrière-plan et vous notifierons. » · Ce qui est attendu : lien de téléchargement, notification, résultat consultable plus tard."),
    Z("kpi", "Suivi", 3, "Identifiant de tâche (Mono) · progression si exposée · « vous pouvez fermer cet écran » (engagement tenu)."),
    Z("cta", "Actions", 1, "« Me notifier » or · « Attendre ici » fantôme (avec progression) · « Annuler la tâche » texte."),
  ],
  comps=_guard("504"),
  states=[("En arrière-plan", "tâche créée, notification enregistrée."),
          ("Progression exposée", "pourcentage réel par étape (assemblage, chiffrement, upload R2)."),
          ("Achèvement", "notification + lien signé (durée affichée)."),
          ("Échec asynchrone", "notification avec motif et réessai possible.")],
  motion=[("Bascule", "transition de l'attente bloquante vers la carte de tâche 240 ms"),
          ("Achèvement", "sceau émeraude, une fois")],
  rules=["Aucune opération longue ne bloque l'interface au-delà de 10 secondes : au-delà, bascule en asynchrone automatique.",
         "La promesse « vous pouvez fermer » doit être tenue : la tâche survit à la fermeture.",
         "Les liens de téléchargement sont signés et expirent (durée affichée), jamais des URLs publiques."],
  tokens=["--violet-500", "--emerald-500", "--mono", "--surface-2"],
  api=["POST /v1/jobs {type}", "GET /v1/jobs/:id", "POST /v1/notify/job-complete"],
  tech="Le serveur renvoie 202 + identifiant de tâche dès qu'une opération dépasse le budget synchrone. Le client lit l'état "
       "via polling adaptatif ou SSE, jamais en bloquant.",
  canon="SYS — 504", chrome=CHROME_SYS),

S("SYS-14", "425 — Réseau instable (WebRTC)", "SYS", "États système", "/etat/425", "Système", "P1", "Appeler avec un réseau faible",
  intent="Écran de secours des sessions média : quand le réseau ne permet pas une qualité correcte, proposer des dégradations "
         "successives plutôt qu'un échec : audio seul, texte temps réel, replanification.",
  zones=[
    Z("media", "État du canal", 4, "Indicateurs : latence, perte, gigue, relais actif. Message clair : « votre connexion ne permet pas la vidéo actuellement »."),
    Z("list", "Dégradations proposées", 4, "Échelle : vidéo 720p → 360p → audio seul → messagerie temps réel de session → replanification. Chaque pallier expliqué, appliqué en un tap, sans quitter la session."),
    Z("kpi", "Continuité", 3, "« La session reste ouverte et tracée » · les notes et décisions restent possibles · le rattachement au dossier est conservé."),
    Z("cta", "Actions", 2, "« Passer en audio seul » or · « Continuer en texte » fantôme · « Replanifier » texte."),
  ],
  comps=_guard("425"),
  states=[("Vidéo dégradée", "360p automatique, proposition d'audio seul."),
          ("Audio seul", "interface simplifiée, qualité de parole prioritaire."),
          ("Texte temps réel", "session textuelle rattachée à l'appel, horodatée."),
          ("Replanification", "proposition de créneau, message aux deux parties, aucune pénalité.")],
  motion=[("Dégradation", "fondu doux entre les modes, jamais de coupure visuelle brutale"),
          ("Bascule texte", "interface qui se réorganise 420 ms")],
  rules=["La dégradation est progressive et toujours proposée, jamais imposée : l'utilisateur choisit le compromis.",
         "Une session dégradée reste valide et tracée : elle produit un compte rendu équivalent.",
         "Aucune pénalité de qualité d'exécution pour un appel dégradé par le réseau : seuls les faits comptent.",
         "L'échec total déclenche automatiquement une proposition de replanification et un incident média (ADM-61)."],
  tokens=["--cyan-500", "--amber-500", "--clay-500", "--mono"],
  api=["GET /v1/calls/:id/quality-state", "POST /v1/calls/:id/degrade {mode}", "POST /v1/calls/:id/reschedule"],
  tech="Détection côté client (stats WebRTC) + décision de repli automatique (simulcast/SVC, préférences de codec, TURN "
       "alternatif) ; l'UI reflète l'état réel sans le simuler.",
  canon="SYS — 425", chrome=CHROME_SYS),

S("SYS-15", "Limites & quotas", "SYS", "États système", "/etat/limites", "Système", "P1", "Les règles du jeu",
  intent="Rendre explicites toutes les limites de la plateforme (candidatures par jour, taille de pièce, devise, pays "
         "couverts) — et expliquer l'origine de chaque limite (gratuité de l'accès au travail, coût réel, réglementation).",
  zones=[
    Z("table", "Table des limites", 5, "Table : domaine (candidatures, messages, pièces, exports, appels), limite, fenêtre, consommation actuelle (barre), explication de la raison."),
    Z("kpi", "Ma consommation", 3, "« 8/10 candidatures aujourd'hui » · « 42/50 envois de pièces ce mois » — visibles avant d'atteindre le mur."),
    Z("list", "Pourquoi ces limites", 4, "Explications : garantir la qualité du matching · prévenir le spam des clients · protéger le travailleur des sollicitations abusives · réglementations locales."),
    Z("cta", "Actions", 1, "« Demander une dérogation » or (cas légitimes : reprise, urgence) · « Voir les règles détaillées » fantôme."),
  ],
  comps=_guard("quotas"),
  states=[("Sous les limites", "barres or, rien à faire."),
          ("Proche de la limite", "ambre à 80 % : information, pas d'alerte anxiogène."),
          ("Limite atteinte", "action bloquée avec message précis + heure de réinitialisation + voie de dérogation."),
          ("Dérogation accordée", "émeraude : limite temporairement relevée, motif et échéance affichés.")],
  motion=[("Barres", "remplissage tnum 240 ms à chaque changement"),
          ("Limite atteinte", "bascule ambre sur la ligne concernée uniquement")],
  rules=["Les limites qui touchent l'accès au travail (candidatures) doivent être généreuses et justifiées : LE LABEUR ne monétise jamais l'accès à l'emploi.",
         "Toute limite a une explication accessible en un tap — aucune règle invisible.",
         "Les limites sont affichées AVANT d'être atteintes, jamais découvertes au moment du blocage.",
         "Les dérogations sont possibles, motivées et tracées."],
  tokens=["--amber-500", "--gold-500", "--emerald-500", "--mono", "--table"],
  api=["GET /v1/limits/me", "POST /v1/limits/waivers {scope, motive}", "GET /v1/limits/policy (public)"],
  tech="Service de quotas centralisé (fenêtres glissantes côté serveur), consommations exposées à l'UI ; les dérogations "
       "sont des objets temporaires versionnés.",
  canon="SYS — limites", chrome=CHROME_SYS),
]
